### ISSUE TITLE
Lehrerfotos werden nicht migriert

### ISSUE THREAD

**Issue by ukloppenburg** [SVWS-NRW/SVWS-Server#1]
Ich habe den SVWS-Server (0.0.31) aufgesetzt und eine bestehende Access-Datenbank zu MariaDB migriert. Angesehen habe ich mir die Datenbank mit Schild Version 3.0.4.1.
Die Fotos der Lehrer werden nicht angezeigt, die der Schüler schon.

**Comment by JuergenRichter** [comment]
Wir werden das prüfen, evtl. ist bei den Lehrerfotos die "on-the-fly" Umwandlung von Base64 nach jpg noch nicht umgesetzt

**Comment by FPfotenhauer** [comment]
Ich habe gerade mal in eine DB geschaut, die Fotos wurden durch den SVWS-Server korrekt in Base64 migirert, ich vermute, dass Schild3.0 aber noch auf das Blob-Feld zugreift. Das ist nach der Migration natürlich leer.
