### ISSUE TITLE
Dokumentation zum Erstellen einer Datenbank

### ISSUE THREAD

**Issue by frostieDE** [SVWS-NRW/SVWS-Server#10]
Irgendwie fehlt in diesem Repository ein Verweis auf eine Dokumentation. 

Die Installationsanleitung für Eclipse ist zwar gut und schön, aber die hilft einem maximal bis zum Punkt, dass man das Projekt bauen kann. Ohne Datenbank bringt einem das aber im Grunde nichts. 

Vielleicht könntet ihr hier die Dokumentation nachreichen oder auf ein Wiki verlinken (oder hier eins erstellen? :wink:)

**Comment by kroerig** [comment]
Irgendwie fehlt die ganze Dokumentation. Das ist alles ein Try & Error -Spiel.
Es gibt im [Wiki](https://schulverwaltungsinfos.nrw.de/svws/wiki/index.php?title=SchILD-NRW) einen Eintrag zu Schild 3 und ein paar [Videos auf Youtube](https://www.youtube.com/@Schulverwaltungssoftware).

Ich versuche mich an der Dockerversion. Die Demo-Datenbank wird hier richtig erstellt. Und nachdem ich das Volume in der docker-compose.yml korrigiert habe, bleiben die Daten auch erhalten. Ich scheitere gerade dran, dem svws-Container einen Java-keystore zu erstellen, damit der Dienst auch mal startet. Wobei ich eigentlich kein TLS im Container terminieren will, das soll eigentlich Traefik machen.

**Comment by FPfotenhauer** [comment]
Wir befinden uns gerade in Version 0.7.1 und arbeiten an einer Dokumentation.
Wir werden die auch bald online stellen.

Die Datenbank zu dokumentierne sehe ich hier als nicht so wichtig an, die Daten sollen je über die API abgegriffen werden.

**Comment by FPfotenhauer** [comment]
Achso. Treafik haben wir hier noch nicht getestet.

**Comment by kroerig** [comment]
Traefik ist ein Reverse-Proxy, der sich sehr komfortabel in Dockerumgebungen integriert. U.a. bringt er auch einen Loadbalancer mit und terminiert das TLS. Im Dockernetzwerk (solange alles auf einem Host läuft) brauchen sich die Container dann nicht auch noch darum kümmern.
Traefik ist das Mittel der Wahl um Anwendungen zu veröffentlichen.
