### ISSUE TITLE
Kursplanung: Regeln lassen sich nicht löschen

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#100]
Version 0.8.10:

Die eingegebenen Regeln lassen sich nicht löschen. Die Anzeige dazu passt auch nicht zur Überschrift.

<img width="393" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/18837070-aced-497e-96e7-c56e63b5c3f7">

**Comment by ThomasBachran** [comment]
@NielsWL : Wurden mit der Blockung bereits Ergebnisse berechnet? Wenn ja, dann wird es vermulich in der Bar unter den Tabs wie folgt aussehen:
![grafik](https://github.com/SVWS-NRW/SVWS-Server/assets/46782864/6ec374f4-9579-48f0-9213-37278881be93)
Wenn dies der Fall ist, dann ist das Bearbeiten der Regeln gesperrt. Einen Hinweis dazu erhält man auch, wenn man mit der Maus über das Sperrsymbol geht. Wenn dies so ist, dann ist das ein gewünschtes Verhalten.

Was das Bild angeht, so ist die Darstellung auf jeden Fall fehlerhaft.

**Comment by hmt** [comment]
Der Fehler ist behoben, das war der Tooltip für die Regelverletzungen. Der Tooltip ist leider nict flexibel genug, um mehrere Zellen aufzunehmen, weil ein `span` um den Inhalt gelegt wird.
Bitte schließen

**Comment by NielsWL** [comment]
Sorry, es wurden Ergebnisse berechnet... Dann macht es keinen Sinn, nachträglich Regeln zu löschen. Sorry.

Ich schließe dann dieses Issue.

**Comment by hmt** [comment]
Nein, alles richtig gemacht, die Anzeige war kaputt und das ist nun behoben :)
