### ISSUE TITLE
Abiturfächer in der EF

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#101]
In der Blockung der EF werden die Abiturfächer angezeigt, was nicht korrekt ist.

<img width="443" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/3b227ad3-98f6-4831-b9e5-f588ab25f4df">

**Comment by ThomasBachran** [comment]
Die Abiturfächer werden für die Einführungsphase ab dem nächsten Pre-Release ausgeblendet.
