### ISSUE TITLE
Fixierung im Abiturfach

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#103]
Wenn ein Schüler in einem Abiturfach fixiert wird, dann wird das Abiturfach nicht mehr angezeigt.

<img width="177" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/1501f1b0-28d5-41f1-a920-77b4a29936d2">

<img width="176" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/0b3be015-99bf-4e3e-93c7-fd188f1f0991">

**Comment by ThomasBachran** [comment]
Der Fehler wurde behoben und sollte im nächsten Pre-Release nicht wieder auftauchen.
