### ISSUE TITLE
Kurs-Schüler-Zuordnung

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#104]
Wenn ich eine Schülergruppe zu einem Kurs hinzugefügt habe (z.B. wegen Kerngruppen in der EF), muss ich alle Schüler dort gleichzeitig fixieren. Ist das anders möglich als in der Tabelle?
Ebenso möchte ich diese Schülermenge übertragen. Das geht zwar, aber dann werden sie hinzugefügt. Die bisherigen Schüler bleiben in dem Kurs. Ich würde gerne ersetzen und nicht nur hinzufügen, die alten Schüler also löschen.

**Comment by NielsWL** [comment]
Zusammenhängend damit kann ich nicht einen einzelnen Kurs ansteuern, um Schüler zu fixieren oder zu lösen. Am besten wäre es auch, "Kurs leeren" als Option hinzuzufügen.

<img width="166" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/ce308567-cf5e-4052-b41e-bcba95c979e1">

**Comment by ThomasBachran** [comment]
@hmt: Das Menu ist nur in dem Fall verfügbar, dass die Blockung bearbeitbar ist. Dort könnte man sicherlich die beiden Optionen Kurs leeren und Kurs löschen anbieten.
Aternativ ist die Option "Kurs leeren" auch in der SubNavBar links neben "Kurs löschen" gut aufgehoben. Kannst du das bitte an dieser Stelle implementieren?

**Comment by NielsWL** [comment]
> Aternativ ist die Option "Kurs leeren" auch in der SubNavBar links neben "Kurs löschen" gut aufgehoben. Kannst du das bitte an dieser Stelle implementieren?<

Das wäre gut.

**Comment by hmt** [comment]
Einmal dies hier eingefügt über das Dropdown:
<img width="560" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/1246495/75aff642-fd46-444c-a024-ccfb47b6deff">

**Comment by NielsWL** [comment]
Sieht gut aus... Fehlt nur ein Leerzeichen :)

**Comment by hmt** [comment]
Wir haben das noch einmal geändert und ein eigenes Dropdown zum Leeren von Kursen ergänzt. Das Leerzeichen war im Commit aber schon drin, nachdem ich das im Screenshot auch gesehen hatte ;-)
