### ISSUE TITLE
LuPO-Import

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#106]
Wenn ich aus der aktuellen LuPO-Datei (Version 2.1.7.3) importieren will, schlägt der Import fehl, ich kann aber nicht nachvollziehen, warum das so ist.
Die Schülermenge ist dieselbe, evt liegt es an den Neuzugängen, die in Schild eingegeben und in der Datei integriert sind...
Kann man da ein Protokoll einbauen, was bisher nur kommt, wenn der Import funktioniert?

<img width="812" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/8c2c51e9-4579-4e8a-a039-513c1f2e7894">

**Comment by NielsWL** [comment]
Das ist mir klar. 
Weitere Tests haben ergeben, dass auch die Schild-ID übereinstimmen muss, die erst in Schild3 erzeugt wird und dann in die LuPO-Datei übertragen werden muss. Jetzt funktioniert der Import wieder.

Jedoch kann ich die Laufbahnen der Neuaufnahmen nicht bearbeiten oder einsehen, der Link führt ins Leere und auch über die Individualdaten gibt es keinen Zugriff. Ebenso werden die Fachwahlen nicht korrekt gezählt, denn es sind in der LuPO-Datei 126 Schüler mit fertigen Laufbahnen, es werden aber nur die 121 Schüler der aktuellen JgSt. 10 angezeigt. Die 5 Neuaufnahmen, die bereits in der DB sind und auch in LuPO, tauchen zwar bei "Laufbahnen" auf, Wahlen sind aber wohl nicht importiert worden (26 Belegungsfehler). Die Schüler sind natürlich einerseits der JgSt. 10 zugerodnet (aktuelles Hj) und andererseits sind die Neuaufnahmen der kommenden EF zugeordnet.

<img width="448" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/5e98a318-b61f-4748-a75a-3b1a131acbfa">

<img width="326" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/5fb6f3dd-9fd5-4de7-971c-4cf7d20c140e">

**Comment by ThomasBachran** [comment]
@NielsWL : Was steht denn in dem Log zu den Neuaufnahmen drinnen? Gibt es da eine Meldung, warum sie übersprungen wurden? (Das Log ist dann nicht automatisch rot)

**Comment by NielsWL** [comment]
Hier das Log für den letzten neu angelegten Schüler:

 
```
  - Lese LuPO-Schüler 127 mit der DB-ID 6063 ein...
    - Ermittle Abiturjahrgang: 2027
    - Prüfe, ob der aktuelle Abiturjahrgang oder ein anderer Abiturjahrgang bereits vorgekommen ist: Ja
    - Prüfe, ob für den Schüler bereits Laufbahnplanungsdaten vorhanden sind... 
    - Schreibe Allgemeine Schüler-Daten in die DB... 
    - Schreibe Fachbezogene Schüler-Daten in die DB... 
      - Fach D: OK
      - Fach E: OK
      - Fach F: OK
      - Fach F5: OK
      - Fach L6: OK
      - Fach L9: OK
      - Fach KU: OK
      - Fach MU: OK
      - Fach LI: OK
      - Fach VP: OK
      - Fach IP: OK
      - Fach GE: OK
      - Fach GEF: OK
      - Fach GEE: OK
      - Fach EK: OK
      - Fach SW: OK
      - Fach SWF: OK
      - Fach SWE: OK
      - Fach PL: OK
      - Fach KR: OK
      - Fach ER: OK
      - Fach KR_C: OK
      - Fach ER_C: OK
      - Fach M: OK
      - Fach PH: OK
      - Fach CH: OK
      - Fach BI: OK
      - Fach SP: OK
      - Fach TRVB: OK
      - Fach TRBB: OK
      - Fach TRLA: OK
      - Fach TRRU: OK
      - Fach TRFU: OK
      - Fach TRTE: OK
      - Fach VKE: OK
      - Fach VKM: OK
      - Fach VKF: OK
      - Fach PXGE: OK
      - Fach PXCH: OK
      - Fach PXPH: OK
      - Fach PXBI: OK
      - Fach PXSP: OK
      - Fach S9: OK
      - Fach S7: OK
      - Fach IF: OK
      - Fach PXKU: OK
      - Fach S0: OK
      - Fach I0: OK
  Import beendet
Löschen der temporären LuPO-Datenbank unter dem Namen "C:\ProgramData\SVWS-Server/temp/svwsdb_YKb5FHNB8iyEJkofkgathf5yrxoPzM1DnnoB14UR.lup".
  [OK]
Fertig!
```

**Comment by NielsWL** [comment]
Die Laufbahndaten kommen aber wohl an. Wenn ich die Schüler unter "Kursplanung" auf die Kurse verteilen möchte oder blocken lasse, sind die Daten da.

**Comment by NielsWL** [comment]
Nach der Blockung und Verteilung auf die Kurse ändert sich die Laufbahnprüfung. Dennoch ist kein Zugriff darauf möglich.

<img width="316" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/0a263011-19f2-4424-ba88-36c16c8be872">

**Comment by ThomasBachran** [comment]
@NielsWL : Die Laufbahnplanungsdaten werden jetzt auch bei den Neuaufnahmen und bei der Warteliste korrekt angezeigt. Im nächsten Pre-Release solltest es dann funktionieren...
