### ISSUE TITLE
Kursplanung für die Q2

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#108]
Ich sehe die aktuelle Umsetzung der Regeln und Möglichkeiten bei der Kursplanung für die EF und die Q1 als fertig an.
Ich möchte aber den Ablauf der Q2-Kursplanung einmal aufschreiben, damit die Vorgehensweise auch in der SVWS-Kursplanung abgebildet werden kann.

1) Es werden zur Q2 Kurse zusammengestrichen (z.B. KU, MU, PL, ...) bzw. finden nicht mehr statt (LI, VP, ...).
2) Es kommen zur Q2 Kurse hinzu (Zusatzkurse).

Um eine gleichmäßige Auslastung der Kurse in allen Fächern hinzubekommen (also auch in den Fächern, die nicht von den Punkten 1 und 2 betroffen sind), blocken wir neu, fixieren aber Schüler in unterschiedlichen Szenarien und mit unterschiedlichen Vorgaben. Denn ob jemand einen GKM in (z.B.) Erdkunde oder ... wechselt, wo keine Klausur geschrieben wird und wo es auch nicht Abiturfach ist, sehe ich als nachrangig zu einer gleichmäßigen Schüleraufteilung an. So entsteht wieder eine maximale Kursdifferenz von 1-3 Schülern. 

Diese Regeln hatten wir bei CNF immer verwendet:
Fixiere#max. Abitur-Kurswechsel (Summe aller SuS) # 13 # -
Fixiere#max. Abitur-Kurswechsel (je SchülerIn) # 1 # -
Fixiere#max. Kurswechsel (je SchülerIn) # 3 # -
Fixiere#max. Kurswechsel (Summe aller SuS) # 110 # -
Fixiere#Teilnehmer#der Fachart#M;GK

Gerne hätte ich auch eine Fixierung für alle Schüler, die ein Fach schriftlich haben. Das ging bisher nicht. Diese Fixierungen müssten natürlich auch per Knopfdruck einzustellen sein, händisch geht das natürlich nicht.

**Comment by NielsWL** [comment]
Ok. Ich habe die Abiturkursfixierungen getestet.
Das funktioniert grundsätzlich, aber in der Praxis gibt es folgendes Problem:
Ich möchte Kurswechsel in Abiturkursen zulassen, wenn dadurch alle Fachwahlen funktionieren. Aber ich habe nichts davon, wenn ich 9 Wahlkonflikte angezeigt bekomme, diese sich aber auch händisch nicht lösen lassen.
Es müssen in dieser Situation erst die Wahlkonflikte gelöst werden, dann erst müssen die Abiturkurswechsel runtergerechnet werden, und dazu danach oder gleichzeitig die Kursdifferenzen.
Das Ziel ist immer: 0 Wahlkonflikte. Selbst ein Wahlkonflikt ist keine Option. (Das gilt aber für alle Blockungen, unabhängig von der Jahrgangsstufe.) Ansonsten ist die Blockung nicht zu gebrauchen.

**Comment by benjaminbartsch** [comment]
@NielsWL: Nach einem Gespräch mit Thomas gestern sind ist die interne Modellierung klar. 

Zur Optimierungsreihenfolge hier eine Frage. Ist diese Reihenfolge ...

1) Allgemeine Regelverletzungen
2) Wahlkonflikte
---> Q2-Regel-Verletzungen
3) Kursdifferenzen
4) Fächerparallelität

... richtig?

**Comment by NielsWL** [comment]
Ja genau. Zwischen Wahlkonflikte und Maximale KD müssten die Abiturfixierungen runtergerechnet werden.
Also so:
1. Allgemeine Regelverletzungen
2. Wahlkonflikte
3. Q2-Regel-Verletzungen
4. Kursdifferenzen
5. Fächerparallelität

**Comment by benjaminbartsch** [comment]
Hallo Nils,

dieses Issues ist sehr kompliziert. Die internen Strukturen geben das zur Zeit nicht her und der Algorithmus selbts zur Zeit auch nicht. Ich habe da lange mit @ThomasBachran drüber diskutiert und wir werden das Issue erstmal nicht angehen. Was wir stattdessen machen werden, ist einen Export/Import anbieten und ich werde mein CNF-Programm so anpassen, dass es das Format lesen kann. 

Aus diesen Grund schließe ich erstmal das Issue.

**Comment by NielsWL** [comment]
Die Lösung finde total gut! 
Zusätzlich gibt es ja größtenteils aktuell keine Q1, so dass nur sehr wenige Schulen mit dem Übergang zur Q2 zu tun haben.
