### ISSUE TITLE
Blockung wiederherstellen

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#109]
Wenn ich für die aktuelle Q1 in einer migrierten DB die Blockung für das vergangene HJ (Q1.1) wiederherstellen möchte, bekomme ich diese Fehlermeldung. Für die EF.2 funktioniert es.

```
{
  "env": {
    "mode": "stable",
    "version": "0.8.10"
  },
  "error": {
    "id": 1,
    "name": "API-Fehler: Dieser Fehler wird durch eine fehlerhafte Kommunikation mit dem Server verursacht. In der Regel bedeutet das, dass die verschickten Daten nicht den Vorgaben entsprechen.",
    "message": "Fetch failed for GET: /db/svwsdb/gost/blockungen/2025/2/restore",
    "stack": "Error: Fetch failed for GET: /db/svwsdb/gost/blockungen/2025/2/restore\n    at RS.getTextBased (https://localhost/assets/index.js:21:25492)\n    at async RS.restauriereGostBlockung (https://localhost/assets/index.js:21:1008218)\n    at async https://localhost/assets/index.js:31:349385\n    at async Proxy.<anonymous> (https://localhost/assets/index.js:28:624007)\n    at async k (https://localhost/assets/SGostKursplanungAuswahl.js:1:25367)",
    "log": null
  }
}
```

<img width="640" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/665b6443-211a-4341-9f61-4dbdba911812">

<img width="306" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/5b1ec3f7-af12-4870-88eb-39b6c3b3fbc7">

**Comment by NielsWL** [comment]
Auch mit dem aktuellen Snapshot funktioniert eine Wiederherstellung der Blockung in der aktuellen Q1 und Q2 nur für die Blockung der EF.

**Comment by ThomasBachran** [comment]
@NielsWL : Der Fehler ist jetzt für das nächste Pre-Release behoben.
