### ISSUE TITLE
Kursplanung: Anzeige Kursdifferenz

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#111]
Während der Berechnung und bei den importierten Ergebnissen sollte die maximale Kursdifferenz aufgeschlüsselt für LK, GK und VTF angezeigt werden, damit man die realen Ergebnisse besser beobachten und einordnen kann.
Ebenso sollte in den Fächern, wo alle Schüler fixiert sind und somit immer eine gleichbleibende KD vorhanden ist, die Anzeige ignoriert werden.

<img width="764" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/f6bacc24-8669-4aae-b1c6-8a466bc328ac">

**Comment by HHayen** [comment]
Hatte @benjaminbartsch schon darum gebeten, ich unterstütze den obigen Wunsch, wenn möglich.

**Comment by benjaminbartsch** [comment]
Ich werden Methoden für die KDs programieren, die diese drei Teile differenzieren.

Das automatische abschalten der KD bei voll-fixierten Fächern (bzw. Facharten) werden ich zunächst nicht programmieren. Dafür gibt es eine Regel, um das manuell abzuschalten (pro Kurs). ggf. kommt später mal ein Automatismus, der diese Regeln dann hinzufügt.

**Comment by benjaminbartsch** [comment]
... wir sind dran an der Umsetzung.
