### ISSUE TITLE
Ausgabe Laufbahnbogen

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/SVWS-Server#112]
Die Ausgabe eines Laufbahnbogens unter "Laufbahnen" führt zu dieser Meldung:

{
  "env": {
    "mode": "stable",
    "version": "0.8.11-SNAPSHOT"
  },
  "error": {
    "id": 3,
    "name": "Programmierfehler: Bitte melden Sie diesen Fehler.",
    "message": "Fehler beim Herunterladen der PDF-Datei zur Laufbahnplanung",
    "stack": "Lc@https://localhost/assets/index.js:21:31356\ne_@https://localhost/assets/index.js:21:32311\nsa@https://localhost/assets/index.js:21:32520\nHt@https://localhost/assets/index.js:21:568093\ns3/<@https://localhost/assets/index.js:41:418292\n",
    "log": null
  }
}

**Comment by hmt** [comment]
Ich kann den Fehler lokal nicht reproduzieren. Geht es um die Ausgabe aller Wahlbögen oder nur der markierten oder gefilterten? Tritt der Fehler grundsätzlich auf oder klappt es manchmal?

**Comment by HHayen** [comment]
![grafik](https://github.com/SVWS-NRW/SVWS-Server/assets/84628225/02ab5c3e-650d-41da-aaff-1b2858605b93)

**Comment by hmt** [comment]
Sagt der Server in der Logausgabe etwas dazu? @M-Plu vielleicht?

**Comment by HHayen** [comment]
Stelle gerade fest: MIt der im Bild oben dargestellten Q1 klappt es, mit der neuen EF nicht. Liegt es evtl. daran, dass die derzeit noch in der 10 sind?

**Comment by hmt** [comment]
da kann @M-Plu am besten etwas zu sagen. Der Fehler scheint vom Server zu kommen.

**Comment by M-Plu** [comment]
Also, ich habe "von Hand" den Abiturjahrgang 2027 eingerichtet und dann dessen Facheinstellungen noch leicht angepasst. Danach habe ich für den ersten Schüler die Wahlen getätigt. Anschließend im obigen Dialog den Wahlbogen für den markierten Schüler gedruckt. Dabei kommt keine Meldung und der Bogen wird erstellt.
Ich nehme das mal mit und kläre das mit @hmt .

**Comment by NielsWL** [comment]
Wo bekomme ich den Snapshot her? @hmt @HHayen @ThomasBachran

**Comment by ThomasBachran** [comment]
@NielsWL : Es gibt keinen Installer für den Snapshot. Wir bauen für das Testen den SVWS-Server mithilfe von Eclipse von Hand. So können wir uns auch schnell zum Testen austauschen, ohne das ein neues Pre-Release erzeugt werden muss.

**Comment by M-Plu** [comment]
So, wer den Server selber baut, der kann gerne jetzt noch mal testen. Ansonsten bis zum nächsten Snapshot warten.

Wir haben jetzt eine detailliertes Logging und die zugehörigen Fehlermeldungen in die Reporting eingebaut. Zudem konnte ich einen Fehler finden, der mit Lernabschnitten bei Neuaufnahmen zusammenhing. Evtl. steckte der hinter dem Problem.

**Comment by M-Plu** [comment]
Zum obigen DropDown und der Schülerauswahl. Die Checkboxes werden nicht berücksichtig, die sind noch zu neu. Markiert ist der Schüler, der angeklickt ist, gefiltert ist die Liste.

**Comment by ThomasBachran** [comment]
> Zum obigen DropDown und der Schülerauswahl. Die Checkboxes werden nicht berücksichtig, die sind noch zu neu. Markiert ist der Schüler, der angeklickt ist, gefiltert ist die Liste.

@NielsWL, @M-Plu : Das stimmt nicht ganz. Ich habe vor etwa 6 Tagen die Anpassung dafür gemacht...

**Comment by NielsWL** [comment]
Ich bekomme immer noch eine Fehlermeldung (Snapshot-Version von heute, 16:29):

{
  "env": {
    "mode": "stable",
    "version": "0.8.11-SNAPSHOT"
  },
  "error": {
    "id": 5,
    "name": "Programmierfehler: Bitte melden Sie diesen Fehler.",
    "message": "Fehler beim Herunterladen der PDF-Datei zur Laufbahnplanung",
    "stack": "Vt: Fehler beim Herunterladen der PDF-Datei zur Laufbahnplanung\n    at Proxy.<anonymous> (https://localhost:8443/assets/index.js:41:418725)\n    at async c (https://localhost:8443/assets/SGostLaufbahnfehler.js:1:3963)",
    "log": null
  }
}

<img width="289" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/4ac29de7-1c98-4ff1-8dbb-e77ad1d361fc">

<img width="337" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/2c56d838-b167-4f50-b242-c55ad75cad6c">

**Comment by NielsWL** [comment]
Ja, sorry, hatte einen Schritt beim Snapshot erstellen vergessen. Es funktioniert.

Aber:

> Zusätzlich sollten einzelne Dateien erstellt werden und nicht eine gemeinsame Datei (oder es gibt dazu eine Auswahl, was noch besser wäre).

**Comment by M-Plu** [comment]
Die Rückgabe erfolgt ja als Download im Browser. Daher kann immer nur eine Datei zurückgegeben werden. Alternativ müsste man daher einzelne Dateien erzeugen, dann packen und anschließend die gepackte Datei zum Download bereitstellen.

**Comment by NielsWL** [comment]
Ich meine die PDF-Dateien, die ausgegeben werden. 

Aus meiner Sicht benötigt man folgende Ausgabe der Laufbahnen:
1) WebLuPO-Datei als Export in einzelne oder mehrere Dateien
2) WebLuPO-Datei als EMail
3) Laufbahnbogen-PDF als EMail (für einzelne oder ausgewählte oder alle Schüler)
4) Laufbahnbogen-PDF als einzelne Datei für einzelne Schüler
5) Laufbahnbogen-PDF für ausgewählte oder alle Schüler jeweils als einzelne PDF-Dateien

Man muss nach dem Export des PDF-Laufbahnbogens von mehreren Schülern auf diese PDFs einzeln zugreifen können und beispielsweise über OneNote verteilen können. Ebenso muss nach einem Beratungsdurchgang der neue PDF-Laufbahnbogen einzeln exportiert werden können (z.B. für Dokumentationszwecke).

Beim Einlesen von Laufbahndaten kann ich nicht einfach LuPO-Schülerdateien, die willkürlich und evt. falsch von Schülern bearbeitet wurden, in mein System integrieren. Also benötige ich nicht nur ein Protokoll der Veränderungen beim Einlesen einer LuPO-Datei, sondern vor allem verändere ich selbst die Laufbahnen im SVWS-Server aufgrund der PDF-Dateien, die mir die Schüler unterschrieben zurückgeben. Und dazu benötige ich die verschiedenen PDF-Versionen 3-5 beim Export...

**Comment by M-Plu** [comment]
Ja, diese PDF meine ich auch und da kann der Browser immer nur eine Datei zurückgeben. 

Aktuell geht 

- ein Schüler oder 
- alle Schüler in einer Datei, wenn man die für den ganzen Jahrgang drucken möchte. 
 
Die Einzeldateioption ginge nur mit einer gepackten Datei, die dann die Einzeldateien enthält. Das sollte aber implementierbar sei,

PDF als E-Mail ist aus meiner Sicht Datenschutztechnisch kritisch, wenn das nicht alles auf schulischen Servern (bzw. deren Dienstleistern) abläuft. Web-LuPO-Dateien sind meines Wissens nach verschlüsselt, Da wär das möglich

Da es hier im Issue um den Laufbahnbogen geht, würde ich für Web-LuPO um ein eigenes Issue bitten.

Nur vielleicht etwas zum Workflow. Das Abtippen von Wahlbögen war eigentlich nicht angedacht. Man kann die Wahldateien der SuS ruhig importieren, da man ja nicht alte Daten importiert, sondern nur für Folgehalbjahre. Wenn da etwas falsch ist, werden diese Fehler angezeigt und man berät. Wenn die Schüler beraten sind, kann man dabei oder später gesamt die Bögen drucken, von den BL unterschreiben lassen und dann an die SuS und die Eltern ausgeben.

**Comment by NielsWL** [comment]
> Die Einzeldateioption ginge nur mit einer gepackten Datei, die dann die Einzeldateien enthält. Das sollte aber implementierbar sein.

Finde ich gut und würde das Problem lösen! Top!

> Nur vielleicht etwas zum Workflow. Das Abtippen von Wahlbögen war eigentlich nicht angedacht.

Da geht es auch nur um die Eingabe möglicher kleiner Änderungen.
Und der Workflow ist ja überall anders, ohne das jetzt zu werten.

> Wenn da etwas falsch ist, werden diese Fehler angezeigt und man berät.

Und man muss jedes Mal, weil Schüler dort Fehler einbauen, alles kontrollieren. Da sehe ich keinen Vorteil.

> PDF als E-Mail ist aus meiner Sicht Datenschutztechnisch kritisch, wenn das nicht alles auf schulischen Servern (bzw. deren Dienstleistern) abläuft.

Läuft bei uns alles auf schulischen Servern. Sollte aber auch den Schulen überlassen werden, das sicherzustellen.

**Comment by HHayen** [comment]
Leider habe ich den Fehler auch immer noch. Aktueller snapshot.

{
  "env": {
    "mode": "stable",
    "version": "0.8.11-SNAPSHOT"
  },
  "error": {
    "id": 1,
    "name": "API-Fehler: Dieser Fehler wird durch eine fehlerhafte Kommunikation mit dem Server verursacht. In der Regel bedeutet das, dass die verschickten Daten nicht den Vorgaben entsprechen.",
    "message": "Fetch failed for GET: /db/GyEic_Anonym/gost/schueler/pdf/laufbahnplanungwahlbogen - Status: 404",
    "stack": "as@https://localhost/assets/index.js:21:23406\npostTextBasedToBinary@https://localhost/assets/index.js:21:26629\n",
    "log": null
  }
}

**Comment by HHayen** [comment]
Jetzt auch unabhängig, ob eine neu angelegte Stufe oder eine "restaurierte".

**Comment by hmt** [comment]
Die Fehlermeldungen sollte nun *schön* formatiert sein, ich vermute, dass der Server nicht auf dem aktuellen Stand ist.

**Comment by M-Plu** [comment]
Ich hatte bei den letzten immer das Gefühl, dass die Begrifflichkeit nicht ganz klar ist. Der dev-Branch wird fortlaufend aktualisiert. Will man mit diesem testen, so muss dieser in der eigenen Entwicklungsumgebung jeweils gepullt und am besten danach einmal neu gebaut werden.

Der SnapShot ist ein "Auszug" aus dem Branch zu einem bestimmten Zeitpunkt und bleibt über mehrere Tage und Wochen unverändert.

Daher bitte neu pullen und bauen.

**Comment by kroerig** [comment]
> Nur vielleicht etwas zum Workflow. Das Abtippen von Wahlbögen war eigentlich nicht angedacht.

[OT]
Das ist aber durchaus üblich, habe ich den Eindruck. Die Schüler bekommen die LuPO Datei und können damit rumspielen (aktuell sofern ein Windows-basiertes Endgerät vorhanden ist). Die wenigsten kommen später mit einer fertigen LuPO Datei zum Beratungsgespräch. Die meisten bringen die Papierversion mit. Nach der Beratung erhalten sie den Laufbahnbogen dann auf Papier. Sollen nochmal eine Nacht drüber schlafen, ggf. Änderungen vermerken und dann unterschrieben wieder abgeben.

Rein digitale Prozesse funktionieren nicht. Textmarker auf dem Bildschirm kommt nicht so gut.
[/OT]

**Comment by HHayen** [comment]
Alles ok, bei mir ging beim Bauen/build etwas schief. Läuft jetzt. Wieder zur Sache:

Bögen werden problemlos für Q1 und Q2 ausgegeben, beide Stufen sind durch Import ja schon vorhanden gewesen.
Für 10 habe ich bei einigen Schülern eine Laufbahn erstellt, für diese scheitert nach wie vor der Laufbahnbogen:
```json
{
  "env": {
    "mode": "stable",
    "version": "0.8.11-SNAPSHOT"
  },
  "error": {
    "id": 1,
    "name": "Programmierfehler: Bitte melden Sie diesen Fehler.",
    "message": "Fehler beim Herunterladen der PDF-Datei zur Laufbahnplanung",
    "stack": "Jc@https://localhost/assets/index.js:21:31421\nrz@https://localhost/assets/index.js:21:32376\nsa@https://localhost/assets/index.js:21:32585\nZt@https://localhost/assets/index.js:21:566235\na3/<@https://localhost/assets/index.js:41:417067\n",
    "log": null
  }
}
```
![grafik](https://github.com/SVWS-NRW/SVWS-Server/assets/84628225/57420f84-1cf9-4560-ad0e-c7d26c834dc2)

Drucke ich direkt aus dem Schülermenü kommt es zu dieser Meldung:
```json
{
  "env": {
    "mode": "stable",
    "version": "0.8.11-SNAPSHOT"
  },
  "error": {
    "id": 2,
    "name": "API-Fehler: Dieser Fehler wird durch eine fehlerhafte Kommunikation mit dem Server verursacht. In der Regel bedeutet das, dass die verschickten Daten nicht den Vorgaben entsprechen.",
    "message": "Fetch failed for GET: /db/GyEic_Anonym/gost/schueler/pdf/laufbahnplanungwahlbogen/0 - Status: 500",
    "stack": "us@https://localhost/assets/index.js:21:23406\npostTextBasedToBinary@https://localhost/assets/index.js:21:26629\n",
    "log": {
      "success": false,
      "log": [
        "Erzeuge Repository",
        "Erzeuge Datenkontext Schule",
        "Erzeuge Datenkontext Schüler - 1 IDs von Schülern wurden übergeben.",
        "Füge Parameter für den Druck hinzu.",
        "Erzeuge PDF-Dateiname.",
        "###  FEHLER  ####################################",
        "    _map hat nicht den KEY 189"
      ]
    }
  }
}
```

**Comment by ThomasBachran** [comment]
Der Fehler sollte jetzt behoben sein. Sollte nochmal ein vergleichbarer Fehler auftreten bitte ein neues Issue erstellen.

**Comment by M-Plu** [comment]
> Ich meine die PDF-Dateien, die ausgegeben werden.
> 
> Aus meiner Sicht benötigt man folgende Ausgabe der Laufbahnen:
> 
> 1. WebLuPO-Datei als Export in einzelne oder mehrere Dateien
> 2. WebLuPO-Datei als EMail
> 3. Laufbahnbogen-PDF als EMail (für einzelne oder ausgewählte oder alle Schüler)
> 4. Laufbahnbogen-PDF als einzelne Datei für einzelne Schüler
> 5. Laufbahnbogen-PDF für ausgewählte oder alle Schüler jeweils als einzelne PDF-Dateien (immer für jeden Schüler eine eigene Datei)
> 

Auch wenn hier schon zu ist, war noch ein Punkt offen: Das Erstellen von einzelnen PDFs. Das ist nun unter Oberstufe > Laufbahnen verfügbar.

**Comment by NielsWL** [comment]
Nun ist es top. Herzlichen Dank!

<img width="204" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/208f3f77-7feb-4640-b054-9e821b059306">
