### ISSUE TITLE
WebLuPO 40 Stunden dunkelgrün

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/SVWS-Server#114]
![grafik](https://github.com/SVWS-NRW/SVWS-Server/assets/84628225/a48a9e8f-22eb-4d2b-81e8-c190e0018e0a)
Das könnte und wird Schüler irritieren:
Ohne hier zu tief die APO §28 zu zerlegen: 40 Stunden sind keine Überbelegung im Sinne der Laufbahnplanung.
Der Wechsel zu Dunkelgrün scheint derzeit bei 36 zu 37 zu liegen, in denke aus der Beratungserfahrung sollte das erst von 40 zu 41 erfolgen.
Das hier ist damit aus Shüler- und Beratungsperspektive auch schwer zu vereinbaren:
![grafik](https://github.com/SVWS-NRW/SVWS-Server/assets/84628225/26a04c73-271d-4583-82d8-3bbb7f675f49)

**Comment by NielsWL** [comment]
@HHayen: Das ist die Anzahl der Kurse, aber dennoch stimme ich dir zu. Wobei wir auch häufig 11,11,10,10 und damit 42 Kurse haben...

**Comment by NielsWL** [comment]
Auch die 12 Kurse in der EF, die notwendig sind, werden dunkelgrün angezeigt...

**Comment by Raffenberg** [comment]
Es gab immer die Empfehlung, dass sich die Stundenbandbreite nicht weit weg von 34 Wochenstunde bewegen soll. Während es bei zu wenigen Stunden eine Vorgabe gibt, ist dies bei zu vielen Stunden nicht der Fall. Insofern hatten wir uns damals (das MSB und ich) darauf verständigt, dass bei einer Überschreitung der Stundenzahlen um einen bestimmten Wert dunkelgrün dargestellt wird. Dann kommt in Lupo auch ein Hinweis:

Hintergrundfarbe der Kursstundensummen der Halbjahre EF.1 bis Q2.2
    Kursstunden werden rot dargestellt, wenn ihre Summe kleiner ist als 30
    Kursstunden werden gelb dargestellt, wenn Ihre Summe zwischen 30 und 32 liegt.
    Kursstunden werden gelbgrün dargestellt, wenn ihre Summe zwischen 33 und 35 liegt.
    Kursstunden werden grün hinterlegt, wenn ihre Summe >36 beträgt
Hintergrundfarbe der Kursstundensummen EF und Q1/2
    Kursstunden werden rot dargestellt, wenn ihre Summe kleiner ist als 34
    Kursstunden werden gelbgrün dargestellt, wenn Ihre Summe größer ist als 33
Hintergrundfarbe der Kursstundensummen
    Kursstunden werden rot dargestellt, wenn ihre Summe kleiner ist als 100
    Kursstunden werden orange dargestellt, wenn Ihre Summe zwischen 100 und 101 liegt
    Kursstunden werden gelbgrün dargestellt, wenn ihre Summe zwischen 101 und 106 liegt
    Kursstunden werden grün dargestellt, wenn ihre Summe größer als 106 ist

**Comment by NielsWL** [comment]
Das betrifft aber noch nicht die Kurse. Da ist die Farbgebung falsch.

**Comment by HHayen** [comment]
Sorry, ich hatte im Ticket in der Überschrift fälschlicherweise "40 Stunden" geschrieben. Wie aber ja ersichtlich ist, meinte ich die Kursanzahl. Und da ist dunkelgrün bei 40 aus meiner Sicht nicht angebracht.Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: NielsWL ***@***.***> Datum: 21.03.24  13:36  (GMT+01:00) An: SVWS-NRW/SVWS-Server ***@***.***> Cc: HHayen ***@***.***>, Mention ***@***.***> Betreff: Re: [SVWS-NRW/SVWS-Server] WebLuPO 40 Stunden dunkelgrün (Issue #114) 
Das betrifft aber noch nicht die Kurse. Da ist die Farbgebung falsch.

**Comment by ThomasBachran** [comment]
Ich habe die Farben jetzt angepasst und hoffe, dass die Werte jetzt stimmig sind.

@NielsWL, @HHayen, @Raffenberg : Könnt ihr das bitte überprüfen?

**Comment by Raffenberg** [comment]
@ThomasBachran 
Kann ich das auch hier in den Schülerversionen testen, wie im Nightly vom SVWS-Server, oder besser im SVWS-Server von Eclipse?

https://laufbahnplanung.svws-nrw.de/#/load
oder
https://weblupo.svws-nrw.de/#/load

Wo ist eigentlich der Unterschied zwischen den Links?

**Comment by Raffenberg** [comment]
Hier noch die Ergänzung, die ich Thomas zusätzlich geschickt hatte:

Farben bei den Kurszählungen in den Halbjahren
EF
<10 Kurse rot
10 Kurse gelb
>10 Kurse grün
es gibt kein dunkelgrün

Q1/Q2
<9 Kurse rot
9 Kurse gelb
>9 Kurse grün
es gibt kein dunkelgrün
