### ISSUE TITLE
Kursplanung: Fehler

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#115]
Ich habe eine Blockung zum Testen eingerichtet für den Abi2027-Jahrgang für die Q1.1. Ich habe geblockt, Regeln angelegt etc. Dann habe ich den Mathe-VTF gelöscht und dann direkt den angehängten Fehler bekommen, der nun dauerhaft bei der Q1.1 auftaucht. Die anderen Halbjahre kann ich bei der Kursplanung aufrufen.

<img width="570" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/650eb8cb-656b-4c60-bbb7-f6209b5b9646">

**Comment by ThomasBachran** [comment]
@NielsWL : Das könnte mit dem Bug aus Issue #116 zusammenhängen. Kannst du das nochmal ausprobieren, wenn wir das nächste Pre-Release herausgegeben haben?
