### ISSUE TITLE
Kursplanung: Fehler beim Löschen von Kursen

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#116]
Bei einer abgeleiteten Blockung wollte ich einen Sportkurs löschen, was zu dieser Fehlermeldung führte.

**Vorher:**
<img width="714" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/eb8e5416-986b-46f7-95dc-331cfaa80108">

**Nach dem Löschen von SP-GK5:**
{
  "env": {
    "mode": "stable",
    "version": "0.8.10"
  },
  "error": {
    "id": 11,
    "name": "Programmierfehler: Bitte melden Sie diesen Fehler.",
    "message": "GET von 2572 fehlgeschlagen, da kein Mapping existiert!",
    "stack": "Ht: GET von 2572 fehlgeschlagen, da kein Mapping existiert!\n    at Ht.ifMapGetIsNull (https://localhost/assets/index.js:21:565468)\n    at ss.getOfKursSchienenmenge (https://localhost/assets/index.js:27:26097)\n    at ss.stateRegelvalidierung3_kurs_sperren_in_schiene (https://localhost/assets/index.js:27:1152)\n    at ss.stateRegelvalidierung (https://localhost/assets/index.js:25:18390)\n    at ss.stateKursSchieneHinzufuegen (https://localhost/assets/index.js:27:9635)\n    at ss.setKursSchiene (https://localhost/assets/index.js:28:1145)\n    at ss.stateClear (https://localhost/assets/index.js:25:17441)\n    at ss.stateRevalidateEverything (https://localhost/assets/index.js:25:14276)\n    at ss.setRemoveKurseByID (https://localhost/assets/index.js:28:3441)\n    at https://localhost/assets/index.js:31:352719",
    "log": null
  }
}

<img width="707" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/0b83d5f3-efa5-40aa-82ed-e4d808fbf9a2">

**Comment by ThomasBachran** [comment]
@NielsWL : Danke für die Rückmeldung. Der Fehler ist beim Speichern in der DB-Bereich bereits behoben. Die Anpassung für die GUI ist bereits in Arbeit. Ich schließe das Issue hier.
