### ISSUE TITLE
Feature: Filterwunsch bei Wechsel Laufbahnplanung Jahrgang zu Schüler 

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/SVWS-Server#117]
Wechselt man von der allgemeinen LAufbahnplanung aus "Oberstufe"->"Abschnitt"->Laufbahnplanung in die individuelle Schülerlaufbahnplanung, werden im Auswahlcontainer alle Schüler angezeigt.
Schön fände ich, wenn sofort ein Jahrgangsstufenfilter greifen würde, so kann einfacher zu einem anderen Schüler der Stufe gewechselt werden, den man direkt im Anschluss bearbeiten möchte.
![grafik](https://github.com/SVWS-NRW/SVWS-Server/assets/84628225/1861ff8b-48a2-40f4-a2f9-679334d07ade)

**Comment by NielsWL** [comment]
Finde ich auch gut.

**Comment by NielsWL** [comment]
Das ist umgesetzt worden, bei mir funktioniert es.

**Comment by HHayen** [comment]
OK. muss dann mal meinen snap überprüfen. Das könnte auch einen anderen Fehler erklären. Danke euch für die schnelle Rückmeldung.

**Comment by HHayen** [comment]
Sorry, bei mir ist ein Build schief gelaufen, Filter funktioniert.
