### ISSUE TITLE
Snapshot

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#118]
Wo bekomme ich den Snapshot her?

**Comment by ThomasBachran** [comment]
siehe #112 : Es gibt keinen Installer für den Snapshot. Wir bauen für das Testen den SVWS-Server mithilfe von Eclipse von Hand. So können wir uns auch schnell zum Testen austauschen, ohne das ein neues Pre-Release erzeugt werden muss.

**Comment by NielsWL** [comment]
Also habe ich keine Chance auf den Snapshot?

**Comment by ThomasBachran** [comment]
Wenn du Lust hast bei dir Eclipse einzurichten schon...
