### ISSUE TITLE
Konverter für "altes" LuPO Format

### ISSUE THREAD

**Issue by kroerig** [SVWS-NRW/SVWS-Server#119]
Hallo zusammen,

gibt es eine einfache Möglichkeit bestehende LuPO Dateien (Access Format) in das neue Format zu konvertieren, sodass man sie a) in das neue WebLuPO laden kann, aber auch in den SVWS übertragen?
Hintergrund: In der Schule beginnen jetzt die Beratungen und Wahlen für die kommende EF. Deren Daten würden wir gerne mal parallel zu Kurs42 und SchILD 2 auch im SVWS Client verarbeiten.
Aber doppelte eine Dateneingabe ist zeitlich nicht machbar.

**Comment by NielsWL** [comment]
Ich habe die Konvertierung durch den Import der alten LuPO-Datei in den SVWS-Server gemacht. Dabei muss nur die Schülermenge 100%ig übereinstimmen, also mit Schild-IDs.

<img width="612" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/51390115-bdac-4b49-9670-a000293f4ce6">
 
 

Danach kannst du die WebLuPO-Dateien über Oberstufe > Laufbahnen exportieren.

<img width="789" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/7b01ec45-3617-4492-9565-79478c76e2b0">

**Comment by FPfotenhauer** [comment]
Danke für das Testen!
