### ISSUE TITLE
Hinweis, Problem bei Update auf SVWS-Server 0.8.10 mit unvollständigen Schemata

### ISSUE THREAD

**Issue by T-Hagel-SK** [SVWS-NRW/SVWS-Server#121]
Hallo zusammen,
wir haben am Freitag die Version 0.8.10 des SVWS-Servers bereitstellen lassen. Die Kollegen aus dem Webserverbereich meldeten daraufhin Fehlermeldungen. 

Ursächlich waren dabei offenbar die zwischenzeitlich angelegten, aber nicht vollständigen Schemata. Erst nachdem diese von den Kollegen aus der svwsconfig.json-Datei entfernt wurden, ließ sich der Server starten.

Schöne Grüße
Thomas Hagel

**Comment by kroerig** [comment]
Dann wären wohl ein paar Serverlogs hilfreich. Wenn ein Schema als ungültig erkannt wird, dann wird es vom Server deaktiviert (steht dann auch im Log), aber starten sollte der Server trotzdem.

**Comment by FPfotenhauer** [comment]
Es stimmt, dass die fehlerhaften Schemata eigentlich deaktiviert sein sollten. 
Der Server muss starten, dann kann man nämlich mit dem Admin-Client die Schemata auch aus der Config löschen.

In diesem Fall würd eich aber erstmal abwarten, denn die Fehler, die durch die nicht anlegbaren Trigger entstanden sind, waren schon sehr "speziell".

Herr Richter sollte das in seinem Schild-Zentral-Tool dann auch beachten, dass Schemata entfernt werden können.

**Comment by kroerig** [comment]
Die Stadt Köln ist immer "sehr speziell" ;-)

Aber es können ja auch durch andere Ursachen unvollständige Schemas (ja der Plural lautet laut Duden so) enstehen, die den Server nicht am Start hindern sollten.

Den Effekt habe ich in der Dockerumgebung ja auch. Hier gebe ich das zu nutzende Schema dem Container ja über Umgebungsvariablen mit. Und wenn das nicht gültig ist, blieb der Server auch beim Start hängen.

**Comment by T-Hagel-SK** [comment]
> Die Stadt Köln ist immer "sehr speziell" ;-)
> 
Nun, das kann ich ja schlecht so stehen lassen. Ich bin mir sicher, dass andere große IT-Dienstleister oder Kommunen dann auch "sehr speziell" in Bezug auf Webserver, Datenbanken, Clients werden, wenn sie ebenfalls mit Schild3 einsteigen.

> Aber es können ja auch durch andere Ursachen unvollständige Schemas (ja der Plural lautet laut Duden so) enstehen, die den Server nicht am Start hindern sollten.
 OK, danke für den HInweis.
 
> Den Effekt habe ich in der Dockerumgebung ja auch. Hier gebe ich das zu nutzende Schema dem Container ja über Umgebungsvariablen mit. Und wenn das nicht gültig ist, blieb der Server auch beim Start hängen.

Demnach gibt es ja eine Funktion, die überprüft, ob die Schemas korrekt sind. Wenn sie es nicht sind, sollte es doch ausreichen, diese auf inaktiv zu setzen und den Server durchstarten zu lassen (und dem Schild3-Admin eine Mitteilung zukommen lassen, die betroffenen Schemas auf x,y,z zu prüfen. Ggf. per Mail mit Angabe des SVWS-Servernamens wenn bei IT-Dienstleistern mehrere SVWS-Server zum Einsatz kommen.

**Comment by T-Hagel-SK** [comment]
> Dann wären wohl ein paar Serverlogs hilfreich. Wenn ein Schema als ungültig erkannt wird, dann wird es vom Server deaktiviert (steht dann auch im Log), aber starten sollte der Server trotzdem.

Hier ein Auszug aus den Logfiles:
Feb 23 11:12:01 server svws_service[775111]:  -> zu Schema s99_Test
Feb 23 11:12:02 server svws_service[775111]:    Fehler: Aktuelle Revision des Schemas konnte nicht ermittelt werden.
Feb 23 11:12:02 server svws_service[775111]:    Revision veraltet - führe Update aus...
Feb 23 11:12:02 server svws_service[775111]: [main] WARN org.mariadb.jdbc.message.server.ErrorPacket - Error: 1146-42S02: Table 's99_Test.Schema_Core_Type_Versionen' doesn't exist
Feb 23 11:12:02 server svws_service[775111]: [EL Warning]: 2024-02-23 11:12:02.857--UnitOfWork(720811350)--Exception [EclipseLink-4002] (Eclipse Persistence Services - 4.0.2.v202306161219): org.eclipse.persistence.exceptions.DatabaseException
Feb 23 11:12:02 server svws_service[775111]: Internal Exception: java.sql.SQLSyntaxErrorException: (conn=27078) Table 's99_Test.Schema_Core_Type_Versionen' doesn't exist
Feb 23 11:12:02 server svws_service[775111]: Error Code: 1146
Feb 23 11:12:02 server svws_service[775111]: Call: SELECT NameTabelle, Name, Version FROM Schema_Core_Type_Versionen
Feb 23 11:12:02 server svws_service[775111]: Query: ReadAllQuery(name="DTOSchemaCoreTypeVersion.all" referenceClass=DTOSchemaCoreTypeVersion sql="SELECT NameTabelle, Name, Version FROM Schema_Core_Type_Versionen")
Feb 23 11:12:02 server svws_service[775111]:    Fehler: Schema kann nicht aktualisiert werden. Das Schema wird deaktiviert.


Besagtes Schema enthält keine Tabellen. 

Wenn ein Schema vorliegt, erscheint dies hier:
Feb 23 11:16:41 server svws_service[775969]:  -> zu Schema schild3_163168
Feb 23 11:16:42 server svws_service[775969]:    Das Schema ist bereits in der angegebenen Revision.

**Comment by kroerig** [comment]
@T-Hagel-SK Das war jetzt nicht auf die IT bezogen.

Der Prozess sollte fehlerhafte Schemas protokollieren und auch deaktivieren, aber er muss trotzdem starten, sonst habe ich nämlich keine Chance ein neues Schema anzulegen, wenn die API nicht verfügbar ist.

**Comment by FPfotenhauer** [comment]
Ich habe das gerade nochmal getestet.
Der Server startet bei mir jetzt mit dem deaktivierten Schema.
Ich schließe das Issue mal.

**Comment by T-Hagel-SK** [comment]
Äh,
wie jetzt "Issue schließen" ?

Was ist mit den Daten aus dem Log ?
Wie wird man als SVWS-Admin darauf hingewiesen, dass und warum ein Schema deaktiviert wurde ?

**Comment by kroerig** [comment]
> Wie wird man als SVWS-Admin darauf hingewiesen, dass und warum ein Schema deaktiviert wurde ?

Das steht im Logfile des Servers, bzw. sieht man es meine ich auch im Admin-Client (also, dass es deaktiviert ist)

**Comment by T-Hagel-SK** [comment]
Siehe auch https://schulverwaltungsinfos.nrw.de/svws/forum/viewtopic.php?t=6483

Bin also nicht der Einzige, der einen entsprechenden Hinweis (ohne Abbiegung über die Logfiles) hilfreich fänd ...
