### ISSUE TITLE
Schüler: Oberster Schüler bleibt sichtbar

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#122]
Wenn ich auf Schüler gehe und dann einen Jahrgang auswähle, bleibt der oberste Schüler ohne Jahrgang stehen. Erst wenn ich auf einen Schüler des Jahrgangs gehe, verschwindet der oberste Schüler. (Version 0.8.11-SNAPSHOT)

<img width="406" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/3ae58ce3-a881-437f-aaf1-926be15173b0">

<img width="408" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/fb3f0f11-1566-419e-a049-7203500641be">

**Comment by ThomasBachran** [comment]
Wenn in die Ansicht gewechselt wird (z.B. aus dem Bereich Oberstufe), dann sind die Default-Einstellungen für den Filter nicht immer korrekt gesetzt. Dennoch sollte der Schüler angezeigt werden. Dieses Verhalten ist also zum Teil gewünscht. Bei einer Änderung am Filter selbst sollte es jedoch abgeschaltet sein. Das ist jetzt im Repository so umgesetzt.

**Comment by NielsWL** [comment]
Der Fehler besteht immer noch...

**Comment by ThomasBachran** [comment]
@NielsWL : Deinen allgemeinen Fall kann ich leider nicht mehr nachvollziehen. Hast du eine besondere Konstellation, wie es bei dir zustande kommt?

**Comment by NielsWL** [comment]
Besondere Konstellation? Nein. 
Habe dir ein Video geschickt, kannst auch nochmal die DB haben, wenn du möchtest.
