### ISSUE TITLE
Mehrere Schema im Docker Container

### ISSUE THREAD

**Issue by kroerig** [SVWS-NRW/SVWS-Server#124]
Hallo,

wie ist es gedacht bei der Docker-Variante mehrere Schemas anzusprechen?

Die Zugangsdaten und den Schemanamen tragen ich ja in den Umgebungsvariablen ein. Daraus generiert der Container beim Start seine Konfigdatei. Lege ich jetzt ein neues Schema an, dann kann ich das nutzen solange der Container existiert.
Kommt aber eine neue SVWS Version, schmeiße ich den Container weg und lasse den neu erzeugen. Und dann greifen wieder die Daten aus der `.env`. Die weiß aber nichts von anderen Schemas.

**Comment by FPfotenhauer** [comment]
Wo wird denn die svwsconfig.json in der Umgebung gespeichert?

**Comment by kroerig** [comment]
Im Dockercontainer. Ich kann die zwar auch über ein Mount nach außen holen. Das nützt aber nichts, denn beim Start des Containers wird die Datei neu generiert.

**Comment by FPfotenhauer** [comment]
Ich habe bei uns einen FeatureWunsch geöffnet. 
Es wird etwas dauern, aber wir werden uns eine Lösung für die svwsconfig.json überlegen.

**Comment by kroerig** [comment]
Es würde ja schon reichen, wenn man in der .env einfach die Variablen mit fortlaufenden Nummern versehen könnte, aus denen dann ein Array erzeugt wird. Und damit baut sich der Container dann die passenden Einträge.

**Comment by T-Hagel-SK** [comment]
> Es würde ja schon reichen, wenn man in der .env einfach die Variablen mit fortlaufenden Nummern versehen könnte, aus denen dann ein Array erzeugt wird. Und damit baut sich der Container dann die passenden Einträge.

Wäre das nicht eine Frage, die an Ribeka gestellt werden müsste ? Ribeka im Sinne von "Bereitstellung einer Infrastruktur für mehr als eine Schule", also SchildZentral3.

Im "Normalfall" sollte ja an einer Schule mit eigenem supporteten Schulverwaltungssystem nur ein SchildNRW-Schema vorliegen ...

**Comment by kroerig** [comment]
Der SVWS wird nicht von Ribeka entwickelt.

Man will aber an eine Schule ggf. auch mal eine Spieldatenbank haben. Und dann braucht man weitere Einträge im SVWS.

**Comment by kroerig** [comment]
Ich habe gerade die aktuelle Version mit dieser Anpassung installiert. Es funktioniert. Aber mit einem kleinen Haken, der in die Anleitung muss: Die Datei muss vor dem ersten Start vorhanden sein und zumindest mal einen rudimentären Inhalt haben, sonst erkennt Docker sie nicht.
