### ISSUE TITLE
Versand der LP Dateien

### ISSUE THREAD

**Issue by kroerig** [SVWS-NRW/SVWS-Server#125]
Hallo,

wir haben uns jetzt dafür entschieden, die Beratung und Wahlen für die kommende EF parallel zu LuPO und Kurs42 auch mit dem SVWS durchzuspielen. Die scharfe Beratung und Datenerfassung findet in LuPO statt, parallel dazu sollen die Schüler aber auch eine LP Datei erhalten und mit dieser im WebLuPO spielen. Die mit LuPO erfassten Wahlen spielen wir dann auch in den SVWS ein und schauen mal, was die Instrumente so hergeben.

Frage jetzt: wie kommen die LP Dateien an die Schüler? Mit LuPO war das recht "einfach". LuPO konnte mit Hilfe des lokalen Mailclients die Schülermails erstellen und versenden.

Im SVWS finde ich keine solche Möglichkeit und die Konfiguration erfragt auch keine SMTP-Daten. Es gibt nur einen Knopf "Alle exportieren", der einem dann eine ZIP-Datei mit den LP Dateien zum Download anbietet.

Was ist hier der Plan?

**Comment by FPfotenhauer** [comment]
Wir haben bereits einen SMTP-Versand getestet und werden das auch irgendwann umsetzen.
Dazu muss man sich aber auch zum Thema Verschlüsselung intensive Gedanken machen.
Das wird noch eine Weile dauern, bis wir dafür Kapazität haben.
