### ISSUE TITLE
Kursplanung: Regel hinzufügen funktioniert nicht

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#127]
Bei Klicken auf das Plus gibt es keine Reaktion.

<img width="447" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/00bda336-68f0-4b76-8a4b-c74198c8f9fa">

**Comment by NielsWL** [comment]
Habe die Blockung mit 0.8.10 aufgemacht und die Regel eingefügt.
Im aktuellen Snapshot 0.8.11 wird die Regel nicht angezeigt.

**Comment by hmt** [comment]
Ich kann das Problem bei mir nicht nachvollziehen. Es lassen sich Regeln analegen und auch anzeigen. Ist der Snapshot ganz aktuell und auch frisch gebaut? Vorgestern habe ich eine Reihe von Anpassungen an den Regeln gemacht, vielleicht sind die noch nicht drin?

**Comment by NielsWL** [comment]
Ich hatte gestern und auch jetzt gerade nochmal den Snapshot über Eclipse frisch gebaut. Das Problem besteht weiterhin.

**Comment by NielsWL** [comment]
Funktioniert jetzt.

**Comment by hmt** [comment]
super!
