### ISSUE TITLE
SVWS-Server 0.8.10: Frage zu Logleveln (svws_java.log)

### ISSUE THREAD

**Issue by T-Hagel-SK** [SVWS-NRW/SVWS-Server#128]
Hallo zusammen,

wir haben hier in Köln weiterhin Probleme unterschiedlicher Natur (SVWS-Server, aber auch Ribeka Schemaverwaltungstool) und ich bin ein Fan der svws_java-Logs geworden, weil man darin so schön auf Fehlersuche gehen kann. Nur wurde nun von unseren Linuxkollegen das Loggen der Java-Logs mit der Version 0.8.10 ausgesetzt, weil die Logdateien größentechnisch explodieren. Es findet ja derzeit nichts darauf statt, außer, wenn ich ab und zu, neben dem Tages"geschäft" verschiedene Dinge über Swagger oder die Admin-Seite, bzw. über das Schemaverwaltungstool von Ribeka ausprobiere. 

Laut den Kollegen von der Webserverbetreuung bläht sich diese Logdatei bereits nach wenigen Minuten auf mehrere MB auf. Man schätzt,  dass die Java-Logdatei etwa 2,5 GB pro Stunde loggen würde. Das würde hier diverse Rahmen sprengen, trotz einem Logrotate-Verfahren... bei dem in festgelegten Zeiträumen die Logdateien auf einen anderen Server komprimiert verschoben werden.

Wenn der Service dauerhaft loggen soll / muss, dann wäre es gut wenn in Erfahrung gebracht werden könnte, wo und wie der Log Level angepasst werden kann. Die Kollegen vermuten, dass er derzeit auf "Verbose / Debug" steht und jede Kleinigkeit loggt. 

Schöne Grüße
Thomas Hagel
Stadt Köln
Fachanwendungssupport

**Comment by FPfotenhauer** [comment]
Wir haben da nicht wirklich etwas eingestellt.
Wo liegt denn diese Log-Datei? Im Log-Verszeichnis, das in der svwsconfig.json eingestellt ist?

**Comment by T-Hagel-SK** [comment]
Eingetragen ist:
  "LoggingPath" : "logs",

In den Ordner werden ja auch die HTTP-Requests abgelegt und eben das Java-Log. Jedoch geht man hier davon aus, dass es sich zum Leidwesen der Festplatte zu Tode loggt...

Ich nehme an, dass die Einstellung auch nicht in der svwsconfig.json-Datei liegt, sondern irgendwo im Quellcode hart eingestellt ist. Wie groß werden Eure Log-Dateien eigentlich ? Die sind doch bei Euch sicherlich öfter in Nutzung als bei uns, die noch am Anfang stehen.

Ließe sich der Parameter für den Loglevel dann nicht auch in die svwsconfig.json-Datei hinterlegen ?

**Comment by FPfotenhauer** [comment]
Ich schließe das mal, wenn das wieder auftritt, dann bitte melden.

**Comment by T-Hagel-SK** [comment]
Es gibt neue Erkenntnisse ...

Die Logfiles explodieren bei uns, wenn:
- nach einem Serverneustart in der svwsconfig.json-Datei Schemas aufgeführt sind, die nicht mehr auf dem DB-Server vorliegen

In dem Fall kommt es zu einem Loop, der alle 10 Sekunden etwa 100-150 Zeilen erzeugt.

Bleiben also die Fragen:
- in welchen Fällen kann es vorkommen, dass das Löschen von Schemas nicht auch die Einträge in der Config-Datei zulässt ?
- wie kann ein Log-Loop vermieden werden ? Am einfachsten doch eigentlich in einer Abfrage, ob das Schema auf dem DB-Server vorliegt oder nicht. Wenn es dort nicht mal namentlich existiert, soll der Schema-Eintrag gelöscht oder auskommentiert werden ? Was wäre da besser ?
-

**Comment by ThomasBachran** [comment]
In dem nächsten Pre-Release wird der Server-Start nicht mehr abgebrochen. Das wird dann abgefangen und der Schema-Name wird erstmal deaktiviert.
