### ISSUE TITLE
Laufbahnbogen: Unterschriftsfelder

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#130]
Beim Laufbahnbogen werden drei Unterschriftsfelder angeboten.
Beim linken Unterschriftsfeld werden die aktuellen Klassenleiter eingetragen, was falsch ist, denn diese sind in den seltesten Fällen die Beratungslehrer aus der Oberstufe. Dazu muss eine Lösung gefunden werden, so dass dort entweder ausgewählt oder irgendwo eingetragen werden kann, wer die Beratung durchgeführt hat.

<img width="600" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/9228dbfc-1564-4c8b-bc57-d641733d8bb0">

**Comment by NielsWL** [comment]
Ich sehe gerade, dass ich es eintragen kann, aber die Infos werden nicht in den Laufbahnbogen übernommen.

<img width="757" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/02c709da-93f5-45d9-9c9b-64a4337c7168">

**Comment by M-Plu** [comment]
Also, es müssen beim Abiturjahrgang die Beratungslehrer eingetragen sein. Beim zweiten Feld steht der Schülername und beim dritten Feld Erziehungsberechtigte. Der Screenshot sieht so abgeschnitten aus. Bitte mal den Bogen einer fehlerfreien Laufbahn drucken, der nur die belegten Fächer enthält und da prüfen.

**Comment by NielsWL** [comment]
Der Bogen einer fehlerfreien Laufbahn (das ist für den Bogen aber unerheblich) ist abgeschnitten, da dort die realen Namen stehen. Unter dem ersten Feld stehen aber eben die aktuellen Klassenlehrer der entsprechenden Klasse 10 und nicht ich als Beratungslehrer.

<img width="597" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/8be56e1c-a4c9-4cb6-82cf-9dfbbab10a36">

**Comment by M-Plu** [comment]
Sind die Beratungslehrer denn beim Abiturjahrgang (nicht bei der Beratung) hinterlegt?

**Comment by NielsWL** [comment]
Tatsache, die Felder hatte ich noch nicht gesehen. Danke für den Hinweis. Da sind bei der Migration wohl die Klassenlehrer der 10a eingetragen worden. Habe ich jetzt geändert.
Jetzt passt auf dem Laufbahnbogen nur die Reihenfolge der Namen der Beratungslehrer nicht. Die werden unabhängig davon, in welcher Reihenfolge ich sie hinzufüge, gedreht.
Gibt es da eine Vorgabe? Alphabetisch wäre sinnvoll, oder?

<img width="295" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/33fa6339-2ff1-4ef6-abc9-26f80ef28ead">

<img width="204" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/48a5b6b6-0be6-4a2a-9536-43bf1c0f740f">

**Comment by NielsWL** [comment]
Sortierung auf dem Laufbahnbogen passt nun. Danke.
