### ISSUE TITLE
Kursplanung > Regeln: Schüler nicht alphabetisch sortiert

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#131]
Bei den Regeln , z.B. "Schüler verbieten mit Schüler", sind die Schüler zuerst nach dem Status, dann nach der aktuellen Klasse und dann erst nach dem Alphabet sortiert. Hier sollte nur eine alphabetische Sortierung erfolgen.

**Comment by benjaminbartsch** [comment]
... ich werde in den internen Datenstrukturen (Manager genannt) die Regeln sortieren.

**Comment by benjaminbartsch** [comment]
...ist umgesetzt.
