### ISSUE TITLE
Kursplanung: Ausdruck Kursliste 

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#132]
Auf der Kursliste werden die Geburtsdaten aufgeführt. Das ist aus meiner Sicht nicht notwendig für den Kurslehrer, sondern wohl auch datenschutztechnisch schwierig, oder?

<img width="600" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/6329f99e-05bb-4135-969c-6b80658e497b">

**Comment by M-Plu** [comment]
Nach VO-DV I §4 (2) Punkt 1 und (6) darf die unterrichtende Lehrkraft das Schülerstammblatt einsehen, also auch das Geburtsdatum.
Das Datum dient eigentlich dazu, dass die Lehrkraft weiß, welcher Schüler volljährig ist (Entschuldigungen, Fehlzeiten, Erster Ansprechpartner bei Probleme ist vollj. Schüler oder Eltern, usw.)
