### ISSUE TITLE
Kursplanung: Kurslisten per EMail

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#133]
Ist eine Versendung der Kurslisten per EMail geplant? Bestimmt, oder?

**Comment by M-Plu** [comment]
E-Mail ist eine offene Kommunikationsform, da sollten keine Kurslisten mit versendet werden (Datenschutz bzgl. der Namen und Geburtsdaten). Es sei denn man kann schulintern die Sicherheit der Übertragung und der unverschlüsselten Speicherung auf den E-Mails-Servern garantieren.

**Comment by NielsWL** [comment]
Für den Datenschutz ist aus meiner Sicht die Schule zuständig, da sollte nicht systemtechnisch der EMail-Versand unterbunden werden. Kann ich aber sonst (hoffentlich) auch über Schild3 realisieren, dann auch nur mit den Daten, die ich möchte, also z.B. ohne Geburtstag. Besser wäre es aber direkt aus der Oberstufenverwaltung im SVWS-Server.

**Comment by kroerig** [comment]
Siehe auch hier #125

**Comment by FPfotenhauer** [comment]
Wir setzen das gerade um.
Sobald die Funktion zur Verfügung steht, kann das getestet werden und es können Issues dazu aufgemacht werden.
