### ISSUE TITLE
Laufbahnbogen: Dateiname

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#134]
Ich würde es sinnvoll finden, den Dateinamen des Laufbahnbogens zu ändern:
Bisher: GostLaufbahnplanung_Abitur_2027_EF1_Nachname_Vorname_(Schild-ID)
Vorschlag: Laufbahnplanung_Abitur_2027_EF1_Nachname_Vorname_(Schild-ID)_JJJJMMTT_hhmm

So wird ein vorher exportierter Laufbahnbogen nicht überschrieben bzw. mit (1) und (2) usw benannt und die Dokumentation kann bei Bedarf vollständig sein.

Wird beim Schulhalbjahr (hier EF1) immer das folgende Halbjahr verwendet? Oder lässt sich das irgendwo einstellen? Denn bei Veränderungen in der ersten Schulwoche des aktuellen Halbjahres müsste auch ein Laufbahnbogen für das aktuelle Halbjahr gedruckt werden können.

**Comment by M-Plu** [comment]
Das mit dem Überschreiben oder nicht Überschreiben ist wieder vom Workflow abhängig, aber ich nehme das mal mit.

Das Halbjahr ist aktuell nicht anpassbar. Da müsste man mal überlegen, wo und wie man das gestalten könnte. Nehme ich auch mal mit.

**Comment by M-Plu** [comment]
Das Datum wird seit heute im dev-Branch im pdf-Dateinamen ergänzt.

**Comment by NielsWL** [comment]
Hinter dem Nachnamen befindet sich noch ein Komma.

Zusätzlich wird so der Dateiname sehr lang, bei Datum und Uhrzeit könnte man die Striche weglassen (20240708_0837) und aus Abitur_2027 könnte man Abi2027 machen. GOSt-Laufbahnplanung-Wahlbogen könnte man auch kürzen...

**Comment by M-Plu** [comment]
OK, wäre das hier besser?

GOSt-Laufbahnwahl_Abi2025__Martin__Ullrich_(1234)_20240708-1215.pdf

Den Hintergrund für den ausführlichen Namen bitte mit bedenken. Es kann mehrere Wahlbögen in der GOSt geben aber auch gleiche Wahlbögen für andere Bereiche als die GOSt. Zudem muss eindeutig Nachname und Vorname getrennt werden können. Ich habe daher das Komma durch 2 Unterstriche ersetzt. Der doppelte Unterstrich davor hebt den Nachnamen ganz gut ab, wenn man längere Listen liest. Ist aber kein Muss.

Ich warte mal auf Rückmeldung, bevor ich das in den kommenden Tagen einpflege.

**Comment by NielsWL** [comment]
Die doppelten Striche sind aus meiner Sicht nicht notwendig, als erstes kommt ja immer der Nachname. Und wenn dann mehrere Dateien untereinander stehen, fängt der Nachname ja immer an der gleichen Stelle an. 
Der Rest sieht gut aus.

**Comment by M-Plu** [comment]
So, der dev ist aktualisiert. Die Trennung zwischen Nachname und Vorname ist erhalten geblieben. So kann der Nachname eindeutig erkannt werden, denn es gibt Namen mit Leerzeichen im Nachnamen und die sollten auch "maschinell" erkannt werden können.
