### ISSUE TITLE
Oberstufe > Fachwahlen: LK-Schüler fehlen

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#135]
In der Auflistung der Schüler mit ihren gewählten Kursarten fehlen bei den Fachwahlen die LK-Schüler in der rechten Tabelle. Wenn ich die Q1.1 aufklappe, stehen dort nur die 105 GK-Schüler. Links in der Tabelle sind 22 LK-Schüler aufgeführt.
Ebenso fehlen die 21 Schüler mit des 4. Abiturfaches in der Auflistung bei Q2.2.

<img width="1283" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/011c8f65-4dbb-4646-b46a-693f71276baf">

**Comment by ThomasBachran** [comment]
@NielsWL : Das mit den Fachwahlen habe ich jetzt so angepasst, dass rechts GKS, GKM, LK und ggf ZK angezeigt werden. Deine Frage nach dem 4. Abiturfach kann ich nicht nachvollziehen. Du kannst die Abiturspalte (!) auswählen und bekommst dann den Abiturbereich angezeigt. Kannst du dir mal anschauen, ob das jetzt übersichtlicher ist?

**Comment by NielsWL** [comment]
Dass ich die Abiturspalöte anklicken kann, war mir nicht bewusst. So ist es aber jetzt (fast) perfekt. Danke.
Nur die Überschriften sind nicht linksbündig... :)  Passt dann nicht zu den Namen...

<img width="580" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/8fa25373-c8fe-445a-abaa-0ae4d47a498a">
