### ISSUE TITLE
Laufbahnbogen: Fächerliste und Formulierung

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#136]
Zwei Vorschläge zur Änderung des Laufbahnbogens.

1) Die Auflistung der noch wählbaren Fächer in kleiner Schrift auf dem Laufbahnbogen (nur Belegung) macht aus meiner Sicht keinen Sinn. Dann kann ich ja auch den kompletten Bogen drucken.

2) Formulierung:

Bisher: 
Die oben aufgeführten Fachwahlen gelten für die weitere Schullaufbahn als verbindlich gewählt, 
solange keine Korrekturwünsche den Beratungslehrkräften mitgeteilt werden.
Korrekturwünsche können vor jedem Halbjahreswechsel nach Rücksprache mit den Beratungslehrkräften durchgeführt werden.
Schulorganisatorische Gründe können zu einer Änderung der Fachwahlen und der Laufbahn führen.

Vorschlag:
Die oben aufgeführten Fachwahlen gelten für die weitere Schullaufbahn als verbindlich gewählt,
solange den Beratungslehrkräften keine **Änderungswünsche** mitgeteilt werden.
**Umwahlen** können vor jedem Halbjahr nach Rücksprache mit den Beratungslehrkräften durchgeführt werden. 
Schulorganisatorische Gründe können zu einer Änderung der Fachwahlen und der Laufbahn führen.

**Korrekturwünsche** können nicht durchgeführt werden...

Einfacher ist es evt., auch dieses Textfeld frei zugänglich zu machen...

**Comment by M-Plu** [comment]
Ich nehme die beiden Punkte mal mit in die Beratung. 

Die Fächer in der Auflistung dienen dazu das Wahlangebot festzuhalten und nehmen in der Form deutlich weniger Platz weg als die leeren Tabellenzeilen.

Beim zweiten Punkt geht es um die Wortwahl: Änderungswünsche = Umwahlen = Korrekturen.

**Comment by M-Plu** [comment]
Habe den Text angepasst: Änderungswünsche und Änderungen.
