### ISSUE TITLE
Kursplanung: Fixierung bleibt erhalten

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#138]
Wenn ich einen Schüler in einem Kurs fixiert habe, dieser Schüler dann in seiner Laufbahn das Fach abwählt (z.B. zur Q2), bleibt die Fixierung in der Kurse-Schienen-Zuordnung bestehen (obwohl das Fach und der Kurs gar nicht mehr angewählt sind). Dies wird dann zusätzlich als Regelverletzung angezeigt.

<img width="534" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/6d1d1e96-61bf-4bd1-8328-8d74bd10e83c">

<img width="142" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/6de73531-d505-47e4-8919-b38fd72f6420">

**Comment by NielsWL** [comment]
Evt könnte man eine Warnung ausgeben und nicht die Fixierung unkommentiert aufheben?

**Comment by hmt** [comment]
@benjaminbartsch was meinst Du?

**Comment by benjaminbartsch** [comment]
@NielsWL : Ich verstehe nicht den Satz "und nicht die Fixierung unkommentiert aufheben". Denn die Fixierung wurde ja gar nicht aufgehoben. Die Regel besteht ja weiterhin (und wird verletzt). Der Schüler ist einfach nicht mehr im Kurs drin, was er ja auch nicht mehr darf, da er die Fachwahl nicht mehr hat.

Ich verstehe nicht genau, wie das gewünschte Verhalten hier sein soll.

**Comment by NielsWL** [comment]
Ich würde folgendes vorschlagen:
Wenn der Schüler das Fach abgewählt hat, muss auch die Fixierung automatisch gelöscht werden. Wenn der Schüler es dann doch wieder hinzunimmt (bei unterschiedlichen Planungsversuchen...), dann muss die Fixierung eben manuell erneuert werden.

**Comment by benjaminbartsch** [comment]
@ThomasBachran: Das wäre dann die Aufgabe der API, oder?

Also wenn Fachwahl sich ändert ---> in der DB alte Fixierungen löschen.

**Comment by ThomasBachran** [comment]
@benjaminbartsch: Das Entfernen der Kurs-Schüler-Zuordnung erfolgt derzeit nicht automatisch und manuell über ein Modal. Dieses Modal aggregiert die Umwahlen und lässt das Entfernen zu. Bei diesem Modal müssen die entsprechenden Fixierungen mit entfernt werden.

**Comment by hmt** [comment]
Dazu zwei Sachen für @benjaminbartsch 
+ das Modal wird nicht mehr angezeigt, wenn die Kurszuordnung fehlerhaft ist: `getErgebnismanager().getOfSchuelerMapIDzuUngueltigeKurse().size()` liefert trotz fehlerhafter Zuordnungen aktuell keine Zahlen
+ die Methode `kursSchuelerUpdate_03b_ENTFERNE_KURS_SCHUELER_PAARE` sollte auch direkt die angeschlossenen Fixierungen auflösen.

**Comment by benjaminbartsch** [comment]
Ich habe die Ursache des zweiten Spiegelpunktes behoben. Zudem hab ich die Ursache gefunden, warum die MAP leer ist. Es lag an `kursSchuelerUpdate_03a_FUEGE_KURS_SCHUELER_PAARE_HINZU`. Hier habe hier ungültige Kurs-Schüler Zuordnungen nicht erlaubt, was hier aber falsch ist, denn bei einer Umwahl ist die Zuordnung einfach falsch und die API lädt ja die Zuordnungen in den Manager rein.

**Comment by benjaminbartsch** [comment]
Erst nachdem man draufklickt (und abbricht) sieht es so aus:

![grafik](https://github.com/SVWS-NRW/SVWS-Server/assets/83505980/e7098cd8-9c43-402b-a535-f8ce747e81af)

**Comment by hmt** [comment]
Das hängt damit zusammen, dass der beim Hover die Farbe ändert. Würde ich im Moment so lassen.

**Comment by benjaminbartsch** [comment]
Und jetzt strören noch zwei Dinge:

1) "Sollen die falschen Kurszuordnungen entfernt werden" ----> Da denke ich als User....ja welche denn **genau**?
2) Nach dem Klick auf okay, bleibt der Button in der Wanrfarbe

**Comment by benjaminbartsch** [comment]
> Das hängt damit zusammen, dass der beim Hover di

... aber der Button muss auffäliger werden. Man merkt gar nicht, dass er da ist.

**Comment by benjaminbartsch** [comment]
![grafik](https://github.com/SVWS-NRW/SVWS-Server/assets/83505980/ccd78bba-53e0-453d-8814-f183a9edef0e)

**Comment by benjaminbartsch** [comment]
Das Problem ist nun behoben. SuS werden nun nicht mehr aus den Kursen gekickt, falls die Fachwahl sich geändert hat. Stattdessen gibt es nun eine Warnung, dass da eine falsche Zuordnung ist mit der Option den S. zu entfernen, was widerum die Regel entfernen würde.
