### ISSUE TITLE
Fachwahlen Werte GK und S

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/SVWS-Server#139]
![grafik](https://github.com/SVWS-NRW/SVWS-Server/assets/84628225/ea487bcb-82e0-4470-bec3-77b275858b68)
Das ist unsere aktuelle Q2.
In den Schülerlaufbahnen haben in Q2.1 selbstverständlich alle!! 48 Schüler D  im GK als S belegt.
Werden hier fälschlicherweise Differenzen mit AB4-Schülern gebildet? Das käme in etwa hin, wenn ich Abgänger zwischendurch berücksichtige. Q2.2 stimmt dann ja wieder, da S=AB3.

Auch hier stimmt es dann NUR in Q2.1 nicht:
![grafik](https://github.com/SVWS-NRW/SVWS-Server/assets/84628225/0bb64f51-7639-4329-acb3-1d3bbac62530)

Aber bei in svws direkt eingetragenen Wahlen stimmen die Zahlen dann, es könnte also ein Problem nur mit Wahlen aus DB-Import sein.

**Comment by ThomasBachran** [comment]
Der Fehler sollte jetzt behoben sein. Es wurden nicht alle Lernabschnitte der Obestufe korrekt ausgewertet.
