### ISSUE TITLE
Datenbankmirgration schlägt fehlt.

### ISSUE THREAD

**Issue by kroerig** [SVWS-NRW/SVWS-Server#14]
Der Versuch über den Schild3 FullClient eine MDB zu importieren schlägt fehlt:

![grafik](https://github.com/SVWS-NRW/SVWS-Server/assets/5148795/95a9c9b2-ba6f-4639-ba0e-661dcd1d1124)
Die MDB Datei ist etwa 180MB groß.

**Comment by frostieDE** [comment]
Hat die JVM denn genügend RAM? Eventuell einfach mal erhöhen (sofern das System das zulässt)?

**Comment by kroerig** [comment]
in der docker-compose.yml steht `JAVA_OPTS=-Xmx2G -XX:MaxRAM=1073741824`. Das habe ich jetzt mal auf 3G geändert, aber um 180MB Daten zu importieren sollte das ja eigentlich reichen.

Leider bricht mir der Import der MDB auch ab, wenn ich ihn beim Start des Containers über das Init-Script startet. Siehe dazu:
https://schulverwaltungsinfos.nrw.de/svws/forum/viewtopic.php?t=6029

**Comment by FPfotenhauer** [comment]
Können wir uns darauf einigen, dass wir nicht an drei Stellen gleichzeitg Issues aufmachen?
Ich habe dort ja Hilfe angeboten.

**Comment by kroerig** [comment]
Das sind zwei verschiedene Fehler. Hier bricht der Import ab, weil dem Prozess der Speicher ausgeht.
Der Fehler im Forum ist ein anderer. Der hat aber nichts mit dem SVWS zutun, daher habe ich nur zur Info verlinkt.

Hier müsst ein Entwickler schauen, warum dem Prozess die zugewiesenen 2G RAM nicht ausreichen.

**Comment by FPfotenhauer** [comment]
Den Fehler bei der Migration haben wir gerade behoben.
Die Migration benötigt tatsächlich etwas mehr RAM.
Mit 8GB kamen wir aber imme raus. Das halten wir für vertretbar.

**Comment by kroerig** [comment]
das werde ich dann testen, wenn das neue Release verfügbar ist.
