### ISSUE TITLE
SVWS-Server 0.8.10: Löschen eines Schemas nur über Admin-Seite möglich, nicht über Swagger

### ISSUE THREAD

**Issue by T-Hagel-SK** [SVWS-NRW/SVWS-Server#140]
Hallo zusammen,
wir mal wieder ...

Ich wollte mal unsere Test-Schemas aufräumen und habe festgestellt, dass das Löschen aus der /admin-Seite problemlos klappt.

Jedoch nicht über Swagger, und auch nicht über das Ribeka-Schemaverwaltungstool (hat dort ein eigenes Ticket).

Swagger liefert folgende Ergebnisse für das Löschen des Testschemas "test_56":

_Curl

curl -X 'POST' \
  'https://svws-server.xxx.de:8443/api/schema/root/destroy/%20test_56' \
  -H 'accept: */*' \
  -H 'Authorization: Basic xxxxxxxxxxxxxxxx' \
  -d ''

Request URL
https://svws-server.xxx.de:8443/api/schema/root/destroy/%20test_56

Server response:
Code: 204	

Details:
Response headers
 content-length: 0 
 server: Jetty(11.0.16) 

Responses
Code: 204
Description: Der Log vom Löschen des Schemas
Links: No links_

Infos aus dem LogFile kann ich erst am Ende des Tages beifügen.

Schöne Grüße
Thomas Hagel
Stadt Köln
Fachanwendungsbetreuung

**Comment by kroerig** [comment]
voher kommt das `%20` in der URL? Das wäre eine Leerstelle, die da nicht hingehört.

**Comment by T-Hagel-SK** [comment]
> voher kommt das `%20` in der URL? Das wäre eine Leerstelle, die da nicht hingehört.

Keine Ahnung, offenbar war mir beim Ausfüllen ein Leerzeichen in die Eingabemaske gerutscht (Copy/Paste ?)
Man kann es aber reproduzieren: 
Setzt man aktiv ein Leerzeichen vor oder nach dem Shemanamen wird jenes "%20" hinzugefügt. D.h. man müsste die Eingabemaske(n) noch um etwaige Leerzeichen am Anfang und Ende prüfen und kürzen.

Sonst bekommt man das hier: /...:8443/api/schema/root/destroy/%20test_schema_swagger%20' \ 

Ich habe es dann noch mal mit einem anderen Schema versucht, aber ohne Leerzeichen:

_curl -X 'POST' \
  'https://svws-server.xxx.de:8443/api/schema/root/destroy/test_schema_swagger' \
  -H 'accept: */*' \
  -H 'Authorization: Basic xxxxxxxxxxxxxxxxxxxxxxxxx' \
  -d ''
Request URL
https://svws-server.xxxde:8443/api/schema/root/destroy/test_schema_swagger_


_Code: 204	
Details:
Response headers
 content-length: 0 
 server: Jetty(11.0.16)_ 


---
Mit der 0.8.10 klappt derzeit das Anlegen neuer Schemas nicht mehr. Bin auf die Logfiles gespannt und eröffne ggf. ein neues Ticket. Es ist momentan alles recht sonderbar, weil mal der eine Vorgang im Admin-Kontext funktioniert, aber nicht in Swagger, dann mal nur in Swagger aber nicht im Admin-Kontext. Mal klappt was nur im Schemaverwaltungsprogramm von Ribeka nicht, das aber über Admin funktioniert ...  Ich hoffe, ich bin der einzige, der solche Probleme hat.

**Comment by hmt** [comment]
Danke für das Issue, heißt das, dass ohne Leerzeichen das Löschen funktioniert hat? Auf die Funktion der Swagger-Schnittstelle haben wir keinen direkten Einfluss, sie ist das Ergebnis einer Java-Bibliothek, die Api-Methoden als Weboberfläche anbietet. Innerhalb des Webclients können wir natürlich Leerzeichen entfernen, eine gute Idee!

**Comment by T-Hagel-SK** [comment]
> Danke für das Issue, heißt das, dass ohne Leerzeichen das Löschen funktioniert hat?

Leider nicht. Unter Swagger klappt das Löschen nicht. Egal ob mit oder ohne Leerzeichen. Hingegen lassen es sich auf der Admin-Seite die Schemas problemlos löschen.

Ich habe mittlerweile die Logdatei vorliegen und daraus mal exemplarisch einen Löschversuch rausgeholt:
[20240305_svws_java-Extrakt_für_fehlgeschlagenen_Löschversuch.log](https://github.com/SVWS-NRW/SVWS-Server/files/14497349/20240305_svws_java-Extrakt_fur_fehlgeschlagenen_Loschversuch.log)

**Comment by hmt** [comment]
Im Log steht, dass die Datenbank nicht gefunden wurde. Ein 204 Response bdeutet ja auch erstmal, dass die Aktion erfolgreich war.

Wenn man den Pfad darunter verwendet, um zu testen, ob die DB existiert, kommt dann auch `true`? 

    /api/schema/root/exists/{schema}

**Comment by FPfotenhauer** [comment]
Klappt es denn mit einem einfachen Schemanamen?
Kann es sein, das Unterstriche o.Ä. dazu führen, dass es nicht funktioniert?
Wozu möchten Sie das noch über die Swagger machen?
Uns ist eher daran gelegen, dass der WebAdminClient genutzt wird.

**Comment by T-Hagel-SK** [comment]
> Klappt es denn mit einem einfachen Schemanamen? Kann es sein, das Unterstriche o.Ä. dazu führen, dass es nicht funktioniert? Wozu möchten Sie das noch über die Swagger machen? Uns ist eher daran gelegen, dass der WebAdminClient genutzt wird.

- Der Fehler tritt auch mit einem Schema-Namen ohne Unterstrich auf.
- Weil Swagger hier mehr Auskunft gibt, was es macht und zurückmeldet :-) 
- Wenn der WebAdminClient auskunftsfreudiger wird und die ganzen Funktionen, die über Swagger verfügbar sind, integriert hat, wäre ich geneigt zu wechseln ... Nein, im Ernst. Ich teste gegen beide Varianten und hier war es halt so, dass der AdminWebClient das Schema löscht und Swagger "zickt".

**Comment by FPfotenhauer** [comment]
Klappt denn das Anlegen von Schemas jetzt?

**Comment by FPfotenhauer** [comment]
Wird beim löschen des Schemas der AdminUser verwendet?

**Comment by FPfotenhauer** [comment]
Bitte wieder öffnen, wenn das Problem noch besteht.

**Comment by T-Hagel-SK** [comment]
> /api/schema/root/exists/{schema}

So ist es. Der Aufruf ergibt die schlichten vier Buchstaben "true".
Aber auch ein Blick in die SQL-Workbench zeigt: da ist das über die /admin-Seite erzeugte Schema. Nur halt ohne Tabellen.

Auch auf der /admin-Seite wird in der Schema-Übersicht das erzeugte Schema angezeigt. 

D.h. die Verbindung zur Datenbank ist da und funktioniert. Unter 0.8.9 lief das ja auch noch mit den Tabellen und Views.

**Comment by T-Hagel-SK** [comment]
> Klappt denn das Anlegen von Schemas jetzt?

Da ich / wir am SVWS-Server nichts mehr gemacht hatten, als manuell die nicht mehr vorhandenen Schema-Einträge in der Config-Datei zu löschen ... ist es dabei geblieben.

In Sachen Ribeka "Schemaverwaltungsprogramm" gibt es dahingehend News, als dass in Kürze ein Update bereitgestellt wird.

Wie sieht es zeitlich (grob) mit 0.8.11 aus ?

**Comment by T-Hagel-SK** [comment]
> Wird beim löschen des Schemas der AdminUser verwendet?

Im Moment verwenden wir auf der Datenbank ohnehin nur einen User. Der mit der Berechtigung neue DB-Schemas anlegen zu können und mit dem man sich auch auf der Admin- und Swaggerseite erfolgreich anmelden kann.

**Comment by T-Hagel-SK** [comment]
> Bitte wieder öffnen, wenn das Problem noch besteht.

Kann ich Issues wieder öffnen ?

Ja, Problem besteht noch ... zumindest bei uns. Gibt es denn ggf. noch weitere Mitleser, die ebenfalls Schild3 in einer zentralen Umgebung (mit mehreren Schulen) testen ?
