### ISSUE TITLE
Oberstufe > Beratung: Beratungslehrer werden geändert

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#141]
Bei jedem Import einer Lehrer-LuPO-Datei (Version 2.1.7.3) werden unter Oberstufe > Beratung die Beratungslehrer zurückgestellt auf die Klassenlehrer der aktuellen 10a.
Wenn ich mich selbst dort eintrage als Beratungslehrer ist die Einstellung nach dem Import der LuPO-Daten reproduzierbar wieder weg.

**Comment by NielsWL** [comment]
Also, dass die Beratungslehrer immer wieder geändert werden, liegt wohl nicht (nur) an dem Import. Heute habe ich nach dem Neubau des Snapshots erneut die Klassenlehrer der 10a als Beratungslehrer drin. Reproduzieren kann ich das bisher nicht. Aber auch die Textvorlagen für die Laufbahnbögen auf der derselben Seite werden immer wieder zurückgesetzt.

**Comment by ThomasBachran** [comment]
@NielsWL : Wie sind denn folgenden Checkboxen bei dem LuPO-Import gesetzt?

![grafik](https://github.com/SVWS-NRW/SVWS-Server/assets/46782864/c5278312-be6d-4abd-8f92-dc58bcabe3f4)

Ist die zweite Option gesetzt, so werden auch die Beratungslehrer auch neu gesetzt, da das Jahrgangs-spezifische Daten sind.

**Comment by NielsWL** [comment]
Ich hatte immer beide Haken gesetzt.
Worauf hat der zweite Haken denn Einfluss? Ist nicht erkennbar...

**Comment by ThomasBachran** [comment]
@NielsWL : Ich habe bei der zweiten Checkbox einen Tooltip ergänzt. Dieser beschreibt jetzt, worauf der Haken alles einen Einfluss hat.
