### ISSUE TITLE
Kursplanung nicht mehr aufrufbar

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#142]
Ohne ersichtlichen Grund kann ich für den Jahrgang 2027 die Kursplanung nicht mehr aufrufen. Vorher habe ich lediglich einen LuPO-Import (Version 2.1.7.3) durchgeführt.

`Fetch failed for GET: /db/svwsdb/gost/blockungen/6/gzip
Error: Fetch failed for GET: /db/svwsdb/gost/blockungen/6/gzip
    at NS.getBinary (https://localhost:8443/assets/index.js:27:24486)
    at async NS.getGostBlockungGZip (https://localhost:8443/assets/index.js:27:1015048)
    at async uP.setAuswahlBlockung (https://localhost:8443/assets/index.js:50:351836)
    at async hP.update (https://localhost:8443/assets/index.js:50:371956)
    at async hP.doUpdate (https://localhost:8443/assets/index.js:47:577369)
    at async yl.beforeEach (https://localhost:8443/assets/index.js:51:37131)`

**Comment by hmt** [comment]
Der Fehler ist mir auch schon untergekommen, leider habe ich heute versehentlich das Schema mit dem gleichen Fehler gelöscht.

**Comment by HHayen** [comment]
Habe ich auch in JG 10/neue EF geschafft. Und gerade auch in Q1:
Ich hatte zuvor testweise die nicht mehr benötigten Fächer L6, L6, S8 als Oberstufenfächer rausgenommen. (Wollte "saubere" EF-Wahlbögen produzieren). Dann knallte die Q1-Kursplanung und ist auch nicht wieder herstellbar, auch nachdem die Fächer wieder zu Oberstufenfächern gemacht wurden.
In 10 habe ich außerdem in svws fehlende Sprachenfolgen erst ergänzt (S9 fehlte bei einigen), dann wieder gelöscht. Danachwar auch die Blockung der neuen EF nicht mehr zu öffnen.
Fazit: Irgendetwas bei Änderungen Sprachenfolgen und Änderungen der Oberstufenfächer führt noch zu Problemen.

**Comment by HHayen** [comment]
![grafik](https://github.com/SVWS-NRW/SVWS-Server/assets/84628225/8c9f2f70-df0b-4205-8978-bfb156db3e35)
Das ist die letzte Fehlermeldung, vorher kamen andere.

**Comment by ThomasBachran** [comment]
@NielsWL : Wir machen derzeit einige Umstellungen an der Kursplanung. Tritt der Fehler aktuell noch auf?

**Comment by ThomasBachran** [comment]
@HHayen : Das Problem ist hier, dass an irgendeiner Stelle in der Blockung mindesten einer der Fächer referenziert wird. Das Problem tritt vermutlich nicht mehr auf, wenn du bei den entsprechenden Fächern wir setzt, dass sie Oberstufenfächer sind. Die Fehlermeldung sollte dann hier konkreter sein.

**Comment by HHayen** [comment]
Habe die Fächer wieder als Oberstufenfächer gesetzt. Nach einigen Versuchen lief die Kursplanung dann wieder. Kurios: Gerade neues dev gebaut, jetzt lässt die Kursplanung für Q1/Q2 erneut nicht öffnen. EF hingegen (welche ja die betroffenen Fächer auch nicht brauchte) funktioniert.
Da ich hier zwar (mit voller Absicht!!) eine Fehlbedienung provoziert habe, diese aber tatsächlich durch Nutzer später möglich ist, sollte das irgendwie abgefangen werden.

**Comment by benjaminbartsch** [comment]
@ThomasBachran, @hmt: Der ErgebnisManager ist nach der Umstrukturierung nun flexibler bei nicht vorhandenen Daten. Falls etwas nicht vorhanden wird, wird dies als Fehlermeldung gespeichert. Die GUI kann mit der folgenden Methode potentielle Fehler erkennen und diese dem Benutzer dann anzeigen:

```
	public List<String> getFehlermeldungen() {
		return _fehlermeldungen;
	}
```

Generell sollte es aber nicht so sein, dass wenn das Ziel ist 
> "saubere" EF-Wahlbögen zu produzieren

dass der Benutzer die Fächer löscht. Ggf. sollte man dem Benutzer hier zwei Möglichkeiten mit einer Warnung geben:
1) Fach löschen (richtig): Alle alten Blockungen sind damit kaputt
2) Fach löschen (deaktivieren): Das Fach existiert noch, wird aber in bestimmten Visualisierungen nicht mehr angezeigt.

Ich bin mir aber nicht sicher, ob 2) in der DB überhaupt umsetzbar ist. Oder alternativ:

3) Für Wahlbögen gibt es eine Fächerliste, aus denen man diejenigen auswählt, die angezeigt werden sollen. Und löschen von Fächern geht gar nicht (oder nur mit Warnung).

**Comment by ThomasBachran** [comment]
Die letzte hier bekannte Problematik ist ein Duplikat von #160 . Ich schließe daher das Issue hier.
