### ISSUE TITLE
Kursplanung: Zusatzkurse werden nicht eingerichtet

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#144]
Wenn ich eine neue Blockung für die Q2 erstelle, werden mir die Zusatzkurse zur Einrichtung angeboten und angezeigt.
Wenn ich aber eine Blockung aus der Q1.2 nach Q2.1 hochschreibe, werden die Zusatzkurse nicht angezeigt. Die entsprechenden Fachwahlen sind aber nach LuPO-Import vorhanden. Letzte Woche ging das noch (glaube ich zumindest...).
Aktueller Snapshot von heute 14:00 Uhr.

<img width="180" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/be41e575-25ec-40d3-aff4-473db22a3cb0">

**Comment by ThomasBachran** [comment]
@NielsWL : Das Erstellen der Kurs wird bei mir in einem solchem Fall angeboten. Eventuell hast du die Zusatzkurse übersehen, da sie erst nach allen Grundkursen angezeigt werden. Dies ist der Fall, wenn du zuerst nach Kursart und dann nach Fach sortierst.

Ich habe das jetzt so angepasst, dass die Zusatzkurse bei der Sortierung als normale Grundkurse betrachtet werden und daher auch bei der Sortierung nach Kursart direkt beim Fach im Anschluss an den Grundkurs angezeigt werden.

**Comment by NielsWL** [comment]
Übersehen habe ich sie nicht. Dass sie unten eingeordnet werden, ist mir ja klar...

**Comment by ThomasBachran** [comment]
@NielsWL : Besteht der Fehler denn weiterhin?
