### ISSUE TITLE
Funktion Synchronisieren und Erläuterungstext

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/SVWS-Server#145]
![grafik](https://github.com/SVWS-NRW/SVWS-Server/assets/84628225/d4a2be40-d73c-41b6-a622-c2be68f960a5)
Diese Erläuterung ist sprachlich zu überarbeiten.
...mit denen.... und der zweite Satzteil ist für Endkunden nicht verständlich. 
Verstehe ich richtig, dass hier so etwas stehen sollte wie:
"Blockungsdaten (KursArt, KursFach, KursNr, KursSchiene) werden in Leistungsdaten der Schüler übernommen. Bei Kursabwahl wird der Kurs in Leistungsdaten gelöscht."

**Comment by ThomasBachran** [comment]
Ich habe den Text ausführlichen auf "Gleicht die Daten dieses Blockungsergebnisses mit den Daten der Kurstabelle und den Leistungsdaten der Schüler ab. Dabei werden ggf. nicht vorhandene Kurs in der Kurstabelle angelegt und die Kurs-Schienen-Zuordnung angepasst. Leere Kurse werden nicht entfernt. Außerdem wird die Kurs-Schüler-Zuordnung in den Leistungsdaten des Schüler aktualisiert".
