### ISSUE TITLE
Kursplanung: Regel fehlt

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#146]
Folgende Regel fehlt:
FachArt XY maximale Kursanzahl pro Schiene: 1
In diesem Beispiel müsste ich nämlich 6 Kombinationen eingeben, wenn ich bei 4 Mathekursen nur einen Kurs pro Schiene erreichen möchte.
Das Problem trat jetzt auf bei einer Blockung für die Q2 (Das war das Rechenergebnis im Screenshot).

<img width="342" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/e6e805df-0be2-4b89-a6d6-f7bc582dd61a">

<img width="671" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/091fa136-1f1d-4245-b986-30c25278c19b">

**Comment by benjaminbartsch** [comment]
Ja, die Regel wird umgesetzt, das ist möglich.
(intern werden dann alle Paarungen als Verbot erzeugt)
