### ISSUE TITLE
Laufbahnen > Druck der Laufbahnbögen (einzeln)

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#147]
Ich bekomme reproduzierbar (Schüler aus der aktuellen 10 auf der Warteliste, aktueller Lernabschnitt für das 2. Hj fehlt, Schüler ist sozusagen noch im vergangenen Halbjahr) beim Einzeldruck der Laufbahnbögen die folgende Fehlermeldung:
```json
{
  "env": {
    "mode": "stable",
    "version": "0.8.11-SNAPSHOT",
    "Commit": "64baccb3183b9ba381ec0c762534b4a9bfc891b6"
  },
  "error": {
    "id": 10,
    "name": "Programmierfehler: Bitte melden Sie diesen Fehler.",
    "message": "Fehler beim Herunterladen der PDF-Datei zur Laufbahnplanung",
    "stack": [
      "Zt: Fehler beim Herunterladen der PDF-Datei zur Laufbahnplanung",
      "    at Proxy.<anonymous> (https://localhost:8443/assets/index.js:50:414483)",
      "    at async d (https://localhost:8443/assets/SGostLaufbahnfehler.js:1:3496)"
    ],
    "log": null
  }
}
```

<img width="234" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/0229e28c-9f86-436c-80bc-741baa00d650">

**Comment by M-Plu** [comment]
Die Fehlermeldung ist aber älteren Version (gemäß Fehlermeldungsformat). Bitte mal mit der aktuellen Version testen.

**Comment by M-Plu** [comment]
Soweit ich die Situation nachstellen konnte, ist das Problem seit heute im dev-Branch behoben.
