### ISSUE TITLE
Fehler in der Doku: Portweiterleitung

### ISSUE THREAD

**Issue by SchILD-Kloppenburg** [SVWS-NRW/SVWS-Server#15]
Auf folgender Doku-Seite
https://doku.svws-nrw.de/Deployment/Linux-Installer/
steht ganz unten "Portweiterleitung".
Beschrieben wird die Umleitung des Ports von 443 auf 8443, ausgeführt wird aber die Umleitung von 80 auf 8080.

**Comment by FPfotenhauer** [comment]
Wir kümmern uns darum, danke für die Meldung.

**Comment by familie-klein** [comment]
Danke, ... habs angepasst!
