### ISSUE TITLE
Kurs aufteilen

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/SVWS-Server#151]
![grafik](https://github.com/SVWS-NRW/SVWS-Server/assets/84628225/5150ca36-cd12-4cd0-a9f7-4f703f29d2d8)
Teilt man wie hier den D-LK1 auf (Aufteilen-Button), so wird der neu eingerichtete Kurs D-LK3 in Schiene 1 erzeugt. Das führt zu Kollisionen, er muss dann erst wieder verschoben werden. 
Ich schlage vor, dass der Tochterkurs direkt in die Schiene des Mutterkurses gesetzt wird. Das wird der Regelfall sein.

**Comment by benjaminbartsch** [comment]
... ist nun so angepasst, dass der neue Kurs die Schienen des alten Kurses übernimmt.
