### ISSUE TITLE
Verschieben eines Kurses wird nicht angezeigt

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/SVWS-Server#152]
Verschiebung eines leeren Kurses in eine andere Schiene ist problemlos möglich.
Verschiebt man einen Kurs, der Schüler enthält, wird diese Verschiebung nicht angezeigt, es sieht aus, als würde es nicht angenommen werden. 
Wechselt man dann in eine andere Ansichtund wieder zurück, wird der Kurs an der gewünschten Stelle angezeigt. Mehrfach Reproduziert.

**Comment by HHayen** [comment]
Möglicherweise handelte es sich um ein Performance-Problem. Gelegentlich dauert die Übernahme der Verschiebung sehr lange, oft geht es sehr schnell. Ich schließe das Ticket erst einmal und teste mal noch in anderen Umgebungen. Bei Bedarf hole ich es wieder hervor.

**Comment by benjaminbartsch** [comment]
... das Verschieben mit oder ohne SuS ist intern so programmiert, dass das keinen Unterschied macht. D.h. es passieren genau die selben Schritte und beides müsste gleich lang benötigen. Bei mir ist es manchmal so, dass nach einem ASSEMBLE oder REBUIILD und dem anschließend Start des Servers dieser sehr langsam ist. Dann ist aber jede Aktion extrem langsam. Die Ursache verstehe ich nicht. Was hilft ist aber, den Server neuzustarten.
