### ISSUE TITLE
Anzeige Koop-Schüler im Kurs

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/SVWS-Server#153]
Inzwischen wurde die Anzeige von Koop-Schülern in einem Kurs geändert. Das sieht jetzt so aus:
![grafik](https://github.com/SVWS-NRW/SVWS-Server/assets/84628225/9f0ef505-f768-4dcd-92b5-331a2e6f0697)
Vorher hätte statt der 30 dort 16|14 gestanden.
Finde ich so jetzt auch ok, aber dann muss anders ersichtlich werden, dass hier ein Kurs mit Externen vorliegt. Zahl fett oder ein * hinter den Kursnamen oder sonst irgendein Hinweis darauf.

**Comment by hmt** [comment]
@HHayen, was hältst Du hiervon? 
<img width="258" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/1246495/985ed7da-9d50-44b6-8043-d71b43bc74b9">

**Comment by HHayen** [comment]
Perfekt!!!! Danke!!Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: hmt ***@***.***> Datum: 28.03.24  20:38  (GMT+01:00) An: SVWS-NRW/SVWS-Server ***@***.***> Cc: HHayen ***@***.***>, Mention ***@***.***> Betreff: Re: [SVWS-NRW/SVWS-Server] Anzeige Koop-Schüler im Kurs (Issue #153) 
@HHayen, was hältst Du hiervon?
image.png (view on web)

**Comment by hmt** [comment]
Super, ist eingecheckt, Du kannst das Issue dann bitte schließen.
