### ISSUE TITLE
Fehler nach Server-Update in Münster

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/SVWS-Server#154]
Sind die aktuellen Serverdateien für die Installation in Münster korrekt?

Wir hatten früher schon einmal den Fehler beim Start von Schild. Aktuellste Schild-Version 84.10 und Server .11

<img width="232" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/75179015/56ca8e18-cbfa-49e9-ab98-8d61e6a8d2df">

Neue Mirgration der Datenbank klappt leider auch nicht über die Admin-Konsole.

**Comment by ThomasBachran** [comment]
Beim SVWS-Server ist die aktuelle Version die 0.8.12 (https://github.com/SVWS-NRW/SVWS-Server/releases/tag/v0.8.12). Wie lautet denn die Fehlermeldung im Log bei der Migration über die Admin-Konsole?

**Comment by AnneSchueller** [comment]
Eine ähnliche Fehlermeldung gab es mal im Zusammenhang mit Sonderzeichen/Umlauten im Passwort. Besteht das Passwort aus ä, ö, ß oder ähnliches?

Der Bug wurde soweit ich weiß behoben.

**Comment by kroerig** [comment]
Ja, der Bug kam von mir und wurde behoben.
Auf welcher Plattform läuft der Server?

**Comment by FPfotenhauer** [comment]
Der Bug hängt eigentlich immer damit zusammen, dass die Versionen nicht zusammen passen und ggf. die Mifration dadurch auch nicht korrekt durchlief.

Bitte Versionen kontrollieren und auch die Migration neu durchführen und prüfen.
