### ISSUE TITLE
Hochschulung im Client nicht sichtbar 

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/SVWS-Server#158]
Eine Hochschulung, die mit SchILD3 durchgeführt wird, wird nicht an den Client übertragen. 
In der DB werden sämtliche Abschnitte korrekt angelegt und die Schüler sind im neuen Jahrgang (in Schild3 und DBeaver)
Im Client tut sich allerdings nichts. Die Schule bleibt hier im alten Abschnitt und die Schüler in den "alten" Klassen.

**Comment by FPfotenhauer** [comment]
Welches Schuljahr wird denn oben links in der Ecke angezeigt?

**Comment by AnneSchueller** [comment]
Fehler gefunden. In Eigene Schule stimmt die Abschnitts-ID. Bei schueler wird diese nicht ersetzt.
Ich erstelle ein entsprechendes Issue in schild3

**Comment by AnneSchueller** [comment]
Ich kann das Issue nicht mehr öffnen....
Ist das hier Aufgabe vom Client?
https://github.com/SVWS-NRW/Schild3-BetaTest/issues/984#issuecomment-2061319046
