### ISSUE TITLE
Fehler in der Doku: Installation auf einem Ubuntu

### ISSUE THREAD

**Issue by SchILD-Kloppenburg** [SVWS-NRW/SVWS-Server#16]
Auf folgender Seite
https://doku.svws-nrw.de/Entwicklungsumgebungen/Eclipse-Ubuntu/
wird oben unter "Software-Installation" im apt-Befehl zwei Mal git installiert.

**Comment by manuel-klein** [comment]
Danke - wurde geändert ✔
