### ISSUE TITLE
Kursplanung nicht mehr aufrufbar nach Einrichtung eines neuen Faches

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#160]
Ich habe gerade eine neues Fach eingerichtet, und den LuPO Import gemacht. Der ist problemlos durchgelaufen, da war das neue Fach bereits drin. Danach konnte ich auf keine Kursplanung des Jahrgangs mehr zugreifen. Migriere jetzt die DB neu.

**Comment by ThomasBachran** [comment]
Wurde behoben.
