### ISSUE TITLE
Kursplanung: Kurs lässt sich nicht löschen

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#161]
Der SP-GK5 lässt sich nicht löschen.
0.8.13-SNAPSHOT be010d124cb39d14cfa6c325b8755eae3e96410b

![image](https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/48629041-3f6a-4708-bdc5-95fb84b20b9f)

**Comment by hmt** [comment]
Geht das Löschen nur bei diesem Kurs nicht? Kann man den Kurs über die Checkbox markieren und in der Nav-Leiste löschen? Macht theoretisch das gleiche, will nur herausfinden, ob es an der Api liegt oder an mir.

**Comment by NielsWL** [comment]
Es geht beides nicht, egal bei welchem Kurs

**Comment by hmt** [comment]
Danke, schaue ich mir an

**Comment by hmt** [comment]
Läuft der Server?  Hier geht es problemlos.

**Comment by NielsWL** [comment]
ja klar...

**Comment by hmt** [comment]
ok, das war nur zur Sicherheit, passiert mir selber oft genug...
Kommst Du mit den Entwicklertools zurecht?
Wäre interessant zu sehen, was die Konsole sagt bzw. der Netzwerkreiter. Wenn ich einen Kurs lösche, dann sieht es so aus:

<img width="1460" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/1246495/ce466735-b945-4916-9f07-c766481a1fd2">

**Comment by NielsWL** [comment]
![image](https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/aa644115-edc1-4096-b23f-90a9693a2fdb)

**Comment by hmt** [comment]
Der Server meldet einen Fehler. Wenn man auf die letzte Zeile unten klickt, kommt das weitere Fenster, da wäre interessant, was als `Response` kommt. Der Server selbst zeigt nichts in den Logs?

**Comment by NielsWL** [comment]
![image](https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/48e1c09b-cb4e-474a-ac5d-37f5a73b38a5)

**Comment by NielsWL** [comment]
Jetzt lässt sich der Kurs wieder löschen, danach kann ich in der entsprechenden Blockung aber keine Berechnung mehr durchführen. Auch ein Neustart des Servers und eine Neuanmeldung hilft nicht. Andere Blckungen des gleichen Jahrgangs im gleichen HJ lassen sich berechnen.
Version: 0.8.13-SNAPSHOT 6c5e3a059530954d1ec286a595c58d57a5fb764c

![image](https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/fe6ea618-9cb2-493f-b9b8-1868716ea72c)

**Comment by NielsWL** [comment]
In meinen restaurierten Blockungen lassen sich die Kurse problemlos löschen...

**Comment by ThomasBachran** [comment]
Ich gehe mal davon aus, dass die Regel KURS_KURSDIFFERENZ_BEI_DER_VISUALISIERUNG_IGNORIEREN auf dem Kurs ist. Diese wurde noch nicht richtig beim Löschen bzw. Zusammenlegen von Kurses berücksichtigt. Der Fehler sollte jetzt behoben sein.
