### ISSUE TITLE
Kursplanung: Anzeige der Kursdifferenzen

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#163]
Gibt es eine Möglichkeit, hinter den Differenzen die Fächer aufzuführen? Zumindest ab KD2...

![image](https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/efba8006-2c5c-452c-af90-d7147393b7bf)

**Comment by benjaminbartsch** [comment]
.... ist intern aufgenommen und wird geändert.

**Comment by benjaminbartsch** [comment]
So sieht es nun aus:

![grafik](https://github.com/SVWS-NRW/SVWS-Server/assets/83505980/a19ba417-4c4a-4bb6-8b60-cb02f627b3e3)

**Comment by NielsWL** [comment]
Top

**Comment by benjaminbartsch** [comment]
.... ach nee lieber lassen ;-)
