### ISSUE TITLE
Fachsortierung

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#165]
Wieso wird ein Fach, das zum Bereich Religionslehre gehört und von der Sortiernummer auch passt, ganz nach unten sortiert bei Oberstufe > Fächer?

![image](https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/5fcc2cd3-32a9-4846-8280-29903814d3ea)

![image](https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/0b189b31-48b4-4e2c-9680-6cbcbedfec79)

![image](https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/998f4b06-8f75-47b3-a97b-2470a1c8aaba)

**Comment by ThomasBachran** [comment]
Die Statistik-Kürzel KN und EN werden für Religion in der Oberstufe Laufbahn-technisch nicht unterstützt. Für die Laufbahnplanung werden die Statistik-Kürzel KR und ER unterstützt. Da diese Statistik-Kürzel für die Oberstufe nicht verwendet werden, wird das Fach am Ende nach den anderen Fächern angehangen.
