### ISSUE TITLE
Oberstufe: Scrollbalken verschwunden

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#166]
Oberstufe: In allen Bereichen (bis auf Kursplanung) sind die Scrollbalken verschwunden. Ich kann z.B. nur alle Fächer sehen, wenn ich die Skalierung des Browsers auf 90% setze.

![image](https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/96690f88-952a-41f6-ae02-8501fc04380a)

**Comment by hmt** [comment]
Die Scrollbalken sind je nach Betriebssystem versteckt oder deaktiv. Sobald ich aber im Bereich scrolle, werden sie sichtbar. Oder lassen sich bei Dir die Bereiche überhaupt nicht scrollen?

**Comment by NielsWL** [comment]
Es lässt sich gar nicht scrollen.

**Comment by hmt** [comment]
Ok, dann muss ich warten, bis sich das jemand mit Zugang zu einem Windows-Rechner anschaut. Auf dem Mac läuft es mit allen Browsern wie vorgesehen.

**Comment by FPfotenhauer** [comment]
Es gibt bei mir keinen horizontalen Scrollbalken, weil der Inhalt an das untere Ende angefügt wird.
Einen vertikalen Scrollbalken gibt es durchaus.
