### ISSUE TITLE
Kursplanung nach Löschen eines Kurses nicht aufrufbar 

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#168]
Die Berechnung einer Kursblockung ist nach Löschen eines Kurses, in dem noch Schüler waren, nicht mehr aufrufbar. Zusätzlich gibt es keine Möglichkeit, aus der Fehlermeldung herauszukommen. Nur ein erneuter LogIn funktioniert.
Version: 0.8.13-SNAPSHOT fc804129ea5411922da04cb5020dd9d3ff6bae6f

![image](https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/751d817c-3196-46f5-91a3-ebc0b0ca4225)

**Comment by NielsWL** [comment]
Ist reproduzierbar, diesmal aber mit einem anderen Fenster und dem Abbrechen-Button.

![image](https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/dacefe8e-bc5b-409e-95e4-50890575cc91)

**Comment by hmt** [comment]
Welche Fehlermeldung gibt es denn?
Zu finden in der Konsole der Entwicklertools, i.d.R. erreichbar über F12, wenn der rote Kasten oben rechts nicht angezeigt wird.

**Comment by ThomasBachran** [comment]
Es wurden im aktuellen Branch Fehler mit diesem Bezug behoben.

**Comment by NielsWL** [comment]
Der Feher besteht nach wie vor. 
0.8.14-SNAPSHOT f077360615f7e11f31028d46bd4c84cabf14dddb

![image](https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/0830e609-d88c-49ae-85ef-b8195fbbb714)

**Comment by hmt** [comment]
@NielsWL https://github.com/SVWS-NRW/SVWS-Server/issues/168#issuecomment-2058379970

**Comment by NielsWL** [comment]
Keine Fehlermeldung.

![image](https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/245ef241-9919-426e-b046-a76e5414dca2)

**Comment by ThomasBachran** [comment]
Hier scheint eine Diskrepanz zwischen dem State im Client und den Workern entstanden zu sein. Ggf. müssen hier Worker neu erstellt bzw. neu konfiguriert werden.

**Comment by hmt** [comment]
@benjaminbartsch wenn ich einen Kurs lösche, dann bleiben die Daten weiterhin unter `manager.daten()` und werden dort nicht entfernt. Das führt dann zu Diskrepanzen bei der Erstellung des Managers im Worker. Zur Erstellung des Workers müssen die Daten des Managers serialisiert werden und dann im Worker neu aufgebaut werden, es können keine Funktionen zum Worker geschickt werden, nur einfache Objekte.

**Comment by benjaminbartsch** [comment]
Ich suche den Fehler ...

**Comment by benjaminbartsch** [comment]
Das Problem ist nun behoben.
