### ISSUE TITLE
Verschieben von Klausuren nur mit ein wenig Geduld

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/SVWS-Server#169]
Im Reiter Klausurplanung/Kalender lassen sich die Klausuren nur schwer "packen".
z.B. können manche Klausuren nur verschoben werden, indem man sie weit oben anklickt und dann nach unten wegzieht. Andere dagegen muss man weit unten anklicken und nach links wegziehen. 

 

https://github.com/SVWS-NRW/SVWS-Server/assets/79116896/f832b34b-8159-4348-b32d-6ebf65a63ec1

**Comment by AnneSchueller** [comment]
Ich habe das nun mit Edge, Crome und Firefox getestet; 
mit localhost und nightly
und auch nochmal mit einem anderen Rechner.
Manche Klausuren kann ich nicht richtig anpacken und ziehen (das bezieht sich nur auf den Reiter Kalender)
Oder gibt es hierzu irgendwo Einstellungen, die ich übersehen haben könnte?

**Comment by mec0-de** [comment]
ok, dann muss ich nochmal schauen. Ich habe im DEV und auf dem Nightly getestet mit Safari und Firefox und kann alle Klausuren einwandfrei ziehen im Kalender. Ich habe keine Probleme, aber wie gesagt, ich schaue teste nochmal auf einem anderen (Windows-) Gerät und melde mich nochmal.
Danke schonmal!

**Comment by FPfotenhauer** [comment]
Welche Kriterien liegen denn vor, ob eine Stunde im Kalender "ablegbar" ist.
Ich habe das mal getestet un dja, einige Klausuren lassen sich an bestimmten Punkten nicht ablegen.
An anderen Stunden im Kalender klappt es dann. Mal mit Überlappungen und mal ohne.

**Comment by mec0-de** [comment]
Das Problem konnten wir mit Thomas Erfahrung aus dem Stundenplan reproduzieren und beheben. Kannst du nochmal testen und das Issue wieder aufmachen, falls es doch noch auftritt?

**Comment by AnneSchueller** [comment]
Funktioniert nun super!
