### ISSUE TITLE
Fehler in der Doku: MariaDB installieren

### ISSUE THREAD

**Issue by SchILD-Kloppenburg** [SVWS-NRW/SVWS-Server#17]
Auf dieser Seite 
https://doku.svws-nrw.de/Entwicklungsumgebungen/Eclipse-Ubuntu/
muss im Code-Abschnitt unter "MariaDB installieren" der Befehl "mariadb --version" stehen, also mit zwei Minuszeichen.

**Comment by manuel-klein** [comment]
Danke - wurde geändert ✔
