### ISSUE TITLE
DB-Backup

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#172]
Könnte der Dateiname beim Erstellen des Backups direkt das Datum und die Uhrzeit enthalten?
Beispiel: svwsdb_20240423_1718.sqlite

![image](https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/b2e56c04-4257-4f77-859a-3fc52f5eda2d)

**Comment by kroerig** [comment]
zur zweiten Frage:
Ja, über die API. z.B. mit curl durch einen Cron-Job oder Windows Taskplaner:

`curl -k -X 'GET' 'https://[SERVERNAME]/db/svws/export/sqlite' -H 'accept: application/vnd.sqlite3' -H 'Authorization: Basic [Anmeldedaten base64 codiert]' --output [DATEINAME].sqlite`

**Comment by NielsWL** [comment]
Die zweite Frage hatte gelöscht, dafür erstelle in ein zweites Issue...
