### ISSUE TITLE
Automatisches DB-Backup

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#173]
Die Frage, wie am besten ein automatisches DB-Backup erstellt wird, ist bestimmt vielschichtig. Evt könnten die Experten dazu mal etwas schreiben und diskutieren. Evt gibt es ja dann auch einen (besten) Weg, der überall funktioniert.

**Comment by hmt** [comment]
Kannst Du die Frage in die Diskussionen verschieben? Ich denke, dort ist es besser aufgehoben.
