### ISSUE TITLE
Laufbahnplanung: Schaltfläche gewünscht

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#176]
Ich würde mir eine Schaltfläche bei der individuellen Laufbahnplanung wünschen, mit der ich zu den Laufbahnen aller Schüler zurückkomme. Bisher kann ich nur zur Kursplanung springen.
Wenn man vor dem Schuljahr (im März/April/Mai) die Laufbahnen prüft und bei den einzelnen Schülern verändert hat, ist dieser Schritt zurück zu der Übersicht aller Laufbahnen regelmäßig durchzuführen.

Von hier:
![image](https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/a10ea549-2dde-41fd-8822-f77364437060)

Hierhin:
![image](https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/609a0963-a2cb-4138-abf2-28920e55a832)

**Comment by ThomasBachran** [comment]
Dies kann im Normalfall über den Back-Button im Browser erfolgen.
