### ISSUE TITLE
Import-/Export-Funktion für Klausurmodul

### ISSUE THREAD

**Issue by Pascal-KO** [SVWS-NRW/SVWS-Server#177]
Liebes SVWS-Team, 
ich habe mir den aktuellen Stand des Klausurplaners angesehen und mich mit Mirko über zukünftige Funktionen ausgetauscht. Wenn ich es richtig verstehe, ist zunächst geplant, eine jahrgangsstufenübergreifende Klausurplanung "nur" in dem Sinne einzurichten, dass auf Raumkollisionen geprüft wird. 

Aktuell ist es mit dem Multi-Klausurplaner von Benjamin möglich, eine breites Spektrum an Regeln zu nutzen, um z.B. Schülerbelastungen gleichmäßig zu verteilen, Lehrerwünsche zu berücksichtigen und auch Klausuren gleichmäßig auf den vorhandenen Unterricht zu verteilen, das Ganze dann auch noch über mehrere Jahrgangsstufen z.B. mit Blick auf die Raumkapazitäten. Das übersteigt den Klausurplanungs-Modus vom SVWS-Server derzeit deutlich.

Ich bin in Sorge, dass ich mit der Nutzung von Schild3 nicht mehr dazu in der Lage bin, den Multi-Klausurplaner zu verwenden und bitte daher dringend um die Einrichtung einer Import-/Export-Funktion (vergleichbar mit der aktuellen in Kurs42). 

Beste Grüße
Daniel

**Comment by FPfotenhauer** [comment]
Wir können aktuell keine Kapazitäten für die Progrmmierung solcher Schnittstellen bereit stellen.
Perspektivisch ist so oder so eine Abkehr von den ständigen Impoerten/ Exporten mit CSV gedacht.
Das Vorgehen der letzten 20 Jahre hat sich durch die Erfindung von APIs auch etwas überholt.
Man muss hier immer abwägen, was man an Fortschritt verwirft, wenn man neue Software so programmiert, dass alle Altlasten noch gehen. Nachteil ist sicherlich, dass man eine komplette Neuprogrammierung, was wir ja machen, nicht immer so an den Start bringen kann, dass diese alles kann, was in der alten Software so ging.

**Comment by NielsWL** [comment]
Ein ordentlicher Export bzw. über die API eine Möglichkeit die entsprechenden Daten auszulesen, sollte ja funktionieren. Der Import ist für die Klausuren und den Betrieb von Schild nicht notwendig. Den Import benötigte man bisher nur für die Darstellung über die Kurs42-Reports. Das lässt sich sicher anders regeln.
Trotzdem finde ich den Verlust der Funktionalitäten und Möglichkeiten, die uns in der Oberstufe bisher über Kurs42 zur Verfügung standen, nicht so einfach wegwischbar. Dass nicht alle "Altlasten" erhalten bleiben müssen, ist klar. Einige Dinge für die täglichen Arbeit sind ja auch schon übernommen bzw. sogar verbessert worden. Dennoch hängen auch an den Schulen Unmengen an Arbeitsstunden dran, Reports neu zu programmieren oder über andere (Dritt-)Programme zu ersetzen, wenn es denn überhaupt geht.

**Comment by kroerig** [comment]
Ich spiele jetzt mal den Bad Guy:
Das sind Drittprogramme. _Eigentlich_ sollte sich alles, was eine Schule im Alltag braucht mit den vom Ministerium und IT.NRW bereitgestellten Tools lösen lassen. Eigentlich deshalb weil die Anforderungen im Alltag bei manchen höher sind als das, was die bereitgestellten Tools leiten können. Und dann haben findige Benutzer sich halt eigene Lösungen gebaut. "Schatten IT" nennt man das. Und die Anwender haben sich an ihre eigenen Prozesse so sehr gewöhnt, dass sie sie für normal halten.

Es geht aber auch ohne sie. Vielleicht nicht so komfortabel und vielleicht sind auch die Ergebnisse nicht ganz so optimal, wie sie sein könnten, aber es geht. Und so unterstützen SchILD3 und der SVWS Server halt nur die Funktionen, die sie für einen Betrieb benötigen.

Wenn Drittanbieter hier andocken wollen, dann müssen sie ihre Software an die neuen Schnittstellen anpassen. Wie @FPfotenhauer schon schreibt: Es macht keinen Sinn in einer neuen Software Altlasten mitzuschleppen nur weil ein paar Anwender sich darauf aufbauend eigene Lösungen geschaffen haben (und der damalige Entwickler nicht mehr greifbar ist).

**Comment by NielsWL** [comment]
Also sind alle Kurs42-Reports "Schatten-IT"?

**Comment by kroerig** [comment]
Nein. Kurs42 ist ein offiziell zur Verfügung gestelltes Programm. Und die Aufgaben von Kurs42 übernimmt ja der SVWS Server.

**Comment by NielsWL** [comment]
Dann bin ich gespannt, denn insbesondere die umfangreichen und programmierbaren Reports von Kurs42 sind unabdingbar für die Oberstufenpraxis.
Und für den Klausurplaner muss ja "nur" ein Kurs42-Export, den es auch schon seit Jahren gibt, eingerichtet werden. Lässt sich bestimmt irgendwie über die API lösen, aber das ist nur für die wenigsten Informatiker (was ich auch nicht bin) selbstständig durchführbar.
