### ISSUE TITLE
Fehler beim Klick auf Lehrkräfte oder Klassen im Client

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/SVWS-Server#178]
Nach der Migration einer Originaldatenbank sieht zunächst in SchILD3 alles richtig aus.

Im Client erhalte ich beim Klick auf Lehrkräfte folgenden Fehler:
![image](https://github.com/SVWS-NRW/SVWS-Server/assets/79116896/a66a63a5-0a0d-4457-94c7-bc4978fd123a)

Ein Blick in die DB zeigt, dass es NULL Einträge in der Tabelle K_Lehrer beispielsweise beim Vornamen gibt. Kann dies damit zusammenhängen?

Beim Klicken auf Klasse und Kurse erscheint die gleiche Fehlermeldung.

**Comment by ThomasBachran** [comment]
Der Fehler wurde behoben und sollte im nächsten Pre-Release nicht wieder auftreten.
