### ISSUE TITLE
Sortierung der Klassen

### ISSUE THREAD

**Issue by atiw-webmaster** [SVWS-NRW/SVWS-Server#179]
Hallo.

Wir haben ein Testumgebung installiert und haben folgendes Problem:

Auf der Webseite - im Menü "Schüler" sind die Klassen in dem Drop-Down-Menü leider nicht alphabetisch nach dem Kürzel sortiert.
Außerdem sind in dem Drop-Down-Menü alte Klassen sichtbar, die in der SchILD3-Anwendung als nicht sichtbar markiert wurden.
 
Im Menü "Klassen" kann die Sortierung manuell mit einem Klick auf die Spalte "Kürzel" sortiert werden.

Gibt es eine Möglichkeit, die Klassen per default nach dem Kürzel zu sortieren?

Gruß
Marco

**Comment by FPfotenhauer** [comment]
Die Klassen werden nach der Sortierung sortiert.
Wenn man das Alphabetisch haben möchte, dann muss man das in Schild3 einmal in der Sortierung machen.

Bitte beachten: Im WebClient  wird es perspektivisch nur noch eine Sortierung geben! Die Sortierung SekII (die es in Schild3 noch gibt) entfällt im WebClient.

**Comment by atiw-webmaster** [comment]
Hallo Herr Pfotenhauer.
Ich habe mal ein wenig getestet und die Sortierung in SchILD3 angepasst.
Im WebClient gibt es aber noch eine Stelle, wo die Sortierung abweicht:

- Schild 3  - alles ok (Bild 1)
- WebClient / Klassen  - ok (Bild 2)
- WebClient / Schüler - Übersicht ok (Bild 3)
- WebClient / Schüler - Klassen-Filter falsche Sortierung (Bild 4)

![01](https://github.com/SVWS-NRW/SVWS-Server/assets/126562549/ec4d7277-2150-4a4a-a418-8c8a89310610)
![02](https://github.com/SVWS-NRW/SVWS-Server/assets/126562549/6616e65f-950a-4ca9-8a66-f77114d80389)
![03](https://github.com/SVWS-NRW/SVWS-Server/assets/126562549/b0a683e7-f38a-44b2-9a27-0a07ec35aa9b)
![04](https://github.com/SVWS-NRW/SVWS-Server/assets/126562549/bb7843f0-7382-4669-9c3d-e69a91327224)

**Comment by ThomasBachran** [comment]
Vielen Dank für die Rückmeldung. Die Sortierung im Filter sollte natürlich entsprechend sein.

**Comment by ThomasBachran** [comment]
Wird im nächsten Pre-Release behoben sein.

**Comment by atiw-webmaster** [comment]
> Vielen Dank für die Rückmeldung. Die Sortierung im Filter sollte natürlich entsprechend sein.

Hallo Herr Bachran.
Ich habe die aktuelle Server-Version installiert und das Problem mit der Sortierung im Filter und "Schüler" ist bei mir immer noch da?!  

Siehe original-Post:
- WebClient / Schüler - Klassen-Filter falsche Sortierung (Bild 4)

**Comment by atiw-webmaster** [comment]
Das ist die installierte Version: 0.8.15 45ad17fcf385a1380a1f8711e97ade31c781d599

**Comment by hmt** [comment]
Es handelt sich vermutlich nicht um einen Fehler. Wenn sie bei der Klassenansicht den Filter `nur sichtbar` entfernen, dann müssten die Klassen in der exakt gleichen Reihenfolge angezeigt werden. Die Markierung `nicht sichtbar` kann in Zukunft entfallen, da die Klassen gegenüber Schild 2 Schuljahresabschnittbezogen gespeichert werden und somit leere Klassen entsprechend gelöscht werden können. Dadurch wird die Filterung nicht mehr benötigt.
Klärt das die Frage/die Fehleranzeige?

**Comment by atiw-webmaster** [comment]
Der "Fehler" in der Sortierung ist nicht in der Klassenansicht, sondern in der Schüleransicht.
siehe oben (WebClient / Schüler - Klassen-Filter falsche Sortierung (Bild 4) )

**Comment by ThomasBachran** [comment]
@atiw-webmaster : An genau der Stelle ist die Sortierung der Klassen bei dem Schülerfilter aber korrekt und würde auch mir der Ansicht bei den Klassen übereinstimmen. Das liegt an dem von @hmt beschriebenen Filter. Bei dem Übergang von Schild 2 zum SVWS-Server wurden Schuljahresabschnittsbezogene Klassen eingeführt. Die alten Klassen wurden zunächst für alle Schuljahresabschnitte angelegt - was eigentlich zu viel ist. Die jetztige Klassendefinition sollte dann "aufgeräumt" werden, da im aktuellen Abschnitt die Klassen von früher nicht mehr benötigt werden. Das Flag sichtbar ist damit nicht mehr notwendig und wird dann verschwinden. Das unterschiedliche Verhalten liegt aktuell daran, dass die Übersichten in Schild 3 und im Client das Flag sichtbar noch berücksichtigen. Im Client wird das Verhalten ab dem nächsten Pre-Release angepasst sein, so dass sie dort übereinstimmen.

**Comment by atiw-webmaster** [comment]
ok, vielen Dank. 
Ich werde mir das genauer anschauen und die alten klassen mal löschen.
