### ISSUE TITLE
Linux-Installer installiert keine Datenbank

### ISSUE THREAD

**Issue by SchILD-Kloppenburg** [SVWS-NRW/SVWS-Server#18]
Wir haben den Linux-Installer unter Debian 12 ausgeführt und wollten eine Testdatenbank anlegen. Es wird zwar ein Schema svws angelegt, dieses ist jedoch komplett leer.

**Comment by manuel-klein** [comment]
Danke für die Meldung, ich gebe das weiter.

**Comment by FPfotenhauer** [comment]
Ist das Schema komplett leer (ohne Tabellen)?
Oder sind nur keine Daten drin?

**Comment by kroerig** [comment]
Den Effekt habe ich hier auch jedes mal, wenn ich die Docker-Container wegwerfe oder nachdem eine DB Migration abgebrochen ist. Der SVWS-Server startet nicht ohne ein vollständiges DB-Schema. Aber wenn der SVWS nicht läuft, lässt ich auch kein Import starten.

Der SVWS muss auch ohne DB-Schema starten um einen Import zu ermöglichen.

**Comment by mbrass** [comment]
> Wir haben den Linux-Installer unter Debian 12 ausgeführt und wollten eine Testdatenbank anlegen. Es wird zwar ein Schema svws angelegt, dieses ist jedoch komplett leer.

Haben Sie die Datenbank selbst installiert oder wurde diese mit dem Skript eingerichtet?
Haben Sie im Dialog ausgewählt das Testdaten importiert werden soll? 
Wenn ja haben Sie das korrekte Password für diese angeben?

**Comment by SchILD-Kloppenburg** [comment]
Die Datenbank wurde mit dem Skript eingerichtet.
Im Dialog haben wir ausgewählt, Testdaten zu importieren.
Zum Passwort:  Wenn ich das richtig verstanden habe, benötige ich für die Testdatenbanken kein Passwort, sondern für das Schema. Soweit ich mich erinnere, haben wir svwsadmin eingegeben.

**Comment by FPfotenhauer** [comment]
Das Passwort für die Testdatenbanken ist das Access-Kennwort.
