### ISSUE TITLE
Übertragene Blockung deaktivieren

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/SVWS-Server#180]
Während einer Fortbildung zum SVWS-Client mit einigen Fachberatern kam der große Wunsch auf, dass man eine Blockung, die beispielsweise für die kommende EF bereits übertragen wurde, nochmal deaktivieren kann, sodass Umwahlen nicht über die Lernabschnitte laufen müssen, sondern in der Laufbahn hier im ausgegrauten Bereich. Dadurch bekommt man auch direkt eine Rückmeldung, ob das ohne weiteres möglich ist:

![image](https://github.com/SVWS-NRW/SVWS-Server/assets/79116896/6438c1c3-8bf7-4756-bfb5-640c8bc104c6)

**Comment by ThomasBachran** [comment]
Die benötigte Funktionalität ist in der API (https://localhost/debug/index.html#/Server/revertActivateGostBlockungsergebnis) jetzt verfügbar. Die Integration in den Client steht noch aus.

**Comment by hmt** [comment]
<img width="382" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/1246495/4f4cd294-9534-4a97-8d41-e5f7dd1de378">
Man kann nun über das Halbjahr eine bereits persistierte Blockung wieder deaktivieren. Dazu poppt dann ein entsprechendes Modal auf.
