### ISSUE TITLE
Kataloge: Standardsortierung wiederherstellen

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/SVWS-Server#184]
In Katalogen, z.B. Fächer, sollte ein Knopf stehen, um nach der "Sortierung" zu sortieren.

Lasse ich mir die Fächern nach Kürzel oder Bezeichnung anzeigen, muss man erst einmal den Katalog verlassen und neu aufrufen, um zur Standardsortierung zurückzukehren.

**Comment by hmt** [comment]
Bei den Fächern sollte es nun wieder funktionieren. Die anderen Kataloge folgen noch

**Comment by ThomasBachran** [comment]
@hmt, @FrodBRA : Welche Auswahllisten sind hier denn alles betroffen?

**Comment by ThomasBachran** [comment]
@FrodBRA : Ich schließe das Issue an dieser Stelle, habe den Aspekt aber in unsere interne Planung übernommen.
