### ISSUE TITLE
Kataloge: Nicht-Sichtbare Einträge in der Auswahlliste ausblenden

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/SVWS-Server#185]
Kataloge sollten in der Auswahlliste einen Schalter haben, mit dem sich steuern lässt, ob "nicht sichtbare" Einträge in der Auswahlliste angezeigt werden oder nicht.

(Beispiel: Fächer)

**Comment by hmt** [comment]
Wird bearbeitet, die Fächer haben nun einen Schalter für Sichtbar/Unsichtbar. Wird weiter verbessert und in anderen Katalogen ergänzt

**Comment by ThomasBachran** [comment]
@hmt, @FrodBRA : Auch dieser Aspekt ist in unsere interne Planung übernommen worden. Ich schließe daher das Issue an dieser Stelle.
