### ISSUE TITLE
Kataloge -> Fächer -> Maximale Zeichenzahl bei Fachbemerkungen: Negative Werte zugelassen; Feld lässt sich nicht wieder leeren

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/SVWS-Server#186]
Das Feld "Maximale Zeichenanzahl bei Fachmerkungen" ist im Standard leer

Klickt man die Hoch- und Runterpfeile an, initialisiert sich das Feld mit dem Wert "0" und zählt hoch und runter.

- Es lassen sich negative Werte einstellen, dies sollte nicht möglich sein.
- Es lassen sich beliebig hohe Werte einstellen.
- Stellt man den Wert 0 ODER negative Werte ein, werden diese auch für andere Fächer bei Änderung des Faches angezeigt.
- Erst wenn man den Katalog neu öffnet ODER ein Fach mit einem positiven Wert anklickt, wird bei einem anderen Fach wieder der "Standard-Ungesetzt" Status angezeigt.

Was bedeutet der Wert von "0"? Das scheint "keine Grenze" zu sein, korrekt?

**Comment by hmt** [comment]
> Das Feld "Maximale Zeichenanzahl bei Fachmerkungen" ist im Standard leer
> 
> Klickt man die Hoch- und Runterpfeile an, initialisiert sich das Feld mit dem Wert "0" und zählt hoch und runter.
> 
>     * Es lassen sich negative Werte einstellen, dies sollte nicht möglich sein.
ist korrigiert
> 
>     * Es lassen sich beliebig hohe Werte einstellen.
ist korrigiert
> 
>     * Stellt man den Wert 0 ODER negative Werte ein, werden diese auch für andere Fächer bei Änderung des Faches angezeigt.

Das sollte nun behoben sein.

>     * Erst wenn man den Katalog neu öffnet ODER ein Fach mit einem positiven Wert anklickt, wird bei einem anderen Fach wieder der "Standard-Ungesetzt" Status angezeigt.
> 
> 
> Was bedeutet der Wert von "0"? Das scheint "keine Grenze" zu sein, korrekt?
0 ist momentan nicht mehr zulässig. Es sind Werte zwischen 1 und 2.147.483.646 erlaubt, das ist der maximale interne Wert der Java/JavaScript-Integer. Letzteres wird automatisch bei ungültigen Eingaben gesetzt.

Da sind nun auch noch andere Sachen aufgetaucht, die behoben werden müssen. Dazu wird es ein neues Issue geben. Danke für die Fehlermeldung!
