### ISSUE TITLE
Kataloge -> Religionen: Religionen sollten "nicht sichtbar" gestellt werden können + Sortiermöglichkeit fehlt

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/SVWS-Server#188]
Im Katalog besteht nicht die Möglichkeit,

- Die Sichtbarkeit einzustellen (siehe hierzu auch https://github.com/SVWS-NRW/SVWS-Server/issues/185 )
- Die Sortierreihenfolge zu ändern

Entsprechend sollten "unsichtbare" Religionen auch per Schalter in der Auswahlliste ein- und ausgeblendet werden können.

**Comment by hmt** [comment]
Ist nun vorhanden und kann geschlossen werden.
