### ISSUE TITLE
Linux installer testet nicht auf Webserver

### ISSUE THREAD

**Issue by SchILD-Kloppenburg** [SVWS-NRW/SVWS-Server#19]
Wir haben auf einem frisch gemieteten Debian-Server das Installtionsskript für Linux laufen lassen. Dabei haben wir festgestellt, dass der SVWS-Server zwar installiert wurde, mangels eines Webservers aber nicht lief.
Bitte erweitert das Skript so, dass darauf hingewiesen wird, dass ein Webserver vorhanden ist.
Oder er wird gleich automatisch installiert...

**Comment by manuel-klein** [comment]
Der Webserver (jetty) ist eigentlich integriert. In .env-Datei (im Installationsverzeichnis des SVWS-Server, z.B. /opt/app/svws-server, unter /svws-server-app) müsste stehen, auf welchem Port der funkt.

**Comment by FPfotenhauer** [comment]
Der Server wird per Default auf Port 8443 gesetzt. Vielleicht ist das schon das Problem.

Also Aufruf per https://localhost:8443 oder https:// meinedomain.de:8443

**Comment by FPfotenhauer** [comment]
Da kein Webserver benötigt wird, schließe ich mal das Issue.
Wenn der SVWS-Server nicht läuft, wird das einen anderen Grund haben, für den man ein neues Issue aufmachen kann.
