### ISSUE TITLE
Stundenplan: manuelles Verschieben von Stunden 

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#191]
Ich kann im Stunden einmal gesetzte Stunden nicht manuell verschieben. Es erscheint zwar die Hand, aber es lässt sich nichts greifen.

**Comment by hmt** [comment]
Aktuell kann man nur in der Stundenplan-App unter Klassen den Unterricht verschieben. Meinst Du das oder einen anderen Stundenplan? Es gibt ja durchaus mehrere Orte im Client, wo ein Stundenplan angezeigt wird.

**Comment by NielsWL** [comment]
Genau da geht es nicht...

**Comment by hmt** [comment]
Auf der nightly-Seite habe ich gerade den Stundenplan der EF mit allen Kursen und Schienen frei bewegen und verschieben können. Kannst Du mir eine Schritt-Für-Schritt Anleitung machen, damit ich das auf dem nightly nachvollziehen kann? https://nightly.svws-nrw.de/#/1/stundenplan/1/klasse

**Comment by NielsWL** [comment]
Im Chrome kann ich nichts verschieben.
![image](https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/06d66ce3-00f6-4dec-b3e4-975d4a20fa87)

**Comment by hmt** [comment]
ok, danke, das stimmt. Danke für den Hinweis.

**Comment by hmt** [comment]
Problem gefunden, Lösung noch keine.

Die Komponente `StundenplanAnsicht.vue` bekommt von `SStundenplanKlasse.vue` die `onDrag`-Methode und auch `dragValue` als Props übergeben.

```ts {2}
	function onDrag(data: StundenplanAnsichtDragData, event?: DragEvent) {
		dragData.value = data;
		if (event === undefined)
			return;
		let id = '';
		if (data instanceof StundenplanKlassenunterricht)
			id = `klasse-${data.idFach}-${data.idKlasse}`;
		else if (data instanceof StundenplanKurs)
			id = `kurs-${data.id}`;
		else if (dragData.value instanceof StundenplanSchiene || dragData.value?.isTranspiledInstanceOf("java.util.List"))
			id = `schiene-${dragData.value.hashCode().toString()}`;
		const element = document.getElementById(id);
		if ((element !== null) && (event.dataTransfer !== null))
			event.dataTransfer?.setDragImage(element, 0, 0);
	}
```

Die Zuweisung in Zeile 2 scheint ein sofortiges `dragEnd`-Event in Chrome auszulösen, was aber nur vorkommt, wenn man innerhalb der Zeitraster etwas ziehen will. Die Seitenleiste ist ok. Offenbar löst das `dragData` bei Neuzuweisung in der `StundenplanAnsicht` als Prop dieses Event aus.

**Comment by ThomasBachran** [comment]
Ist im dev-Branch jetzt behoben.
