### ISSUE TITLE
Stundenplan Infobox "Umstellung AB-Wochen" -> "Abbrechen" tut nix, ok beendet die Box

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/SVWS-Server#192]
Klicke ich bei der "Umstellung auf AB-Wochen", funktioniert der Schalter "Abbrechen" nicht, "Ok" beendet die Infobox.

**Comment by hmt** [comment]
Fehler wurde behoben, es gibt nun einen Folgefehler, der ebenfalls zur Zeit bearbeitet wird. Das Issue kann nun aber geschlossen werden.
