### ISSUE TITLE
Schüler -> Individualdaten: Fehlender Absatz zwischen "Migrationshintergrund" und der  Checkbox "Migrationshintergrund vorhanden"

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/SVWS-Server#194]
Version: Nightly 0.8.15-SNAPSHOT 8bebd07117729b48c16cb72abd3a3762ac18de01

Bei den anderen Überschriften folgt ein größerer Absatz, die Checkbox steht sehr dicht unter der Überschrift

**Comment by hmt** [comment]
Das passiert nur, wenn der Client auf weniger als 1288pixel verkleinert wird. Ich habe aber etwas Platz geschaffen: 
<img width="515" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/1246495/843ad0ef-2fef-45a7-9da3-fb9987389f65">
"Normal" sieht es so aus:
<img width="537" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/1246495/8dfd7d1c-1bac-4a8a-a09b-30bc6ec85781">
