### ISSUE TITLE
Änderung der Staatsangehörigkeit von bezeichnung --> bezeichnungSuche  in schild3/export/csv 

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/SVWS-Server#196]
In Schild3 wird das Feld BezeichnungSuche für die Angabe der Staatsangehörigkeiten genutzt, da im Feld Bezeichnung teilweise benutzerunfreundlichen Bezeichnungen hinterlegt sind, wie beispielsweise hier (Plurinationaler Staat Bolivien) :

![image003](https://github.com/SVWS-NRW/SVWS-Server/assets/79116896/e6cc17fa-3065-43d8-8bc5-9f04ff8ed92c)

In der Liste der für den Export (CSV, Excel) verfügbaren Felder taucht die Feldbezeichnung anstatt die der BezeichnungSuche auf. Gemeint ist diese Methode:
![image004](https://github.com/SVWS-NRW/SVWS-Server/assets/79116896/5b6468a0-beed-4296-a1b9-62a209244431)

Alle Einträge, die im Feld „LookupFeldname“ den Eintrag „mtblStaat.bezeichnung“ haben, müssen auf „mtblStaat.bezeichnungSuche“ geändert werden.

![image005](https://github.com/SVWS-NRW/SVWS-Server/assets/79116896/48d58950-6a95-49ab-87f7-c43070dffa64)

**Comment by hmt** [comment]
Das hatten wir an anderer Stelle schon einmal als Issue. Da sind auch teilweise falsche Schreibweisen drin, z.B. 
* `Côte d’Ivoire` mit falschem Apostroph. 
* Iran wird voll ausgeschrieben in der Suche: `"Iran", "Islamische Republik Iran"` andere Republiken nicht. 
* `São Tomé und Príncipe` wird sich kaum finden lassen mit einer deutschen Tastatur, wenn man nicht weiß, wie es geht.

Einfacher wäre es wahrscheinlich wenn ein Array mit Schreibweisen zur Verfügung steht, unter denen der Eintrag gefunden werden kann. Da könnte dann vereinfacht z.B. neben der korrekten Schreibweise auch `Sao Tome und Principe` stehen.
