### ISSUE TITLE
Abfragefehler beim Anzeigetext "nicht-unterrichtliche Tätigkeit"

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/SVWS-Server#197]
Auszug von hier: https://github.com/SVWS-NRW/Schild3-BetaTest/issues/894

Hier liegt ein Fehler in der entsprechenden Abfrage vor. Da diese aber jetzt vom SVWS-Server geliefert wird, müsste das auch dort angepasst werden. Dazu ist bei dem Eintrag für den Anzeigetext "nicht-unterrichtliche Tätigkeit" der Inhalt von "LookupSQLText" wie folgt zu ersetzen:

falsche Abfrage
select A.AnrechnungStd from LehrerAbschnittsdaten A where A.Lehrer_ID=% order by A.Jahr desc, A.Abschnitt desc

korrekte Abfrage
select LA.AnrechnungStd from LehrerAbschnittsdaten LA, EigeneSchule ES where LA.Lehrer_ID=% AND LA.Schuljahresabschnitts_ID=ES.Schuljahresabschnitts_ID

**Comment by ThomasBachran** [comment]
@AnneSchueller : Das wurde im aktuellen Entwicklungsbranch angepasst.
