### ISSUE TITLE
Abiturjahrgang hinzufügen funktioniert nicht

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#198]
Version: 0.8.15-SNAPSHOT 0e68bb752b29071e75087c8fe4447e593822f834
Browser: Chrome

![image](https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/d30117eb-fd01-4fab-88ad-26a467798623)

**Comment by ThomasBachran** [comment]
@NielsWL : Das Problem sollte jetzt im dev-Branch behoben sein. Kannst du das bitte bei dir nochmal überprüfen?

**Comment by NielsWL** [comment]
Funktioniert wieder. Die Q1 und Q2, die vorher nicht gingen, waren sofort da, ohne dass ich es neu hätte machen müssen.
