### ISSUE TITLE
SVWS-Server 0.8.14: Fehlende Fehlerbehandlung in SVWSKonfiguration.java

### ISSUE THREAD

**Issue by T-Hagel-SK** [SVWS-NRW/SVWS-Server#199]
Hallo zusammen,
wir haben nochmal von vorne begonnen, nachdem wir weiterhin Probleme hatten, neue Schemas anzulegen und Datenbanken zu migrieren. Da auch danach die Probleme blieben, haben wir angefangen auf die Fehlersuche zu gehen. 

Am Ende dieser Vorgänge bekamen wir immer wieder die folgende Fehlermeldung angezeigt:
_Prüfe, ob das Schema bereits existiert...
  ist noch nicht vorhanden
Erstelle Ziel-Schema für MARIA_DB (servermame:port/schemaname)
  -> Verbinde mit einem DB-Root-Manager zu der Ziel-DB...
    - Datenbank-Verbindung erfolgreich aufgebaut (driver='MARIA_DB', schema='S387', location='servername:port', user='schemaname-admin')
    - Prüfe, ob der Benutzer noch angelegt werden kann oder ob das angebene Kennwort zu einem existierenden Benutzer passt... [OK]
    - Entferne aus der Ziel-DB das alte Schema, falls vorhanden... [OK]
    - Erstelle in der Ziel-DB das Schema und den Admin-Benutzer: [Fehler]
  -> Erstellen fehlgeschlagen! (Das Schema konnte nicht erstellt werden oder der Admin-Benutzer konnte nicht angelegt werden.)_

Hier habe ich dann unsere Datenbankexperten dazugezogen und konnten dann beim Betrachten des MariaDB-Servers auf erweiterter Logebene feststellen, dass hier nicht nur das Schema angelegt wurde, sondern auch der Admin-Benutzer. Die Fehlermeldung "Erstellen fehlgeschlagen! (Das Schema ...)" blieb jedoch hartnäckig dieser Meinung, dass das eben nicht der Fall sei.

Also haben wir über GitHub im Quellcode versucht herauszufinden, was da im einzelnen passiert und welche Funktionen aufgerufen werden. Am Ende wurde der Kollege in der Datei svws-db/src/main/java/de/svws_nrw/config/SVWSKonfiguration.java in der Zeile 265 fündig. In der catch-Anweisung fehlt leider eine passende Fehlerbehandlung. Denn die hätte eigentlich anzeigen müssen, dass hier die Benutzerrechte des Webserver-Users nicht ausreichen, um die Json- und XML-Config-Dateien zu schreiben.

Könnte das für nachfolgende Versionen noch ausgebessert werden ?

Schöne Grüße
Thomas Hagel

Stadt Köln
Fachanwendungsbetreuung / SchILD3-Koordinator

**Comment by ThomasBachran** [comment]
Vielen Dank für die detaillierte Rückmeldung! Die war sehr hilfreich. Wir haben das bei uns bereits angepasst. Im nächsten Pre-Release sollte die Fehlermeldung dann besser sein.

**Comment by T-Hagel-SK** [comment]
Bestätige, der Fehler wurde in der 0.8.15 behoben. 👍 

Dafür haben wir nun ein anderes Problem, aber hier muss ich erst mal wieder schauen, wo das gelagert ist (es wird zwar beim Schemaanlegen ein Benutzer erstellt, aber kein Schema) ...
