### ISSUE TITLE
Nicht mögliche Fächerkombinationen in Lupo

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/SVWS-Server#2]
Ich schätze, das der Issue hier richtig sein sollte:
Bei den nicht möglichen Fächerkombinationen in Q1/Q2 sollte die Kursart ZK aufgenommen werden. So können die Schule Konstellationen verwirklichen, dass z.B. nur ein ZK gewählt werden kann. Auf diese Weise können ZKs ggf. im Vormittag verblockt werden.

Das ist schon ein lange gehegter Wunsch vieler Schulen, der in Lupo nicht umgesetzt wurde, weil es dort ein filigranes Konstrukt war.

**Comment by ThomasBachran** [comment]
Die Möglichkeiten bei der Definition der Regeln werden hier ausgeweitet. Dabei wird die Kursart frei unter den Kursarten der gymnasialen Oberstufe auswählbar sein. Es werden also prinzipiell auch Regeln bezüglich ZK, PJK und VTF möglich.
