### ISSUE TITLE
Kursänderung wird nicht unmittelbar synchronisiert im Lernabschnitt des Schülers

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/SVWS-Server#200]
![image](https://github.com/SVWS-NRW/SVWS-Server/assets/79116896/e96f601c-4403-405f-90a9-0082ff7ad01b)

Anschließend auf Synchronisieren.
Im Reiter Lernabschnitte bleibt der Kurs bei MU-GK3.
Erst mit einem Switch auf den aktuellen Lernabschnitt und wieder zurück wird die Anpassung vorgenommen.

**Comment by ThomasBachran** [comment]
@AnneSchueller : Das kann ich aktuell im dev-Branch nicht mehr nachvollziehen. Kannst du das bei dir nochmal prüfen?

**Comment by AnneSchueller** [comment]
Im Dev klappt das nun beim direkten Verschieben eines Kurses.
Nicht aber beim Löschen eines Kurses:
Nach dem Verschieben eines Kurses in  "Kurse hier zum Löschen ablegen" ist der Kurs noch im  Lernabschnitt drin.
Weist man dann diesen nicht verteilten Kurs erneut einem anderen Kurs zu bleibt der alte im Lernabschnitt erhalten.
(Im Screenshot oben: MU-GK3 in den Mülleimer. Dann MU-GK nach MU-GK2. Im Lernabschnitt ist nun noch MU-GK3 gespeichert)

**Comment by ThomasBachran** [comment]
@AnneSchueller : Ich kann bei mir keinen Fehler nachvollziehen:
- im ersten Schritt entferne ich den Kurs in der Blockung und synchronisiere dann. Hier wird dann der alte Kurs und die alte Zuordnung nicht gelöscht (siehe Beschreibung des Prozesses)
- im zweiten Schritt ordne ich MU-GK2 zu. Danach muss ich nochmals synchronisieren. Danach ist der Kurs dann auch korrekt in den Leistungsddaten zugeordnet.

Hast du eventuell die Leistungsdaten zu MU zwischendurch manuell gelöscht?

**Comment by AnneSchueller** [comment]
Aufgrund der Beschreibung war mir nicht ganz klar, dass Kurse die ich beim Schüler in der Blockung entferne nicht mit synchronisiert werden. So klappt es jetzt.
