### ISSUE TITLE
Änderungen bei Fächern sind nicht im Beratungsreiter sichtbar

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/SVWS-Server#201]
**Fächer nach Anlegen des Abiturjahrgangs:** (wird korrekt übernommen)
![image](https://github.com/SVWS-NRW/SVWS-Server/assets/79116896/c31aec85-17ba-446a-8fb4-26a07881c025)

**Anpassungen der Fächer für den Abiturjahrgang:**
![image](https://github.com/SVWS-NRW/SVWS-Server/assets/79116896/f332814d-49a4-458a-8e2b-e8ec93947736)

**Änderungen in der Beratungsvorlage nicht sichtbar:**
![image](https://github.com/SVWS-NRW/SVWS-Server/assets/79116896/bee3b664-091b-4dfd-8bd1-a2ad78cee725)

**Comment by ThomasBachran** [comment]
Das Problem wurde behoben und ist in Kürze im dev-Branch verfügbar.
