### ISSUE TITLE
Fehlermeldung beim Switch auf Stundenplan 

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/SVWS-Server#202]
Es kommt zu folgender Fehlermeldung beim Klick auf Stundenplan:
![image](https://github.com/SVWS-NRW/SVWS-Server/assets/79116896/f65f6a80-7dc5-438a-8b62-a6d2f435d806)

Dabei ist der Kollege mit Schlüssel 133 unsichtbar und nicht statistikrelevant. Löscht man ihn aus der DB kommt hier keine Fehlermeldung.

@ThomasBachran: Ich lege Dir die DB in die Membox  in Austauschordner Schuldaten/Thomas

**Comment by ThomasBachran** [comment]
Der Fehler wurde intern behoben, ist aber zur Zeit noch nicht in dem dev-Branch behoben. Dies passiert aber in den nächsten Tagen.
