### ISSUE TITLE
Nach Import von .lup-Dateien fehlt der Laufbahnplanungsreiter bei Schülern

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/SVWS-Server#203]
Der Abiturjahrgang wird korrekt angelegt.
Wahlen sind korrekt importiert.
Bei den Schülern wird der Reiter Laufbahnplanung allerdings erst nach Neuanmeldung sichtbar.

**Comment by ThomasBachran** [comment]
@AnneSchueller : Ist das aktuell noch der Fall?

**Comment by AnneSchueller** [comment]
Mit der neuen Version funktioniert das direkte Anlegen der Laufbahnen im Schülerreiter.
