### ISSUE TITLE
SVWS-Server 0.8.15: DBRootManager.java prüft nicht ob der Datenbank-Benutzer nicht der Root-User ist

### ISSUE THREAD

**Issue by T-Hagel-SK** [SVWS-NRW/SVWS-Server#205]
Hallo zusammen,
wir haben in Köln weiterhin Probleme den SVWS-Server komplett zum Laufen zu bekommen. Nachdem Ribeka kürzlich die neue Version des Schemaverwaltungsprogramms herausgebracht hat, habe ich dort festgestellt, dass beim Schreiben eines Schemas nicht geprüft wird, ob der angegebene Datenbankbenutzer bereits existiert und ihn dann einfach mit geringeren Rechten versieht. Da ich dabei den Root-User angegeben hatte, zerschießt mir das Programm damit reproduzierbar den Root-User.

Das ist in Klärung bei Ribeka. Da ich seit der Version 0.8.15 aber beim Datenbankmigrieren, sowie beim losen Anlegen eines leeren Schemas aber wieder eine Fehlermeldung erhalten habe, dass der Benutzer oder das Schema nicht angelegt werden konnte, hatte ich mich wieder auf die Suche durch den Quellcode gemacht und dabei in der Datei DBRootManager.java die Funktion dropDBUserIfExist gefunden.

Pfad:
svws-db-utils/src/main/java/de/svws_nrw/db/utils/schema/DBRootManager.java

Soweit ich den Quellcode verstehe prüft der zwar, ob ein User existiert, er prüft aber nicht, ob dieser User nicht "zufällig" auch der oder ein Root-User ist. Oder ?

An anderen Stellen im Quellcode ist die Rede von root- und admin-Usern. Evtl. wären die Abfragen, ob ein Benutzer gelöscht werden soll um diese beiden Zusatzabfragen noch zu prüfen. Oder im admin-User-Fall wenigstens per Rückfrage am Bildschirm, ob man sich wirklich sehr sicher sei, dass ein admin-User gelöscht werden soll.

In unserem Fall war das jetzt beim Schema-Anlegen offenbar nicht der Fall, bzw. diese Funktion kam hier offenbar nicht zum Zuge, da ich mit dem root-User weiterhin in der MySQL Workbench Tabellen anlegen und löschen lassen kann.

Sobald ich mehr Infos zu unserem Problem habe, dass ich über den SVWS-Server keine Schemas (aber Benutzer) mehr anlegen kann, mache ich dazu ein eigenes Ticket auf...

Schöne Grüße
Thomas Hagel

Stadt Köln
Fachanwendungsbetreuung

**Comment by ThomasBachran** [comment]
Hallo Herr Hagel,

eine Rückfrage, ob ich Ihr Szenario richtig verstanden habe. Sie planen den priviligierten Datenbank-Benutzer auch für den Zugriff vom SVWS-Server auf die Datenbank-Schemata zu nutzen?

Hier ist mMn eine Trennung des DB-Nutzers für die Schema-Administration mit priviligierten Rechten und den jeweiligen Datenbank-Benutzer für den Zugriff auf die einzelnen SVWS-DB-Schemata hilfreich.

Beim Löschen eines Schemas `X` werden die Rechte für den zugeordneten Benutzer des Schemas `X` auf `X` entsprechend eingeschränkt. Hier wird sozusagen aufgeräumt. Handelt es sich hier um den priviligierten Benutzer so beschneidet er seine Rechte.

**Comment by ThomasBachran** [comment]
Der Admin-Client wird ab dem nächsten Pre-Release
- bei den einzelnen Schemata oben neben der Revision auch den Datenbankbenutzer anzeigen, der dem Schema in Der SVWS-Konfiguration zugeordnet ist
- die Verwendung der Benutzernamen des gerade angemeldeten priviligierten Benutzers und des Benutzers root unterbinden

**Comment by T-Hagel-SK** [comment]
Was heißt planen. 
Bei der Vorstellung des Systems wurde uns mitgeteilt, dass man sich auf dem SVWS-Server unter Admin mit dem Root-Benutzer der Schild3-Datenbank anmelden soll. Anderes ist mir nicht bekannt. Es ließe sich auch ein weiterer DB-Benutzer anlegen.

Wenn Sie da gerade eh beim Anpassen sind, ich empfände es als ausgesprochen hilfreich, wenn bei den ganzen Benutzernamen nicht nur einfach "Benutzername" stehen würde, sondern aussagekräftigere Namen, wie "Schema-Admin-Name", oder "Root-DB-Name" oder "Admin-DB-Name" ... Es gibt ja im Quellcode eine Unterscheidung zwischen Username, Adminuser und Rootuser. Nur weder im SVWS-Admin (noch bei Ribeka im Schemaverwaltungsprogramm).

Hilfreich wäre für mein (oder auch für das von anderen ?) Verständnis eine Anleitung oder Erklärung was es mit den ganzen Benutzernamen und Rechten auf sich hat. Welche Aufgaben sie in dem ganzen Werk haben und wie sie warum eingesetzt werden. Ich habe noch nicht ganz verstanden, warum man auf der Schild3-Datenbank für jedes Schulschema einen eigenen Admin-Benutzernamen erstellen soll ?

Wir hätten dann am Ende 260 solcher Schema-Admins ... das finde ich wiederum eeeeeeetwas unübersichtlich und überhaupt nicht unterhaltsam zu pflegen.

Welche DB-Rechte hat dieser Schema-Admin, bzw. welche sollte er haben ?
Wenn ich mir die vom SVWS-Server 0.8.15 erzeugten Admins anschaue, haben die offenbar keine Rechte, oder ich lese die Auswertung falsch. 
![202240611_SVWS_0-8-15_Angelegte_Benutzer_haben_offenbar_keine_Rechte](https://github.com/SVWS-NRW/SVWS-Server/assets/158161190/b4f24029-0e7c-41ee-886a-44284ba8fb27)

**Comment by kroerig** [comment]
Also ich habe hier auf dem DB Server folgende Benutzer:
root: der globale DBMS Admin. Darf Benutzer und Datenbanken (Schema) anlagen
Ein eingeschränkter Benutzer pro Schema: Wird vom SVWS beim Anlegen des Schemas automatisch eingerichtet.

Und so ist das auch üblich. Jede Anwendung (=Schule) hat ihre eigene Datenbank(en) mit eigenem Benutzer, der auch nur dieses Schema nutzen darf. Das stellt schon mal sicher, dass Anwendungen nicht auf Daten zugreifen können, die sie nichts angehen.

Wenn man jetzt nicht als Root arbeiten möchte (was eigentlich empfohlen wäre), dann legt man sich einen Benutzer an, der nur genau das darf, was man gerade an Rechten braucht.

Jetzt kenne ich SchildZentral nicht. Möglicherweise braucht das noch einen zusätzlichen Benutzer, der Rechte auf allen Datenbanken hat.

Was man aber auch keinen Fall macht ist: Mit dem Root Benutzer in der Anwendung arbeiten.

**Comment by T-Hagel-SK** [comment]
"_Also ich habe hier auf dem DB Server folgende Benutzer: root: der globale DBMS Admin. Darf Benutzer und Datenbanken (Schema) anlagen Ein eingeschränkter Benutzer pro Schema: Wird vom SVWS beim Anlegen des Schemas automatisch eingerichtet._"
Automatisch eingerichtet ? Ist es nicht so, dass man den Benutzer und Passwort noch eintragen (bzw. erzeugen lassen) muss ?
 
"_Und so ist das auch üblich. Jede Anwendung (=Schule) hat ihre eigene Datenbank(en) mit eigenem Benutzer, der auch nur dieses Schema nutzen darf. Das stellt schon mal sicher, dass Anwendungen nicht auf Daten zugreifen können, die sie nichts angehen._"

Wenn man 260 Schulen betreut, wird genau das sehr aufwändig zu pflegen sein. Ich habe mich noch nicht durch die APIs gepflügt (mein Teamleiter reisst mir ohnehin schon den Kopf ab, wenn er erfährt, dass ich auf Quelltextebene nach Problemen suche), aber man kann unberechtigte Zugriffe sehr sicherstellen, wenn man die Abfragen gegen die Schulnummer macht. Die Technik kommt ja bei SchildZentral zum Einsatz. Die meisten Datenbanktabellen sind dort an die Schulnummer gebunden. 

"_Wenn man jetzt nicht als Root arbeiten möchte (was eigentlich empfohlen wäre), dann legt man sich einen Benutzer an, der nur genau das darf, was man gerade an Rechten braucht_."

Dem stimme ich gerne zu, nur wurde uns bei der Vorstellung damals mitgeteilt, man möge sich auf dem SVWS-Server unter Admin mit dem Root-DB-Benutzer anmelden. Deswegen hatte ich nicht nur hier, sondern auch bei Ribeka mehrfach Übersichten über Rechte, Rollen, etc. angefragt. 
Ich bin ja noch nicht mal soweit, dass hier irgendeine Schule migriert wurde und gegen die ich im Rahmen von SchildZentral3 hätte testen können.

In SchildZentral gibt es das sog. Schemaverwaltungsprogramm mit dem man für jede betreute Kommune eigene Schemas anlegen kann UND die Parameter der jeweiligen Schild3-Schulen für den Datenbank- und SVWS-Server zu hinterlegen. Beim Starten des PC-Clients startet dann nicht die CON-Datei der jeweiligen Schule, sondern die sog. zentralschema-CON. Der Client sucht dann für die jeweilige Schulnummer nach den entsprechenden Zugangsdaten. Damit kann man sehr elegant verhindern, bei der Client-Installation 260 CON-Dateien mitzuliefern ... Außerdem kann man über diese Schemaverwaltung zur Laufzeit auch die SVWS-Server wechseln, falls mal einer down oder überlastet ist. 

"_Was man aber auch keinen Fall macht ist: Mit dem Root Benutzer in der Anwendung arbeiten._"
Nun, im Januar hatte ich Hr. Pfotenhauer gefragt, wie man die Admin-Seite aufrufen könne, da kam folgende Antwort:
"_Mit der Benutzerkennung und dem Kennwort des MariaDB-Users müsste es eigentlich gehen._" 

Und ja mit dem DB-Rootuser geht es. Also das Anmelden. Das Ansehen der in der Datenbank angelegten Schemas, aber mit 0.8.15 kann ich nicht mal mehr Schemas anlegen.

**Comment by ThomasBachran** [comment]
@kroerig hat die Unterscheidung zwischen dem priviligierten Benutzer (z.B. root) und den anderen Schul-spezifischen Datenbanknutzern ganz gut beschrieben. Die Schul-spezifischen Benutzer werden vom Admin-Client automatisiert erzeugt und auch wieder entfernt. Aus diesem Grund sollte hier nicht der priviligierte Benutzer genommen werden. Die Schul-spezifischen DB-Benutzer werden in der SVWS-Konfiguration `svwsconfig.json` abgelegt. Bei der Nutzung des Schild 3-NRW-Clients wird zur Zeit bei der Einrichtung auch das Schul-spezifische DB-Kennwort benötigt damit dieser Client direkt auf die Datenbank zugreifen kann.

@T-Hagel-SK : Bei Ihrer Datenbank-Abfrage haben sie nur die allgemeinen Benutzerrechte angezeigt. Diese werden aber vom SVWS-Server gar nicht vergeben. Interessant sind aber die Schema-spezifischen Rechte, da der erzeugte Benutzer nur auf das erzeugte Schema zugreifen darf und nicht auf andere Schemata. Das kann man in der Tabelle `mysql.db` auslesen (s. Grafik)

![grafik](https://github.com/SVWS-NRW/SVWS-Server/assets/46782864/eebfcc1e-1f8e-4185-b79a-12ec3ddc93a0)

**Comment by kroerig** [comment]
siehe auch hier: https://github.com/SVWS-NRW/SVWS-Server/issues/206#issuecomment-2168244256

**Comment by kroerig** [comment]
> Wenn man 260 Schulen betreut, wird genau das sehr aufwändig zu pflegen sein. Ich habe mich noch nicht durch die APIs gepflügt (mein Teamleiter reisst mir ohnehin schon den Kopf ab, wenn er erfährt, dass ich auf Quelltextebene nach Problemen suche), aber man kann unberechtigte Zugriffe sehr sicherstellen, wenn man die Abfragen gegen die Schulnummer macht. Die Technik kommt ja bei SchildZentral zum Einsatz. Die meisten Datenbanktabellen sind dort an die Schulnummer gebunden.

Das mache ich hier täglich. Also nicht unbedingt im Quelltext (den habe ich meist nicht), aber Fehler in Anwendungen suchen und dem Hersteller um die Ohren hauen ist ein "Hobby" von mir. (@dev: Bitte nicht persönlich nehmen)

Nein, die Datentrennung nur anhand einer Mandantennummer (Schulnummer) ist keine saubere Datentrennung. Die kann ich nämlich, wenn die Software SQL Queries nicht sauber filtert bevor sie ausgeführt werden umgehen.
Mit der Kombination aus Datenbank + Datenbankbenutzer, kann ich bei sauberer Konfiguration des DB Servers (und das macht der SVWS Server hier), meine zugewiesene Datenbank nicht verlassen. Ich sehe die andern Datenbanken noch nichtmal.

**Comment by T-Hagel-SK** [comment]
> @kroerig hat die Unterscheidung zwischen dem priviligierten Benutzer (z.B. root) und den anderen Schul-spezifischen Datenbanknutzern ganz gut beschrieben. 

Ja, hat er ;-)
Ist das Rechte/Rollenkonzept irgendwo beschrieben ?

> Die Schul-spezifischen Benutzer werden vom Admin-Client automatisiert erzeugt und auch wieder entfernt. Aus diesem Grund sollte hier nicht der priviligierte Benutzer genommen werden. 

Wäre dann ein Hinweis hilfreich, dass nicht der oder ein Root-Benutzer verwendet werden soll ? Inkl. Link zum Abschnitt in der jeweiligen Anleitung.
Oder bin ich der einzige "Depp", der das nicht verstanden hat ?

> Die Schul-spezifischen DB-Benutzer werden in der SVWS-Konfiguration `svwsconfig.json` abgelegt. Bei der Nutzung des Schild 3-NRW-Clients wird zur Zeit bei der Einrichtung auch das Schul-spezifische DB-Kennwort benötigt damit dieser Client direkt auf die Datenbank zugreifen kann.

Das ist dann wohl das, was Ribeka mit dem Schemaveraltungsprogramm in etwa/genauso löst. Nur, dass diese Werte dann in der Datenbank unter einer als "zentralschema" genanntes Schema hinterlegt sind. 

> @T-Hagel-SK : Bei Ihrer Datenbank-Abfrage haben sie nur die allgemeinen Benutzerrechte angezeigt. Diese werden aber vom SVWS-Server gar nicht vergeben. Interessant sind aber die Schema-spezifischen Rechte, da der erzeugte Benutzer nur auf das erzeugte Schema zugreifen darf und nicht auf andere Schemata. Das kann man in der Tabelle `mysql.db` auslesen (s. Grafik)
 
Die Abfrage select * from mysql.db  liefert mir zwei DBs und User, die ich irgendwann mal im Rahmen der ganzen Tests angelegt hatte. Die DBs existieren nicht mehr, da ich immer mal wieder ganz von vorne anfange. Diese User haben aber alle Rechte, inkl. der Grant_priv-Rechte. 

Ich frag mal bei unseren Datenbankkollegen nach, dass sie unserem Root-User auch die Grant-Rechte einräumen. Dann würde ich an der Stelle mal weiter testen.

Vielen Dank Ihnen beiden für den Freitagspätnachmittaglichen, erfrischenden Support ... ganz dicken Daumen nach oben 👍

**Comment by ThomasBachran** [comment]
> > @kroerig hat die Unterscheidung zwischen dem priviligierten Benutzer (z.B. root) und den anderen Schul-spezifischen Datenbanknutzern ganz gut beschrieben.
> 
> Ja, hat er ;-) Ist das Rechte/Rollenkonzept irgendwo beschrieben ?
> 

Die Dokumentation befindet sich derzeit im Aufbau. In der Anwender-Dokumentation gibt es einen kurzen Abschnitt zum Admin-Client. Dort wird das Konzept der Rechte aber noch nicht genauer beschrieben.

> > Die Schul-spezifischen Benutzer werden vom Admin-Client automatisiert erzeugt und auch wieder entfernt. Aus diesem Grund sollte hier nicht der priviligierte Benutzer genommen werden.
> 
> Wäre dann ein Hinweis hilfreich, dass nicht der oder ein Root-Benutzer verwendet werden soll ? Inkl. Link zum Abschnitt in der jeweiligen Anleitung. Oder bin ich der einzige "Depp", der das nicht verstanden hat ?

Das habe ich bereits als Rückmeldung im Admin-Client berücksichtigt (siehe Kommentar weiter oben). Der Fehler sollte dadurch beim Anlegen von Schemata im Admin-Client nicht weiter auftreten können.

> > Die Schul-spezifischen DB-Benutzer werden in der SVWS-Konfiguration `svwsconfig.json` abgelegt. Bei der Nutzung des Schild 3-NRW-Clients wird zur Zeit bei der Einrichtung auch das Schul-spezifische DB-Kennwort benötigt damit dieser Client direkt auf die Datenbank zugreifen kann.
> 
> Das ist dann wohl das, was Ribeka mit dem Schemaveraltungsprogramm in etwa/genauso löst. Nur, dass diese Werte dann in der Datenbank unter einer als "zentralschema" genanntes Schema hinterlegt sind.

Das klingt plausibel, da die Verwaltung der vielen Schemata eine der Aufgaben von Schild-Zentral ist. Der Admin-Client ist hier nicht für die Administration einer Großinstallation eines Rechenzentrums ausgelegt, sondern für kleinere Installationen...

> 
> > @T-Hagel-SK : Bei Ihrer Datenbank-Abfrage haben sie nur die allgemeinen Benutzerrechte angezeigt. Diese werden aber vom SVWS-Server gar nicht vergeben. Interessant sind aber die Schema-spezifischen Rechte, da der erzeugte Benutzer nur auf das erzeugte Schema zugreifen darf und nicht auf andere Schemata. Das kann man in der Tabelle `mysql.db` auslesen (s. Grafik)
> 
> Die Abfrage select * from mysql.db liefert mir zwei DBs und User, die ich irgendwann mal im Rahmen der ganzen Tests angelegt hatte. Die DBs existieren nicht mehr, da ich immer mal wieder ganz von vorne anfange. Diese User haben aber alle Rechte, inkl. der Grant_priv-Rechte.

Solche alten Benutzer-Rechte sollten mittlerweile vermieden werden, da der SVWS-Server versucht die Rechte beim Löschen eines Schemas wieder zu entfernen. Hier müsste man vermutlich einmalig aufräumen.

> 
> Ich frag mal bei unseren Datenbankkollegen nach, dass sie unserem Root-User auch die Grant-Rechte einräumen. Dann würde ich an der Stelle mal weiter testen.
> 
> Vielen Dank Ihnen beiden für den Freitagspätnachmittaglichen, erfrischenden Support ... ganz dicken Daumen nach oben 👍

Ihnen ein schönes Wochenende!

**Comment by T-Hagel-SK** [comment]
> Die Dokumentation befindet sich derzeit im Aufbau. In der Anwender-Dokumentation gibt es einen kurzen Abschnitt zum Admin-Client. Dort wird das Konzept der Rechte aber noch nicht genauer beschrieben.

Bin gespannt ... Vorschlag: einen Link auf die Admin-Seite setzen, der auf diesen Abschnitt verweist :-)


> Wäre dann ein Hinweis hilfreich, dass nicht der oder ein Root-Benutzer verwendet werden soll ? Inkl. Link zum Abschnitt in der jeweiligen Anleitung. Oder bin ich der einzige "Depp", der das nicht verstanden hat ?
 
> Das habe ich bereits als Rückmeldung im Admin-Client berücksichtigt (siehe Kommentar weiter oben). Der Fehler sollte dadurch beim Anlegen von Schemata im Admin-Client nicht weiter auftreten können.

Top 👍 

> Solche alten Benutzer-Rechte sollten mittlerweile vermieden werden, da der SVWS-Server versucht die Rechte beim Löschen eines Schemas wieder zu entfernen. Hier müsste man vermutlich einmalig aufräumen.

Das ist der Grund warum ich bei den neuen Serverversionen und den neuen Versionen, die Ribeka mir liefert, gerne alles droppe, was ich sehen kann. Werde in dem Zuge dann auch verstärkt ein Auge auf die User haben.

Ich frag jetzt nicht nach einem Aufräumbutton. Ich versuche es mir zu merken.
 
So, jetzt aber alle weg von den Dienstrechnern ...
