### ISSUE TITLE
SVWS-Server 0.8.15: Anlegen neuer Schemas nicht mehr möglich

### ISSUE THREAD

**Issue by T-Hagel-SK** [SVWS-NRW/SVWS-Server#206]
Hallo zusammen,
ich stecke fest ...

Mit der SVWS-Version 0.8.14 wurde unter "leeres Schema anlegen" sowohl ein Schema, als auch ein Benutzer angelegt, brach dann aber mit der nicht abgefangenen Fehlermeldung ab, dass ein Schema oder Benutzer nicht angelegt werden konnten, obwohl das Problem daran lag, dass das neue Schema nicht in die Config-Datei gespeichert werden konnte.

Das wurde ja nun u.a. in 0.8.15 abgefangen, dafür aber wird jetzt nicht mal mehr ein Schema angelegt, dafür weiterhin ein Benutzer.

Der an den SVWS-Server übermittelte DB-Nutzer hat alle Rechte der DB-Welt und mit diesem kann ich mit der MySQL Workbench auch neue Schemas anlegen und löschen. Nur halt nicht vom SVWS-Server aus. 

Logausgabe dazu:

_Prüfe, ob das Schema bereits existiert...
  ist noch nicht vorhanden
Erstelle Ziel-Schema für MARIA_DB (Servername:Port/S3Test)
  -> Verbinde mit einem DB-Root-Manager zu der Ziel-DB...
    - Datenbank-Verbindung erfolgreich aufgebaut (driver='MARIA_DB', schema='S3Test', location=Servername:Port', user='S3TestAdmin')
    - Prüfe, ob der Benutzer noch angelegt werden kann oder ob das angebene Kennwort zu einem existierenden Benutzer passt... [OK]
    - Entferne aus der Ziel-DB das alte Schema, falls vorhanden... [OK]
    - Erstelle in der Ziel-DB das Schema und den Admin-Benutzer: [Fehler]
  -> Erstellen fehlgeschlagen! (Das Schema konnte nicht erstellt werden oder der Admin-Benutzer konnte nicht angelegt werden.)_

In der MySQL-Workbench sehe ich, dass der Benutzer "S3Test" angelegt wurde, wie auch alle anderen Benutzer, mit denen ich hier schon getestet habe. Alle vom SVWS-Server angelegte Benutzer haben aber offenbar keine Rechte ?

Sucht man den Quellcode nach dem Fehlertext ab, landet man bei der Datei "DBRootManager.java" in Zeile 504-507:
_logger.log("- Erstelle in der Ziel-DB das Schema und den Admin-Benutzer:");
	if (!root_manager.createDBSchemaWithAdminUser(config.getUsername(), config.getPassword(), config.getDBSchema()))
		throw new DBException("Das Schema konnte nicht erstellt werden oder der Admin-Benutzer konnte nicht angelegt werden.");
logger.logLn(0, " [OK]");_

Sucht man nun nach "createDBSchemaWithAdminUser" landet man in der gleichen Datei bei Zeile 264-276, dann beginnt die Funktion zuerst mit der Anlage des Schemas und dann mit dem Anlegen des Benutzers. Offenbar fehlt hier die Fehlerbehandlung für den Fall, dass ein Schema nicht angelegt werden kann:

_if (!createDBSchema(nameSchema))
	return false;_

Den gleichen Fehlertext erhalte ich folglich auch, wenn ich versuche eine Schule aus der SchildZentral2-Datenbank zu migrieren ...

Läuft hier bei uns einfach etwas schief und wenn ja, was ?

Schöne Grüße
Thomas Hagel

Stadt Köln
Fachanwendungssupport / SchILD3-Koordination

Screenshots dazu:

![20240613_SVWS_0-8-15_Parameter_für_Anlage_neues_Schema_über_Adminseite](https://github.com/SVWS-NRW/SVWS-Server/assets/158161190/3aae7ad6-258d-4c66-aebf-aae503663cf8)

![202240611_SVWS_0-8-15_Angelegte_Benutzer_haben_offenbar_keine_Rechte](https://github.com/SVWS-NRW/SVWS-Server/assets/158161190/cb7732b4-9ce6-4535-ba02-0da05a811423)

**Comment by T-Hagel-SK** [comment]
Vielleicht noch als Hintergrundinfo ...
Wir setzen keine Dockerinstanz ein. Der SVWS-Server ist ein virtualisierter Webserver auf RedHat 9.3-Basis. Der MariaDB-Server steht ein paar Racks weiter bei den anderen MariaDB-Servern. Beide Systeme stehen bei uns im Rechenzentrum und werden von den jeweiligen Teams (Linux- und Datenbank) betreut.

Der Aufruf des SVWS-Servers läuft über einen Reverse Proxy und Datenbank und Webserver sind durch Firewallregeln geschützt.

**Comment by kroerig** [comment]
Laut dem Bild fehlt dem _schild_poc_ User der GRANT Recht. D.h. er kann zwar Benutzer anlegen, diesen aber keine Rechte zuweisen. Das dürfte erklären, warum der Prozess mit "Das Schema konnte nicht erstellt werden oder d**er Admin-Benutzer konnte nicht angelegt werden**." auf die Nase fällt.

Und deswegen geht die Installationsanleitung auch von aus, dass man sich für die Schema-Verwaltung als (Datenbank-) Root anmeldet, denn Root hat das GRANT Recht.

Wenn Sie nicht mit Root arbeiten möchten oder dürfen, dann brauchen Sie einen Benutzer mit GRANT Recht, der muss aber ggü. dem Root Benutzer keine Rechte für die Steuerung der Prozesse haben.

**Comment by kroerig** [comment]
> Alle vom SVWS-Server angelegte Benutzer haben aber offenbar keine Rechte ?

Nein. Sie haben keine globalen Rechte. Brauchen Sie auch nicht. Sie erhalten nur Rechte auf ihre eigene Datenbank. Die stehen in einer anderen Tabelle.

**Comment by ThomasBachran** [comment]
@kroerig hat für dieses Issue auf das entscheidende Problem hingewiesen. Der priviligierte Datenbank-Nutzer muss auch das Recht haben auf ein neu erstelltes SVWS-Schema dem erstellten Datenbank-Benutzer die Schema-spezifischen Rechte zu geben. Das Hinzufügen der GRANT-Privilegien ist für diesen Benutzer also nötig.

Ich schließe daher dieses Issue.

**Comment by T-Hagel-SK** [comment]
Kurze Rückmeldung ... mit den Grant_priv-Eigenschaften klappt es nun ...

Das Anlegen eines neuen Schemas klappt nun.

Beim Migriereren aus der Schild2-DB klappte das meiste. Hierzu dann ein eigenes Issue, weil das Log nicht ausgibt, welche IDs oder welche Datensätze bemängelt werden. Außerdem folgte nach der Migration ein Fehler 502.

Es wäre allerdings hilfreich, wenn in der Anleitung stehen würde, welche Rechte der Root-User haben soll. Offenbar reichte die Aussage "alle" bei den Kollegen nicht aus. Evtl. scheut sich auch der eine oder andere DB-Admin einen User mit wirklich allen Rechten auszustatten. Ich nehme an, dass das innerhalb einer Docker-Variante jedoch bereits berücksichtigt ist und man als Schuladmin ein Komplettpaket erhält.

**Comment by kroerig** [comment]
Der _root_- Benutzer ist der einzige Benutzer, der nach der Installation einer MariaDB existiert und hat dementsprechend alle Rechte. Den beschneidet man auch nicht. Man schränkt ihn in größeren und professionellen Installationen aber so ein, dass er sich z.B. nur lokal (für den Notfall) anmelden darf. Für die Arbeit legt man sich dann Benutzer an, die genau das dürfen, was man braucht. Aber einen Benutzter mit GRANT-Rechten braucht man schon. Sonst wird es schwierig.
