### ISSUE TITLE
SVWS-Server 0.8.15: Migrations-Log Informationen erweitern, bzw. Fehlermeldungen umformulieren

### ISSUE THREAD

**Issue by T-Hagel-SK** [SVWS-NRW/SVWS-Server#209]
Hallo zusammen,

wir haben nun das erste Mal eine Testschule aus der SchildZentral2-Datenbank in ein eigenes Schema unter Schild3 hinbekommen .... Zeit also mal einen Blick in das Logfile zu werfen. Dabei sind mir ein paar Dinge aufgefallen:

1. So ein Migrationslog kann sehr lang ausfallen. Wäre es möglich, die Migrationslog-Infos in eine eigene Log-Datei auszulagern ? Idealerweise je Schulnummer ?

Meines Erachtens würde eine Aufteilung die Fehlersuche vereinfachen, wenn es einen Server-Log und einen Migrations-Log gäbe. Insbesondere, wenn man sich an Schild3 herantastet.  

2. Gerade wenn man mehere Datenmigrationsanläufe benötigt, fänd ich einen Zeitstempel hilfreich, wann eine solche Migration gestartet wurde.

3. In Fehlerfällen sind die Angaben z.T. irreführend und/oder ungenau:
Z.B. haben wir in unserer Testschule offenbar Probleme bei:
- Tabelle EigeneSchule_Faecher:
   -> "Entferne ungültigen Datensatz: Ein Fach muss ein gültiges Statistik-Kürzel haben. Dieses darf nicht null sein." 
- Tabelle CredentialsLernplattformen: 
   -> "Entferne ungültigen Datensatz: Benutzername darf nicht leer sein."
   -> sowie "Die Kombination auf Lernplattform und Benutzername ist nicht eindeutig (ID 848)"
- Tabelle LehrerDatenschutz: 
   -> "Entferne ungültigen Datensatz: Es gibt keinen Lehrer mit der angebenen ID in der Datenbank."
- Tabelle SchuelerLernplattform:
   -> "Entferne ungültigen Datensatz: Es gibt keinen Schüler mit der angebenen ID in der Datenbank."
- Tabelle SchuelerLernabschnittsdaten:
  -> "Anpassung eines fehlerhaften Datensatzes(ID: 6332911): Die Lernabschnittsdaten haben einen leeren Schulgliederungs-Eintrag. Dieser wird auf null gesetzt."
- Tabelle SchuelerLD_PSFFachBem:
  -> "Entferne ungültigen Datensatz: Es gibt keinen Lernabschnitt mit der angebenen ID in der Datenbank."
- Tabelle Logins:
   -> "Entferne ungültigen Datensatz: Es gibt keinen User mit der angebenen ID in der Datenbank."

Anmerkungen dazu:
Aktuell kann ich aus diesem Log nicht, bzw. nur bedingt feststellen, welcher Datensatz, bzw. welche ID konkret gemeint ist, um 
zu prüfen, warum eine Migration hier nicht möglich war. Meldungen á la  "Entferne..." irritieren zunächst. Ich hatte mich spontan gefragt, wo hier etwas entfernt wird. Etwa in der Schild2-Datenbank ? Bei Stichproben jedenfalls war das nicht der Fall. In der Schild3-Datenbank wurden offenbar nur die Daten geschrieben, für die es keine Fehlermeldung gab. 

Hier wäre m.E. der Text "Der Datensatz mit der ID (Nr) konnte nicht migriert werden" besser geeignet. Idealerweise inkl. Begründung, wie das ja bei der Fehlermeldung "diese darf nicht null sein" der Fall ist.

Sonstige Fehlermeldungen: 
- "Fehlerbehebung bei einer fehlenden Kursart, Kursart raten und setzen auf PUK, falls die Kurs_ID nicht gesetzt ist (7470)"
- Schulnummerprüfung ergibt bei einer Testschule: "Fehler: Schule konnte für die Schul-Nummer xxxxxx nicht im Verzeichnis der Schulen gefunden werden!"
- "Entferne fehlerhafte doppelte Datensätze in Bezug auf die Unique-Constraint SchuelerLeistungsdaten_UC1 aus den Leistungsdaten (1) (2800)" gilt von Leistungsdaten (1) bis (5)

Außerdem finden sich einige Fehler in Bezug auf Tabellen, die offenbar bei uns nicht vorliegen:
- Tabelle K_Textdateien: "Fehler: Die Tabelle ist im Quell-Schema nicht definiert."  
- Tabelle EigeneSchule_Zertifikate: "Fehler: Die Tabelle ist im Quell-Schema nicht definiert."
- Tabelle Credentials: Fehler: "Die Tabelle ist im Quell-Schema nicht definiert."
- Tabelle ErzieherLernplattform:  "Fehler: Die Tabelle ist im Quell-Schema nicht definiert."
- ... (usw.)

Vorschlag:
Wäre es nicht sinnvoll, vor der Migration die Quell-Datenbank auf fehlende Tabellen und mögliche Fehler zu prüfen und dann:
- keinen Fehler auswerfen, weil eine Tabelle nicht vorhanden ist, sondern sie einfach anzulegen 
- dem Admin eine Ausgabe der fehlerhaften Einträge inkl. der jeweiligen IDs zu liefern, ggf. als Export-Datei zum Herunterladen
- den Admin über Schaltflächen entscheiden lassen, welche Daten und Fehlerhinweise ignoriert werden können
Im Prinzip sowas, was man von der lustigen Jahresstatistik her kennt.

Bei unserer Testschule mit nicht realen Namen und Leistungsdaten ist es quasi egal, wenn hier ein paar / einige Einträge nicht migriert werden. Aber bei Schulen mit realem Datenbestand frage ich mich, wie groß der Aufwand dann werden wird um ggf. fehlende Schüler-/Lehrer- und andere Daten herauszufiltern und Wege zu finden, wie die fehlerhaften Daten korrekt migriert werden können?

Schöne Grüße
Thomas Hagel

Stadt Köln
Fachanwendungsbetreuung

**Comment by kroerig** [comment]
> Bei unserer Testschule mit nicht realen Namen und Leistungsdaten ist es quasi egal, wenn hier ein paar / einige Einträge nicht migriert werden. Aber bei Schulen mit realem Datenbestand frage ich mich, wie groß der Aufwand dann werden wird um ggf. fehlende Schüler-/Lehrer- und andere Daten herauszufiltern und Wege zu finden, wie die fehlerhaften Daten korrekt migriert werden können?

Nehmen Sie mal eine kleine reale Schule, dann sehen die Meldungen ganz anders aus. **Und wichtig:** Vor der Migration nach SVWS müssen alle SchILD 2 Updates mit den Anpassungen der Datenbank durchlaufen sein.

Das sich in den Datenbanken viele Leichen befinden, dürfte auch damit zusammenhängen, dass SchILD2000 in der Vergangenheit nicht immer vollständig aufgeräumt hat.

Ich hatte am Anfang schon ein paar Issues eröffnet, weil z.B. Tabellenamen nicht passten. Das betraf aber ehr eine Linux MySQL/ MariaDB als Quell-DB.

Was das Migrationslog angeht. Wenn man die Migration über den Admin-Client bzw. die API (Swagger) direkt macht, dann bekommt man auch nur die Logeinträge zu diesem Job als JSON zurück. Was das Schildzentral Tool da macht kann es nicht sagen. Aber wenn, dann sollte dieses die Einträge zu jedem Job speichern und nicht der Server.

**Comment by kroerig** [comment]
Es gibt ja noch das SchILD Migrationstool, mit dem man ein Datenbank von einem Format in ein anderes überführen kann, das ist gesprächiger wenn es um fehlerhafte Datensätze geht. Aber vermutlich kann das nicht mit SchildZentral umgehen, denn dann würde es die ganze Datenbank konvertieren wollen.

Aber die Frage hatte ich auch schon mal gestellt: https://schulverwaltungsinfos.nrw.de/svws/forum/viewtopic.php?p=35167

Ich fände es solches Tool, das die Datenbank vor (und nicht erst während) einer Migration prüft auch recht hilfreich. Dann muss man die Arbeit nämlich nur einmal machen.

**Comment by FPfotenhauer** [comment]
Die Schild2-Zentral Datenbank zu prüfen und zu korrigieren ist allerdings nicht die Aufgabe des SVWS-Teams.
Die Migrationsprotokolle alle bis auf den letzten Eintrag zu prüfen ist m.E. auch gar nicht notwendig.
Für uns ist wichtig, ob die Datenbanken nach der Migration mit Schild3 und dem SVWS-Client starten.

Ob dann alle wichtigen Daten da sind und die Schule arbeiten kann, muss die Schule dann melden.
Fehler bei der Migration werden wir natürlich bei konkreten Fällen korrigieren.
Die Arbeit eines Schild-Zentral-Dienstleisters können wir aber leider nicht mit unseren Kapazitäten leisten.

**Comment by T-Hagel-SK** [comment]
Jaaaaa ....
Ich weiß ... SchildZentral / SchildNRW ... 

und ja, ich versuche bei meinen Fragen auch immer diese Unterschiede im Blick zu behalten. Das was m.E. rein Ribeka-bezogen ist, stelle ich dort ja in deren Ticketsystem. 

Aber die Frage nach einer Möglichkeit vor der Migration einen Testlauf starten zu können, wie bei ASDPC ja auch, sollte unabhängig von SchildNRW oder SchildZentral möglich sein. 

In Bezug auf SchildZentral hilft mir die aktuelle Migration gerade wenig, weil der PC-Client für SchildZentral noch ein, zwei weitere Tabellen abfragt, die ich momentan wegen eines Fehlers im Schemaverwaltungsprogramm nicht durchführen kann. 

Wichtig für mich war hier erst mal überhaupt einen lauffähigen SVWS-Server hinzubekommen um mal mit den Migrationen starten zu können. Und auch hier wäre eine aussagekräftigere Rückmeldung welche Datensätze nicht migriert werden können hilfreich. Das aber ist wieder etwas, was sowohl SchildNRW als auch SchildZentral betrifft...

**Comment by kroerig** [comment]
> Ob dann alle wichtigen Daten da sind und die Schule arbeiten kann, muss die Schule dann melden.

Wie soll die Schule das prüfen? Jeden Schüler anfassen und schauen, ob die Daten noch mit SchILD2 übereinstimmen? Vorher alles ausdrucken und händisch abhaken? Das funktioniert nicht. Man kann ggf. Stichproben machen. Das geht dann nur mit "Mut zur Lücke".

Nach Murphys Gesetz fallen die richtigen Fehler erst dann auf, wenn es zu spät ist. Ich merke es ja jetzt schon: Die Schulen haben im Alltag nicht die Ressourcen um nebenbei noch Logikfehler in einer neuen Software zu finden. Denn um wirklich Abweichungen und Programmfehler zu finden, muss ich über einen längeren Zeitraum parallel arbeiten. Und zwar eigentlich ein ganzes Schuljahr um alle Fälle einmal durchgespielt zu haben. Jede Schule hat ihre Eigenheiten und auch die Fachberater kennen die nicht alle.

**Comment by T-Hagel-SK** [comment]
Da wir es gerade bei den Schülern mit Daten zu tun haben, die eine gewisse Aufbewahrungsfrist einzuhalten haben, ist es unerlässlich, dass bei der Datenmigration alles rüberkommt. Wie Sie richtig bemerken, können Schulen das -auch zeitlich- kaum nebenbei abfedern. Hier muss die Software helfend unterstützen. Ein Parallelbetrieb über einen solch langen Zeitraum sehe ich ebenfalls aus Zeitgründen nicht.

Mut zur Lücke geht nicht. Nicht bei diesen Datenbeständen. Zu überlegen wären dann ggf. auch Maßnahmen zur Datenarchivierung aus Schild2 heraus. Aber dazu müssten die Schulen, bzw. die Fachberater aus ihrem Erfahrungsfundus besser was zu sagen können :-)

Ich weiß von ein paar "Dramen", als Schulen von IBIS zu SchILD gewechselt sind. Aber auch von anderen Systemen zu SchILD. 

Aber hier kommt man von SchILD zu SchILD und da sollte es doch "kein Problem" sein, hier mit entsprechenden Werkzeugen die Arbeit an den Schulen soweit wie möglich zu vereinfachen. 

Hinzu kommt doch auch, dass -wohl nicht nur bei uns- der vorliegende Datenbestand z.T. noch "Leichen" aus eben jenen Exporten vorliegen, bzw. Daten in den falschen Tabellen gelandet sind, wie Faxnummern bei eMail-Feldern. 

Wie gesagt, ich würde ein System bevorzugen, das vor der Migration zunächst mal die Tabellen aufräumt. Welche sind noch aktuell, welche könnten archiviert und dann gelöscht werden ? Welche Datenfelder die übrigbleiben sind mit Daten gefüllt, die migriert werden können ? Die, die nicht migrierbar sind, sind detailliert auszuweisen.

**Comment by kroerig** [comment]
Was die Aufbewahrung angeht: Die zwingt einen nicht die Daten in eine neue Software zu übernehmen. Die können auch in der alten verbleiben, wenn sichergestellt ist, dass man noch auf sie zugreifen kann. Ich werde das möglicherweise so handhaben: Vor der Migration erstelle ich eine Kopie der Datenbank. In dieser lasse ich SchILD alles wegräumen, was nicht mehr verwahrt werden muss (Fristen) und ggf. auch über Aufräumen hart alles älter als acht Jahre. Dann sollte das für SchILD3 eine schlanke Datenbank geben.
Die Daten sind damit ja nicht weg. Über SchILD2 kann man sie ja noch abrufen.

>Hinzu kommt doch auch, dass -wohl nicht nur bei uns- der vorliegende Datenbestand z.T. noch "Leichen" aus eben jenen Exporten vorliegen, bzw. Daten in den falschen Tabellen gelandet sind, wie Faxnummern bei eMail-Feldern.

Diese Sachen ermittle ich über direkte SQL Abfragen und habe ein Script, dass z.B. regelmäßig Rufnummern in der Datenbank ins internationale Format konvertiert.

> Wie gesagt, ich würde ein System bevorzugen, das vor der Migration zunächst mal die Tabellen aufräumt.

Änderungen an der Quelle könnten fatal sein. Wenn dann nur auf einer Kopie.

**Comment by T-Hagel-SK** [comment]
Was die Aufbewahrung betrifft:
Zu den Aufbewahrungsfristen und Optionen sollten sich die Entwickler austauschen, nicht wir zwei IT-Techniker :-)

Nicht immer lassen sich alte Anwendungen weiterhin bereithalten oder sind unter künftigen Betriebssystemen lauffähig. Ich hatte da mal ein BK das sich den IBIS-Datenbestand auf einem ausrangierten Notebook vorgehalten hatte. Bei einem Gymnasium hatte mal der Admin den Zustand in einer virtuellen Maschine aufbewahrt. Aber das kann doch nicht allen Ernstes die Lösung sein. Zumal das aktuelle Migrationswerkzeug schon - meines Erachtens - sehr gut aufgestellt ist.

Wenn wir hier in Köln die Umstellung auf Schild3 durchziehen, wird SchildZentral2 allerdings nach einer Übergangszeit gänzlich verschwinden. Die Pflege zweier Varianten ist dann - gerade bei der Menge - nicht unerheblich und nicht zu stemmen.

Änderungen an der Quelle erfolgen jedes Mal bei der Jahresstatistik :-) Aber lassen wir hierzu mal die Entwickler zu Wort kommen :-)

**Comment by kroerig** [comment]
> Nicht immer lassen sich alte Anwendungen weiterhin bereithalten oder sind unter künftigen Betriebssystemen lauffähig.

Ja. In dem Fall verlangt der Gesetzgeber, dass man auch die Laufzeitumgebung einfrieren muss. Wir haben hier einige VMs mit alter Software in Betriebssystem, die wir noch falls Rückfragen kommen, aufbewahren müssen.

Im Fall der Schulen würde es technisch vermutlich reichen die Schulen aus Schildzentral in Access-Dateien zu migrieren und ein passendes SchILD2 NRW + Windows ISO daneben zu legen.

>Zu den Aufbewahrungsfristen und Optionen sollten sich die Entwickler austauschen, nicht wir zwei IT-Techniker :-)

Entwicker setzten das um, was bei ihnen bestellt wird. Hier ist der Productowner gefragt die Richtung vorzugeben.

**Comment by T-Hagel-SK** [comment]
> Ja. In dem Fall verlangt der Gesetzgeber, dass man auch die Laufzeitumgebung einfrieren muss. Wir haben hier einige VMs mit alter Software in Betriebssystem, die wir noch falls Rückfragen kommen, aufbewahren müssen.

Verlangt der Gesetzgeber genau das ?  Das "Einfrieren einer Laufzeitumgebung" ? Wer soll das denn in den Schulen bewerkstelligen ? Nicht alle Schulen haben das entsprechende Personal oder die Moneten das in Auftrag zu geben. 

> > Zu den Aufbewahrungsfristen und Optionen sollten sich die Entwickler austauschen, nicht wir zwei IT-Techniker :-)
 
> Entwicker setzten das um, was bei ihnen bestellt wird. Hier ist der Productowner gefragt die Richtung vorzugeben.

Ja gut, ich meine damit auch die Kollegen um Hr. Pfotenhauer und Co :-) 


Aber vielleicht können wir ja wieder auf den Ursprung des Issues zurückkommen. Da ging es um eine Datenprüfung vor der Migration, sowie um sprechendere Fehlermeldugnen aus denen hervorgeht welcher Datensatz warum nicht migrierbar ist.

**Comment by kroerig** [comment]
> Die Schild2-Zentral Datenbank zu prüfen und zu korrigieren ist allerdings nicht die Aufgabe des SVWS-Teams. Die Migrationsprotokolle alle bis auf den letzten Eintrag zu prüfen ist m.E. auch gar nicht notwendig. Für uns ist wichtig, ob die Datenbanken nach der Migration mit Schild3 und dem SVWS-Client starten.

Sagt mir: Da wird nichts kommen, wenn es nicht jemand bei Ribeka bestellt. Sagt mir aber auch: Die Datenquallität ist uns egal, Hauptsache der SVWS Server findet eine Datenbank und startet.

> Ob dann alle wichtigen Daten da sind und die Schule arbeiten kann, muss die Schule dann melden. Fehler bei der Migration werden wir natürlich bei konkreten Fällen korrigieren. Die Arbeit eines Schild-Zentral-Dienstleisters können wir aber leider nicht mit unseren Kapazitäten leisten.

Sagt mir: Mit SchILD Zentral haben wir nichts zutun (was im Prinzip auch stimmt, denn SchILD Zentral ist ein kommerzielles Produkt der Firma Ribeka, das auf dem von Land bestellen SchILD NRW aufbaut).

Aber: der SVWS bietet eine Möglichkeit der Migration aus diesem Produkt an. Und somit muss der SVWS Team auch sicherstellen, dass alle Daten richtig von A nach B wandern.

Aber @T-Hagel-SK: Nehmen Sie mal eine echte Schule für den Test. Die Quelldaten bleiben ja unberührt. Die Schule hier hat etwa 800 Schüler. Die sind auf einigermaßen aktueller Hardware schnell migriert. Die Beispieldatenbanken habe ich den Eindruck sind nicht immer ganz optimal.

Bisher fand ich die Logeinträge des SVWS bei der Migration recht verständlich. Und im Gegensatz zu den Anfängen der öffentlichen Testphase legt er sich auf nicht mehr auf die Nase, wenn er über einen unsinnigen Datensatz stolpert. Die groben Fehler dürfte da wohl raus sein.

Logische Fehler kann der Importer natürlich nur soweit auflösen, wie es Gesetzmäßigkeiten gibt, die eingehalten werden müssen, und die man prüfen kann. Sinnfreie Eingaben von Anwendern gehören da nur bedingt zu.

Aber ja, dort wo der Prozess auf einen logischen Fehler trifft, den er korrigiert, sollte er den Datensatz ausgeben, damit man im Nachgang schauen kann, was da in der Quelle (angeblich) falsch ist.
Beim Beseitigen von bekannten Leichen sehe ich das nicht so kritisch.

Ich müsste nochmal einen Import mit der aktuellen Version machen und schauen, ob die o.g. Tabellen bei mir auch angemeckert werden bzw. ob sie in der DB existieren.

**Comment by kroerig** [comment]
> Außerdem finden sich einige Fehler in Bezug auf Tabellen, die offenbar bei uns nicht vorliegen:
> 
>     * Tabelle K_Textdateien: "Fehler: Die Tabelle ist im Quell-Schema nicht definiert."
> 
>     * Tabelle EigeneSchule_Zertifikate: "Fehler: Die Tabelle ist im Quell-Schema nicht definiert."
> 
>     * Tabelle Credentials: Fehler: "Die Tabelle ist im Quell-Schema nicht definiert."
> 
>     * Tabelle ErzieherLernplattform:  "Fehler: Die Tabelle ist im Quell-Schema nicht definiert."

Bis auf die genannte `K_Textdateien` gibt es die anderen Tabellen bei mir im SchILD2 Schema.

**Comment by T-Hagel-SK** [comment]
> Bis auf die genannte `K_Textdateien` gibt es die anderen Tabellen bei mir im SchILD2 Schema.

Davon gehe ich aus, dass sie Bestandteil zumindest von SchILD2-NRW sind. Ich gebe das mal an Ribeka weiter. 
Dreht aber in meine erste Frage, der Migrationsprüfung vorab.

**Comment by T-Hagel-SK** [comment]
> Die Schild2-Zentral Datenbank zu prüfen und zu korrigieren ist allerdings nicht die Aufgabe des SVWS-Teams. Die Migrationsprotokolle alle bis auf den letzten Eintrag zu prüfen ist m.E. auch gar nicht notwendig. Für uns ist wichtig, ob die Datenbanken nach der Migration mit Schild3 und dem SVWS-Client starten.

Ehm, meine Anfrage bezieht sich jetzt nicht ausschließlich auf die SchILD2-Zentral Datenbank, sondern allgemein auf SchILD-Datenbanken. Ich bin mir relativ sicher, dass eine Prüfung vorab die Datenlagequalität erheblich verbessern wird. Wir wissen ja, dass die SchILD2-Datenbanken i.d.R. noch von Importfehlern geprägt sind. Dass dort aber auch i.d.R. Tabellen enthalten sind, die seit Jahren nicht mehr verwendet werden. Offenbar gibt es aber auch Tabellen, die nur in SchILD2-NRW enthalten sind. Die im Migrationslog gemeldeten Tabellen frage ich mal bei Ribeka an, ob und was uns da entgangen sein mag.

Es geht nicht darum, die Migrationsprotokolle bis auf den letzten Eintrag zu prüfen, sondern es geht darum, dass die Daten möglichst vollständig in der neuen Datenbank ankommen, oder wie will man sonst sicherstellen, dass bei der Migration nicht gar aktive Schüler "verschütt" gehen ? Und was wäre zu tun, wenn das der Fall ist und SchILD2 z.B. nicht mehr vorhanden ist ?

Ich hatte die Migrationsprotokolle so verstanden, dass sie genau dafür da sind, um zu prüfen, wo etwas nicht migriert werden konnte. Was liegt also näher, diese um die Möglichkeit zu erweitern, aufzuzeigen, welcher Datensatz (ID) und was daran fehlerhaft ist ?

**Comment by T-Hagel-SK** [comment]
> Ob dann alle wichtigen Daten da sind und die Schule arbeiten kann, muss die Schule dann melden. Fehler bei der Migration werden wir natürlich bei konkreten Fällen korrigieren. Die Arbeit eines Schild-Zentral-Dienstleisters können wir aber leider nicht mit unseren Kapazitäten leisten.

Wie gesagt, es geht mir nicht um SchILDzentral, sondern um SchILD allgemein. Wenn schon der SVWS-Server das führende System ist und dort ein Migrationstool vorliegt, dann sollte das meinem Verständnis nach auch ermöglichen, der Schule Hilfsmittel an die Hand zu geben, um möglichst alle Daten zu migrieren, bzw. migrieren zu können.

> Sagt mir: Mit SchILD Zentral haben wir nichts zutun (was im Prinzip auch stimmt, denn SchILD Zentral ist ein kommerzielles Produkt der Firma Ribeka, das auf dem von Land bestellen SchILD NRW aufbaut).

Wenn Ribeka einen eigenen SVWS-Server bereitstellen würde, könnte ich mich dort austoben, wie ich das ohnehin schon zum Leidwesen von Ribeka tue. Aber meinem Verständnis nach ist dieser hier angebotene SVWS-Server das führende System.


> Aber @T-Hagel-SK: Nehmen Sie mal eine echte Schule für den Test. Die Quelldaten bleiben ja unberührt. Die Schule hier hat etwa 800 Schüler. Die sind auf einigermaßen aktueller Hardware schnell migriert. Die Beispieldatenbanken habe ich den Eindruck sind nicht immer ganz optimal.

Nun, ich habe das jetzt mal mit einer realen Schule aus der sog. Demo-Datenbank probiert. In unsere Demo-Datenbankumgebung spiegeln wir regelmäßig unsere produktive Datenbank, um den Schulen dann zu Schulungszwecken eine entsprechende Umgebung bereitstellen zu können. 

Nun, auch hier werde ich wieder von tausenden Einträgen im svws-server.log geflutet. Z.B. mit dem Hinweis "Entferne ungültigen Datensatz: Es gibt keinen Schüler mit der angegebenen ID in der Datenbank". Durchforste ich bei GitHub den Quellcode werde ich mal in SVWS-Server/svws-db-utils/src/main/java/de/svws_nrw/db/utils/schema
/DBMigrationManager.java in Zeile 1346 fündig. Dort steht:

_if ((daten.Schueler_ID == null) || (!schuelerIDs.contains(daten.Schueler_ID))) {
		logger.logLn(LogLevel.ERROR, "Entferne ungültigen Datensatz: Es gibt keinen Schüler mit der angebenen ID in der Datenbank.");
		entities.remove(i);_

Es sollte doch also möglich sein, den Logtext noch um die ID des Schülers zu erweitern UND die Angabe dazuzuschreiben, dass hier offenbar im Bereich der Förderempfehlungen eine Abfrage keinen erwarteten Wert oder Eigenschaft vorgefunden hat.

Wenn man aber Fehlermeldungen nicht dynamisch erzeugt, sondern von vorneherein festlegt, wie ab Zeile 185 ...:
_private static final String strFehlerKeinLernabschnitt =
			"Entferne ungültigen Datensatz: Es gibt keinen Lernabschnitt mit der angebenen ID in der Datenbank.";
private static final String strFehlerLernabschnittUngueltigNull =
			"Entferne ungültigen Datensatz: Abschnittsdaten müssen einen gültigen Lernabschnitt haben - null ist unzulässig.";
private static final String strFehlerLernabschnittUngueltig = "Entferne ungültigen Datensatz: Abschnittsdaten müssen einen gültigen Lernabschnitt haben.";

private static final String strFehlerKeinLehrer = "Entferne ungültigen Datensatz: Es gibt keinen Lehrer mit der angebenen ID in der Datenbank.";

private static final String strFehlerKeineCredentials = "Korrigiere fehlerhaften Datensatz: Entferne den Bezug zu den nicht vorhandenen Credentials.";_

... dann wäre es hilfreich, wenn man die jeweilige Variable um eben diese Infos erweitert.

> Logische Fehler kann der Importer natürlich nur soweit auflösen, wie es Gesetzmäßigkeiten gibt, die eingehalten werden müssen, und die man prüfen kann. Sinnfreie Eingaben von Anwendern gehören da nur bedingt zu.

Logische Fehler könnten in einer Vorprüfung angezeigt werden, um sie dann individuell prüfen und ggf. korrigieren zu können und erst danach die Migration durchführen.

 
> Aber ja, dort wo der Prozess auf einen logischen Fehler trifft, den er korrigiert, sollte er den Datensatz ausgeben, damit man im Nachgang schauen kann, was da in der Quelle (angeblich) falsch ist. Beim Beseitigen von bekannten Leichen sehe ich das nicht so kritisch.

Wenn wir doch hier mit dem Mega-Update die Möglichkeit haben, nicht nur die Datenbanktabellen besser zu strukturieren und gewachsene Fehler zu beseitigen, warum dann nicht auch die Möglichkeit nutzen und die Datenqualität zu verbessern ?

**Comment by T-Hagel-SK** [comment]
Aber, um auch wieder auf den Ursprungsvorschlag zu kommen, fänd ich eine Aufteilung des Migrationslogs in eine von der svws-server.log-Datei abweichende Datei oder als Datei zum Download extrem hilfreich ... denn durch die tausenden Fehlereinträge durch Mitteilungen über entfernte Schüler, Lehrer, etc. hat die Datei jetzt schon, obwohl nur bislang ich mit dem Server arbeite, eine Größe von 13 MB.

Wenn ich dort alleine nach "Entferne ungültigen Datensatz" suche und diese Einträge lösche, sind das bei nicht mal eine Handvoll Migrationsversuche schlappe 12.349 Einträge. Wie soll die Datei aussehen, wenn wir hier mal alle 260 Schulen migrieren wollen ?

**Comment by T-Hagel-SK** [comment]
> Sagt mir: Da wird nichts kommen, wenn es nicht jemand bei Ribeka bestellt. Sagt mir aber auch: Die Datenquallität ist uns egal, Hauptsache der SVWS Server findet eine Datenbank und startet.

Hm, sagt mir, dass sich darüber wohl noch nicht allzu viele Tester Gedanken gemacht haben. Aktuell ist dieser Issue eine recht einsame Diskussion...

**Comment by FPfotenhauer** [comment]
Am besten wäre es wohl, die Fehler zu identifizieren und an Ribeka weiter zu geben.
Im aktuellen Schild2-Zentral-Modul sollte dann ein Tool zur Verbesserung der Datenqualität zur Verfügung gestellt werden.

**Comment by ThomasBachran** [comment]
Die Umsetzung der oben genannten Punkte beziehen sich hier in vielen Teilen nicht auf den SVWS-Server. Aus der langem Diskussion ist es aufwendig, die hier wesentlichen Punkte zu extrahieren. Da in der Zwischenzeit einige Punkte bereits umgesetzt wurden, werde ich dieses Issue zunächst schließen. Sollten Sie noch weitere Vorschläge zu diesem Thema haben, dann öffnen Sie doch bitte weitere Issues, welche die gewünschten Features oder Fehler konkret beschreiben. Für längere Diskussionen verwenden Sie bitte Github-Discussions und nicht die Github-Issues.

In der Zwischenzeit wurden u.a.
- Präzisierungen der Fehlerrückmeldungen vorgenommen, so dass u.a. auch die IDs der betroffenen Datensätze (besser) erkennbar sind
- Für Prozesse, welche auch vom Admin-Client unterstützt werden, wurde im Server ein weiteres Logging-Ziel neben der Konsole eingerichtet, so dass nun neben dem allgemeinen Log auch Schema-spezifische Logs geschrieben werden. Die Verwendung der Schulnummer ist hier nicht möglich, da diese bei manchen Prozessen noch nicht verfügbar ist. Das neue Verhalten lässt sich in der `svwsconfig.json` mit der Option `LoggingEnabled` aktivieren bzw. deaktvieren. Dort ist auch der Ort für die Log-Dateien konfiguriert.
- Bei den Schema-spezifischen Logs werden nun zeilweise der Zeitpunkt des Eintrags und das Log-Level (INFO, ERROR) mit ausgegeben. Das ist bei der Konsolenausgabe deaktiviert.

Die Optimierungen werden dann mit dem nächsten Pre-Release zur Verfügung stehen.

**Comment by T-Hagel-SK** [comment]
Es sollte ein Issue werden, keine Diskussion.
Es waren konkrete Ideen und HInweise genannt worden. Ich schau mir dann mal im nächsten Release an, was davon bereits umgesetzt werden konnte und melde mich ggf. nochmal dazu.

Das weitere Loggingziel: Super. 
Nennung der IDs: Super. 
Zeitpunkte: Super.

**Comment by T-Hagel-SK** [comment]
> Am besten wäre es wohl, die Fehler zu identifizieren und an Ribeka weiter zu geben. Im aktuellen Schild2-Zentral-Modul sollte dann ein Tool zur Verbesserung der Datenqualität zur Verfügung gestellt werden.

Dazu wäre es ja gut, wenn man die Fehler anhand der IDs identifizieren könnte :-) Aber das kommt ja mit der nächsten Version schon.
Sollte das Tool zur Verbesserung der Datenqualität dann nicht auch für SchildNRW bereitgestellt werden ?
