### ISSUE TITLE
Kursplanung: Fehler beim Sperren von neu angelegten Kursen

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#213]
In der Q2 werden die neu angelegten Zusatzkurse nicht gesperrt. Das ist reproduzierbar.

![image](https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/39ae14d7-a5ce-4dc7-bebc-d7901ce45164)

**Comment by NielsWL** [comment]
Beim Entsperren ist es genauso, wenn ich nur die neuen Kurse sperren möchte, geht es.

**Comment by benjaminbartsch** [comment]
@NielsWL 
Okay das ist reproduzierbar. Ich mache dazu bei uns ein internen Issue auf und schreibe noch genauer, wie ich es erzeugt habe.

**Comment by ThomasBachran** [comment]
Das Problem wurde behoben und sollte im nächsten Pre-Release nicht mehr auftreten.
