### ISSUE TITLE
Kursplanung: Wahlkonflikte

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#214]
Beim Blocken der Q2 (Schüler in Abiturkursen festgesetzt) passt die Anzeige nicht zum Ergebnis. Warum es überhaupt so viele Wahlkonflikte (1023) werden, ist aus rätselhaft. Denn die Anzeige sagt auch, dass Schüler den LKs nicht zugeordnet werden, obwohl alle LK fixiert sind.

![image](https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/036d714b-9a33-48c9-8a0f-cc42022a8542)

**Comment by NielsWL** [comment]
Ein Ergebnis...

![image](https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/1e593b16-3cda-4d0b-accf-814759ce90bc)

**Comment by NielsWL** [comment]
![image](https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/ba7fe19b-0f36-4eaf-85d4-79491b47cbdd)

**Comment by benjaminbartsch** [comment]
@NielsWL:
Das ist sehr schwer für mich nachzuvollziehen, da brauche ich einen Export der Daten, damit ich diese bei mir zum Testen importieren kann. 

Ich habe eine Idee. Der Algorithmus kann nicht **direkt** mit fixierten SuS umgehen. Stattdessen werden alle anderen Kurse (der selben Fachart) dem Schüler intern verboten. Am Ende werden dann die SuS die fixiert sind einfach dem Kurs hinzugefügt, was widerum zu Konflikten führt, wenn die Kurse des Schülers in der selben Schiene gelandet sind. 

Ich hatte den Algorithmus aber mal angepasst, so dass dieser effektiver arbeitet bei vielen fixierten SuS. Deswegen wundert das mich. Insbesondere wenn **SuS und Kurs zusammen" fixiert sind (bei LKs) ...das sollte völlig unproblematisch sein.

**Comment by benjaminbartsch** [comment]
@NielsWL: Okay, ich habe das Problem lösen können. Die Berechnung des Tooltips wurde durch eine Umstrukturierung so verändert, dass alle Zuordnungen als falsch gelten. 

Ich schließe das Issue, da es mMn doch nichts mit dem Algorithmus zu tun hatte.
