### ISSUE TITLE
Fehler Aufruf 0.8.16

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/SVWS-Server#215]
Nach Update von 0.8.15 zu 0.8.16 erhalte ich beim Aufruf diese Fehlermeldung:
![grafik](https://github.com/SVWS-NRW/SVWS-Server/assets/84628225/3165d3bc-d78f-4d4d-bb32-8a4cc6ea9774)

Nach Downgrade auf 0.8.15 funktioniert wieder alles.
Edit: System: Debian 12 in virtuellen Containern auf ProxMox-Server. Gab nie Probleme.

Fehlermeldung nach "systemctl status svws":
Jul 10 11:21:29 svws09 java[532]:     Fehler: Schema kann nicht aktualisiert werden. Das Schema wird deaktiviert.

**Comment by HHayen** [comment]
Gesamtes journal ist jetzt bei den Entwicklern.

**Comment by kroerig** [comment]
dann warte ich sicherheitshalber bevor ich meinen Docker-Container austausche.

**Comment by ThomasBachran** [comment]
Es hat sich hierbei um einen fehlerhaften Eintrag in der svwsconfig.json gehandelt:
- `"TLSKeyAlias" : null,` ist gültig und wählt den "erstbesten" Eintrag
- `"TLSKeyAlias" : "",` ist nicht gültig, wird aber ab dem nächsten Pre-Release zukünftig wie `null` gehandhabt.

Über die Option können ggf. mehrere Zertifikate im SVWS-Server verwaltet werden und über den Alias wird dann das Zertifikat ausgewählt, welches verwendet wird. Die verwendeten Alias-Einträge werden bei Start des Servers im Log aufgeführt (siehe Abbildung, dort lautet der Alias "selfsigned").

![grafik](https://github.com/SVWS-NRW/SVWS-Server/assets/46782864/9cb6c09f-be3f-4678-9844-5306aae3bbb4)

Durch setzen des Alias auf null bzw. den korrekten Namen konnte das Problem behoben werden.
