### ISSUE TITLE
Zeitraster ändern

### ISSUE THREAD

**Issue by KaBe47Du** [SVWS-NRW/SVWS-Server#217]
Bei dem versuch, das Zeitraster zu ändern, treten verschiedene Fehler auf, u. a.: 

- Beim Versuch, 1. Stunde um 8:45 enden und die 2. um 8:45 beginnen zu lassen (Doppelstundenmodell), erscheint der Fehler: "Die Änderung der Stundenzeiten würde zu einer Überschneidung führen und ist nicht zulässig." 
- Das Löschen von Stunden gelingt nicht, bspw. wird die gelöschte 2. Stunde dann innerhalb der 1. angezeigt (s. u.) 
![Fehler_Zeitraster-2](https://github.com/user-attachments/assets/67f80825-1d99-4fe6-b3e7-9f3d6cf3e31a)
- Beim Versuch, die gänderten Stundenzeiten zu aktualisieren, erscheint eine seltsame Anzeige (s. u.) 
![Fehler_Zeitraster-3](https://github.com/user-attachments/assets/4c1e306d-45ef-4677-8d6a-bfd1b93c665b)
- auch sonst manchmal seltsame Anzeige, besonders hinsichtlich linker Spalte und Beginn/Ende (s. u.)
![Fehler_Zeitraster](https://github.com/user-attachments/assets/eefbf620-8b3b-4934-bdb2-026ee6f9b187)
- Fehlermeldung in verschiedenen Situationen: s. u.

```json
{
  "env": {
    "mode": "stable",
    "version": "0.9.0",
    "Commit": "36cd4e6f6bee686d9bc07161086394eac080eb82"
  },
  "error": {
    "id": 3,
    "name": "Programmierfehler: Bitte melden Sie diesen Fehler.",
    "message": "beginn1 > ende1",
    "stack": [
      "No@https://localhost/assets/index.js:22:31601",
      "cN@https://localhost/assets/index.js:22:32548",
      "Gl@https://localhost/assets/index.js:22:32757",
      "jn@https://localhost/assets/index.js:24:210641",
      "ifTrue@https://localhost/assets/index.js:24:210680",
      "zeitrasterGetSchneidenSich@https://localhost/assets/index.js:53:557270",
      "zeitrasterGetSchneidenSichListeMitIgnore@https://localhost/assets/index.js:53:557568",
      "setup/s<@https://localhost/assets/SStundenplanZeitrasterPausenzeit.js:1:9581",
      "vk/this.effect<@https://localhost/assets/index.js:10:9155",
      "run@https://localhost/assets/index.js:10:1485",
      "get value@https://localhost/assets/index.js:10:9399",
      "setup/</<.default</<.default<@https://localhost/assets/SStundenplanZeitrasterPausenzeit.js:1:11037",
      "t@https://localhost/assets/index.js:14:3072",
      "Dt@https://localhost/assets/index.js:14:6940",
      "setup/<@https://localhost/assets/index.js:56:96260",
      "mm@https://localhost/assets/index.js:14:3386",
      "Ie@https://localhost/assets/index.js:14:22555",
      "run@https://localhost/assets/index.js:10:1485",
      "QE/Wt/E.update@https://localhost/assets/index.js:14:23334",
      "Zu@https://localhost/assets/index.js:14:46",
      "Ok@https://localhost/assets/index.js:14:1805",
      ""
    ],
    "log": null
  }
}
```

**Comment by kroerig** [comment]
Sind da nicht normalerweise (kurze) Pausen zwischen den Stunden? Dann erübrigt sich das Problem.

**Comment by KaBe47Du** [comment]
Nein, wir machen 90' durch. Alternativ (und besser) könnte man die Zeile 1./2. nennen, aber das geht aufgrund des numerischen Feldes für die Bezeichnung nicht.

**Comment by FPfotenhauer** [comment]
Sollte in der 0.9.1 behoben sein.
