### ISSUE TITLE
Scrollbalken bei Schienen fehlt

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/SVWS-Server#218]
Unter Oberstufe/Kursplanung fehlt bei den Schienen ein Scrollbalken, sodass ggf. nicht alle Schienen sichtbar sind:

![image](https://github.com/user-attachments/assets/45f92b4c-4547-4c6b-a554-c952abac6740)

**Comment by ThomasBachran** [comment]
Wurde im dev-Branch umgesetzt.
