### ISSUE TITLE
Anzeige Kurse nach Filter

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/SVWS-Server#219]
![grafik](https://github.com/user-attachments/assets/75e05942-186c-48b6-9e45-87c900f4ad86)
Filter auf EF liefert diese Ansicht eines 06er-Kurses. 
Es ist immer der zuletzt markierte Kurse, es ist niocht möglich, keinen Kurs zu markieren, nachdem einer markiert wurde.

**Comment by hmt** [comment]
Das hängt damit zusammen, dass auch nach einer Änderung der Daten, der Datensatz nicht verloren gehen soll. Ob es bei den Kursen sein muss, sollte geprüft werden.

Beispiel: Schüler werden nach "aktiv" gefiltert, wahrscheinlich die reguläre Ansicht. Schüler geht ab, Status wird auf "Abgänger" gesetzt. Die Eingabe ist noch nicht abgeschlossen, man will noch dieses oder jenes eintragen, aber durch die neue Statuszuweisung würde dieser Schüler nicht mehr in der Liste stehen und man müsste erst wieder nach "Aktiv/Abgänger" filtern, um weiterarbeiten zu können.

Das war der Grund für diese Art der Listendarstellung

**Comment by HHayen** [comment]
Klingt absolut schlüssig. Nur hier bei "Kursen" vielleicht nicht so erforderlich bzw. sogar störend.

**Comment by hmt** [comment]
@ThomasBachran was meinst Du, müssen wir hier zusätzlich etwas bedenken?
