### ISSUE TITLE
Datenbankmigration API Funktionen fehlen

### ISSUE THREAD

**Issue by kroerig** [SVWS-NRW/SVWS-Server#22]
In der aktuellen 0.7.7 vermisse ich in der Swagger UI die Root-Funktionen zum Anlegen und Löschen einer Datenbank inkl. Benutzer sowie die Migration?
Wie bekomme ich denn jetzt eine DB mirgriert?

Bug oder Feature?

**Comment by ThomasBachran** [comment]
Die ist immer noch vorhanden. Man muss einfach nur oben den Link für die Schemaverwaltung nutzen:
![grafik](https://github.com/SVWS-NRW/SVWS-Server/assets/46782864/c9c3ca73-b395-4e10-8f39-ffea94345dc9)

**Comment by kroerig** [comment]
Gut versteckt. Aber so eine Änderung gehört in die Release Notes.
