### ISSUE TITLE
Stundenplan Import im falschen Abschnitt

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/SVWS-Server#224]
Importiert man einen Units-Stundenplan für den kommenden Abschnitt, wird dieser unter Stundenplan  im falschen Abschnitt einsortiert.

**Comment by ThomasBachran** [comment]
Das Problem müsste mit Commit 4c9128aff023fe96928e6ba2b16fc0297118fddb behoben sein.
