### ISSUE TITLE
Abgleich Stundenplan - Schienen

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/SVWS-Server#227]
Aktuell müssen erst Schienen im Client erstellt werden (z.B. Diff-Kurse in JG 9) bevor der Stundenplan erstellt wird.

Wird der Stundenplan zuerst erstellt und man legt Schienen erst im Nachgang Schienen an, sind diese im Stundenplan nicht sichtbar. 
Hier wäre ein Abgleich sinnvoll.

**Comment by ThomasBachran** [comment]
Die Schienen sollten jetzt automatisch angepasst werden. Kannst du das bitte prüfen?

**Comment by AnneSchueller** [comment]
Klappt jetzt für nachträglich hinzugefügte Kurse
