### ISSUE TITLE
Sortiermöglichkeit fehlt

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/SVWS-Server#228]
Unter Stundenplan/Unterrichte

Sinnvoll wäre eine Standardsortierung der Unterrichtsliste. Zudem Sortiermöglichkeiten durch Anklicken der Spalten Stunde/Kurs oder Fach/ Lehrer ...

![image](https://github.com/user-attachments/assets/0cb499fa-01eb-4fda-81c8-a93613089fd1)

**Comment by hmt** [comment]
Ist drin, meine Commit-Message war falsch formatiert, es wurde nicht automatisch geschlossen.
