### ISSUE TITLE
SVWS Client hängt nach fehlerhafter Anmeldung

### ISSUE THREAD

**Issue by kroerig** [SVWS-NRW/SVWS-Server#23]
Ich beobachte folgendes Verhalten im SVWS Client (0.7.7):

Loginseite aufrufen und versuchen mit existentem Benutzer aber falschen Passwort anmelden:
![grafik](https://github.com/SVWS-NRW/SVWS-Server/assets/5148795/5182c223-d40d-4590-934d-ad422d64ce04)

Dann erneut auf den Anmelden-Button klicken:
![grafik](https://github.com/SVWS-NRW/SVWS-Server/assets/5148795/4ad6e952-4383-4417-990f-3f200514dbfb)

Ergbnis: Der Browser hängt sich auf:
![grafik](https://github.com/SVWS-NRW/SVWS-Server/assets/5148795/83c45740-90e6-4516-b869-39a570105c5b)

Nanchmal auch denn, wenn man beim zweiten Versuch das richtiges Passwort eingibt.

Dann hilft auch kein Reload der Seite.
Browser: Firefox 

Im Edge erscheint stattdessen ein BasicAuth-Fenster:
![grafik](https://github.com/SVWS-NRW/SVWS-Server/assets/5148795/293531c0-99f8-494e-a6af-040a5159154d)

**Comment by FPfotenhauer** [comment]
Ich kann das Verhalten immer dann reproduzieren, wenn ich zweimal hintereinander ein falsches Passwort eingebe. Danke.

**Comment by ThomasBachran** [comment]
Der Fehler wurde behoben und sollte in der nächsten Version nicht mehr auftreten.

Vielen Dank für die Rückmeldung!

**Comment by kroerig** [comment]
Es wäre schön, wenn Sie zu den Issues auch den jeweiligen PR referenzieren könnten. So lässt sich dann auch nachvollziehen, woher Änderungen kamen.
