### ISSUE TITLE
Scrollen funktioniert nicht

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/SVWS-Server#230]
Unter Schule/Benutzergruppe

Durch das Aufklappen von Kompetenzen rutschen untere Einträge aus dem Bildschirm. 
Ein Runterscrollen ist nicht möglich:

![image](https://github.com/user-attachments/assets/cdb89f6d-e0a7-4c3a-b666-508589ac93ff)

**Comment by ThomasBachran** [comment]
@AnneSchueller : Ich kann das Problem bei mir aktuell nicht nachvollziehen. Kannst du das bei dir nochmal prüfen. Wenn der Fehler noch auftritt, dann müssten wir uns das gemeinsam anschauen. Wenn nicht, kannst du das Issue dann bitte schließen.

**Comment by AnneSchueller** [comment]
Funktioniert bei mir jetzt auch
