### ISSUE TITLE
Fragen zum SVWS-Server 

### ISSUE THREAD

**Issue by T-Hagel-SK** [SVWS-NRW/SVWS-Server#231]
Hallo zusammen,
da meine Anfragen in der Diskussionsrunde entweder keiner liest, sich keiner zuständig fühlt oder sieht, frage ich sie hier. 

Uns stellt sich weiterhin die Frage, was es verhindert, die schiere Menge an Datenbanken und SVWS-Servern ressourcen- und kostenschonend zu reduzieren. Warum ist es z.B. nicht möglich, stadtweit mit einem Webserver auszukommen ? So wie das für viele anderen Anwendungen auch möglich ist. Wir haben z.B. auch nur einen SchildWeb-Server und nicht Dutzende im Einsatz.

Mir sind Aussagen bekannt wie "Pro Schule einen SVWS-Server", bzw. "Pro Schule die Kursblockungen durchführt, einen SVWS-Server", sowie "Mehrere Grundschulen können sich einen SVWS-Server"... 

Ich frage, weil wir in Köln mit 67 Gymnasien und Gesamtschulen in dieser Rechnung alleine schon 67 produktive SVWS-Server benötigen würden. Die restlichen 158 Schulen würden dann x weitere SVWS-Server belegen ?

Was uns aber vollends umhaut ist das Festhalten an der Vorgabe unter SchildZentral die Mandantenfähigkeit aufzugeben und für jede Schule eine eigene Datenbank, bzw. Schema einzurichten. Dazu gesellt sich dann noch eine Datenbank je Schule für die Ribekamodule, plus eine Schulträgerdatenbank, so dass wir in Köln dann auf schlanke 531 produktive Datenbanken kommen. 

Verschlankt man dann hier das bisherige Angebot, dass für jede Schule auch ein Testumfeld auf einem Demo-Datenbankserver möglich ist, auf eine Demodatenbank pro Schulform, dann kommen wir auf eine Kostensteigerung im Vergleich zu SchildZentral2 um den Faktor 80. 

Setzt man weiterhin auf jede Schule kann in ihrem Datenbestand auch in einer Demoumgebung testen, sind wir bei Faktor 190, weil dann auch für die Demoschulen die Anzahl der SVWS-Server mutmaßlich mitwächst.

Wäre es hingegen möglich, die Datenbanken auf maximal 3 produktive zu reduzieren und wäre es möglich am Ende nur einen, maximal zwei SVWS-Server stadtweit bereitzustellen, würde das sich das bei uns "nur" noch um den Faktor 4 erhöhen, was im direkten Vergleich der kleinere Brocken wäre.

In der Dokumentation steht unter [https://doku.svws-nrw.de/Projektanforderungen.html#plattformubergreifende-losung] folgender Aspekt:
"_Der SVWS-Server muss in einer Sprache entwickelt werden, die plattformübergreifend einsetzbar ist. Dabei ist unbedingt wünschenswert, dass die Server in der Schule und in Kommunalen Rechenzentren unter Linux betrieben werden können, damit den Schulträgern an dieser Stelle Kosten erspart bleiben können."_

Das ist lieb und nett gemeint, geht aber in der Rechenzentrumsrealtität vorbei oder trifft auf nur wenige, kleinere zu. Denn die Linuxvarianten, die hier zum Einsatz kommen sind i.d.R. Enterprise-Versionen mit entsprechenden Supportleistungen und auch die MariaDB-Server liegen auf kostenpflichtigen Serverbetriebssystemen. Hinzu kommen Kosten für Backup- und Incidentsteuerungssysteme. Alles andere als Mandantenfähigkeit führt bei allen IT-Dienstleistern zu erheblichen Mehrkosten, die den Schulträgern in Rechnung gestellt werden.

Das nur am Rande ... mich würde dennoch weiterhin interessieren, was einen SVWS-Server so langsam macht, dass man ihn nicht von mehreren oder allen Schulen, bzw. eigentlich Nutzern, gleichzeitig nutzen kann. Zum Größenvergleich ... an guten, normalen Tagen tummeln sich auf unserer SchildZentral-Datenbank um die 500-600 Anwender. Von denen sind aber nicht alle mit Abfragen beschäftigt, sondern lediglich in den Programmmodulen angemeldet. Das wäre doch bei einem SVWS-Server auch nicht anders. Nicht jeder der den PC-Client startet oder sich über den Webbrowser anmeldet, führt dann permanent Abfragen durch. Es ist mir ein Rätsel.

Schöne Grüße aus Köln
Thomas Hagel

Fachanwendungssupport & SchildZentral3-Koordination

**Comment by FPfotenhauer** [comment]
Wie sind denn Ihre Tests mit vielen Schulen auf einem SVWS-Server ausgefallen?
Aus der Sicht der Entwickler ist es durchaus möglich sehr viele Schulen auf einem Server laufen zu lassen.
Über Erfahrungswerte würden wir uns sehr freuen. Unser Docker-Container hat mittlerweile die Security-Checks bestanden.
Das ist aus unserer Sicht die beste Variante mit mehreren Servern umzugehen.

Das pro Schule ein SVWS-Server eingerichtet werden muss, ist nicht korrekt wiedergegeben. Es kommt auf den Grad der Virtualisierung an, die dahinter steckt. Wenn man einen leistungsstarken Server hat, kann man dort sicherlich 50 Schulen oder mehr betreiben. Dort kann man aber auch 50 DockerContainer aufsetzen. Dann hätte jede Schulen "einen" Server, faktisch ist es aber nur einmal Hardware.

Man muss hier sehr stark aufpassen wovon man redet. Es ist bei der Administration eine "Geschmacksfrage", was einem lieber ist.
Schulträger, die auf Schild-NRW setzen werden hier von uns unterstützt.

Manche Schulträger bevorzugen Schild-Zentral. Da muss sich dann der Dienstleister um das Konzept der Umgebung kümmern.

Ich werde meine Antwort an die Diskussion anheften, da es sich hier um kein Issue handelt, was wir beheben können.
