### ISSUE TITLE
Stundenplan: Import aller Unterrichte in der Sek. II schlägt fehl

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#232]
Beim Import der Stundenplandatei aus Untis werden nur die Hauptklassen (Kl.-Gruppe 1) importiert, nicht aber die "Kerngruppen" (D, E, M), die als Kl.-Gruppe 2 definiert sind. Das erste Bild zeigt die Einträge in den Stammdaten von Untis. Im zweiten Bild hätten die Kerngruppen Mo und Di in 1/2 ihren Unterricht.

So fehlen alle Unterrichte dieser Kerngruppen im Stundenplan. Das dürfte aber gängige Praxis sein bei solch einem Konzept in der EF.

![image](https://github.com/user-attachments/assets/8aa2920a-c303-41ea-9889-973743082b91)

![image](https://github.com/user-attachments/assets/f9f3138a-69f4-4401-889d-ff3d5e32a520)

**Comment by ThomasBachran** [comment]
Vielen Dank für die Rückmeldung. Die Unterstützung von Teilklassen wird beim aktuellen Import der Stundenplan-Datei GPU001.txt noch nicht unterstützt. Hierzu werden zusätzlich Informationen der GPU003.txt benötigt. Ich übernehme dieses Feature in unsere interne Planung und schließe es hier.
