### ISSUE TITLE
Stundenplan: Änderung der Stundenzeiten im Katalog

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#233]
Änderung der Stundenzeiten im Katalog führt zu einer Fehlermeldung, wenn man überlappende Zeit eingibt. Das ist auch ok, aber man kommt nur wieder raus, wenn man den Bereich verlässt. Zusätzlich wird der Fehler aufgerufen, obwohl keine Überlappung exisitiert und man einfach einen neue Stunde anklickt.

![image](https://github.com/user-attachments/assets/fa3380bc-5178-46b1-b0dc-2ca1d55aec7a)

```json
{
  "env": {
    "mode": "stable",
    "version": "0.9.1",
    "Commit": "745eacb1aaa7dbd45376d4041b93119cccf468e1"
  },
  "error": {
    "id": 1,
    "name": "Programmierfehler: Bitte melden Sie diesen Fehler.",
    "message": "beginn1 > ende1",
    "stack": [
      "tr: beginn1 > ende1",
      "    at tr.ifTrue (https://localhost/assets/index.js:24:2193)",
      "    at It.zeitrasterGetSchneidenSich (https://localhost/assets/index.js:53:540533)",
      "    at It.zeitrasterGetSchneidenSichListeMitIgnore (https://localhost/assets/index.js:53:540833)",
      "    at https://localhost/assets/SStundenplanZeitrasterPausenzeit.js:1:9343",
      "    at Vp.fn (https://localhost/assets/index.js:10:9266)",
      "    at Vp.run (https://localhost/assets/index.js:10:1485)",
      "    at get value (https://localhost/assets/index.js:10:9511)",
      "    at CE (https://localhost/assets/index.js:10:1642)",
      "    at get dirty (https://localhost/assets/index.js:10:1204)",
      "    at Wt.k.update (https://localhost/assets/index.js:14:26810)"
    ],
    "log": null
  }
}
```

**Comment by hmt** [comment]
ich glaube, dass dieser Fehler hier bereits vor einiger Zeit behben wurde, da ich in dem Zusammenhang auch die Fehlermeldung angepasst hatte und breiter darstelle:

<img width="342" alt="image" src="https://github.com/user-attachments/assets/6c8041d5-a973-4f7a-bcfd-afa1c9198762">

Bitte schließen, wenn das zutrifft.

**Comment by FPfotenhauer** [comment]
Kann ich hier schließen?
