### ISSUE TITLE
Frage: Woher bekommt man den WeNoM

### ISSUE THREAD

**Issue by kroerig** [SVWS-NRW/SVWS-Server#234]
Hallo,

wie und wo erhällt man den unter https://doku.svws-nrw.de/Projekte/WeNoM/ beschriebenen WebNotenManager?
Im Forum habe ich einen Post (https://schulverwaltungsinfos.nrw.de/svws/forum/viewtopic.php?p=37715#p37715) von März gefunden, dass der weitgehend fertig sei.

Ich würde den gerne mal installieren und schauen welche Anforderungen der so mitbringt. Und natürlich wie er sich so bereitstellen lässt, dass auch alle damit arbeiten können.
Gibt es ihn als fertiges Dockerimage?

Danke.

**Comment by FPfotenhauer** [comment]
Das Produkt ist noch in der Entwicklung und nicht in einer Beta-Phase.
Ich kann Ihnen aber gerne eine Preview zur Verfügung stellen.
Dazu würde ich aber gerne vorher einige Informationen geben.
Würden Sie mir bitte eine Mail schreiben?
