### ISSUE TITLE
SQLite-Sicherung aus SchILD3 funktioniert nicht mehr

### ISSUE THREAD

**Issue by JuergenRichter** [SVWS-NRW/SVWS-Server#236]
Ich habe heute festgestellt, dass die SQlite-Sicherung aus SchILD3 (Aufruf des SVWS-Servers 0.9.2) nicht mehr funktioniert. Es wird zwar der Responsecode 200 geliefert, die erzeugte Datei ist aber 0 kB groß. Mit einer früheren Version hat es noch geklappt (Datei vom 23.8.2024):

![image](https://github.com/user-attachments/assets/6e6637c1-042b-4d0c-a556-df1204cb538a)

Wenn ich das über die SwaggerUI mache, sind die Dateien in "C:\ProgramData\SVWS-Server\temp" ebenfalls 0 kB groß:
![image](https://github.com/user-attachments/assets/043c30db-fcbd-4407-b6c9-71878cc67848)

**Comment by ThomasBachran** [comment]
Der Fehler ist jetzt bei uns behoben und wird im nächsten Pre-Release behoben sein.
