### ISSUE TITLE
Kursart wird bei Kurszuweisung ignoriert

### ISSUE THREAD

**Issue by SchILD-Kloppenburg** [SVWS-NRW/SVWS-Server#237]
Ich wollte die Kurszuweisung in der Mittelstufe ausprobiert und habe nightly.svws-nrw.de in der Version 0.9.3-SNAPSHOT 6eb0214964290463a730ac8c29947d779c679ddb verwendet.

- Wähle einen Schüler aus, z. B. Dominik Batta (9A)
- gehe auf Lernabschnitte
- richte mit '+' unten rechts ein neues Fach ein
- wähle Spanisch ab Klasse 8
- wähle den Kurs N-S-1

Bei den Kursen ist die Kursart FS3 hinterlegt. in der Ansicht Lernabschnitte wird zwar der Kurslehrer übenommen, aber nicht die Kursart.

Gruß, Ulrich Kloppenburg

**Comment by ThomasBachran** [comment]
@SchILD-Kloppenburg : Vielen Dank für die Rückmeldung. Der Fehler wurde soeben mit Commit c95298009d9637c9b77d6e9cb106dfd2307cce3e behoben.
