### ISSUE TITLE
Laufbahnplanung: Beratungsdatum auf Knopfdruck verändern

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#240]
Das Beratungsdatum lässt sich nicht verändern, auch nicht, wenn ich etwas verändert habe. Hatte vorher mal geklickt, nun im dritten Fach in der Q2.2 etwas geändert auf "S", aber das Beratungsdatum lässt sich nicht auf Knopfdruck speichern. Auch wenn ich einen anderen Schüler auswähle und dann wieder zurück zum aktuellen Schüler gehe, tut sich nichts.

Wenn ich das Datum händisch verändere, kann ich auch wieder speichern, aber das kann ja nicht Sinn der Sache sein...

![image](https://github.com/user-attachments/assets/f11763be-af61-481f-ae84-57c565f557e8)

**Comment by hmt** [comment]
ich habe nun einen Bugfix eingespielt, der auf Änderungen in der Planung reagiert. Sobald man eine Neuberechnung der Laufbahnfehler auslöst, wurde irgendwas an der Laufbahnplanung geändert. Das führt dazu, dass das Datum auf _heute_ angepasst wird und man auf _Speichern_ klicken kann (muss man aber nicht). Ebenso kann man wie vorher auch ohne Änderungen etwas an der Beratung anapssen und speichern.
Ich hoffe, dass ich das nun sinnvoll gelöst habe, obwohl es meinem Verständnis nach über dieses Issue hinausgeht, was jetzt passiert.
