### ISSUE TITLE
Laufbahnbogen: Beschreibung

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#242]
Auf dem Laufbahnbogen oben rechts steht "Wahl für die EF.2", sobald das neue Halbjahr angefangen hat. Wenn ich den Wahlbogen aber neu drucken will zum Unterschreiben nach Umwahlen, ist das falsch.

![image](https://github.com/user-attachments/assets/4603bcb1-8b80-4013-a7ac-aa227432f399)

**Comment by ThomasBachran** [comment]
Wenn der Schüler bereits in diesem Halbjahr ist, dann ist das zunächst korrekt. Du kannst aber beim Schüler auf ein altes Halbjahr zurückgehen (siehe Bild). Dann wird er die EF.2 entsprechend anpassen.

![grafik](https://github.com/user-attachments/assets/bbc02a54-5ffa-49cd-ad38-66db3d9cdc1e)

**Comment by NielsWL** [comment]
Das stimmt zwar, aber dann ändert sich auch die Klasse von EF auf 10 (hier 10e2). Das stimmt ja wieder nicht! Denn die Schüler sind in der EF und so muss das auch auf dem Wahlbogen stehen.
Vorschlag, es gibt ein (voreingestelltes) Feld, wo das Beratungshalbjahr geändert werden. Der Standard ist so, wie es jetzt umgesetzt ist.

![image](https://github.com/user-attachments/assets/7ec7e336-de4e-49c0-8a30-c87bba8659cc)

**Comment by M-Plu** [comment]
Bitte mal schauen, in der Version von heute wird jetzt die Klasse des Schülers aus dem aktuellen Abschnitts der Schule verwendet.

**Comment by NielsWL** [comment]
Jetzt wird bei Auswahl eines vorherigen Halbjahres folgendes angezeigt:

![image](https://github.com/user-attachments/assets/fc39081b-7f31-4ea9-8212-d5f24911e40f)

Bei Auswahl des aktuellen Halbjahres dies:

![image](https://github.com/user-attachments/assets/419cbadd-53f8-43a9-907c-45bfe766d854)

**Comment by NielsWL** [comment]
Ich denke wirklich, dass das untere richtig ist, ich aber über ein Dropdown-Menü einstellen können muss, für welches Halbjahr die Wahl ist, so dass "Wahl ab..." veränderbar ist.

**Comment by NielsWL** [comment]
Die Klasse ist ja auch, sobald die Schüler in der Sek. II sind, egal. Das steht ja in der ersten Zeile.

**Comment by NielsWL** [comment]
1) Die Klassen bilden wir auch, wir nennen sie Kerngruppen. Dann macht das Sinn, wenn diese in Schild eingegeben sind.
2) Ich habe auch links bei Schülern das HJ ausgewählt, dann über die Laufbahnplanung, dann der Druck.
3) Was passiert, wenn der Schüler in der 10 noch gar nicht im System war. Dann geht der Weg nicht.
4) Wenn man so mehrere Bögen drucken möchte, so wie wir jetzt aktuell das mit 20 Schülern wegen Umwahlen gehabt hatten, dann ist der Weg sehr aufwändig, jedes Mal einzeln den Druck anzustoßen.
5) Lösungsvorschlag: Es gibt eine PDF für das aktuelle Halbjahr zum Druck, eine PDF für das Folgehalbjahr zum Druck. Habe ich gestestet über eine Veränderung in der HTML Datei. Denn nur dies muss ja getauscht werden, der rest passt ja: `${schueler.gostLaufbahnplanung().folgeAuswahlGOStHalbjahr()} `
So könnte ein Auswahlbutton bzw. -feld entfallen.

**Comment by M-Plu** [comment]
Zum Punkt 4: Will man mehrere Bögen drucken, dann am besten unter Oberstufe > Laufbahnen gehen. Dort kann man die Schüler auswählen und dann den Druck starten, entweder als Gesamt-PDF oder als ZIP mit den einzelnen PDF pro Schüler)

> Jetzt wird bei Auswahl eines vorherigen Halbjahres folgendes angezeigt:
> 
> ![image](https://private-user-images.githubusercontent.com/71388959/370000244-fc39081b-7f31-4ea9-8212-d5f24911e40f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNjUxODAsIm5iZiI6MTcyNzE2NDg4MCwicGF0aCI6Ii83MTM4ODk1OS8zNzAwMDAyNDQtZmMzOTA4MWItN2YzMS00ZWE5LTgyMTItZDVmMjQ5MTFlNDBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDA4MDEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmNGFmODc5NzI5NzM2ZWZjMWQyNTdiYzI2ZGJmZWE5ZjIxNmE0NjIxMDA2YjIzMjhiNjZmYTkxMjY4MzU4MzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cRWLoyN8Gxv5uw91ZYnQwd8e6t1BclzVd53RuElU9rU)
> 
> Bei Auswahl des aktuellen Halbjahres dies:
> 
> ![image](https://private-user-images.githubusercontent.com/71388959/370000457-419cbadd-53f8-43a9-907c-45bfe766d854.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNjUxODAsIm5iZiI6MTcyNzE2NDg4MCwicGF0aCI6Ii83MTM4ODk1OS8zNzAwMDA0NTctNDE5Y2JhZGQtNTNmOC00M2E5LTkwN2MtNDViZmU3NjZkODU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDA4MDEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiMjNmNWI2NTM2MjMyMDQzZWJiYmNkYTgzOTg5OTQxNzdmNmU1YjcyOWE2MjAyNmY4NjQ4NGZhNzUzMjM0MmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9KY3MpKk91t30WacQDYcJlvlWQ-PRTUvXQ35GLcQew0)

Ist die leere Ausgabe (Bild 1) bei einem Schüler entstanden, der erst zur EF an die Schule gekommen ist? Ich muss halt nachvollziehen, warum bei dir eine andere Ausgabe erscheint, als bei dir.

Ich werde hinter "Abitur 2027" die Stufe mit Halbjahr entfernen, die ist je eigentlich redundant. Aber die Stufe "Wahl ab ..." muss ja korrekt angezeigt werden.

**Comment by M-Plu** [comment]
So, bitte noch mal testen, ob die Ausgabe nun überall stimmt. Dann würde ich schließen.

**Comment by NielsWL** [comment]
Ich persönlich finde die Lösung zwar nicht anwenderfreundlich, weil die Funktion des Drucks für die unterscheidlichen Halbjahre nicht offensichtlich ist und man nicht ohne Anleitung darauf kommen kann, aber es funktioniert.

**Comment by M-Plu** [comment]
Bitte bedenken, dass der Client im Gegensatz zu LuPO und Kurs42 mehrere Halbjahre verwaltet. Daher ist hier die Analogie eher zum Schild-Report-Explorer zu sehen, und da muss man auch das entsprechende Halbjahr vor dem Druck wählen.
