### ISSUE TITLE
Schüler-Laufbahnberatung "zuletzt beraten von"-Dropdown-Liste entlasten

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/SVWS-Server#243]
Bei Oberstufenschülern der Tab "Laufbahnplanung".

Oben rechts steht das Feld "Beratung - zuletzt beraten von". Klickt man darauf, geht eine Liste mit allen Lehrkräften auf. 

Diese Liste sollte entlastet werden.

Hier würde ich vorschlagen, dass in der Dropdownliste "für die Beratung relevant Lehrkräfte" nach oben sortiert werden. D.h.
1. Zuerst wird auf alle LK gefiltert, die in ihren Rechten irgendwelche Rechte der Laufbahnplanung haben.
2. Diese werden alphabetisch geordnet.
3. Diese alphabetische Liste wird nun in der Dropdown-Liste oben angezeigt. Darunter folgen dann ganz normal alle anderen Lehrkräfte (die zuerst angezeigten sind natürlich entfernt).

Es wäre weiterhin gut, wenn der aktuelle Nutzer per Default in das Feld eingetragen werden würde - sofern Laufbahnberatungsrechte bestehen - und direkt ohne Dropdown-Auswahl zur Verfügung stünde.

**Comment by ThomasBachran** [comment]
@FrodBRA : Vielen dank für die Rückmeldung. Ich übernehme diesen Aspekt in unsere interne Planung und schließe das Issue an dieser Stelle.
