### ISSUE TITLE
Neuorganisation Katalogsortierung

### ISSUE THREAD

**Issue by FrodBRA** [SVWS-NRW/SVWS-Server#247]
Unter "Schule" werden die Kataloge wie folgt sortiert

* Schulbezogene Kataloge
* Allgemeine Kataloge 

Die Kataloge werden über die Viewkomponente aufgeklappt; die Einstellungen werden nutzerbasiert gespeichert.

"Datenaustausch" bleibt.

**Comment by FrodBRA** [comment]
Wir hatten uns SchILD3 angesehen und die Sortierung und auch die Unterteilung in Untergruppen, getrennt durch Striche, als recht brauchbare Grundlage empfunden.

Minus die Kataloge, die nicht benötigt werden oder ausgelagert wurden; eventuell auch minus der Inhalte, die noch kommen, aber noch nicht im Ansatz da sind.

Die Förderschwerpunkte sollen von den Allgemeinen in die Schulbezogenen Kataloge wandern.

**Comment by ThomasBachran** [comment]
@FrodBRA : Es gibt bereits einen ersten Entwurf der Umsetzung im dev-Branch für die App Schule. Wir werden hier noch im Bereich Datenaustausch etwas verschieben, so dass das Verhalten der Auswahlliste dort dann auch einheitlich ist.
