### ISSUE TITLE
Fehlende Aktualisierung bei Kursplanung nach Umwahl

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/SVWS-Server#248]
Nach der Umwahl eines Schülers (hier Chemie LK --> Physik LK) wird die Anzahl der Chemie-LK Wähler unter Kursplanung nicht aktualisiert. Auch dann nicht, wenn eine neue Blockung erzeugt wird:

![image](https://github.com/user-attachments/assets/52d9da9a-691a-4f65-8e49-eac25f76fc19)

Beim Schüler selbst ist in dem Reiter die Umwahl sichtbar:
![image](https://github.com/user-attachments/assets/c724bf9e-d6d0-405b-8f74-d1a0880ce029)

**Comment by hmt** [comment]
@ThomasBachran das hängt aktuell damit zusammen, dass nur bei Neuauswahl des Abiturjahrgangs die Daten eingelesen werden:

```ts
const listFachwahlStatistik = await api.server.getGostAbiturjahrgangFachwahlstatistik(api.schema, abiturjahr);
```

Kann der Manager diese Datenebenfalls erzeugen, @benjaminbartsch ?

**Comment by hmt** [comment]
Bugfix ist drin, kommt im Laufe des Tages in den dev-Branch, bitte schließen
