### ISSUE TITLE
Migrationsscript 0.9.2: Benutzerverwaltung, hier Migration der Users- und Kompetenzen-Tabelle

### ISSUE THREAD

**Issue by T-Hagel-SK** [SVWS-NRW/SVWS-Server#250]
Hallo zusammen,

ich bin nun wieder mit dem SVWS-Server 0.9.2. (und dem neuen PC-Client 3.0.88.15, sowie dem Schemaverwaltungsprogramm 1.3.1.1 eingestiegen. Ja, SchildZentral3, ich weiß. Da aber laut Ribeka deren Schemaverwaltungsprogramm für die Datenmigration das gleiche Programm verwendet, platziere ich die Frage hier.

Dabei sind mir mehrere Fehler aufgefallen, auf die ich nach und nach eingehe. Hier aber geht es um die Migration der Schild-Benutzer und deren Benutzerrechte. Nach der Migration einer Schule aus der SchildZentral2-Datenbank verlieren hier alle User ihre vorherigen Rechte. Die Tabellen "BenutzergruppenMitglieder" und "Benutzerkompetenzen" sind beide leer.

Im Fehlerlog (SchildZentral) steht dazu:
        201 - Users, Credentials: Übertrage die Password-Hashes in die Credentials-Tabelle (19)
        202 - BenutzerAllgemein: Kopiere alle nicht-Lehrer-Benutzer (16)
        203 - K_Lehrer: Setze die Kennwortinformationen aus der Benutzertabelle (3)
        204 - Benutzer: Erstelle Benutzer-Einträge für allgemeine Benutzer, die nicht in der Lehrer-Tabelle vorkommen (16)
        205 - Benutzer: Erstelle Benutzer-Einträge für Benutzer, die in der Lehrer-Tabelle vorkommen (3)
        206 - BenutzerEmail: Kopiere Email-Informationen aus der Users-Tabelle (0)
        207 - Benutzergruppen: Übertrage die Benutzergruppen aus der Tabelle Usergroups (8)
        208 - BenutzergruppenKompetenzen: Übertrage die Kompetenzen der Benutzergruppen aus der Tabelle Usergroups (120)
        209 - Benutzergruppen: Setze das Flag IstAdmin für administrative Gruppen (1)
        210 - BenutzergruppenKompetenzen: Setze Default-Werte für die Stundenplanung anhand vorhandener Kompetenzen (18)
        211 - BenutzergruppenKompetenzen: Setze Default-Werte für das Noten-Modul anhand der Kompetenzen zu den Schüler-Leistungsdaten (23)
        212 - BenutzergruppenKompetenzen: Setze Default-Werte für das Datenbank-Management anhand der alten Kompetenz Backup durchführen (3)
        213 - BenutzergruppenKompetenzen: Setze Default-Werte für Oberstufenberechnungen anhand der alten Kompetenz zum Kurs42-Import (18)
        214 - BenutzergruppenKompetenzen: Setze Default-Werte für Oberstufenberechnungen anhand der alten Kompetenz zum Kurs42-Import (12)
        215 - BenutzergruppenKompetenzen: Entferne alte Admin-Einträge, da diese keine Verweise auf die Kompetenztabelle besitzen (1)
        216 - BenutzergruppenMitglieder: Füge die Benutzer aus der Tabelle Users zu den Benutzergruppen hinzu (21)
        217 - BenutzergruppenMitglieder: Entferne fehlerhafte Einträge für Gruppen, die nicht existieren (21)
        218 - Benutzer: Setze das Flag IstAdmin für administrative Benutzer, falls es von einer Gruppenzuweisung geerbt wird (0)
        219 - BenutzerKompetenzen: Entferne alle Benutzerkompetenzen, die nicht in der Tabelle Kompetenzen definiert sind (0)
        220 - BenutzergruppenKompetenzen: Entferne alle Gruppenkompetenzen, die nicht in der Tabelle Kompetenzen definiert sind (0)
        221 - Benutzer: Prüfe, ob der Admin-Benutzer auch administrative Rechte hat, falls es keinen anderen administrativen Benutzer gibt (0)

Daraus ergeben sich folgende Fragen:

1. Anhand welcher Kriterien werden aus der ehemaligen Tabelle "Users" festgemacht, wer hier Lehrer ist und wer nicht ? Das Migrationstool macht aus ehemals 19 Lehrern in der Tabelle "Users" in SchildZentral 3 Lehrer und 16 Allgemeine Benutzer (???)
2. Es gibt wohl (wenn man sich 204 anschaut) einen Abgleich der Namen gegen die Tabelle K_Lehrer. Über welchen Wert geht diese Abfrage ?
3. Die eMail-Adresse der Lehrer wird m.E. aus der falschen Tabelle gezogen. In unserer zentralen Datenbank haben hier von über 6.200 Einträgen nur 36 Lehrer eine Mailadresse hinterlegt. Die Mailadressen der Lehrer werden jedoch unter dem Katalog K_Lehrer "gepflegt", bzw. vorgehalten. 
3b. Wie lassen sich die Mailadressen, die in der Tabelle "Users" z.T. vorgehalten werden, eingetragen, bzw. korrigiert ? 
4. Siehe 216 und 217.  Gegen welche Gruppen wird geprüft, ob sie existieren ? In SchildZentral2 existieren sie ja offenbar, aber das Matching zu Schild3 passt hier wohl nicht. 
Das hat bei der Migration einer Schule zur Folge, dass die User nun keine Rechte mehr haben. Ist ja nicht schlimm, weil 16 von 19 ohnehin nicht als Lehrer migriert wurden ... :-/ 
5. Wenn man sich schon die Mühe macht, das Benutzerkonzept in Schild3 neu zu gestalten, warum hat man dann nicht auch die Tabellen "Kompetenzen" und Kompetenzgruppen" nicht "BenutzerKompetenzen" und "BenutzerKompetenzgruppen" umbenannt ?Dann wären alle Tabellen, die mit dem Block "Benutzer" zu tun haben, untereinander beisammen. 

Schöne Grüße aus Köln
Thomas Hagel

Fachanwendungssupport / Schild3-Koordination

**Comment by hmt** [comment]
Danke für die Meldung, erste Nachfrage zu 3. Welche E-Mailadresse ist hier gemeint? Im Katalog K_Lehrer gibt es dienstliche und private Mailadressen.

**Comment by ThomasBachran** [comment]
Die Zuordnung zu Lehrern erfolgt in Schild über das Lehrer-Kürzel. Stimmt das mit einem Lehrer der Lehrertabelle überein so liegt ein Match vor, so dass die Daten übernommen werden. Da die Handhabung hier der Handhabung aus Schild entspricht, schließe ich dieses Issue erstmal. Es kann ja wieder geöffnet werden, wenn hier konkrete Informationen zu einem Fehler vorliegen. Für Diskussionen bitte ich auch direkt eine Diskussion und kein Issue anzulegen.

**Comment by T-Hagel-SK** [comment]
Das mit dem Lehrerkürzel ist so eine Sache, wenn man eine zentrale Datenbank hat ... 
Da wiederholen sich die Kürzel unweigerlich ..., zumal ja auch hier wieder eine Plausibilitätsprüfung dahingehend fehlt, ob das eingetragene Kürzel schon mal existiert...

**Comment by ThomasBachran** [comment]
Es gibt einen guten Grund dafür, dass im SVWS-Schema eine Tabelle Benutzer existiert und mit IDs gearbeitet wird...

**Comment by T-Hagel-SK** [comment]
> Die Tabelle `BenutzerEmail` speichert die SMTP-Daten der Benutzer. Damit ist es möglich, direkt über SMTP Mails aus SchildNRW zu versenden. Die Daten der Benutzer werden aus der Tabelle `User` (Schild2) migriert. Allerdings werden die Daten nicht migriert, wenn Sie unvollständig sind, also wenn `Email` und `Emailname` fehlen. Das ist so gewollt. Das Feld `Computername` wird in Schild zu irgendeiner Anzeige verwendet. Es wird nur auf `Email` und `Emailname` geprüft.

Das ist jetzt aus den bisherigen Kommunikationsschaubildern nicht ersichtlich ... 
Gibt es neben dem SMTP-Versand auch noch weitere Dienste, die Daten aus dem SVWS-Server nach draußen ins Internet senden / empfangen ? Und wenn ja, über welche Ports ?

Ich habe bislang noch keinen PC-Client so richtig zum Starten bekommen. Ich nehme an, dass es für die Eingabe dieser SMTP-Daten ein entsprechendes Eingabefeld gibt. Gibt es dort auch die Möglichkeit, diese Daten per Dateiimport (csv, xlsx, txt) für meherer/alle Lehrer zu importieren ?

Liegen die Passwörter dann in Klartext vor, oder werden die verschlüsselt dargestellt ?

**Comment by hmt** [comment]
Im SVWS-Client findet man die Eingabe unter Schule. Das Passwort ist verschlüsselt.

**Comment by kroerig** [comment]
Die Daten gibt es auch unter SchILD2 NRW schon. Sie sind zweigeteilt:

Unter Einstellungen -> Globale Einstellungen -> E-Mail-Versand trägt man allgemein den SMTP Server ein, der verwendet werden soll.

Unter Einstellungen -> Individuelle Einstellungen -> E-Mail-Kontodaten bearbeiten (SMTP) trägt dann jeder Benutzer seine Absenderdaten ein.

Unter SchILD3 NRW nimmt man diese Einstellungen unter Verwaltung -> Einstellungen vor.
Und dann kann SchILD2 NRW (und auch SchILD3 NRW) Mails verschicken ohne einen MUA bemühen zu müssen.

**Comment by T-Hagel-SK** [comment]
> Die Daten gibt es auch unter SchILD2 NRW schon. Sie sind zweigeteilt:
> 
> Unter Einstellungen -> Globale Einstellungen -> E-Mail-Versand trägt man allgemein den SMTP Server ein, der verwendet werden soll.
> 
> Unter Einstellungen -> Individuelle Einstellungen -> E-Mail-Kontodaten bearbeiten (SMTP) trägt dann jeder Benutzer seine Absenderdaten ein.
> 
> Unter SchILD3 NRW nimmt man diese Einstellungen unter Verwaltung -> Einstellungen vor. Und dann kann SchILD2 NRW (und auch SchILD3 NRW) Mails verschicken ohne einen MUA bemühen zu müssen.

Prima, Danke.
Die Einstellungen entfallen bei den städtischen Kölner Schulen, da hier nicht über SMTP gesendet wird, sondern das vorherschende Mailprogramm genutzt wird.
Aber für die Schulen, die über SMTP gehen wollen, müssen dann eben schauen, dass ihr SVWS-Server in der Lage ist, über die jeweiligen SMTP-Ports nach draussen zu mailen. 

Gibt es für die Schulen eine Übersicht, welche Ports für den SVWS-Server in den Firewalls / Proxies freizuschalten sind ?

**Comment by T-Hagel-SK** [comment]
> Das mit dem Lehrerkürzel ist so eine Sache, wenn man eine zentrale Datenbank hat ... Da wiederholen sich die Kürzel unweigerlich ..., zumal ja auch hier wieder eine Plausibilitätsprüfung dahingehend fehlt, ob das eingetragene Kürzel schon mal existiert...

Da muss ich mich wohl korrigieren. Unter SchildZentral wird nur geprüft, ob das Lehrerkürzel innerhalb der Schule vorkommt. Ich nehme an, dass das für SchildNRW genauso abgefragt wird. Aber in SchildZentral wird nicht abgefragt, ob das Lehrerkürzel nicht auch schon in einer anderen Schule vorliegt. Melde ich daher gleich mal an Ribeka weiter. 

Ich habe ohnehin nicht verstanden, warum man in Schild mit dem Lehrerkürzel, statt mit einer internen Nummer arbeitet. Wie gut, dass das in Schild3 dann der Fall sein wird.

**Comment by kroerig** [comment]
Auch in SchILD2 gibt es eine Lehrer ID neben dem Kürzel.

> Unter SchildZentral wird nur geprüft, ob das Lehrerkürzel innerhalb der Schule vorkommt.

Das macht ja auch Sinn. Die Kombination aus Schulnummer + Kürzel muss in dieser Installation eindeutig sein.

**Comment by T-Hagel-SK** [comment]
> Auch in SchILD2 gibt es eine Lehrer ID neben dem Kürzel.
> 
> > Unter SchildZentral wird nur geprüft, ob das Lehrerkürzel innerhalb der Schule vorkommt.
> 
> Das macht ja auch Sinn. Die Kombination aus Schulnummer + Kürzel muss in dieser Installation eindeutig sein.

Seufz. Ja. Klar ist da auch eine ID ...
Allerdings hat irgendwer irgendwann mal gemeint, dass man sinnigerweise gegen das Kürzel statt gegen die Lehrer-ID abfragt. Und wenn ich das richtig überblicke, wird die Lehrer-ID auch in Abfragen verwendet, aber eben nicht in allen ... 

Anderes Problem bei den Kürzeln ist, dass Lehrer auch nur Menschen sind und auch mal den Nachnamen ändern. Dann ist das mit dem Kürzel auch so eine Sache.

**Comment by kroerig** [comment]
> Anderes Problem bei den Kürzeln ist, dass Lehrer auch nur Menschen sind und auch mal den Nachnamen ändern. Dann ist das mit dem Kürzel auch so eine Sache.

Ja, Namensänderung nur mit Zustimmung des Admins ;-)

> Und wenn ich das richtig überblicke, wird die Lehrer-ID auch in Abfragen verwendet, aber eben nicht in allen ...

Das könnte historisch bedingt durchaus sein. Da sollte @JuergenRichter etwas so sagen können.

**Comment by T-Hagel-SK** [comment]
Auch hier. Warum wird ein Issue geschlossen, bevor die genannten Punkte besprochen oder geklärt sind. Bei den ganzen Fragen wurde jetzt nur der Punkt der eMail-Adressen und Lehrerkürzel behandelt ...

:-(

Offen:

1. Anhand welcher Kriterien werden aus der ehemaligen Tabelle "Users" festgemacht, wer hier Lehrer ist und wer nicht ? Das Migrationstool macht aus ehemals 19 Lehrern in der Tabelle "Users" in SchildZentral 3 Lehrer und 16 Allgemeine Benutzer (???)

4. Siehe 216 und 217. Gegen welche Gruppen wird geprüft, ob sie existieren ? In SchildZentral2 existieren sie ja offenbar, aber das Matching zu Schild3 passt hier wohl nicht.
Das hat bei der Migration einer Schule zur Folge, dass die User nun keine Rechte mehr haben. Ist ja nicht schlimm, weil 16 von 19 ohnehin nicht als Lehrer migriert wurden ... :-/

5. Wenn man sich schon die Mühe macht, das Benutzerkonzept in Schild3 neu zu gestalten, warum hat man dann nicht auch die Tabellen "Kompetenzen" und Kompetenzgruppen" nicht "BenutzerKompetenzen" und "BenutzerKompetenzgruppen" umbenannt ?Dann wären alle Tabellen, die mit dem Block "Benutzer" zu tun haben, untereinander beisammen.
