### ISSUE TITLE
Migrationsscript 0.9.2: Schüler ... Fehlermeldung enthält keine ID

### ISSUE THREAD

**Issue by T-Hagel-SK** [SVWS-NRW/SVWS-Server#252]
Hallo zusammen,

wie bereits erwähnt sind mir bei der Datenmigration aus SchildZentral2 nach 3 Dinge im Migrationslog aufgefallen.

So wird z.B. weiterhin bei den Schülern nicht angezeigt, welche ID nicht gefunden werden konnte.  Die Fehlermeldung lautet:
_Entferne ungültigen Datensatz: Es gibt keinen Schüler mit der angebenen ID in der Datenbank._

Das macht dann eine Suche gegen Fehler schwierig.

Das hatte ich aber auch schon mal in https://github.com/SVWS-NRW/SVWS-Server/issues/209 gemeldet. Da wurde dann ja auch gleich nachgebessert, nur bei den Schülern nicht.

Schöne Grüße
Thomas Hagel

Stadt Köln
Fachanwendungsbetreuung / Schild3-Koordination

**Comment by ThomasBachran** [comment]
Vielen Dank für die konkrete Rückmeldung. Die Stelle bei der Lernplattform wurde übersehen. Der Fehler wird in dem nächsten Pre-Release behoben sein.
