### ISSUE TITLE
Migrationsscript 0.9.2: Import aus SchildZentral2-Datenbanken ... fehlende Dateneingrenzung auf Schulnummer beim Einlesen in den Zwischenspeicher

### ISSUE THREAD

**Issue by T-Hagel-SK** [SVWS-NRW/SVWS-Server#253]
Hallo zusammen,

beim Betrachten einer 11 MB großen Migrationslog-Datei habe ich mich unweigerlich gefragt, warum ein Logfile derart lang und groß geworden ist. 

Unter anderen sind unsere Logfiles deswegen so groß, weil wir hier mehrere zehntausend Fehlermeldungen á la 
_Entferne ungültigen Datensatz: Es gibt keinen Schüler mit der angebenen ID in der Datenbank._
und mehrere tausend Fehlermeldungen à la 
_Entferne ungültigen Datensatz: Es gibt keinen Lehrer mit der ID 12345 in der Datenbank._

Betrachte ich mir die Menge an Schülern und Lehrern in der Quelldatenbank und vergleiche die mit der Menge im Logfile, würde ich darauf tippen, dass hier noch eine Abfrage gegen die Schulnummer fehlt. Unter SchildNRW macht das freilich wenig Sinn. Bei Migrationen aus der SchildZentral-Datenbank hingegen führt das Weglassen der Schulnummer dazu, dass dann eben ALLE Datensätze eingelesen werden. 

Die können dann jedoch beim Abgleich gegen die Schulnummer nicht gefunden werden und führen zu diesen Fehlermeldungen.

Daher sollte es nicht nur aus Performancegründen, sondern auch zum Vermeiden überlanger Logfiles, möglich sein, die Abfrage so zu ermöglichen, dass beim Einlesen der Daten schon auf die Schulnummer gefiltert wird und nicht erst danach.

Das ließe sich dann natürlich auch auf alle anderen Tabellen ausbreiten, wie z.B. Lernabschnitte, K_Lehrer, Logins, etc.  

Schöne Grüße

Thomas Hagel
Stadt Köln
Fachanwendungsbetreuung / Schild3-Koordination

**Comment by ThomasBachran** [comment]
Die erste Fehlermeldung zu den Schülern kann ich bei den Lernplattformen zuordnen. Ist das bei den Lehrer-Fehlermeldungen auch der Fall? Oder tritt das bei anderen Tabellen auf?

**Comment by T-Hagel-SK** [comment]
Stimmt. Das hatte ich in dem ellenlangen Logfile übersehen. Hier noch mal in etwas ausführlicher in der Reihenfolge des Migrationslogs und kommentiert:

1. Tabelle CredentialsLernplattformen:
      - Lese Datensätze: 7588 Datensätze eingelesen (Freier Speicher: 0.11G/0.42G/4.12G)
      Entferne ungültigen Datensatz (ID 5280): Die Kombination auf Lernplattform und Benutzername ist nicht eindeutig.
      Entferne ungültigen Datensatz (ID 4878): Benutzername darf nicht leer sein. 
      ...
      - Schreibe 6574 Datensätze: 
        Datensätze 0-6573 erfolgreich geschrieben. (Freier Speicher: 0.29G/0.42G/4.12G)
      6574 Datensätze geschrieben, 0 fehlerhafte Datensätze übersprungen.

Da in dieser Tabelle die Schulnummer fehlt (SchildZentral), könnte man vor dem Einlesen übers Eck gegen die Tabelle Lernplattform nur die Datensätze einlesen, in denen die LernplattformID der übermittelten Schulnummer entspricht. Das wäre in unserem Fall bei dieser Schule sogar 0, weil es eine recht neue Schule ist.
In unserer Datenbank tritt der Fall "Benutzername = NULL" jedoch nur in einer veralteten Testschule auf, trotzdem kann es nicht schaden, auch gegen diese Eigenschaft zu prüfen, bevor man sich zu viele Daten in den Speicher lädt und erst dann prüfen lässt. 

Hier ist mir außderm die "die Kombination auf Lernplattform und Benutzername"-Bedingung unklar. Im besagten Fall gibt es einen Benutzernamen, aber BenutzernamePseudonym ist NULL. In der Datenbank haben wir 6.583 Datensätze, in denen der Benutername nicht NULL und BenutzernamePseudonym gleich NULL ist. Es gibt aber keine Einträge, in denen beide Felder nicht NULL sind (???) 

----

2.     Tabelle LehrerDatenschutz:
      - Lese Datensätze: 1624 Datensätze eingelesen (Freier Speicher: 0.27G/0.42G/4.12G)
      Entferne ungültigen Datensatz: Es gibt keinen Lehrer mit der ID 61924 in der Datenbank.
      ...
      Entferne ungültigen Datensatz: Es gibt keinen Lehrer mit der ID 1975 in der Datenbank.
      Tabelle LehrerFotos:

Hier fehlt eine Zusammenfassung zu der Anzahl der geschriebenen Datensätze. Nach dem letzten Eintrag geht es schon mit der Tabelle LehrerFotos weiter im Migrationslog. 
Würde man hier vor dem Einlesen gegen die Schulnummer filtern, wäre man hier schnell durch. Die Anzahl der Datensätze ist bei dieser betroffenen Schule nämlich 0 :-)
Die zuviel eingelesenen LehrerIDs sind folglich anderen Schulnummern zugeordnet.

----

3.     Tabelle LehrerLernplattform:
      - Lese Datensätze: 3126 Datensätze eingelesen (Freier Speicher: 0.26G/0.42G/4.12G)
      Entferne ungültigen Datensatz: Es gibt keinen Lehrer mit der ID 61805 in der Datenbank.
      ...
      Entferne ungültigen Datensatz: Es gibt keinen Lehrer mit der ID 146 in der Datenbank.
    Tabelle Personengruppen:

Auch hier fehlt die Zusammenfassung mit der Anzahl der geschriebenen Datensätze. Nach dem letzten Eintrag geht es mit der Tabelle Personengruppen weiter. 
Hier müsste übers Eck abgefragt werden, welche Lehrer in der Tabelle K_Lehrer der übermittelten Schule zugeordnet sind.

----

4.     Tabelle SchuelerLernplattform:
      - Lese Datensätze: 37256 Datensätze eingelesen (Freier Speicher: 0.36G/0.51G/4.12G)
      Entferne ungültigen Datensatz: Es gibt keinen Schüler mit der angebenen ID in der Datenbank.
      ...
      Entferne ungültigen Datensatz: Es gibt keinen Schüler mit der angebenen ID in der Datenbank.
      - Schreibe 1 Datensätze: 
        Datensatz 0 erfolgreich geschrieben. (Freier Speicher: 0.28G/0.51G/4.12G)
      1 Datensätze geschrieben, 0 fehlerhafte Datensätze übersprungen.

D.h. hier ist 37.255 mal die Abfrage durchgelaufen, um am Ende genau einen Datensatz zu migrieren ... Hier ein Filter übers Eck gegen die Tabelle Schueler, ob die SchülerID der übermittelten Schulnummer entspricht.

----


5.     Tabelle SchuelerKAoADaten:
      - Lese Datensätze: 498 Datensätze eingelesen (Freier Speicher: 0.24G/0.51G/4.12G)
      Entferne ungültigen Datensatz in SchuelerKAoADaten (ID 233211): Es gibt keinen Lernabschnitt mit der ID null in der Datenbank.
      ...
      Entferne ungültigen Datensatz in SchuelerKAoADaten (ID 139108): Es gibt keinen Lernabschnitt mit der ID null in der Datenbank.
    Tabelle SchuelerLD_PSFachBem:

Auch hier fehlt wieder die Zusammenfassung mit der Anzahl der geschriebenen Datensätzen. Der nächste Logeintrag betrifft die Tabelle SchuelerLD_PSFachBem. 
Hier aber ist es so, dass wohl diese Abfrage gegen die Schulnummer gefiltert wird, denn in der Quelldatenbank sind für diese Schule genau 498 Einträge vorhanden. Jedoch könnte man auch hier noch einen Vorfilter gegen Lernabschnitte mit der ID = NULL setzen.


Ribeka bietet bei der Migration über deren Schemaverwaltungsprogramm noch einen Prüfbericht an, in dem für jede Tabelle aufgezeigt wird, wie viele Datensätze in der Quelldatenbank vorlagen und wieviele migriert wurden. Gibt es das auch für den SVWS-Server ? Ich habe im Logordner noch nichts dazu gesehen.

Leider gibt die Prüfliste bei Differenzen nicht aus, welche Datensätze nicht übertragen werden konnten. Das wäre allerdings sehr hilfreich und könnte die Arbeiten in den Schulen, den Schild- und IT-Admins erheblich beschleunigen.

**Comment by ThomasBachran** [comment]
Vielen Dank für die ausführlichere Aufstellung. Viele Aspekte kommen durch die Unterschiede zwischen den Schild-NRW-Datenbanken und den entsprechenden Zentraldatenbanken zustande. So enthalten nicht alle Schild-NRW-Tabellen den Eintrag für die SchulnrEigner - dort wird sie ja auch nicht benötigt. Ich werde daher für die Tabellen *Lernplattform und *Datenschutz das Verhalten so anpassen, dass eine Filterung der SchulnrEigner angepasst wird.

Ansonsten ist es technisch nicht so, dass die Filterung der Datensätze über SQL-Abfragen gesteuert wird. Das wäre insgesamt zu fehleranfällig, da sich die vorhanden Datenbanken aus denen migriert wird sich leider unterscheiden und beim Laden der Daten flexibel agiert werden muss. Die Gründe dafür sind recht komplex, so dass ich hier nicht näher darauf eingehen möchte. Daraus ergibt sich allerdings, dass die Datensätze, die bei den Tabellen nicht übernommen werden mit dem entsprechenden Grund angegeben werden. Für die Tabelle CredentialsLernplattformen werde ich daher das Verfahren nicht anpassen, auch wenn die Rückmeldung des Logs hier nur eingeschränkt hilfreich ist.
Bei der Tabelle SchuelerKAoADaten findet hier eine Filterung der Datensätze statt. Hier kann mMn bei Bedarf die entsprechende Datenbank aufgeräumt werden, bevor eine Migration stattfindet, um die Anzahl der Meldungen zu reduzieren. Die Benachrichtigung während der Migration soll aber als Information erhalten bleiben.

**Comment by T-Hagel-SK** [comment]
Gibt es eigentlich nur ein "Migrationsscript" für alle Datenbankvarianten (SchildNRW: Access, SQL-Server, sowie SchildZentral: SQL-Server) oder gibt es für die Migration aus SchildZentral evtl eine eigene Migration ?

Um mal so grob zu verstehen, was insbesondere Köln  die Herausforderung ist, hier mal ein paar Zahlen:
Datenbankvolumen: 26 GB
Anzahl Schüler-IDs: 85.5580
Anzahl Lehrer-IDs: 31.425
Anzahl SchülerLernAbschnitte: 465.8884

Ich würde trotzdem frech empfehlen sich gerade das Thema CredentialsLernplattformen genauer anzuschauen. Denn wenn hier keine Filterung übers Eck gegen die Schulnummer erfolgt, schreibt das Migrationstool in jede migrierte Schule ALLE Einträge dieser Tabelle in die Schild3-Tabelle der Schule ... Ich glaube nicht, dass das gewünscht ist.

Was das Aufräumen vor der Migration betrifft, so hatte ich dazu ja auch schon letztes Jahr Fragen gestellt und auch immer wieder in Tickets zu Migrationsproblemen davon gesproche. Bis heute gibt es dazu keine zufriedenstellende Antworten. Es macht eindeutig Sinn VOR der Migration die Schild2-Datenbank aufzuräumen. Doch dazu brauchen die Schulen Hilfestellungen und ggf. ein Aufräum-Modul oder ein Datenvorbereitungsmodul, das nicht nur aufräumt, sondern auch dokumentiert, wo was geändert wurde und wo was von Hand gegengeprüft werden sollte.

Nur so vermeiden wir, dass fehlerhafte oder falsche Einträge auch in der Schild3-Datenbank landen ...

**Comment by kroerig** [comment]
> Doch dazu brauchen die Schulen Hilfestellungen und ggf. ein Aufräum-Modul oder ein Datenvorbereitungsmodul, das nicht nur aufräumt, sondern auch dokumentiert, wo was geändert wurde und wo was von Hand gegengeprüft werden sollte.
> 
> Nur so vermeiden wir, dass fehlerhafte oder falsche Einträge auch in der Schild3-Datenbank landen ...

Ja, ein Tool, dass die SchILD2 DB vor einer Migration auf Konsistenz prüft hatte ich ja auch schon mal angefragt (nicht hier, sondern im Forum).
Alles abklappern wird vermutlich nicht funktionieren, dafür gibt es vermutlich zu viele Möglichkeiten. Aber schauen, ob z.B. in den Stammdaten die Felder syntaktisch richtig füllt sind (bei E-Mail also auch eine E-Mailadresse und nichts anderes drinsteht) wäre bestimmt schon mal hilfreich.

**Comment by T-Hagel-SK** [comment]
> > Doch dazu brauchen die Schulen Hilfestellungen und ggf. ein Aufräum-Modul oder ein Datenvorbereitungsmodul, das nicht nur aufräumt, sondern auch dokumentiert, wo was geändert wurde und wo was von Hand gegengeprüft werden sollte.
> > Nur so vermeiden wir, dass fehlerhafte oder falsche Einträge auch in der Schild3-Datenbank landen ...
> 
> Ja, ein Tool, dass die SchILD2 DB vor einer Migration auf Konsistenz prüft hatte ich ja auch schon mal angefragt (nicht hier, sondern im Forum). Alles abklappern wird vermutlich nicht funktionieren, dafür gibt es vermutlich zu viele Möglichkeiten. Aber schauen, ob z.B. in den Stammdaten die Felder syntaktisch richtig füllt sind (bei E-Mail also auch eine E-Mailadresse und nichts anderes drinsteht) wäre bestimmt schon mal hilfreich.

Sollen wir hierzu mal eine Diskussion starten oder ein Wiki, in dem man diese Felder benennt, die in den Datenbanken offensichtlich mit falschen oder fehlerhaften Inhalten gefüllt sind ?

**Comment by ThomasBachran** [comment]
Für die Diskussion würde ich gerne auf das Forum für SchildNRW verweisen, da es dabei ja primär um die Datenkonsistenz **vor** der Migration geht. Beim SVWS-Server geht es aber um die Migration selbst, welche dann mit mehr oder weniger konsistenten DBs umgehen muss...

Da das eigentliche Thema des Issue bereits geklärt ist, schließe ich dieses Issue erstmal. Hierzu wird es dann wie oben beschrieben Anpassungen geben.

**Comment by kroerig** [comment]
Der Threat im Forum:
https://schulverwaltungsinfos.nrw.de/svws/forum/viewtopic.php?t=6029

**Comment by T-Hagel-SK** [comment]
> Für die Diskussion würde ich gerne auf das Forum für SchildNRW verweisen, da es dabei ja primär um die Datenkonsistenz **vor** der Migration geht. Beim SVWS-Server geht es aber um die Migration selbst, welche dann mit mehr oder weniger konsistenten DBs umgehen muss...
> 
> Da das eigentliche Thema des Issue bereits geklärt ist, schließe ich dieses Issue erstmal. Hierzu wird es dann wie oben beschrieben Anpassungen geben.

Ähhm, nein. Das eigentliche Thema ist noch offen. 
Es bleibt die Problematik mit den CredentialsLernplattformen, bei dem momentan alle Credentials in die Schild3-Datenbanken der Schulen migriert werden, eben weil hier keine Trennung nach Schulnummer erfolgt.

**Comment by ThomasBachran** [comment]
> Ähhm, nein. Das eigentliche Thema ist noch offen. Es bleibt die Problematik mit den CredentialsLernplattformen, bei dem momentan alle Credentials in die Schild3-Datenbanken der Schulen migriert werden, eben weil hier keine Trennung nach Schulnummer erfolgt.

Die CredentialsLernplattformen kann vom SVWS-Server bei der Migration auch anhand einer SchulnrEigner gefiltert werden. Ob die Zentral-Datenbank dies zur Verfügung stellt, ist Aufgabe von SchildZentral. Die Lösung kann perspektivisch also an dieser Stelle bereitgestellt werden.

**Comment by T-Hagel-SK** [comment]
In SchildZentral gibt es in der Tabelle keine Schulnummer. Sie kann aber übers Eck über über die Tabelle Lernplattformen anhand der Lernplattform-ID ermittelt werden.

**Comment by kroerig** [comment]
Für mich zum Verständnis:

Wenn die Tabelle `CredentialsLernplattformen` Datenbank von SchildZentral genauso aussieht wie in SchILD NRW, dann hat die Migrationsroutine gar keine Chance die Daten einfach zu filtern, denn die Tabelle enthält bei mir weder eine Spalte um eine Schulnummer erfassen zu können, noch eine Referenz auf eine Schülernummer.

Aber anders herum gibt es eine Beziehung: In der Tabelle `Schueler` nämlich gibt es ein Feld `CredentialID`. D.h. die Migrationsroutinen müssen die bereits migrierte Tabelle  `Schueler` durchgehen und anhand dieser die passenden Einträge aus der  Tabelle `CredentialsLernplattformen` fischen.
Und auch die Tabellen `SchuelerLernplattform` und `LehrerLernplattform` enthalten eine Referenz auf die CredentialID`.

So sollten dann auch nur die Datensätze in der Datenbank landen, die dort auch hingehören.

Oder übersehe ich hier etwas?

**Comment by T-Hagel-SK** [comment]
Wenn ich die Tabelle richtig verstanden habe, landen in dieser die Startpasswörter zu den jeweils von den Schulen angelegten Lernplattformbezeichnungen. Ob sie dort eine Unterscheidung nach Lehrer, Personengruppenpersonen oder Schüler machen, weiß ich.

Allerdings ist es möglich, eine Abfrage über alle Lernplattform-IDs einer Schule zu machen und nur die Datensätze mit den ermittelten Lernplattform-IDs in den Zwischenspeicher zu holen, um sie dann anschließend nach Schild in die jeweilige Schule in die dortige Tabelle CredentialsLernplattformen zu speichern.

Aktuell tummeln sich da je Schule ungefiltert alle Credentials ...
