### ISSUE TITLE
Sicherheitsscan SVWS-Server 0.9.2 - docker-container + Zukünftige Sicherheitsscans in der Pipeline

### ISSUE THREAD

**Issue by SchulenITK** [SVWS-NRW/SVWS-Server#255]
Hallo,

den docker-container des SVWS-Server 0.9.2 haben wir wieder gescannt, anbei die beiden Reports. 

Wir dürfen von unserer IT-Sicherheit aus nichts einsetzten was "HIGH" deklariert wurde, wenn ein Fix vorhanden ist.

Die beiden Scan-Tools sind frei und open source und lassen sich auch in die Pipeline integrieren. Daher ist unsere Bitte, dass Sie diese Tools (oder gleichwertige) nutzen, damit wir in Zukunft auch die neusten Updates des SVWS-Servers direkt einsetzten können. 

Generell sieht es eigentlich gut aus, daher bitte nicht falsch verstehen, denn die Vulnerability, welche hier als HIGH deklariert wurde, ist erst nach Veröffentlichung der Version 0.9.2 behoben worden. Aber zwischen Veröffentlichung der Version und tatsächlichem Update vergehen - zumindest bei uns - gerne 1-2 Wochen.

[trivy_report_svws-server_test_20240923_a.pdf](https://github.com/user-attachments/files/17130444/trivy_report_svws-server_test_20240923_a.pdf)
[zap_report_baseline_svws-server_20240923_a.pdf](https://github.com/user-attachments/files/17130445/zap_report_baseline_svws-server_20240923_a.pdf)

https://github.com/aquasecurity/trivy

https://www.zaproxy.org/

**Comment by hmt** [comment]
Und jetzt mal aus Interesse nachgefragt, was passiert, wenn ein Container ausgeliefert wird, der ok ist, damit das Update durchgeführt wird und wenig später eine Vulnerability mit HIGH auftaucht?

**Comment by kroerig** [comment]
Dann hängt man in der Zwickmühle, dass man eigentlich die Software abschalten müsste, damit aber den ganzen Betrieb lahmlegen würde.
Also hofft und bangt man, dass der Maintainer/ Entwicker schnell genug mit einem Fix o.ä. um die Ecke kommt und es einen bis dahin nicht erwischt hat.
Hier spielt FLOSS dann hoffentlich ihre Stärke aus, weil hinter der Software/ Lösung nicht nur ein Hersteller steck sondern eine Gemeinschaft an Entwicklern.

Und dann hat man die Software hoffentlich als Container ausgerollt und muss nicht 250 VMs patchen.

**Comment by SchulenITK** [comment]
Wenn der Release des SVWS-Servers mit SchILD abgestimmt ist oder neue Versionen des SVWS-Servers tendenziell abwärtskompatibel wären - zu einem gewissen Grad - würde das Problem zumindest geringer werden. Aber korrekt, das auszuschließen wird schwierig, ohne selbst am container zu schrauben - was wir zunächst natürlich vermeiden wollen.

**Comment by FPfotenhauer** [comment]
Es macht auf jeden Fall Sinn, dass wir die Container selber scannen können.
Ich weiß nur nicht, wie schnell wir das umsetzen können.
Die Releases sind auf jeden Fall mit Schild3 abgestimmt in der server.json im Installationsverzeichnis von Schild3 ist immer die Server-Version, die zu Schild3 passt hinterlegt.

Das Issue lasse ich deshalb mal auf, wir schauen uns die Projekt gerne an.
Vielen Dank für die konstruktive Rückmeldung.

**Comment by kroerig** [comment]
> Die Releases sind auf jeden Fall mit Schild3 abgestimmt in der server.json im Installationsverzeichnis von Schild3 ist immer die Server-Version, die zu Schild3 passt hinterlegt.

Diese Versionsprüfung ist aber aktuell sehr streng. SchILD3 meckert schon, wenn in der server.json 0.9.2 steht, der SVWS sich aber noch mit 0.9.1 meldet. Man kann die Meldung dann ignorieren, aber es kann aktuell passieren dass einzelne Funktionen nicht (mehr) funktionieren, wenn hier z.B. eine Funktion in SchILD3 auf die API umgestellt wurde, diese aber erst in einer neueren Version des SVWS verfügbar ist. Das ändert sich hoffentlich, wenn die Software als stable gilt.

Nach den Vorgaben des semantic versionings, darf es sich bei einem Punkt-Release 0.9.X nur um Fehlerkorrekturen handeln. Die API darf sich aber nicht ändern. Wenn das der Fall ist muss sich die zweite Stelle ändern. Dann muss man aber bis zu einer neuen Hauptversion Altlasten noch mitschleppen.

**Comment by FPfotenhauer** [comment]
Ein kurzer Zwischenbericht:
Wir können jetzt die Verschiedenen Branches vom SVWS-Server scannen und dies auch vor dem Release.
Mit anderen Worten können wir zum Zeitpunkt des Releases sicherstellen, dass keine Sicherheitshinweise aus der Kategorie HIGH vorliegen.

In die Pipeline werden wir das später bringen, das ist etwas komplizierter.

**Comment by FPfotenhauer** [comment]
Momentan haben wir das problem, dass eine Sicherheitslücke im MySQL-Treiber nicht gefixed wird.
In deren Repository liegt schon seit 2 Wochen ein Fix, aber er wurde nicht eingespielt.

Wir würden trotzdem gerne ein release erstellen, weil wir einige Probleme aus dem anderen Issue gefixed haben.

**Comment by FPfotenhauer** [comment]
So. Die Sicherheitslücken sind nun gefixed und wir haben keine Meldungen mit HIGH mehr.
Es wird diese Woche ein Release geben. Ich schließe das Issue einmal. 

Das wir das in die Pipeline einbauen ist auf unserer TODO.
