### ISSUE TITLE
SVWS-Server 0.9.2: svwsconfig.json enthält weiterhin bereits gelöschte Schemas

### ISSUE THREAD

**Issue by T-Hagel-SK** [SVWS-NRW/SVWS-Server#258]
Hallo zusammen,

bei einer aktuellen Durchsicht der svwsconfig.json-Datei bin ich über längst gelöschte Schemas gestolpert, die im Zuge von Aufräumarbeiten mit dem Schildzentral-Schemaverwaltungsprogramm aufgefallen sind. Dort kam der Hinweis, dass ein Schema noch auf dem Server vorläge.

Wie auch immer. Ich war davon ausgegangen, dass ein Serververwaltungsprogramm Schemas, die darüber gelöscht werden, diese auch aus der svwsconfig.json-Datei entfernt. Möglicherweise war das in vorherigen Versionen nicht der Fall.

Zwar ignoriert der SVWS-Server beim Start den Umstand, dass Schemas auf der Datenbank nicht mehr gefunden werden und startet durch. Aber ein Serververwaltungsprogramm oder eine Serververwaltungswebseite sollte m.E. auch in der Lage sein und die Möglichkeit bieten, die in der svwsconfig.json-Datei vorliegenden Einträge anzuzeigen und zu vermerken, dass dazu keine passenden Datenbanken gefunden werden können. 

Wenn das der Fall ist, sollte man als Admin die Möglichkeit haben, hier ggf. auf den korrekten Pfad und Bezeichnungen zu prüfen, zu korrigieren und bei Bedarf auch aus der svwsconfig.json-Datei zu löschen.

Das mag im Falle einer Schule eher übersichtlich sein. Aber, wenn man dann mal mehrere oder alle Schulen über einen SVWS-Server laufen lassen möchte, wird das wahnsinnig unübersichtlich.

Und ganz evtl. ließen sich die Einträge dort noch um einen Zeitstempel erweitern. Ggf. zwei. Einen für die Anlage des Schemas und einen für einen Löschauftrag.

Hier eine Screenshotsammlung aus dem aktuellen SVWS-Server, der Datenbank und der svwsconfig.json-Datei:

![20240930_SVWS-Server_0-9-2_json-Datei_wird_nicht_aktualisiert_wenn_DBs_gelöscht_werden](https://github.com/user-attachments/assets/e19e933e-c5d4-419c-b24c-ec7321d6930d)

Schöne Grüße
Thomas Hagel

Stadt Köln
Fachanwendungsbetreuung / Schild3-Koordination

**Comment by kroerig** [comment]
Ich gehe jetzt mal davon aus, dass das Serververwaltungsprogramm die Schemas über die dafür vorgesehene API anlegt. Die löscht die Einträge auch wieder aus der Datei. Es sei denn, die Datei wäre für den Prozess nicht schreibar.

**Comment by ThomasBachran** [comment]
Der Admin-Client kümmert sich seit längerer Zeit auch um das Entfernen aus der SVWS-Konfiguration. Hier wird es sich vermutlich um alte Einträge handeln, wo dies noch nicht der Fall war. Wenn dies ab Version 0.9.3 des SVWS-Servers noch der Fall sein sollte, dann wäre ein neues Issue an dieser Stelle hilfreich. Für die Zwischenzeit werde ich dieses Issue schließen.

**Comment by T-Hagel-SK** [comment]
> Ich gehe jetzt mal davon aus, dass das Serververwaltungsprogramm die Schemas über die dafür vorgesehene API anlegt. Die löscht die Einträge auch wieder aus der Datei. Es sei denn, die Datei wäre für den Prozess nicht schreibar.

Von der API gehe ich aus. 
Meine Frage ging aber in die Richtung SVWS-Server, der beim Starten prüft, ob die dort hinterlegten Datenbanken existieren. Falls nicht, sollten diese m.E. in der Adminkonsole aufgeführt werden, um sie dann entweder neu anlegen zu lassen (im Falle von versehentlich gelöscht) oder in der Config.Datei dauerhaft zu entfernen.

Wann soll die 0.9.3 denn kommen ?
