### ISSUE TITLE
Backups werden nicht generiert

### ISSUE THREAD

**Issue by SBHGE** [SVWS-NRW/SVWS-Server#260]
Ich benutze die aktuelle SVWS-Server Version 0.9.2.
Ich logge mich auf die Admin-Oberfläche ein und möchte eine Backup von einem bestehenden Schema erstellen.
Ich klicke im entsprechenden Menü auf "Backup starten" und ein Download beginnt.
![grafik](https://github.com/user-attachments/assets/a7e95369-bb94-4d51-9796-093282184805)
Nur hat die Datei die runtergeladen wird eine Größe von 0 Byte. Entsprechend ist in der Datei kein Inhalt vorhanden.
![grafik](https://github.com/user-attachments/assets/5e62b507-5359-455e-bb37-4004bfe354d0)
 Das gleiche lässt sich im Schild3 Clienten unter "Verwaltung" --> "Datenbank" --> "Datenbank sichern" reproduzieren. Die gespeicherte Datei im SVWS-Arbeitsverzeichnis hat auch die Größe von 0Byte.
![grafik](https://github.com/user-attachments/assets/724161c4-0ace-4452-9b3c-58b134d23473)
![grafik](https://github.com/user-attachments/assets/a86fac18-89c6-4ac6-9edc-774f93b60d4f)

**Comment by kroerig** [comment]
Siehe hier:
https://github.com/SVWS-NRW/SVWS-Server/issues/236

**Comment by SBHGE** [comment]
> Siehe hier: #236

Danke für die Rückmeldung
