### ISSUE TITLE
Fehler bei der Migration

### ISSUE THREAD

**Issue by kroerig** [SVWS-NRW/SVWS-Server#27]
Folgende Fehler sehe ich bei der Migration:

Tabelle **EigeneSchule_Kursart**:

```
Datensatz 43 konnte nicht geschrieben werden - Datensatz wird übersprungen.
[FEHLER] MigrationDTOKursarten(ID=44, Bezeichnung=Förderung neu zugewanderter Schüler in Deutschfördergruppen (teilweise äußere und innere Differenzierung), InternBez=DFG, Kursart=DFG, KursartAllg=DFG, Sortierung=44, Sichtbar=true, Aenderbar=true, SchulnrEigner=XXXXXX)
Datensatz 44 konnte nicht geschrieben werden - Datensatz wird übersprungen.
[FEHLER] MigrationDTOKursarten(ID=45, Bezeichnung=Förderung neu zugewanderter Schüler in Deutschförderklassen (vollständige äußere Differenzierung), InternBez=DFK, Kursart=DFK, KursartAllg=DFK, Sortierung=45, Sichtbar=true, Aenderbar=true, SchulnrEigner=XXXXXX)
```
Auf der Konsole sehe dann noch folgende Meldungen:

```
[qtp439513824-49] WARN org.mariadb.jdbc.message.server.ErrorPacket - Error: 1062-23000: Duplicate entry 'DFK-DFK' for key 'EigeneSchule_Kursart_UC1'
[EL Warning]: 2023-10-17 09:57:16.052--UnitOfWork(2049962602)--Exception [EclipseLink-4002] (Eclipse Persistence Services - 4.0.2.v202306161219): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLIntegrityConstraintViolationException: (conn=111551) Duplicate entry 'DFK-DFK' for key 'EigeneSchule_Kursart_UC1'
Error Code: 1062
Call: INSERT INTO EigeneSchule_Kursart (ID, Aenderbar, Bezeichnung, InternBez, Kursart, KursartAllg, SchulnrEigner, Sichtbar, Sortierung) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
        bind => [9 parameters bound]
Query: InsertObjectQuery(MigrationDTOKursarten(ID=41, Bezeichnung=Förderung neu zugewanderter Schüler in Deutschförderklassen (vollständige äußere Differenzierung), InternBez=DFK, Kursart=DFK, KursartAllg=DFK, Sortierung=41, Sichtbar=true, Aenderbar=true, SchulnrEigner=XXXXXX))
```
```
[qtp439513824-49] WARN org.mariadb.jdbc.message.server.ErrorPacket - Error: 1062-23000: Duplicate entry 'DFG-DFG' for key 'EigeneSchule_Kursart_UC1'
[EL Warning]: 2023-10-17 09:57:16.073--UnitOfWork(1457111188)--Exception [EclipseLink-4002] (Eclipse Persistence Services - 4.0.2.v202306161219): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLIntegrityConstraintViolationException: (conn=111551) Duplicate entry 'DFG-DFG' for key 'EigeneSchule_Kursart_UC1'
Error Code: 1062
Call: INSERT INTO EigeneSchule_Kursart (ID, Aenderbar, Bezeichnung, InternBez, Kursart, KursartAllg, SchulnrEigner, Sichtbar, Sortierung) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
        bind => [9 parameters bound]
Query: InsertObjectQuery(MigrationDTOKursarten(ID=44, Bezeichnung=Förderung neu zugewanderter Schüler in Deutschfördergruppen (teilweise äußere und innere Differenzierung), InternBez=DFG, Kursart=DFG, KursartAllg=DFG, Sortierung=44, Sichtbar=true, Aenderbar=true, SchulnrEigner=165256))
```

```
[qtp439513824-49] WARN org.mariadb.jdbc.message.server.ErrorPacket - Error: 1062-23000: Duplicate entry 'DFK-DFK' for key 'EigeneSchule_Kursart_UC1'
[EL Warning]: 2023-10-17 09:57:16.076--UnitOfWork(1435853120)--Exception [EclipseLink-4002] (Eclipse Persistence Services - 4.0.2.v202306161219): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLIntegrityConstraintViolationException: (conn=111551) Duplicate entry 'DFK-DFK' for key 'EigeneSchule_Kursart_UC1'
Error Code: 1062
Call: INSERT INTO EigeneSchule_Kursart (ID, Aenderbar, Bezeichnung, InternBez, Kursart, KursartAllg, SchulnrEigner, Sichtbar, Sortierung) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
        bind => [9 parameters bound]
Query: InsertObjectQuery(MigrationDTOKursarten(ID=45, Bezeichnung=Förderung neu zugewanderter Schüler in Deutschförderklassen (vollständige äußere Differenzierung), InternBez=DFK, Kursart=DFK, KursartAllg=DFK, Sortierung=45, Sichtbar=true, Aenderbar=true, SchulnrEigner=XXXXXX))
```
In der Konsolenausgabe tauchen die zwischen den o.g. API-Meldungen auf.

Der Inhalt der Quell-DB:
ID|Bezeichnung                                                                                              |InternBez|Kursart|KursartAllg|Sortierung|Sichtbar|Aenderbar|SchulnrEigner|
--|---------------------------------------------------------------------------------------------------------|---------|-------|-----------|----------|--------|---------|-------------|
| 1|3. Abiturfach                                                                                            |AB3      |AB3    |GK         |        70|+       |+        |       XXXXXX|
| 2|3. Fremdsprache (vierstündig)                                                                            |FS3      |FS3    |FS3        |       140|+       |+        |       XXXXXX|
| 3|3-stündiges Fach im math.-naturwiss., gesellschaftswiss. oder künstlerischen Schwerpunkt                 |F3       |F3     |F3         |       150|+       |+        |       XXXXXX|
| 4|4. Abiturfach                                                                                            |AB4      |AB4    |GK         |        80|+       |+        |       XXXXXX|
| 5|Angleichungskurs                                                                                         |AGK      |AGK    |AGK        |       130|+       |+        |       XXXXXX|
| 6|Arbeitsgemeinschaft                                                                                      |AGGT     |AGGT   |AGGT       |       160|+       |+        |       XXXXXX|
| 7|Arbeitsstunde                                                                                            |AST      |AST    |AST        |       170|-       |+        |       XXXXXX|
| 8|Ersatzfach für Sport als 4. Abiturfach                                                                   |EFSP     |EFSP   |GK         |       190|-       |+        |       XXXXXX|
| 9|Fächerkombination im math.-naturwiss., gesellschaftswiss. oder künstlerischen Schwerpunkt                |WPII     |WPII   |WPII       |        40|+       |+        |       XXXXXX|
|10|Fördergruppe für Schüler/-innen o. dt. Sprachkenntn., die keine Vorber.- bzw. Auffangklasse besuchen     |FG       |FG     |FG         |       200|-       |+        |       XXXXXX|
|11|Förderunterricht in der Erprobungsstufe                                                                  |EES      |EES    |EES        |       180|-       |+        |       XXXXXX|
|12|Grundkurs mündlich                                                                                       |GKM      |GKM    |GK         |        50|+       |+        |       XXXXXX|
|13|Grundkurs schriftlich                                                                                    |GKS      |GKS    |GK         |        60|+       |+        |       XXXXXX|
|14|Hausunterricht                                                                                           |HU       |HU     |HU         |       210|+       |+        |       XXXXXX|
|15|Leistungskurs I                                                                                          |LK1      |LK1    |LK         |       100|+       |+        |       XXXXXX|
|16|Leistungskurs II                                                                                         |LK2      |LK2    |LK         |       110|+       |+        |       XXXXXX|
|17|Maßnahmen äußerer Differenzierung in Klassen mit hohem Migrantenanteil                                   |MAD      |MAD    |MAD        |       220|-       |+        |       XXXXXX|
|18|Muttersprachlicher Unterricht in Vorbereitungs- und Regelklassen                                         |MEU      |MEU    |MEU        |       230|-       |+        |       XXXXXX|
|19|Pflichtunterricht für Teile von Klassen                                                                  |PUT      |PUT    |PUT        |        20|+       |+        |       XXXXXX|
|20|Schüler mit isolierter Lese- und Rechtschreibschwäche (Legasthenikergruppe)                              |LRS      |LRS    |LRS        |       240|-       |+        |       XXXXXX|
|21|schwerpunktübergreifende Angebote                                                                        |SPA      |SPA    |SPA        |       250|-       |+        |       XXXXXX|
|22|Sportförderunterricht                                                                                    |SPFU     |SPFU   |SPFU       |       260|-       |+        |       XXXXXX|
|23|Unterricht im Klassenverband                                                                             |PUK      |PUK    |PUK        |        10|+       |+        |       XXXXXX|
|24|Unterricht in der Muttersprache anstelle einer Pflichtfremdsprache oder eines Wahlpflichtfaches          |UMPF     |UMPF   |UMPF       |       270|-       |+        |       XXXXXX|
|25|Unterricht in einer Profilgruppe (Sek.I ab Klasse 07)                                                    |PROJ     |PROJ   |PROJ       |       280|-       |+        |       XXXXXX|
|26|Wahlpflichtbereich I                                                                                     |WPI      |WPI    |WPI        |        30|+       |+        |       XXXXXX|
|27|Zusatzkurs gem. § 12 APO-GOSt                                                                            |ZK       |ZK     |ZK         |        90|+       |+        |       XXXXXX|
|28|zusätzliche Unterrichtsveranstaltung (z.B. Schulchor)                                                    |ZUV      |ZUV    |ZUV        |       120|+       |+        |       XXXXXX|
|29|zusätzlicher Förderunterricht im Fach Deutsch für Schülerinnen und Schüler in Regelklassen               |ZUF      |ZUF    |ZUF        |       290|-       |+        |       XXXXXX|
|30|Förderangebot (Ganztagsbereich)                                                                          |FOGT     |FOGT   |FOGT       |        30|+       |+        |       XXXXXX|
|31|Ergänzungsstunden                                                                                        |EGS1     |EGS1   |EGS1       |        31|+       |+        |       XXXXXX|
|32|Zusätzlicher Förderunterricht im Rahmen der Initiative "Komm mit"                                        |KMFÖ     |KMFÖ   |KMFÖ       |        32|+       |+        |       XXXXXX|
|33|Vertiefungsfach                                                                                          |VTF      |VTF    |VTF        |        33|+       |+        |       XXXXXX|
|34|Projektkurs                                                                                              |PJK      |PJK    |PJK        |        34|+       |+        |       XXXXXX|
|35|Förderung in der deutschen Sprache (Sprachfördergruppe gemäß 13-63 Nr. 3, Absatz 2.2.3)                  |FS       |FS     |FS         |        35|+       |+        |       XXXXXX|
|36|Unterricht im Rahmen der Initiative "Kein Abschluss ohne Anschluss" einschl. "Schule trifft Arbeitswelt" |BUS      |BUS    |BUS        |        36|+       |+        |       XXXXXX|
|37|Unterricht im Rahmen des Schulversuchs Talentschule                                                      |TAL      |TAL    |TAL        |        37|+       |+        |       XXXXXX|
|38|kein Eintrag zulässig                                                                                    |*****    |*****  |*****      |        38|+       |+        |       XXXXXX|
|39|Wahlplflichtbereich: Arbeitsgemeinschaften aufgrund der Regelung in § 3 Abs. 6 APO-SI                    |WPU      |WPU    |WPU        |        39|+       |+        |       XXXXXX|
|40|Arbeitsgemeinschaften aufgrund der Regelung in § 3 Abs. 6 APO-SI                                         |AG       |AG     |AG         |        40|+       |+        |       XXXXXX|
|41|Förderung neu zugewanderter Schüler in Deutschförderklassen (vollständige äußere Differenzierung)        |FSD      |FSD    |FSD        |        41|+       |+        |       XXXXXX|
|42|Wahlpflichtbereich, Fremdsprachlich                                                                      |WP1FS    |WP1FS  |WP1FS      |        42|+       |+        |       XXXXXX|
|43|Förderung in der deutschen Sprache außerhalb von Sprachfördermaßnahmen gemäß Erlass 13-63 Nr. 3          |FDS      |FDS    |FDS        |        43|+       |+        |       XXXXXX|
|44|Förderung neu zugewanderter Schüler in Deutschfördergruppen (teilweise äußere und innere Differenzierung)|DFG      |DFG    |DFG        |        44|+       |+        |       XXXXXX|
|45|Förderung neu zugewanderter Schüler in Deutschförderklassen (vollständige äußere Differenzierung)        |DFK      |DFK    |DFK        |        45|+       |+        |       XXXXXX|
|46|Wahlpflichtbereich, 2. Fremdsprache                                                                      |WPIGY    |WPIGY  |WPIGY      |        46|+       |+        |       XXXXXX|

**Comment by ThomasBachran** [comment]
Hierbei handelt es sich um keinen Fehler, sondern um das Ergebnis von Aufräumarbeiten im Rahmen der Migration. In zukünftigen Versionen werden wir die Exceptions unterdrücken und eine klarere Formulierung im Log wählen, damit es hier zu keinem Mißverständnis kommt.
