### ISSUE TITLE
Diskrepanzen in der Spaltenbezeichnung

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/SVWS-Server#270]
Tabelle: Schuelerlernplattform und Lehrerlernplattform

In Schild2 heißt das Feld EinwilligungenAbgefragt
Im SVWS-Server heißt das Feld EinwilligungAbgefragt

![image](https://github.com/user-attachments/assets/7b0cce41-ac2a-4287-93b8-e1739dff505b)

**Comment by ThomasBachran** [comment]
Das Problem wurde mit einem Fix bei der Migration behoben. Siehe Commit d0599406b76f55885ce742bfcd46de37ec713bce .
