### ISSUE TITLE
Hinweise zum Schild3-Wiki, fehlende Informationen

### ISSUE THREAD

**Issue by T-Hagel-SK** [SVWS-NRW/SVWS-Server#271]
Hallo zusammen,

offenbar mehren sich die Informationen, dass am 18.10.2024 Schild3 in einen "öffentlichen Beta-Test" gehen, so war es zumindest im NRW-Forum in einem Kurs42-Beitrag zu lesen.

Nur, ich finde nirgendwo irgendwelche Hinweise, wann was veröffentlicht wird. Selbst im Schild3-Wiki unter
https://schulverwaltungsinfos.nrw.de/svws/wiki/index.php?title=%C3%9Cbersicht:_SchILD-NRW_3_(Einf%C3%BChrung)
 ist hierzu nichts zu finden und schon gar nicht, dass sich Schild3 wohl aktuell noch in einer Pre-Beta-Testphase befindet. 

D.h. wir IT-Dienstleister haben hier seit Anfang des Jahres zusammen mit Ribeka zahllose Stunden in eine Pre-Beta-Version gesteckt ??
Die Antwort darauf ist off-topic. 

Hier in dem Issue soll es nur um die Informationslage gehen:
- Im besagten Wiki findet sich oben unter "Beziehen Sie [SchILD-NRW 3](https://svws.nrw.de/) kostenfrei über die Webseite des MSB für Schulverwaltungssoftware." ein Link auf die Webseite "https://svws.nrw.de/" . Dort ist jedoch mit keinem Wort Schild3 erwähnt, geschweige denn eine Art Roadmap oder Vorstellung von Schild3. Oder wie man Schild3 "herunterladen" oder installieren kann.

- Im letzten Punkt des oben genannten Wikibeitrages steht "Nutzen Sie das vielfältige Supportangebot über die Webseite des MSB für Schulverwaltungssoftware und die Fortbildungsangebote Ihrer Bezirksregierung." Hier wären Links zu diesen Webseiten hilfreich.

- Auf der Seite fehlen auch die Besonderheiten, die mit Schild3 daherkommen, wie z.B., dass neben PC-Clients auch Teile (welche) browserbaisert zur Verfügung stehen und hier z.B. Kurs42 und LuPO quasi generalsaniert werden/wurden.

- Es fehlen aber auch Links zu Bedienungs- und Installationsanleitungen, sowie insbesondere Hinweise zu Abgrenzungen, die so ein Beta-Test mit sich bringt.

Schöne Grüße
Thomas Hagel

Stadt Köln
Fachanwendungsbetreuung / Koordination Schild3

**Comment by kroerig** [comment]
So wie ich es verstanden habe, bedeutet öffentlicher Betatest, dass die Fachberater SVWS & SchILD3 bei interessierten Schulen einrichten können. Bisher haben bevorzugt die Fachberater für sich getestet. Wer die Software selbst gefunden hat und testen wollte, musste mit dem auskommen, was im Netz zu finden ist.

Auf den Downloadseiten wird die Software daher vermutlich erst auftauchen, wenn sie allgemein verfügbar ist. Da müssen dann ja auch wieder Admin- und Anwenderschulungen stattfinden.

**Comment by T-Hagel-SK** [comment]
Da würde mch mal die Sicherweise des MSB/IT.NRW interessieren.

Selbst wenn die Software noch nicht freigeeben ist, sollte m.E. aber zumindest auch auf den offiziellen Seiten zumndest ein paar Kerninformationen bereitgestellt werden. Seien es Meilensteine, Roadmaps, weiterführende Informationen, die interessierte Schulen dazu veranlassen könnte, sich im Schulalltag noch nebenbei mit Schild3 zu beschäftigen.

**Comment by AnneSchueller** [comment]
Vielen Dank für die Hinweise. 
Informationen auf der Homepage folgen zeitnah.

**Comment by AnneSchueller** [comment]
Die Homepage wurde am 25.11.24 angepasst.

**Comment by T-Hagel-SK** [comment]
Ich bin da wohl Opfer der zahlreichen Webseiten zu dem Thema geworden ... 

Unter https://svws.nrw.de/svws-server/schild-nrw3 findet sich ja nun sowas wie eine Übersichtsseite, die inhaltlich mitunter - und rein subjektiv - unglücklich formuliert ist. 

Hinweise zum Programm:
"_und kann ab sofort  in einer Testumgebung betrieben werden_" 
-> Das verschweigt, dass die Schulen selber eine Testumgebung aufbauen müssen. Testumgebung klingt zunächst nach einem fertigen System das man direkt testen kann. Nicht, dass man sich hier erst was selber baut.

"_SchILD-NRW3 ist die zentrale Oberfläche für die Verwaltung der ..._"
Welche Oberfläche ? Mit Hilfe von Schild-NRW3 kann man der in der Liste genannten Aufgaben nachgehen. Sowohl im PC-Client als auch im Webbrowser. Wobei mir bis heute die Trennung unbekannt ist. Wäre es nicht sinnvoller gewesen, sich im PC-Client nur auf die Module zu konzentrieren, die nicht im Browser abbildbar sind ?

"_SchILD-NRW3 greift hierbei zum Teil direkt auf die MariaDB zu und bedient sich zum anderen Teil bereits aus den Daten, die der SVWS-Logikserver bereitstellt._"
-> Ist das für die Schulen wirklich so relevant, dass es hier auf diese Übersichtseite stehen muss ? Der wesentliche Kern ist doch, dass erstmals Arbeiten im Webbrowser (barrierfrei) möglich werden, dass die Inhalte optisch aufgewertet und übersichtlicher gestaltet wurden. Dass Kurs42 und LuPO im Browser laufen, dass es einen LuPO-Webserver gibt, auf dem Geräteunabhängig die Planung erfolgen kann. Das sind doch tolle und wichtige Kerninformationen, die auch Lust auf das neue System machen könnten. Wie viele Leser dieser Seite wissen was mit "MariaDB" oder "SVWS-Logikserver" gemeint ist ?

SchildNRW3 ist ein Meilenstein und er wird auf der Seite unter Wert beschrieben.. Es ist auch ein Ausblick auf SchildNRW4 in dem alles browserbasiert laufen soll.

Download der Installationsdatei:
Der gesamte Text entspricht ja nicht den Tatsachen. Die Schild-NRW3-Installationsdatei installiert nur den PC-Client. Hier ist mit keinem Wort erklärt, dass Schild3 ein System aus SVWS-Server und PC-Client ist. Dass man zur Nutzung des PC-Clients erst mal einen SVWS-Server benötigt sollte da schon stehen. Wie man zur Erstellung einer Testumgebung auf einem Windows-PC kommt, erfährt man erst in einem Unterpunkt aus dem Block Hilfen und Anleitungen --> https://schulverwaltungsinfos.nrw.de/svws/wiki/index.php?title=Schnellinstallation_SVWS-Server_und_SchILD-NRW_3

Hilfen und Anleitungen:
"_Im Forum haben wir einen eigenen Bereich für SchILD-NRW3 geschaffen..._"
Hier wäre der Link zu dem Forum hilfreich ...

Im Wiki https://schulverwaltungsinfos.nrw.de/svws/wiki/index.php?title=%C3%9Cbersicht:_SchILD-NRW_3_(Einf%C3%BChrung) steht dann auch wieder  "Beziehen Sie [SchILD-NRW 3](https://svws.nrw.de/) kostenfrei über die Webseite des MSB für Schulverwaltungssoftware." hier wäre es doch einfacher, hier nicht den Link zur Hauptseite zu verlinken, sondern auf die Wikiunterseite https://schulverwaltungsinfos.nrw.de/svws/wiki/index.php?title=SVWS-Server 


Aber vielleicht habe ich auch einfach eine ganz andere Sichtweise auf die Dinge ... vielleicht mach ich mir auch einfach zu viele Gedanken ...
