### ISSUE TITLE
Datenaustausch SVWS-Server mit dem externen Notenmodul

### ISSUE THREAD

**Issue by Blomeyer** [SVWS-NRW/SVWS-Server#272]
- Der SVWS-Server Release 0.9.4 exportiert Daten für das externe Notenmodul. Dies gilt auch für (Ankreuz-) Kompetenzen :-)
Auch der Import vom Notenmodul funktioniert ohne Probleme. 
**Frage**: Gibt es eine Möglichkeit die Konsistenz einer JSON-Notendatei automatisiert zu prüfen? Bei dem Import einer fehlerhaften JSON-Datei, antwortet der Server lediglich mit einem "bad gateway" (o.ä.)
- Das SVWS-Release 0.9.4 exportiert jetzt auch die Eigenschaft „passwordHash“ im Lehrerobjekt der NM3-JSON-Datei. Anscheinend wird dieses Feld nie gesetzt. Auch nicht das Initialpasswort (?!).
**Frage**: Wie ist das Verfahren zur Generierung eines Passwortes über NM3 geplant? Wann wird es voraussichtlich verfügbar sein?
- Im Objekt „Bemerkungen“ fehlen noch einige Eigenschaften (z.B.: "tsLELS" oder "tsSchulformEmpf").

**Comment by ThomasBachran** [comment]
>   **Frage**: Gibt es eine Möglichkeit die Konsistenz einer JSON-Notendatei automatisiert zu prüfen? Bei dem Import einer fehlerhaften JSON-Datei, antwortet der Server lediglich mit einem "bad gateway" (o.ä.)

Aktuell gibt es da neben dieser Methode keine weitere Möglichkeit. Die Fehlermeldung 400 zeigt ein Problem beim Deserialisieren der JSON-Datei an. Ergänzt wirde dies ggf. durch einen Fehlermeldung in der Antwort, die von der genutzten Bibliothek stammt.
 
> * Das SVWS-Release 0.9.4 exportiert jetzt auch die Eigenschaft „passwordHash“ im Lehrerobjekt der NM3-JSON-Datei. Anscheinend wird dieses Feld nie gesetzt. Auch nicht das Initialpasswort (?!).
>   **Frage**: Wie ist das Verfahren zur Generierung eines Passwortes über NM3 geplant? Wann wird es voraussichtlich verfügbar sein?

In der Datenbank müssen zunächst die Password-Hashes angelegt sein. Hierfür gibt es mehrere API-Methoden um diese zu verwalten. Unten Screenshots aus der Swagger-UI...
Sind dieser angelegt, so müssten sie auch in der JSON-Datei erscheinen.
 
> * Im Objekt „Bemerkungen“ fehlen noch einige Eigenschaften (z.B.: "tsLELS" oder "tsSchulformEmpf").

Ich habe die 3 Felder LELS, schulformEmp und foerderbemerkungen jeweils um die Zeitstempel ergänzt und jetzt auch beim Import ergänzt. Der Teil war noch nicht fertig programmiert. Mit dem nächsten Release stehen die dann zur Verfügung.

![grafik](https://github.com/user-attachments/assets/4b6845f3-9958-4f35-a49b-93f2c9ed3740)
![grafik](https://github.com/user-attachments/assets/c3c9917b-d608-4233-96fc-2b273abdc03c)

Da die Fragen damit geklärt sein sollten, schließe ich dieses Issue.

Vielen Dank für Ihre Rückmeldung!
