### ISSUE TITLE
Export von nicht fachgebundenen Kompetenzen

### ISSUE THREAD

**Issue by Blomeyer** [SVWS-NRW/SVWS-Server#273]
- Die nicht fachgebundenen Ankreuzkompetenzen (d.h. das Pseudofach „ASV“) werden beim Export der Daten für das externe Notenmodul nur dann für den KL exportiert, wenn der KL mindestens einmal in der UV einem Unterricht in dieser Klasse zugeordnet wurde. Diese Annahme ist sehr wahrscheinlich, aber nicht zwingend. 
- Noch eine Frage zum richtigen Verständnis: Wenn im Objekt „ankreuzkompetenzen“ im Array „kompetenzen“ das Attribut „istFachkompetenz“ den Wert ‚false‘ hat, dann ist damit das Pseudofach „ASV“ gemeint?

**Comment by ThomasBachran** [comment]
In Bezug auf den ersten Punkt habe ich die Datenaggregation im SVWS-Server angepasst. Die Informationen zu Schülern von Klassenlehrern werden jetzt berücksichtigt, wenn diese keine Lerngruppe in der Klasse haben. Das Problem sollte dann beim nächsten Release behoben sein.

Was die Frage zu "istFachkompetenz" angeht, so ist Ihre Interpretation korrekt. Es handelt sich dann um ASV.
