### ISSUE TITLE
Filter werden nicht aktualisiert

### ISSUE THREAD

**Issue by SimonFrank14** [SVWS-NRW/SVWS-Server#277]
Ich habe einen Bug im Webclient in Zusammenhang mit den Filtern festgestellt:

Ich habe aktuell einen Schüler in einer leeren DB angelegt. Der Schüler hat den Status "Neuaufnahme". Deswegen ist mit dem Default Filter (Status: Aktiv, Extern) erstmal nichts zu sehen. Wenn ich den Status anpassen und Neuaufnahme hinzufüge, dann sehe ich den Schüler. So weit so gut. Wenn ich jetzt den Status "Neuaufnahme" wieder entferne, ist der Schüler nach wie vor in der Liste, obwohl er nicht mehr den Filterkriterien entsprechen dürfte.

**Comment by FPfotenhauer** [comment]
Alles gut, danke. Ich hab die beiden offen hierher verschoben, das sind nur 2 clicks.

Unser Client reagiert bewusst so, dass der aktuelle angewählte Schüler bei Filteränderung nicht verschwindet.
Wechselt man dann aber einmal in einen anderen Schüler, der zu der Filterbedingung passt, dann verschwindet der Schüler, der nicht mehr passt.

**Comment by SimonFrank14** [comment]
> Alles gut, danke. Ich hab die beiden offenen hierher verschoben, das sind nur 2 clicks.
> 
> Unser Client reagiert bewusst so, dass der aktuelle angewählte Schüler bei Filteränderung nicht verschwindet. Wechselt man dann aber einmal in einen anderen Schüler, der zu der Filterbedingung passt, dann verschwindet der Schüler, der nicht mehr passt.

Das wird ne Menge Probleme machen und dürfte nicht UX compliant sein. Ich finde es gut, dass der SuS offen bleibt, aber wenn ich filtere, dann will ich davon ausgehen können, dass dort nur die SuS angezeigt werden, die dem Filter entsprechen. Er wird ja sogar unten noch im Counter berücksichtigt, der die Anzahl der Ergebnisse zum Filter anzeigt. Außerdem führt es eben zu den Komplikationen mit dem Multiselect wie in #278 beschrieben

**Comment by SimonFrank14** [comment]
> In dem Zusammenhang ist mir aufgefallen, das das "Filter zurücksetzen" nicht korrekt funktioniert. Hier bleibt im Status nur Neuaufnahme, aber es werden sämtliche SuS aufgelistet:
> 
> ![image](https://private-user-images.githubusercontent.com/79116896/379133341-2568d98c-7840-47e8-adf8-0c9edb6cdd8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2ODIxNzEsIm5iZiI6MTcyOTY4MTg3MSwicGF0aCI6Ii83OTExNjg5Ni8zNzkxMzMzNDEtMjU2OGQ5OGMtNzg0MC00N2U4LWFkZjgtMGM5ZWRiNmNkZDhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDExMTExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4MThiN2Y5ZjVmMmQyMjc4Zjg5ZDUwNDYyYzMxY2FiMTIyYjA0ZjUwYzRiYjQ5OWNhYmJlMmEwYmVmY2ZmNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Uapfm9JLXzC82vANg8Ywh2ceGmufiAXxMU3cOeWht3c)

Das Problem ist beim kompleten Filter und nicht nur beim Status

**Comment by SimonFrank14** [comment]
Verstehe ich nicht ganz.

Der Schüler würde dann ja links im Filter verschwinden, ok. Aber inwiefern schränkt mich das ein und warum muss ich den dann neu auswählen? Im Detailfenster rechts kann er ja ausgewählt bleiben...

**Comment by FPfotenhauer** [comment]
Bitte nicht falsch verstehen. Diese Diskussion wurde auch schon ausführlich bei Schild-NRW2 geführt und kommt alle Jahre immer wieder hoch.

Wir haben uns erst mal für dieses Verhalten entschieden.

**Comment by EwaldReinhardt** [comment]
Das Problem bisher in Schild war, dass der Filter laufend dynamisch aktualisiert wurde und beim Ändern eines Eintrags, der Element des Filterns ist, der Schüler unmerklich durch einen anderen ersetzt wurde und ggfs. weitere Daten beim falschen Schüler geändert wurden.
Dieses "dynamische" Filter sollte nie den aktuellen Schüler entfernen, von daher ist das jetzt schonmal besser.
Wenn aber die Filtereinstellungen angefasst werden, sollte gerade aktive Schüler aus der Liste rausgenommen werden, was ja beim Filtern über das Suchfeld auch passiert.

Das Thema kann aber sicherlich zu einem späteren Zeitpunkt verfolgt werden.

**Comment by SimonFrank14** [comment]
Ok, der Bug, dass man den Filter über den Button oben nicht resetten kann sollte aber trotzdem verfolgt und gefixt werden @FPfotenhauer.

Ich verstehe, dass Sie sich da so entschieden haben. Ich denke, dass man das dann in der UI gesondert Hervorheben muss und insbesondere beim neuen Filtern darf der Schüler dann nicht in die Gesamtsumme der gefilterten Schüler rein zählen.

**Comment by kroerig** [comment]
wahrscheinlich haben die Anwender damit weniger Probleme als wir hier. Sie kennen es ja nicht anders.
