### ISSUE TITLE
[Usability] Auswahl in Filter Dialog

### ISSUE THREAD

**Issue by SimonFrank14** [SVWS-NRW/SVWS-Server#278]
Ich habe im folgenden Szenario bei der Auswahl von Schülern noch einen Punkt, den ich für schlechte User Experience halte:

Ich habe einen Filter in dem z.B. eine Schülerin enthalten ist und wähle diese per Checkbox aus. Anschließend passe ich den Filter an, sodass sie nicht mehr drinnen ist. Ich mache meine Auswahl und nehme z.B. alle SuS, die im neuen Filter sind. Jetzt habe ich ja die neuen SuS + die alte Schülerin. Ich habe von hier aus keine Möglichkeit das Auswählen abzubrechen. Ich muss wieder auf den altern Filter zurück und die Schülerin deselektieren, um rechts wieder Schüler Infos anzeigen zu können. Alternativ kann ich die Seite neu laden, wo ich mich dann aber auch wieder anmelden muss.

Noch schlimmer wird dieser Bug mit dem gewünschten Verhalten aus #277 bei der vorherigen Auswahl und Ansicht eines Schülers im rechten Bereich. Also gleiches Setup: Ich filtere, wähle einen Schüler aus der rechts erscheint, passe den Filter an, sodass der Schüler nicht mehr enthalten sein sollte und anschließend mache ich ein Select All. Jetzt wird der Schüler links plötzlich ausgeblendet, verschwindet aus der sichtbaren UI und ich habe unten ganz klein den Hinweis, dass der Schüler noch mit ausgewählt ist für den Gruppenprozess. Ich habe keine Möglichkeit den über den Deselect All wieder weg zu bekommen und ich muss die ganze Liste danach suchen. Wenn ich das aber nicht mitbekomme, dann habe ich plötzlich im Worst Case einen Schüler mit gelöscht, den ich gar nicht löschen wollte, nur weil dieser rechts noch im Filter behalten wurde.

**Comment by hmt** [comment]
Danke für die ausführliche Rückmeldung; für dieses Issue und #277 werden wir die Komponenten entsprechend erweitern.
