### ISSUE TITLE
Fehler beim Schema Wechsel

### ISSUE THREAD

**Issue by SimonFrank14** [SVWS-NRW/SVWS-Server#279]
Ich habe noch einen Bug gefunden, der beim Wechsel in ein neues Schema auftritt:

1. Ich bin in meinem Schema testdb angemeldet und in irgendeiner Datenauswahl. 
![image](https://github.com/user-attachments/assets/484dd61a-f7f3-46bb-b0f0-9c6bf00d9db0)

2. Ich lade die Seite neu / dupliziere den Tab. Jetzt wähle ich hier mein zweites Schema emtpydb aus.
![image](https://github.com/user-attachments/assets/3008bde0-2124-423d-bd7d-d63e4201ce61)

Der Redirect von meinem Schüler steht noch in der URL oben.

3. Ich melde mich an und dann erhalte ich den Fehler, da die Redirect URL nicht existiert.
![image](https://github.com/user-attachments/assets/ed03d97a-272b-4726-baca-52f7cfd46d61)

Mein Vorschlag wäre folgender: Die Redirect URL sollte auf das ausgewählte Schema bezogen werden und nur dann angewendet werden, wenn dieses Schema wieder ausgewählt wird. Bei anderen Schemata sollte sie verworfen werden. Wo die Info gespeichert wird, wäre egal. Die könnte in der URL oder im Local Storage o.Ä. landen.

**Comment by ThomasBachran** [comment]
Das Schema wird jetzt in der URL mit angegeben, so dass die redirect-URL ggf. verworfen werden kann. Im nächsten Release wird die Änderung dann enthalten sein.
