### ISSUE TITLE
Unsinniger Katalogeintrag

### ISSUE THREAD

**Issue by kroerig** [SVWS-NRW/SVWS-Server#28]
Bei der Migration werden ja fehlerhafte/unvollständige Einträge in den Katalogen entfernt.
Mit ist da in meiner Datenbank folgender Eintrag im Katalog "Haltestellen" aufgefallen:
![grafik](https://github.com/SVWS-NRW/SVWS-Server/assets/5148795/8dbf0527-bb27-4481-8fc7-1d7008ed5f95)

Ist das Kunst oder kann das weg?
Wenn letzteres: Kann der Migrationsjob solche Einträge erkennen und aufräumen?

**Comment by FPfotenhauer** [comment]
Was spricht denn dagegeb, den Eintrag in Schild2 zu löschen?

**Comment by kroerig** [comment]
Im Prinzip nichts. Mir war es nur aufgefallen, als ich geschaut hatte, ob die Migration der Kataloge nach den Anpassungen vollständig war.
Im Alltag fallen solche Einträge vermutlich nicht auf. Daher die Frage, ob die bei der Migration aufgeräumt werden könnten, oder vllt. einen Hinweis ausgeben.

**Comment by FPfotenhauer** [comment]
Solche Einträge können auch später gelöscht werden.
Wir würden das, nach Rücksprache im Team, zunächst nicht anfassen.
