### ISSUE TITLE
[Bug] Direktes Aufnehmen von Fotos aus der Web UI funktioniert nicht

### ISSUE THREAD

**Issue by SimonFrank14** [SVWS-NRW/SVWS-Server#280]
Wenn ich bei einem Schüler ein Foto aufnehmen möchte, dann wird dieses nicht gespeichert.

Zum Nachstellen:
1. Ich öffne den Schüler und klicke oben auf die Kamera
![image](https://github.com/user-attachments/assets/06dff5f3-9226-45dd-9852-0fbb36b0448f)

2. Die Kamera wird geöffnet (nach Zulassen der Berechtigung)
![image](https://github.com/user-attachments/assets/a3ba21e8-c569-4151-804e-d0b4e23cec9f)
und ich kann das `Bild speichern`

Anschließend ist aber kein Bild vorhanden
![image](https://github.com/user-attachments/assets/069b9759-1ecb-4fdd-9de8-ec5fd880b064)

Hier einmal die Network Logs:
https://gigamove.rwth-aachen.de/de/download/bdd2b9f50f5ffc1cf1e00422ba87c3fe

**Comment by hmt** [comment]
Die Aufnahmen sind nun im nächsten Release dabei, Upload, WebCam, Löschen.
