### ISSUE TITLE
Verfügbarkeit POST APIs für Schüler / Erzieher

### ISSUE THREAD

**Issue by SimonFrank14** [SVWS-NRW/SVWS-Server#281]
Guten Abend,

ich wollte einmal nachfragen, ab wann die POST APIs zum Erstellen von Schülern & Erziehungsberechtigen zur Verfügung steht. Ich habe eine ganze Reihe an Daten, die ich aus unserer digitalen Anmeldung über die API in SchILD einpflegen möchte. Außerdem wollte ich einmal fragen, wie in etwa der Zeitplan aussieht, ab wann die neue SchILD und der SVWS in den Stable Betrieb übergehen.

Danke.

**Comment by FPfotenhauer** [comment]
Wir entwickeln gerade die Roadmap für 2025.
Schild-NRW3 und der SVWS-Server sollen ca. ab Frühjahr 2025 produktiv nutzbar sein.
Eine stabile versionierte API für solche Drittanwendungen ist auch in Planung.
Da wir mit Schulbewerbungen.de und anderen Projekten kooperieren, wird da definitiv etwas kommen.

Bitte immer Rücksicht auf unsere Resourcen nehmen.
Unser primäres Ziel im WebClient ist erstmal die Umsetzung der wichtigsten Funktionen.
