### ISSUE TITLE
Eintrag Räume

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/SVWS-Server#283]
Kann die Möglichkeit einer praktikableren Raumeingabe realisiert werden? Z.B. dass jeder Kurs einen Basisraum erhalten kann?
![grafik](https://github.com/user-attachments/assets/4f0d2a80-347b-4ef4-b037-da6f617ed754)
  
  
Das vereinfacht die Eingabe erheblich, denn gerade muss ich in Stundenplan->Unterrichte jeder einzelnen Stunde einen Raum zuweisen:  
![grafik](https://github.com/user-attachments/assets/1185c3be-ac10-48bb-a9d0-186c2074372b)

In der Tabelle der Unterrichte kann dann ja immer noch für Einzelstunden ausgewiesen werden, wenn die in einem anderen Raum stattfinden sollten.

**Comment by kroerig** [comment]
Ähm. Wozu stehen die Räume überhaupt in SchILD? Das ist doch Aufgabe der Stundenplaner den Unterricht auf die passenden Räume zu verteilen. SchILD muss doch eigentlich nur wissen, dass es einen Unterricht/Kurs gibt und für die Blockung wann er stattfindet, aber warum wo?

**Comment by HHayen** [comment]
Puuuh, nehmen Sie es mir bitte nicht übel, das wird mir hier zu viel Text. 
Glauben Sie mir einfach bitte, dass Beratungslehrer und Oberstufenkoordinatoren sehr gerne wissen, wo wann bei wem und mit wem etwas stattfindet.
Unter- und Mittelstufenkoordinatoren übrigens i.d.R. auch, auch ein Sekretariat, Schulleitung sowieso. 
Und nicht an jeder Schule haben alle gleichermaßen umfänglichen Zugriff auf das Stundeunplanprogramm. Aber eigentlich immer auf Schild.
Oder andersherum: Ohne Raumeintrag braucht es eigentlich die gesamte Stundenplanansicht nicht.

**Comment by ThomasBachran** [comment]
@hmt, @benjaminbartsch : Die Umsetzung kann nicht an der angegebenen Stelle stattfinden, da es sich um Stundenplandaten handelt. Hier müssten wir in der entsprechenden App eine geeignete Stelle abstimmen.

**Comment by HHayen** [comment]
Ganz großer Luxus wäre dann, wenn auf Basis der eingetragenen Unterrichtsräume diese in der Klausurplanung voreingetragen sein könnten, wenn sie denn eindeutig sind....

**Comment by FPfotenhauer** [comment]
Kann man bei den Kursen nicht auch den Stundenplan mit Raum einblenden, wenn vorhanden?
Bei den Klassen wird das ja auch schon gemacht.

**Comment by ThomasBachran** [comment]
> Kann man bei den Kursen nicht auch den Stundenplan mit Raum einblenden, wenn vorhanden? Bei den Klassen wird das ja auch schon gemacht.

Die Frage wäre dann hier, wie die Unterrichtsmenge konkret definiert sein sollte, die bei einem Kurs angezeigt werden soll. Bei den Klassen ist das durch die Klasse klar gegeben. Eine komplette Stundenplanansicht für nur einen Kurs wäre mMn überdimensioniert. Eine kleinere Ansicht mit der Auflistung der Unterrichtstunden wäre hier für später hingegen gut umsetzbar.

**Comment by hmt** [comment]
Bitte im DEV-Mode einmal testen, ist nun drin via cd9ab92b7178d2a3724ddb18fadb5a5ae3809290
