### ISSUE TITLE
Oberstufe: Lehrkraft in der Kursübersicht

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#289]
Hier müsste in der Kursübersicht bitte die Lehrkraft angezeigt werden. Insbesondere beim Umwählen ist es notwendig, diese Info sehen zu können.

![image](https://github.com/user-attachments/assets/c2a7eb33-6083-4097-b75a-104a0881c8d9)

**Comment by hmt** [comment]
sieht nun so aus: 
<img width="646" alt="image" src="https://github.com/user-attachments/assets/5b4936ea-d1f5-4506-89ab-3caf7a023444">

**Comment by NielsWL** [comment]
Top! Danke.
