### ISSUE TITLE
Schema anzeigen

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/SVWS-Server#29]
Könnte z.B. an dieser Stelle:
![grafik](https://github.com/SVWS-NRW/SVWS-Server/assets/84628225/f954ae0d-07d6-4935-87e9-83281623b635)
oder auch an anderer der Name des geöffnetes Schemes angezeigt werden?
Ich teste derzeit in mehreren Schemata gleichzeitig (Simulation z.B. Fortbildung), gelegentlich verliere ich den Überblick, wo ich gerade bin.

**Comment by ThomasBachran** [comment]
Das ist eine gute Idee. Ich habe das mit Commit 459942b9568bec3fdfcfd8c54f7b10fc3d41333e umgesetzt. Es wird dir also spätestens mit dem nächsten Release zur Verfügung stehen...
