### ISSUE TITLE
Frage zur OpenAPI

### ISSUE THREAD

**Issue by judowe** [SVWS-NRW/SVWS-Server#291]
Frage ist es vorgesehen über die OpenApi auch neue Schüler in der Datenbank anzulegen?

Ich finde in der Swagger API Doku nur die Endpunkte zum Auslesen und Aktualisieren der Schülerstammdaten, nicht aber einen Endpunkt zum Erstellen eines neuen Schüler-Stammdatensatzes.

Habe ich etwas übersehen, oder ist das nicht vorgesehen? Wenn nein warum nicht?

Könnte diese Möglichkeit in der API ergänzt werden?

**Comment by hmt** [comment]
Dieser Endpunkt wird kommen, aber wie @kroerig schon beschrieben hat, werden aktuell nur die Endpunkte ergänzt, für die wir auch den Client vorbereiten. Einen zeitlichen Rahmen kann ich deshalb aktuell noch nicht geben.
