### ISSUE TITLE
ENM-Notendatei: idJahrgang immer Null

### ISSUE THREAD

**Issue by Blomeyer** [SVWS-NRW/SVWS-Server#292]
In der ENM-Notendatei wird im JSON-Array **klassen** die Eigenschaft **idJahrgang** nicht gesetzt.
![idJahrgang](https://github.com/user-attachments/assets/55f87dca-806a-428f-b4b8-37f051ac0382)

**Comment by ThomasBachran** [comment]
@Blomeyer : Gibt es denn in Schild bei der Datenbank einen korrekten Jahrgangs-Eintrag? Bei der Zusammenstellung der ENM-Daten wird die Jahrgangs-ID gesetzt. Hierbei gilt die Dokumentation der ENM-Daten:
``` Java
	/** Die ID des Jahrgangs aus der SVWS-DB zu der die Klasse gehört (z.B. 11) oder null, falls es sich um eine jahrgangsübergreifende Klasse handelt */
	@Schema(description = "Die ID des Jahrgangs aus der SVWS-DB zu der die Klasse gehört oder null, falls es sich um eine jahrgangsübergreifende Klasse handelt.",
			example = "11")
	public Long idJahrgang;
```
