### ISSUE TITLE
Benutzername ist case sensitive

### ISSUE THREAD

**Issue by SchILD-Kloppenburg** [SVWS-NRW/SVWS-Server#293]
Wenn ich mich einlogge, muss ich meinen Namen jetzt unbedingt groß schreiben (Kloppenburg) und nicht wie bisher beim Login (kloppenburg). Da es wohl keine zwei Benutzer geben wird, die sich nur durch Groß- und Kleinschreibung unterscheiden werden, würde ich mich freuen, wenn der Benutzername vor dem Login in Kleinbuchstaben gewandelt würde.
Danke!

**Comment by AnneSchueller** [comment]
Man kann in der Benutzerverwaltung mit Adminrechten den Benutzernamen ändern. Das geht mit Schild3 in der Benutzerverwaltung über die rechte Maustaste oder im Client unter Einstellungen.

**Comment by FrodBRA** [comment]
Ich denke es geht nicht darum, dass man einen Nutzernamen ändert, sondern dass Groß´- und Keinbuchstaben als identisch behandelt werden.

Sowohl beim Login also auch beim Versuch, einen zweiten identischen Nutzernamen der sich nur in der Verwendung von Groß- und Kleinbuchstaben unterscheidet.

Daher: NUTZER = Nutzer = nutzer = NuTzEr usw. 

Das verhindert Fehler, sowohl bei der Doppeltanlage von Nutzern als auch bei "Mein Login geht nicht!"

**Comment by HHayen** [comment]
Es scheinen in der Benutzerverwaltung Felder vertauscht und/oder falsch beschriftet zu sein:
Vier Felder mit vier Bezeichnungen, für die es nur zwei gibt, und dann rechts vertauscht:

![grafik](https://github.com/user-attachments/assets/e864b469-ce97-468c-b4e7-be8df872e345)

Es sollte doch nur geben: **Anmeldename (=Benutzername (gerne nicht case sensitive, auch nicht bei Lehrerkürzeln falls generiert))** und **Name =(Anzeigename (case sensitive))**

**Comment by FPfotenhauer** [comment]
Unter vielen Betriebssystemen (nicht Windows :-) )  ist es üblich, dass auch der Benutzername case-sensitive ist....

**Comment by SchulenITK** [comment]
> Unter vielen Betriebssystemen (nicht Windows :-) ) ist es üblich, dass auch der Benutzername case-sensitive ist....

Wobei das im Web unüblich ist. Da man den Namen im WebClient manuell eingeben muss und kein Dropdown wie in SchILD hat, wird das mit Sicherheit initial sowie fortlaufend ein Problem bei Usern sein.

**Comment by SchILD-Kloppenburg** [comment]
In Schild ist die Groß- und Kleinschreibung egal, im SVWS-Server nicht. Es ging mir darum, dass es wenigstens konsistent sein sollte.

**Comment by kroerig** [comment]
Dann legt man die Benutzer/Login-Namen einfach grundsätzlich in Kleinbuchstaben an. Für bestehen Konten könnte das entweder global bei der Migration angepasst werden, oder man macht es manuell über ein SQL-Statement.

**Comment by FrodBRA** [comment]
> man 

Hier ist der Knackpunkt, ja. ;)

**Comment by kroerig** [comment]
Das lässt sich ja jetzt noch in SchILD2 anpassen. Ich vermute mal, dass die meisten aus Bequemheit die Loginname (=Kürzel?) in Kleinbuchstaben eingetragen haben. Es tippt sich dann einfach schneller.

Aber ja, unter richtigen Betriebsystemen ist `mueller` ein andere Benutzer als `Mueller`.

**Comment by FrodBRA** [comment]
Ich verstehe nicht, was die ideologische 90er Linuxdebatte über "richtige" und "echte" Betriebssysteme und was die INTERN machen damit zu tun haben, dass es technisch unaffine Standardnutzer verwirrt, wenn Nutzernamen case sensitiv sind?

Ja technisch spielt das für das OS und in der DB eine Rolle, hier stimme ich vollkommen zu. Nein, das hat nun überhaupt gar nichts damit zu tun, dass hier formuliert wurde, Nutzernamen im SVWS-Server, -Client, und SchILD und allen anderen Programmen sollten nicht case sensitiv sein und der Server sollte schlicht alle Variationen gleich behandeln. Wir reden hier über den _Userspace_, der hat meiner Perspektive nun einmal andere Randbedingungen.

**Comment by kroerig** [comment]
Das Thema ist ja schon geschlossen. Also wird sich vermutlich so schnell nichts daran ändern.
