### ISSUE TITLE
Klausurplanung: Zählung gelöschter Schüler in Kursen

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/SVWS-Server#294]
In der Klausurplanung wird ein Schüler gezählt, der eine Löschmarkierung enthält.
Der Schüler taucht in keiner Liste mehr auf, wird auch in der Kursplanung nicht gezählt.
![grafik](https://github.com/user-attachments/assets/0c17b9f3-05b1-468a-bafe-0b6c3a795a91)

**Comment by ThomasBachran** [comment]
@HHayen : Ich habe im dev-Branch eine Anpassung gemacht. Kannst du bei dir bitte prüfen, ob das Problem dort jetzt auch bei dir behoben ist?

**Comment by HHayen** [comment]
Nein, es wird immer noch der gelöschte Schüler mit Namen in der Kursliste unter Kurse angezeigt und in der Klausurplanung mitgezählt.
In der Kursplanung unter Oberstufe erscheint er nicht.

**Comment by ThomasBachran** [comment]
@HHayen : Es gab noch eine zweite problematische Stelle. Jetzt besser?

**Comment by HHayen** [comment]
Ist bei mir jetzt fehlerfrei.
