### ISSUE TITLE
Kurse: Reaktivitäts-Bug Anzeige Jahrgang

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/SVWS-Server#297]
Darstellungsfehler: 
Kurse: Erste Ansicht ist der erste Kurs aus Stufe 05.
Wählt man dann Stufe EF aus und wechselt zu einem EF-Kurs, wird in den Kursangaben weiter Stufe 05 angezeigt.

![grafik](https://github.com/user-attachments/assets/bffe197d-30c0-416c-8ea1-9abde5820ad4)

Klickt man die "05" weg, hat der Kurs aber gar keinen Jahrgang mehr:

![grafik](https://github.com/user-attachments/assets/23d941ba-4e4c-424b-9761-ef78ca543ebe)

erst ein erneutes Setzen von EF zeigt für alle Kurs "EF" an.

**Comment by ThomasBachran** [comment]
@HHayen : Tritt der Fehler bei dir noch im dev-Branch auf?

**Comment by ThomasBachran** [comment]
OK. In Issue #302 wurde das bereits überprüft. Ich schließe daher auch dieses Issue.
