### ISSUE TITLE
Probleme mit dem Installer

### ISSUE THREAD

**Issue by tpre** [SVWS-NRW/SVWS-Server#298]
Hallo!

Vielleicht sehe ich heute Abend den Wald vor Bäumen nicht, aber ich habe mit dem Installer so meine Probleme. Manche Angaben, Auswahlmöglichkeiten und Begrifflichkeiten sind meiner Meinung nach falsch bzw. nicht sinnvoll. (Im Endeffekt würde ich den Installer anders aufbauen.)

Seite "SVWS--Server-Konfiguration":

Der Installer sollte **zwischen Installation und Update** unterscheiden und dies dem Benutzer auch anzeigen. Bei einer Installation kann man davon ausgehen, dass alles überschrieben wird. Bei einem Update sind fast alle Punkte des Installers überflüssig, außer dem Kopieren der neuen Dateien. Warum sollte man, bei eier erkannten SVWS-Server-Installation es dem Benutzer ermöglichen, komplett erneut zu installieren inkl. DB, Zertifikat, Migration, ... ? Erscheint mir nicht sinnvoll.

**Warum kann man die Installation des SVWS-Servers hier abwählen?** (der eigentlichen Aufgabe des Installers)
Installiere ich weder eine DB noch den SVWS-Server, was bleibt dann? Nur eine Migration? Wohin? -> Nicht sinnvoll und verwirrend.

**Die beiden Punkte unter  "Installiere SVWS-Server ...." benutzen falsche Steuerelemente.** Eigentlich müssen Radiobuttons benutzt werden und nicht Checkboxen, die sich wie Radiobuttons verhalten. Es fehlt u.U. (je nachdem wie man Updates behandelt) ein dritter Punkt Update.

Der Begriff des **Datenbankschemas** wird für mein Verständnis falsch verwendet. Der normale Benutzer weiß nicht, was ein Schema ist. Es sollte besser Datenbank benutzt werden, zumal man aus einem Schema nicht migrieren kann. Man migriert Daten aus einer Datenbank, aber nicht Tabellendefinitionen u. a. (Bestandteile eines Schema).

Der Installer sollte prüfen, ob schon eine **Zertifikat-Datei SVWS.cer** im Ordner Dokumente des aktuellen Benutzers vorhanden ist und dann im Installer darauf hinweisen. In so einem Fall ist es unnötig, ein neues Zertifikat zu erstellen, dass dann umständlich beim Benutzer installiert werden muss. Man kann davon ausgehen, dass das die vorhandene Datei ein Zertifikat einer vorherigen Installation ist. Ich hatte jedenfalls den SVWS-Server deinstalliert und alle Reste gelöscht, nur nicht die Zertifikatdatei.
Im Wiki sollte das beschrieben werden. Im Wiki ist die Rede vom "Windows-Systemordner "Dokumente"". Es müsste heißen "Dokumente-Ordner des installierenden Benutzers". "Dokumente" ist kein Systemordner.

**"DB-Konfiguration" sollte besser "Datenbank-Server-Konfiguration" heißen**. Es geht hier nicht um die DB, sondern um den DB-Server.  "Server" sollte "IP-Adresse" heißen. Außerdem sollten die Angaben zu DB, Benutzer und Kennwort auf diese Seite. Ebenso sollten die Abgaben (root-Kennwort, Port) bei einer zu installierenden MariaDB auf diese Seite. Man kann aktuell bei DBMS keine Angabe machen und kommt auf die nächste Seite.

Die Seite "DB-Admin-Zugriff erlauben" ist überflüssig, Die Abfrage des root-Kennworts sollte auf die vorherige Seite.

**Fehler: Nach der Seite "DB-Admin-Zugriff erlauben" wiederholt der Installer bei mir einige Seiten diverse Male**, wo man erneut die gleichen Angaben machen kann bevor man zur Installation kommt.

Im Endeffekt funktioniert bei mir die Installation mit Migration aus einer Schild 2-MariaDB-DB nicht. Es wird laut Ausgabe zwar eine DB erstellt, die aber später nicht existiert. Scheinbar ist der Migrationsteil recht buggy.

Es funktioniert aber die normale Installation ohne Migrationsversuch.

**Comment by FPfotenhauer** [comment]
Die Installation ist hier sehr ausführlich beschrieben.
https://schulverwaltungsinfos.nrw.de/svws/wiki/index.php?title=Installation_SVWS-Server_und_SchILD-NRW_3

Die Begriffe Datenbank und Schema sind synonym. Wenn man das googelt, dann gibt es da einfach verschiedene Sprechweisen. Wir nutzen schon seit Jahren unsere Begriffe.

Wenn jemand die Zertifikatsdatei aus dem Ordner Dokumente entfernt, dann liegt da keine Datei. Beim "Update", was man an den ausgegrauten Feldern erkennt, wird auch keine neue erstellt.

Die unteren Bemerkungen beziehen sich anscheinend auf ein anderes Tool, das finde ich so gar nicht im SVWS-Server-Installer.

Der Installer wird mit Inno-Setup erstellt. Das ist ein Tool, das aus der Delphi-Welt entstammt. Wenn sich hier jemand dazu durchdringen könnte, sich einmal intensiv mit diesem Tool zu beschäftigen und dann einen PULL-Request mit Verbesserungen stellen mag, dann wären wir hier wirklich sehr dankbar. Sich aus der Java-Welt in diese Tools einzuarbeiten ist nicht immer ganz einfach, weil das doch sehr in der Windows-Welt verhaftet ist.
