### ISSUE TITLE
Zusätzliche Felder in Lehrer-Kontaktdaten

### ISSUE THREAD

**Issue by WJohannsen** [SVWS-NRW/SVWS-Server#299]
Guten Abend,

in den Lehrer-Basisdaten -> Kontaktdaten gibt es nur die Möglichkeit, eine Festnetz und eine Mobilfunknummer anzugeben. Aus diesem Grund wurden bisland diverse andere Felder in den Individualdaten missbraucht, um weitere Kontaktinformationen abzuspeichern - z.B. Fax (ja, tatsächlich...) oder in Sonderfällen eine ausländische Festnetznummer, da die Kollegin zwischen ihrer Wohnung am Dienstort und ihrer Familie im Ausland pendelt.

Ich bitte daher die Möglichkeit, weitere Felder mit Kontaktdaten zu ergänzen. Einen Widerspruch zur VO-DV II sehe ich hier nicht, da hier für im Abschnitt "Erreichbarkeit privat: Anschrift Wohnsitz, Anschrift Postzustellung, Telefon, Fax*, E-Mail*" keine Beschränkung der Anzahl der Telefonnummern gegeben ist.

Ich weiß nicht, ob dies nun in den SVWS-Server oder den SchILD3-Client gehört, daher Crossposting (https://github.com/SVWS-NRW/Schild3-BetaTest/issues/1173).

**Comment by FPfotenhauer** [comment]
Der Gedanke ist natürlich nachvollziehbar. Wir befinden uns momentan in der Grundentwicklung des Web-Clients.
Unsere Kapazitäten sind damit leider komplett ausgelastet.

Wir werden perspektivisch an allen Stellen die Kontaktdaten von Personen angleichen und solche Vorschläge dann berücksichtigen.

**Comment by WJohannsen** [comment]
Dann bitte ich darum, die Formatvalidierung der vorhandenen Felder ebenfalls auf Eis zu legen. Bislang liegt die ausländische Nummer in einem der E-Mail-Adressen-Felder. Wenn das wegfällt, können wir die ausländische Nummer gar nicht hinterlegen.
