### ISSUE TITLE
Vorlage Laufbahnplanung

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/SVWS-Server#30]
Oberstufe->Beratung, bei ausgewähltem Abijahrgang werden Eintragungen von Fachwahlen (z.B. D = S) nicht in die Schülervorlage übernimmen, die Beratungsansicht der Schüler ist also trotz gefüllter Vorlage leer.

**Comment by ThomasBachran** [comment]
Das liegt an dieser Stelle daran, dass die Planung des Schülers von der Vorlage beliebig abweichen kann/darf. Es gibt beim Schüler einen Knopf zurücksetzen. Dieser übernimmt die Vorlage für diesen einen Schüler.

Zu Beginn des Beratungszeitraums ist es natürlich interessant die Vorlage auf alle Schüler zu übertragen. Dafür gibt es bei `Oberstufe -> Fachwahlen` den Knopf `Alle Fachwahlen zurücksetzen`.

Unter `Oberstufe -> Beratung` findet sich für den Vorlagen-Abiturjahrgang eine Vorlage, die in einzelne Abiturjahrgänge übernommen werden kann. Bei den Abiturjahrgängen gibt es dort dann den Knopf `Zurücksetzen`.

Wenn ich das richtig sehe, dann handelt es sich dann hier um keinen Fehler. Ist das korrekt?

**Comment by HHayen** [comment]
Wäre dann eine Benennung "Auf Vorlage zurücksetzen" nicht sinnvoller?

**Comment by ThomasBachran** [comment]
Bei den Vorlagen waren noch ein paar andere Sachen nicht wirklich fertig bzw. gut benannt. Ich habe das mal ein wenig überarbeitet. In der nächsten SVWS-Server-Version wird dann mein Vorschlag enthalten sein.

@HHayen : Kannst du dir das dann nochmal insgesamt anschauen? Mich würde insbesondere eine Rückmeldung zu dem Verhalten des Knopfes "Nicht feste Schüler-Fachwahlen zurücksetzen" interessieren...

**Comment by HHayen** [comment]
Selbstverständlich.

**Comment by FPfotenhauer** [comment]
Bitte wieder öffnen, wenn noch Rückmeldung kommt.
