### ISSUE TITLE
Fehler beim Zugriff auf Lernabschnitte mit eingeschränkten Benutzerrechten für Lehrerdaten

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/SVWS-Server#300]
Hat ein Benutzer eingeschränkte Rechte und darf Lehrerdaten nicht einsehen, so folgt eine Fehlermeldung beim Klick auf die Lernabschnitte der SuS:

{
  "env": {
    "mode": "stable",
    "version": "1.0.1",
    "commit": "c2d7303f829db846867f57b54d660e606f84e7cd",
    "kompetenzen": "KEINE,SCHUELER_INDIVIDUALDATEN_ANSEHEN,SCHUELER_INDIVIDUALDATEN_AENDERN,SCHUELER_LOESCHEN,SCHUELER_INDIVIDUALDATEN_VERMERKE_AENDERN,SCHUELER_INDIVIDUALDATEN_KAOA_DATEN_AENDERN,SCHUELER_INDIVIDUALDATEN_EINWILLIGUNGEN_AENDERN,SCHUELER_LEISTUNGSDATEN_ANSEHEN,SCHUELER_LEISTUNGSDATEN_FUNKTIONSBEZOGEN_AENDERN,SCHUELER_LEISTUNGSDATEN_ALLE_AENDERN,BERICHTE_ALLE_FORMULARE_DRUCKEN,IMPORT_EXPORT_DATEN_IMPORTIEREN,IMPORT_EXPORT_SCHUELERDATEN_EXPORTIEREN,IMPORT_EXPORT_LEHRERDATEN_EXPORTIEREN,IMPORT_EXPORT_SCHNITTSTELLE_SCHILD_NRW,IMPORT_EXPORT_ACCESS_DB,IMPORT_EXPORT_XML,IMPORT_EXPORT_SCHULBEWERBUNG_DE,SCHULBEZOGENE_DATEN_ANSEHEN,KATALOG_EINTRAEGE_ANSEHEN,UNTERRICHTSVERTEILUNG_ANSEHEN,UNTERRICHTSVERTEILUNG_PLANUNG_ANSEHEN,NOTENMODUL_NOTEN_AENDERN_FUNKTION,NOTENMODUL_NOTEN_ANSEHEN_ALLGEMEIN,NOTENMODUL_NOTEN_ANSEHEN_FUNKTION"
  },
  "capturedError": {
    "id": 0,
    "name": "API-Fehler: Dieser Fehler wird durch eine fehlerhafte Kommunikation mit dem Server verursacht. In der Regel bedeutet das, dass die verschickten Daten nicht den Vorgaben entsprechen.",
    "message": "Fetch failed for GET: /db/GY_Abi/lehrer/ - Status: 403",
    "stack": [
      "Error: Fetch failed for GET: /db/GY_Abi/lehrer/",
      "    at QA.getTextBased (https://localhost/assets/index.js:22:286401)",
      "    at async QA.getLehrer (https://localhost/assets/index.js:53:662864)",
      "    at async Promise.all (index 3)",
      "    at async tH.setSchueler (https://localhost/assets/index.js:57:123827)",
      "    at async rH.update (https://localhost/assets/index.js:57:125946)",
      "    at async rH.doUpdate (https://localhost/assets/index.js:56:62560)",
      "    at async va.beforeEach (https://localhost/assets/index.js:60:11674)"
    ],
    "log": null
  }
}

**Comment by ThomasBachran** [comment]
@AnneSchueller : Das Problem ist vermutlich im dev-Branch behoben. Kannst du das bitte prüfen und dieses Issue dann ggf. schließen?

**Comment by AnneSchueller** [comment]
klappt jetzt
