### ISSUE TITLE
SVWS.cer - Datei ist nicht angelegt worden bzw. verschwunden

### ISSUE THREAD

**Issue by Raphael-Kemna** [SVWS-NRW/SVWS-Server#301]
Hallo zusammen,

bei der Installation unseres SVWS-Servers ist keine SVWS.cer-Datei installiert worden.
Diese soll ja im Verzeichnis C:\Users\<benutzername>\Dokumente\SVWS.cer abgelegt sein.
Hier ist bei mir leider nichts vorhanden.
Kann das Anlegen irgendwie wiederholt werden?
Wir nutzen IServ als Server-Umgebung. Die Verzeichnisse "Local.V6" und "Remote.V2" werden umgelenkt auf ein Laufwerk I:, aber nur beim Abmelden. Vielleicht wurde dabei diese Zertifikatsdatei gelöscht?

LG
Raphael

**Comment by ThomasBachran** [comment]
Die Datei muss nicht neu angelegt werden. Aktuell haben wir aber nur einen etwas umständlichen Weg über einen direkten Aufruf der API-Methode im Browser: `https://localhost/config/certificate_file`. Dabei ist localhost ggf. durch den Hostnamen oder die IP-Adresse des Servers zu ersetzen. Der Browser fragt dann nach den Benutzerdaten und man erhält als Rückgabe die Datei.
