### ISSUE TITLE
Eintrag bei Kurse/Jahrgang fehlerhaft 

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/SVWS-Server#302]
https://github.com/SVWS-NRW/Schild3-BetaTest/issues/1178

Ergänzung:
Ändert man im Client den Jahrgang bei einem Kurs, so ändern sich bei allen Jahrgängen die Einträge. Sichtet man die Datenbank mit DBeaver sind die Jahrgänge bei den Kursen korrekt.

**Comment by ThomasBachran** [comment]
@AnneSchueller : Das ist vermutlich ein Duplikat von #297 . Kannst du den Fehler mal versuchen mit dem dev-Branch zu reproduzieren und hier eine Rückmeldung geben, ob dort der Bug noch besteht?

**Comment by AnneSchueller** [comment]
funktioniert mit dem dev-Branch
