### ISSUE TITLE
Datum und Uhrzeit im Logfile 

### ISSUE THREAD

**Issue by kroerig** [SVWS-NRW/SVWS-Server#303]
Hallo,

ich habe gerade eine neue DB Migration durchgeführt und in den Konsolenlogs des Servers den Stand verfolgt.
Heute ist der 18.11.
In der Konsolenausgabe des SVWS aber steht:
**2024-11-17**T16:56:20.701 INFO Migration abgeschlossen.

Zur Kontrolle ein `docker exec  4b817c01af96 date`:
Mon Nov 18 05:09:51 PM UTC 2024

Das passt soweit.

Warum logged der Server mit falschen Zeitangaben?

**Comment by kroerig** [comment]
In der Hoffnug auf eine Besserung habe ich den Umgebungsvariablen den Wert `TZ=Europe/Berlin` hinzugefügt und den Container neu erstellt. Das änderte zwar die Darstellung der Uhrzeit. Der Java-Prozess zeigt sich davon aber unbeindruckt
```
2024-11-17T17:13:51.280 INFO org.eclipse.jetty.server.AbstractConnector - Started Server@4b00d59{SSL, (ssl, alpn, h2, http/1.1)}{0.0.0.0:8443}
2024-11-17T17:13:51.335 INFO org.eclipse.jetty.server.Server - Started oejs.Server@3c87e851{STARTING}[12.0.14,sto=0] @10726ms

```

**Comment by ThomasBachran** [comment]
@kroerig : Kann das etwas mit der Zeitzonen-Konfiguration zu tun haben?

Vielleicht hilft das hier weiter?
- https://webwork.blog/zeitzonen-in-docker-containern/
- https://stackoverflow.com/questions/24551592/how-to-make-sure-dockers-time-syncs-with-that-of-the-host

**Comment by kroerig** [comment]
Daher stammt ja meine Idee, dem Container die Variable TZ mitzugeben. Und auch das Mounten von `/etc/localtime` bringt nur kosmetische Änderungen auf der CLI.

Datum und Uhrzeit im Container stimmen ja auch, nur der Java-Prozess interessiert sich nicht dafür.

**Comment by FPfotenhauer** [comment]
Die Request.logs haben das korrekte Datum und sind nur um eine Stunde "verschoben".

**Comment by ThomasBachran** [comment]
Wenn die Uhrzeit in den Logs um eine Stunde verschoben ist, dann liegt das daran, dass die Logs in UTC geschrieben werden. Haben wir hier Winterzeit, so beträgt die Different 1 Stunde. Bei Sommerzeit 2 Stunden. Das zuvor beschriebene Problem bei Docker unterscheidet sich hier, da die Abweichung sich anders verhält.

**Comment by FPfotenhauer** [comment]
Das Problem ist kein Docker Problem. Die Ausgabe in der Console ist um einen Tag verschoben. Die Stunde Verschiebung in den Request-Logs ist ok, damit kann man leben.

**Comment by ThomasBachran** [comment]
@FPfotenhauer : Den Bug außerhalb des Docker-Containers konnte ich nachvollziehen. Der sollte behoben sein.
@kroerig : Mir ist allerdings nicht ganz klar, ob die Abweichung in Docker den gleichen Ursprung hat. Ist die Verschiebung dort auch um einen Tag (Angaben des Logs sollten in UTC sein)

**Comment by kroerig** [comment]
ja.

Wir haben gerade den 03.12.2024 10:47 und der Java-Prozess logged beim Start: 2024-12-02T09:47

**Comment by ThomasBachran** [comment]
Vielen Dank für die Rückmeldung. Dann ist es wirklich das gleiche Problem gewesen. Bei der Umrechnung wurde aus Versehen ein zusätzlicher Tag eingeführt (0. Januar 1970), da ein +1 im Code ausgelassen wurde. Im nächsten Release ist der Fehler dann behoben.
