### ISSUE TITLE
Importproblem bei Adressen (Wahrscheinlich schon Fehler in Schild 2.0)

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/SVWS-Server#304]
In Schild 2 werden die Adressen teilweise falsch abgespeichert, wenn die Schule von Adresse getrennt verwalten auf eine Adresse zurückgeht:
![image](https://github.com/user-attachments/assets/11b93074-dd3f-47f6-a0a4-523288fbbb56)

Es kommt in der Schild2-Datenbank dann zu fehlerhaften Adresseingaben.

In Schild 3 bzw. auf dem Server passiert dann folgendes beim Import:
![image](https://github.com/user-attachments/assets/e3bdbeb8-56fd-4ce8-abec-12453beace38)

**Comment by M-Plu** [comment]
Bitte mal mit einer aktuellen (SnapShot) Version >= 1.0.2 testen. Da sollte das Problem schon nicht mehr auftreten. Ansonsten kannst du die hier wieder melden, wenn es damit weiterhin besteht.

Wie ist es denn um die Anzeige und den Ausdruck davon in Schild 3 bestellt. Wenn da ein Fehler auftritt, bitte für Schild 3 ein Issue erstellen.

**Comment by ThomasBachran** [comment]
@Kluesenerm Tritt das Problem nur bei den Reports auf oder auch in der Client-Anwendung selber unter Individualdaten (s.u.)?

![grafik](https://github.com/user-attachments/assets/156d6b5c-d229-4252-a9e7-4c647bd80a76)

**Comment by FPfotenhauer** [comment]
Gibt es hier eine Rückmeldung?
Ansonsten würde ich das Issue einmal schließen.

**Comment by FPfotenhauer** [comment]
Bitte wieder öffnen, falls der Fehler nochmals auftritt.
