### ISSUE TITLE
Kursplanung wird nicht mehr angezeigt

### ISSUE THREAD

**Issue by ngbvol** [SVWS-NRW/SVWS-Server#305]
Beim Aufruf Kursplanung erhalten wir die Fehlermeldung:

{
  "env": {
    "mode": "stable",
    "version": "1.0.1",
    "commit": "dcaa57cd620efd8832b036b2f295dd88d24fb3b6",
    "kompetenzen": "KEINE,ADMIN,SCHUELER_INDIVIDUALDATEN_ANSEHEN,SCHUELER_INDIVIDUALDATEN_AENDERN,SCHUELER_LOESCHEN,SCHUELER_INDIVIDUALDATEN_VERMERKE_AENDERN,SCHUELER_INDIVIDUALDATEN_KAOA_DATEN_AENDERN,SCHUELER_INDIVIDUALDATEN_EINWILLIGUNGEN_AENDERN,SCHUELER_LEISTUNGSDATEN_ANSEHEN,SCHUELER_LEISTUNGSDATEN_FUNKTIONSBEZOGEN_AENDERN,SCHUELER_LEISTUNGSDATEN_ALLE_AENDERN,BERICHTE_ALLE_FORMULARE_DRUCKEN,BERICHTE_STANDARDFORMULARE_DRUCKEN,BERICHTE_AENDERN,BERICHTE_LOESCHEN,IMPORT_EXPORT_DATEN_IMPORTIEREN,IMPORT_EXPORT_SCHUELERDATEN_EXPORTIEREN,IMPORT_EXPORT_LEHRERDATEN_EXPORTIEREN,IMPORT_EXPORT_SCHNITTSTELLE_SCHILD_NRW,IMPORT_EXPORT_ACCESS_DB,IMPORT_EXPORT_XML,IMPORT_EXPORT_SCHULBEWERBUNG_DE,SCHULBEZOGENE_DATEN_ANSEHEN,SCHULBEZOGENE_DATEN_AENDERN,EXTRAS_BACKUP_DURCHFUEHREN,EXTRAS_GELOESCHTE_DATEN_ZURUECKHOLEN,EXTRAS_FARBEN_FUER_FACHGRUPPEN_AENDERN,EXTRAS_DATEN_AUS_KURS42_IMPORTIEREN,EXTRAS_DATEN_PERSONENGRUPPEN_BEARBEITEN,KATALOG_EINTRAEGE_ANSEHEN,KATALOG_EINTRAEGE_AENDERN,KATALOG_EINTRAEGE_LOESCHEN,LEHRERDATEN_ANSEHEN,LEHRERDATEN_AENDERN,LEHRERDATEN_LOESCHEN,LEHRER_PERSONALDATEN_ANSEHEN,LEHRER_PERSONALDATEN_AENDERN,SCHULPFLICHTVERLETZUNG_ANSEHEN,SCHULPFLICHTVERLETZUNG_AENDERN,SCHULPFLICHTVERLETZUNG_LOESCHEN,UNTERRICHTSVERTEILUNG_ANSEHEN,UNTERRICHTSVERTEILUNG_PLANUNG_ANSEHEN,UNTERRICHTSVERTEILUNG_ALLGEMEIN_AENDERN,UNTERRICHTSVERTEILUNG_FUNKTIONSBEZOGEN_AENDERN,STUNDENPLAN_ALLGEMEIN_ANSEHEN,STUNDENPLAN_FUNKTIONSBEZOGEN_ANSEHEN,STUNDENPLAN_IMPORT,STUNDENPLAN_EXPORT,STUNDENPLAN_AENDERN,STUNDENPLAN_AKTIVIEREN,NOTENMODUL_ADMINISTRATION,NOTENMODUL_NOTEN_AENDERN_ALLGEMEIN,NOTENMODUL_NOTEN_AENDERN_FUNKTION,NOTENMODUL_NOTEN_ANSEHEN_ALLGEMEIN,NOTENMODUL_NOTEN_ANSEHEN_FUNKTION,DATENBANK_SCHEMA_ERSTELLEN,DATENBANK_SQLITE_IMPORT,DATENBANK_SQLITE_EXPORT,OBERSTUFE_ABITURJAHRGAENGE_VERWALTEN,OBERSTUFE_LAUFBAHNPLANUNG_ALLGEMEIN,OBERSTUFE_LAUFBAHNPLANUNG_FUNKTIONSBEZOGEN,OBERSTUFE_LUPO_IMPORT,OBERSTUFE_KURSPLANUNG_ALLGEMEIN,OBERSTUFE_KURSPLANUNG_FUNKTIONSBEZOGEN,OBERSTUFE_KURSPLANUNG_BLOCKUNG_AKTIVIEREN,OBERSTUFE_KLAUSURPLANUNG_AENDERN,OBERSTUFE_KLAUSURPLANUNG_ANSEHEN_ALLGEMEIN,OBERSTUFE_KLAUSURPLANUNG_ANSEHEN_FUNKTION,ABITUR_ANSEHEN_ALLGEMEIN,ABITUR_ANSEHEN_FUNKTIONSBEZOGEN,ABITUR_AENDERN_ALLGEMEIN,ABITUR_AENDERN_FUNKTIONSBEZOGEN,ABITUR_EINGABE_ERGEBNISSE_ALLGEMEIN,ABITUR_EINGABE_ERGEBNISSE_FUNKTIONSBEZOGEN,CARDDAV_NUTZEN,CARDDAV_ERZIEHER_ANSEHEN,CALDAV_NUTZEN,CALDAV_EIGENER_KALENDER,CALDAV_KALENDER_ANSEHEN_ALLGEMEIN,CALDAV_KALENDER_ANSEHEN_FUNKTIONSBEZOGEN,ABSCHLUSS_SEKI_ANSEHEN_ALLGEMEIN,ABSCHLUSS_SEKI_ANSEHEN_FUNKTIONSBEZOGEN,ABSCHLUSS_SEKI_AENDERN_ALLGEMEIN,ABSCHLUSS_SEKI_AENDERN_FUNKTIONSBEZOGEN,ABSCHLUSS_SEKI_EINGABE_ERGEBNISSE_ALLGEMEIN,ABSCHLUSS_SEKI_EINGABE_ERGEBNISSE_FUNKTIONSBEZOGEN,ABSCHLUSS_BK_ANSEHEN_ALLGEMEIN,ABSCHLUSS_BK_ANSEHEN_FUNKTIONSBEZOGEN,ABSCHLUSS_BK_AENDERN_ALLGEMEIN,ABSCHLUSS_BK_AENDERN_FUNKTIONSBEZOGEN,ABSCHLUSS_BK_EINGABE_ERGEBNISSE_ALLGEMEIN,ABSCHLUSS_BK_EINGABE_ERGEBNISSE_FUNKTIONSBEZOGEN"
  },
  "capturedError": {
    "id": 0,
    "name": "API-Fehler: Dieser Fehler wird durch eine fehlerhafte Kommunikation mit dem Server verursacht. In der Regel bedeutet das, dass die verschickten Daten nicht den Vorgaben entsprechen.",
    "message": "Fetch failed for GET: /db/ngb/gost/blockungen/1/gzip - Status: 404",
    "stack": [
      "Error: Fetch failed for GET: /db/ngb/gost/blockungen/1/gzip",
      "    at nI.getBinary (https://192.168.59.105:8443/assets/index.js:22:291945)",
      "    at async nI.getGostBlockungGZip (https://192.168.59.105:8443/assets/index.js:53:626515)",
      "    at async bW.setAuswahlBlockung (https://192.168.59.105:8443/assets/index.js:57:300062)",
      "    at async OW.update (https://192.168.59.105:8443/assets/index.js:57:321846)",
      "    at async OW.doUpdate (https://192.168.59.105:8443/assets/index.js:56:58550)",
      "    at async va.beforeEach (https://192.168.59.105:8443/assets/index.js:60:14994)"
    ],
    "log": {
      "id": null,
      "success": false,
      "log": [
        "Das Fach mit der ID 84 ist nicht als Fach der gymnasialen Oberstufe gekennzeichnet.",
        "  de.svws_nrw.data.gost.DataGostBlockungsdaten.getBlockungsdatenManagerFromDB(DataGostBlockungsdaten.java:194)",
        "  de.svws_nrw.data.gost.DataGostBlockungsdaten.getGZip(DataGostBlockungsdaten.java:352)",
        "  de.svws_nrw.api.server.APIGostKursplanung.lambda$getGostBlockungGZip$4(APIGostKursplanung.java:212)",
        "  de.svws_nrw.data.benutzer.DBBenutzerUtils.runWithTransactionOnErrorSimpleResponse(DBBenutzerUtils.java:370)",
        "  de.svws_nrw.api.server.APIGostKursplanung.getGostBlockungGZip(APIGostKursplanung.java:212)",
        "  java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)",
        "  java.base/java.lang.reflect.Method.invoke(Method.java:580)",
        "  org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:154)",
        "  org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:118)",
        "  org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:560)",
        "  org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:452)",
        "  org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:413)",
        "  org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)",
        "  org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:415)",
        "  org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:378)",
        "  org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:356)",
        "  org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:70)",
        "  org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:429)",
        "  org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:240)",
        "  org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:154)",
        "  org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:321)",
        "  org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:157)",
        "  org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:229)",
        "  org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:222)",
        "  org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:55)",
        "  org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)",
        "  jakarta.servlet.http.HttpServlet.service(HttpServlet.java:723)",
        "  org.eclipse.jetty.ee10.servlet.ServletHolder.handle(ServletHolder.java:736)",
        "  org.eclipse.jetty.ee10.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1614)",
        "  org.eclipse.jetty.ee10.servlet.ServletHandler$MappedServlet.handle(ServletHandler.java:1547)",
        "  org.eclipse.jetty.ee10.servlet.ServletChannel.dispatch(ServletChannel.java:824)",
        "  org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:436)",
        "  org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:464)",
        "  org.eclipse.jetty.ee10.servlet.SessionHandler.handle(SessionHandler.java:717)",
        "  org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1060)",
        "  org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:151)",
        "  org.eclipse.jetty.server.Handler$Sequence.handle(Handler.java:805)",
        "  org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:575)",
        "  org.eclipse.jetty.server.Server.handle(Server.java:182)",
        "  org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:662)",
        "  org.eclipse.jetty.util.thread.Invocable$ReadyTask.run(Invocable.java:105)",
        "  org.eclipse.jetty.http2.server.internal.HttpStreamOverHTTP2$1.run(HttpStreamOverHTTP2.java:135)",
        "  org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:478)",
        "  org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:441)",
        "  org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)",
        "  org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:195)",
        "  org.eclipse.jetty.http2.HTTP2Connection.produce(HTTP2Connection.java:210)",
        "  org.eclipse.jetty.http2.HTTP2Connection.onFillable(HTTP2Connection.java:157)",
        "  org.eclipse.jetty.http2.HTTP2Connection$FillableCallback.succeeded(HTTP2Connection.java:442)",
        "  org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)",
        "  org.eclipse.jetty.io.ssl.SslConnection$SslEndPoint.onFillable(SslConnection.java:575)",
        "  org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:390)",
        "  org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:150)",
        "  org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:99)",
        "  org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)",
        "  org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:478)",
        "  org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:441)",
        "  org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:293)",
        "  org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:201)",
        "  org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:311)",
        "  org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:979)",
        "  org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1209)",
        "  org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1164)",
        "  java.base/java.lang.Thread.run(Thread.java:1583)"
      ]
    }
  }
}

**Comment by ThomasBachran** [comment]
Ok. Jetzt ist das doppelt zum transferierten Issue #306 ... Ich schließe diese Variante hier.
