### ISSUE TITLE
Anzeigeproblem: "Nur sichtbare" zeigt auch "Nicht sichtbare" Lehrkraft an

### ISSUE THREAD

**Issue by WJohannsen** [SVWS-NRW/SVWS-Server#308]
Die (nach Nachname) alphabetisch erste Lehrkraft in unserer Datenbank ist auf "nicht sichtbar" gestellt. Dennoch wird sie angezeigt, obwohl der Filter auf "Nur sichtbare" gestellt ist.

Version: 1.0.1 dcaa57cd620efd8832b036b2f295dd88d24fb3b6

![Screenshot 2024-11-21 112349](https://github.com/user-attachments/assets/ded0b3bc-0d14-4977-b1fe-3b2caafbb289)

**Comment by ThomasBachran** [comment]
@WJohannsen : Vielen Dank für die Rückmeldung. Der Fehler wird im nächsten Release behoben sein.
