### ISSUE TITLE
Benutzerrechte Katalogeinträge ansehen.

### ISSUE THREAD

**Issue by FPfotenhauer** [SVWS-NRW/SVWS-Server#309]
https://github.com/SVWS-NRW/Schild3-BetaTest/issues/1198

Wenn ich das Recht "Katalogdaten ansehen" bei einem User entferne, kann dieser User sich gar nicht mehr anmelden, weil er dann einfach keinen Katalog mehr sehen darf.

Das macht keinen Sinn. Dieses recht war ursprünglich dazu gedacht, dass diese user die Kataloge nicht sehen dürfen.
In der API müssen sie trotzdem zur Verfügung stehen.

Im SVWS-WebClient führt dies sogar dazu, das Stammdaten nicht gelesen werden können.
Dies bezieht sich auf die Schuldaten. Da ergibt sich das gleiche Problem.

![Bildschirmfoto vom 2024-11-24 14-16-50](https://github.com/user-attachments/assets/6460af9e-51c7-43de-860c-1f11c2d4bfa6)

**Comment by ThomasBachran** [comment]
@FPfotenhauer : Ich habe die Berechtigung für den lesenden Zugriff auf diesen Katalog reduziert. Bei mir tritt der Fehler nicht mehr auf. Kannst du das bei dir bitte prüfen und dieses Issue ggf. schließen.
