### ISSUE TITLE
Eintragungen D und M in Q-Phase

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/SVWS-Server#31]
Eintragungen für die Fächer D und M in der Q-Phase lassen sich nicht löschen.
Einereits logisch, da D und M grundsätzlich belegt sein müssen, dann dürfte es in EF aber auch nicht zu löschen sein.
Andererseits sehr irritierend, da man gerne auch mal wieder alles rückgängig machen möchte.
Ich finde die Funktion (falls sie beabsichtigt war) unnötig und störend.

**Comment by FPfotenhauer** [comment]
Wenn es hier noch eine Rückmeldung gibt, dann bitte einfach wieder öffnen.
