### ISSUE TITLE
SVWS-Server 1.0.1: Problem aus Issue 258 besteht noch: Admin-Seite listet weiterhin keine verwaisten Einträge aus der svwsconfig.json auf

### ISSUE THREAD

**Issue by T-Hagel-SK** [SVWS-NRW/SVWS-Server#310]
Hallo zusammen,

nach ein bisschen Abwarten sind wir wieder bei Tests mit Schild(zentral)3 dabei.

Mittlerweile läuft bei uns auch der PC-Client erstmalig, Dazu komme ich später sicherlich gesondert. Mit [Issue 258]( https://github.com/SVWS-NRW/SVWS-Server/issues/258) hatte ich gemeldet, dass verwaiste Einträge aus der svwsconfig.json-Datei nicht über die Admin-Seite (aber auch nicht über das von Ribeka bereitgestellte Tool) als solche angezeigt werden.

Nun, das ist immer noch der Fall. Es führt u.a. dazu, dass in der Datenbank-Schema-Liste auf der SVWS-Serverstartseite alle Einträge aus der svwsconfig.json-Datei aufgelistet werden. Inkl. derer, die auf dem DB-Server nicht mehr existieren.

In der [Benutzeranleitung](https://svws-nrw.github.io/SVWS-Dokumentation/client/anleitungen_allgemein/anmeldung/) steht dazu unter dem 3. Punkt:
"3 DB-Schema
Hier werden alle gültigen Schemata angezeigt, die auf dem verbundenen Server zur Verfügung stehen.". 

So sollte es sein, ist aber derzeit falsch, da auch die verwaisten Einträgen aufgeführt werden.

Es wäre m.E. hilfreich, wenn auf der Admin-Seite eine Option bestünde, nicht nur die vorhandenen DB-Schemas aufzulisten, sondern auch die Einträge der besagten svwsconfig.json-Datei. Ideal wäre es, wenn in der Auflistung zu erkennen wäre, ob die jeweiligen Datenbanken existieren oder nicht. Wenn nicht, sollte die Möglichkeit bestehen, diese über die Admin-Seite aus der svwsconfig.json-Datei zu entfernen.

Einen ähnlich gelagerten Vorschlag mache ich natürlich auch bei Ribeka, da bei SchildZentral eher das Arbeiten über das sog. Schemaverwaltungsprogramm laufen werden, statt über die Adminseite. Auch hier werden nur die tatsächlichen DB-Einträge auf der Datenbank angezeigt und nicht was noch in der Config-Datei herumwuselt.

Nicht alle Beteiligten werden auch immer einen direkten Draht auf die Config-Datei haben, um sie aufzuräumen oder zu editieren.

Schöne Grüße
Thomas Hagel

Stadt Köln
Fachanwendungsbetreuung / Schild3-Koordination

**Comment by kroerig** [comment]
Wie wurden denn die Datenbanken gelöscht? Einfach auf dem MariaDB-Server? Dann bekommt der SVWS das erst bei einem Neustart mit und würde das Schema deaktivieren. Sind das noch Reste aus alten Tests?

Was passiert, wenn Sie versuchen das Schema über die API `/api/privileged/config/schema/{schema}/remove` zu entfernen?

**Comment by T-Hagel-SK** [comment]
Das liefert mir:
curl -X 'POST' \
  'https://svws-server.xxx.de:8443/api/privileged/config/schema/S3_Test/remove' \
  -H 'accept: */*' \
  -d ''

Request URL
https://svws-server.xxx.de:8443/api/privileged/config/schema/S3_Test/remove

Server response
403 | Error: response status is 403Response headers content-length: 0  server: Jetty(12.0.14)

Folglich ändert sich auch in der Config-Datei nichts.

Ja, die Einträge in der Config-Datei sind noch Reste von vergangenen Tests. Hierbei bin ich immer so vorgegangen, dass ich auf der Datenbankseite alle Tabellen gelöscht und von vorne begonnen habe. Von vorne meint hier, sowohl das Anlegen von Datenbanken über die Server-Adminseite, als auch über das Schemaverwaltungsprogramm von Ribeka.

Das Löschen der Datenbanken mache ich über die SQL-Workbench.

**Comment by kroerig** [comment]
403 sagt: Das Schema darf nicht gelöscht werden.

Für diese API ist SQL-Root Zugriff erforderlich.


> Das Löschen der Datenbanken mache ich über die SQL-Workbench.

Das Prozess sieht vor, dass über den Admin-Client zu machen, denn der ist so programmiert, dass er erst die DB löscht, und wenn das erfolgreich war auch den Eintrag in der Config.

Also jetzt entweder die Config per Hand anpassen oder die Datenbanken zumindest mal als leere Hülle wieder anlegen und dann über den Admin-Client löschen.

**Comment by T-Hagel-SK** [comment]
> 403 sagt: Das Schema darf nicht gelöscht werden.
> 
> Für diese API ist SQL-Root Zugriff erforderlich.
> 
Ich war hier mit Rootrechten drauf,

Aber, der weg über Swagger war ja auch nicht das, was ich angefragt hatte, sondern eine Möglichkeit, über die Admin-Seite nicht nur die Schemas zu sehen/verwalten, sondern auch diese Configdatei.

**Comment by kroerig** [comment]
Die Configdatei wird ja über den Admin-Client verwaltet. In älteren Versionen waren da aber noch ein paar Bugs und so muss man jetzt halt einmal händisch nachhelfen oder zurück auf Los gehen.

**Comment by T-Hagel-SK** [comment]
Sie wollen es nicht verstehen, oder ?

Es geht mir um eine grundsätzliche Funktionaliät, nicht darum, dass ich jetzt manuell was auf dem Server anpasse. Nicht jeder wird am Ende Zugriff auf die Config-Datei haben. Und so viel Programmieraufwand kann diese kleine Sache für eine ADMIN-Seite ja jetzt nicht sein.

**Comment by hmt** [comment]
Bitte auf den Umgangston hier in den Issues achten, @T-Hagel-SK .

Die Bemerkungen von @kroerig sind zutreffend. Ich schließe dieses Issue daher.

**Comment by T-Hagel-SK** [comment]
Ja, klar. Schließt doch einfach weiter offene Fragen ....

**Comment by T-Hagel-SK** [comment]
Das Problem besteht in 1.0.2 immer noch ...

Verweiste Einträge werden auf der Startseite weiterhin zur Auswahl gestellt ...
Verweiste Einträge werden nicht als solche auf der Admin-Seite angezeigt...

**Comment by kroerig** [comment]
Die werden auch da bleiben, wenn Sie sie nicht manuell aus der Datei entfernen oder die komplette Instanz löschen und neu aufsetzen. Siehe https://github.com/SVWS-NRW/SVWS-Server/issues/310#issuecomment-2507855917

**Comment by T-Hagel-SK** [comment]
Ja ich fürchte, das bleibt so.

Ich bleibe dabei ... von einer Adminseite erwarte ich ein bisschen mehr als das was bislang vorliegt .... sie muss auch durch "normale" Schild-Administratoren bedienbar sein, ohne dass diese jetzt noch in Linuxeditoren abtauchen müssen.

Wie gesagt, nicht alle, die SVWS-Server betreuen sollen, werden einen schreibenden Zugriff auf diese Config-Datei erhalten.

Solange das MSB den SVWS-Server jedoch unverändert lässt und darauf pocht, dass nur diese eine Version zum Einsatz kommen darf, wird es Umgebungen geben, wo die Server von Linux-Experten betreut werden, die den Zugriff auf das Schreiben via VI verhindern...

Abhilfe: ein SVWS-Server mit der Option, diesen auch in größeren Umgebungen mit externen Linux- und Datenbank-Expoerten zu ermöglichen.  Aber das ist ja nicht im Focus des MSB

**Comment by kroerig** [comment]
> Wie gesagt, nicht alle, die SVWS-Server betreuen sollen, werden einen schreibenden Zugriff auf diese Config-Datei erhalten.

Das brauchen sie nicht. Das sind jetzt Reste einer vorherigen Installation. Und wir befinden uns noch immer in einer Testphase mit einer Beta-Version. Da kann es durchaus mal vorkommen, dass man Fehler in älternen Versionen manuell nacharbeiten muss.

**Comment by kroerig** [comment]
Ich verstehe das Anliegen, und zitiere mal die Gruppe "Alte Bekannte": "Wenn das die Lösung ist, dann will ich mein Problem zurück!"

> Wo ist das verflixte Problem, eine ADMIN-Seite bereitzustellen, die einen ADMINISTRATOR bei seiner Arbeit unterstüzt ohne ihn ständig über Linux-Tools in Dateien fummeln zu lassen ?

Das ist kein Problem, sondern schlicht nicht erforderlich, weil dieser Fall hier, wenn man sich an die Anleitung hält, in aktuellen Versionen nicht mehr auftreten sollte.

> Ja, es sind Reste einer vorherigen Installation. Ja, ich lasse sie bewusst darin stehen (u.a. weil ich für jede Änderung in dieser Config-Datei ein Ticket bei unseren Linuxkollegen eröffnen muss). Und um zu testen, ob es irgendwann mal eine Version gibt, die sich mit diesen Resten beschäftigt oder eben nicht...

Die Version wird vermutlich nicht so schnell kommen, weil der verursachende Fehler behoben ist. Wenn man das Porzelan zerschlägt (die Datenbanken einfach löscht), dann muss man auch Scherben zusammenkehren (die Konfig aufräumen). Das ist bei anderer Software nicht anders.

Müssen Sie für die Neuanlage von Datenbanken auch ein Ticket eröffnen? Sonst erstellen Sie einfach wieder die fehlenden DBs und Benutzer, spielen einen aktuellen Dump eines SchILD3-Schemas ein und dann sollten Sie die Einträge erfolgreich über den Admin löschen können.

**Comment by T-Hagel-SK** [comment]
".. nicht mehr auftauchen sollte .." sagt schon alles.

"Wenn man das Porzelan zerschlägt (die Datenbanken einfach löscht), dann muss man auch Scherben zusammenkehren (die Konfig aufräumen). "

Man muss die Konfig manuell aufräumen. Ein ordentliches Admin-Tool hingegen hilft dabei.

Wie gut, dass das Ticket schon geschlossen wurde ... es hat keinen Sinn mit Ihnen darüber zu reden, was ich mir unter einem Admin-Tool vorstelle ... Da gehen Erwartungen, Vorstellungen einfach zu weit auseinander.
