### ISSUE TITLE
SVWS-Server 1.0.1: Fotoaufnahme aus Webcam und Bildhochladen klappt nur bei Lehrern nicht 

### ISSUE THREAD

**Issue by T-Hagel-SK** [SVWS-NRW/SVWS-Server#311]
Hallo zusammen,

ich bin durch die Issues 280 und 284 neugierig geworden und bin dankbar, dass das die Fotoverwaltung nun so herrlich unkompliziert geworden ist. 

Allerdings klappt die Aufnahme über die Webcam und das Hochladen von Bildern nur für die Schülerfotos. Bei den Lehrern klappt -bei uns- weder das Speichern über die Webcam noch über das Hochladen. Im Falle der Webcam wird zwar ein Bild erzeugt (Standbild) und der Button zum Speichern angezeigt. Jedoch wird nach Klick auf diesen Button nichts gemacht. Das Bild wird einfach nicht gespeichert. 

Ähnlich verhält es sich beim Hinzufügen einer Bilddatei. Egal in welchem Dateiformat ich das ausprobiere ... JPG, PNG, WEBP ... 

Die gleichen Dateien, die testweise bei den Schülern hinzufügen kann, verweigern bei den Lehrern den Dienst.

Schöne Grüße
Thomas Hagel 

Stadt Köln
Fachanwendungsbetreuung

**Comment by kroerig** [comment]
Ja, das kann ich hier auch nachstellen.

Fehlermeldung:

```json
{
  "env": {
    "mode": "dev",
    "version": "1.0.1",
    "commit": "dcaa57cd620efd8832b036b2f295dd88d24fb3b6"
  },
  "error": {
    "id": 1,
    "name": "API-Fehler: Dieser Fehler wird durch eine fehlerhafte Kommunikation mit dem Server verursacht. In der Regel bedeutet das, dass die verschickten Daten nicht den Vorgaben entsprechen.",
    "message": "Fetch failed for PATCH: /db/svws-leibniz-test/schueler/6924/stammdaten",
    "stack": [
      "Rn@https://schild3:8443/assets/index.js:22:290855",
      "patchTextBased@https://schild3:8443/assets/index.js:22:294895",
      ""
    ],
    "log": null
  }
}
```

**Comment by T-Hagel-SK** [comment]
Ich habe mir mit den Fotos gerade mal auf dem PC-Client 3.1.1.29 angeschaut...

Da gibt es nur bei den Lehrern die Möglichkeit vorhandene Bilddateien zu speichern, aber nicht mit der Webcam einzufangen. Bei den Schülern besteht gar keine Möglichkeit Bilder auszuwählen.

By the way, wo kann ich zum PC-Client Issues aufmachen ?

**Comment by kroerig** [comment]
> By the way, wo kann ich zum PC-Client Issues aufmachen ?

Hier: https://github.com/SVWS-NRW/Schild3-BetaTest/issues

**Comment by T-Hagel-SK** [comment]
> > By the way, wo kann ich zum PC-Client Issues aufmachen ?
> 
> Hier: https://github.com/SVWS-NRW/Schild3-BetaTest/issues (Aber nur, wenn es um den SchILD3 NRW Client geht. Den Client für SchildZentral supportet Ribeka.

Ok. Das ist aber ... na gut ... 
Dann hör ich hier im NRW-Client auf zu kommentieren

**Comment by hmt** [comment]
Moment, das Issue ist hier richtig. Der Web-Client ist Teil des SVWS-Server, ebenso die Laufbahnplanung und der Admin-Client. Im Prinzip alles, was im Login-Fenster **SVWS NRW** anzeigt, gehört hierhin.

**Comment by hmt** [comment]
Danke für das Issue, in der nächsten Version können auch bei Lehrkräften Bilder entweder per Webcam oder Upload hinzugefügt werden. Eine fehlende Webcam wird dann auch erkannt und nicht als Option angeboten.
