### ISSUE TITLE
Fehlermeldung in Lernabschnitte - Allgemein (bei Wiederholer:innen?)

### ISSUE THREAD

**Issue by WJohannsen** [SVWS-NRW/SVWS-Server#312]
Guten Abend, 

beim Durchklicken durch einige SuS erhielt ich immer mal wieder Fehlermeldungen angezeigt:
![Screenshot 2024-12-02 202256](https://github.com/user-attachments/assets/aeda6c7b-0abc-434c-a469-5e919f0ad47e)

Eine erste Gemeinsamtkeit dieser SuS könnte sein, dass es sich um Wiederholer:innen handelt, aber ich kann nicht sicher sagen, ob das der ausschlaggebende Grund ist. 

Hier eine Fehlermeldung im Volltext:
```json
{
  "env": {
    "mode": "stable",
    "version": "1.0.1",
    "commit": "dcaa57cd620efd8832b036b2f295dd88d24fb3b6"
  },
  "error": {
    "id": 8,
    "name": "Fehler : TypeError",
    "message": "B is null",
    "stack": [
      "setup/<@https://localhost/assets/index.js:53:785287",
      "Zf@https://localhost/assets/index.js:14:38",
      "il@https://localhost/assets/index.js:14:111",
      "qy/l.call@https://localhost/assets/index.js:14:33513",
      "oe@https://localhost/assets/index.js:10:15544",
      "Yz@https://localhost/assets/index.js:14:1385",
      "mt@https://localhost/assets/index.js:14:27819",
      "Oe@https://localhost/assets/index.js:14:26672",
      "run@https://localhost/assets/index.js:10:1709",
      "un@https://localhost/assets/index.js:14:26397",
      "Nt@https://localhost/assets/index.js:14:26046",
      "F@https://localhost/assets/index.js:14:22702",
      "Re@https://localhost/assets/index.js:14:25281",
      "we@https://localhost/assets/index.js:14:24611",
      "M@https://localhost/assets/index.js:14:23321",
      "F@https://localhost/assets/index.js:14:22673",
      "Oe@https://localhost/assets/index.js:14:26813",
      "run@https://localhost/assets/index.js:10:1709",
      "un@https://localhost/assets/index.js:14:26397",
      "Nt@https://localhost/assets/index.js:14:26046",
      "F@https://localhost/assets/index.js:14:22702",
      "Oe@https://localhost/assets/index.js:14:26813",
      "run@https://localhost/assets/index.js:10:1709",
      "runIfDirty@https://localhost/assets/index.js:10:2019",
      "Zf@https://localhost/assets/index.js:14:46",
      "qI@https://localhost/assets/index.js:14:1799",
      ""
    ],
    "log": null
  }
}
```

**Comment by FPfotenhauer** [comment]
Können wir uns einmal in Verbindung setzen?
Wir können das hier nicht reproduzieren...

**Comment by WJohannsen** [comment]
Natürlich. Soll ich ein Backup der Datenbank hochladen und )ein paar) betroffene Schüler:innen bennenen?

**Comment by FPfotenhauer** [comment]
Können Sie mir eine Mail senden?
Dann besprechen wir den Weg. Danke!!!

**Comment by WJohannsen** [comment]
OK, es ist wie verhext... 
Bevor ich die Datenbank sichern wollte, habe ich mein Kennwort geändert, um dieses mitzuschicken. Nach dem Ändern des Kennwortes (und der Meldung "wurde erfolgreich geändert") bin ich in eine andere Fehlermeldung gelaufen - vermutlich, weil nun das Kennwort, mit dem ich angemeldet war und das frisch geänderte Kennwort nicht mehr zusammen passen?

Also neu angemeldet - und die Fehlermeldung, die ich gestern Abend hatte und vor fünf Minuten noch reproduzieren konnte, trotz zwischenzeitlicher Ab- und Neuanmeldung am Server, lässt sich tatsächlich nicht mehr reproduzieren. Sorry für die Umstände.

Dafür ist mir in diesem Zusammenhang ein anderes Fehlverhalten in der Benutzerverwaltung aufgefallen, dazu gleich ein neues Issue.
