### ISSUE TITLE
Benutzerverwaltung - Benutzer werden nicht angezeigt

### ISSUE THREAD

**Issue by WJohannsen** [SVWS-NRW/SVWS-Server#313]
Neues Problem...

Wenn ich im SVWS-Client (1.0.1 dcaa57cd620efd8832b036b2f295dd88d24fb3b6, Firefox 133.0 (64-Bit)) als Nutzer mit Admin-Rechten auf Einstellungen klicke, lande ich in der Benutzerverwaltung auf dem ersten Nutzer ohne die Möglichkeit, andere Nutzer zur Bearbeitung auszuwählen:

![grafik](https://github.com/user-attachments/assets/07ba28ad-042d-4f61-a8a0-8fd02493a69c)

Erst nach einem Klick auf "Benutzergruppen" und zurück auf "Benutzer" erscheint die Liste aller Benutzer:

![grafik](https://github.com/user-attachments/assets/128215d0-5052-4762-b4c9-4b9a3be2b44a)

**Comment by ThomasBachran** [comment]
Der Fehler ist bereits bekannt und in unserem Entwicklungszweig behoben. In der künftigen Version 1.0.2 wird er nicht mehr auftauchen.
