### ISSUE TITLE
Beratungsvorlagen werden nicht in die Schülerdatei übernommen

### ISSUE THREAD

**Issue by SchILD-Kloppenburg** [SVWS-NRW/SVWS-Server#314]
Ich habe unter Oberstufe - Allgemeine Vorlagen eine Vorlage zur Beratung erstellt. Dabei habe ich Deutsch und Mathematik schriftlich vorbelegt und Sport mündlich.
Aus dieser Vorlage habe ich einen neuen Abiturjahrgang erstellt.
Aus diesem Abiturjahrgang habe ich unter "Laufbahn" testweise einen Schüler exportiert und eine *.lp-Datei erzeugt. Wenn ich diese im Laufbahnberatungstool hochlade, sind die Vorbelegungen für Deutsch, Mathematik und Sport verschwunden.
SVWS-Server und Beratungstool liegen in der Version1.01 vor.

**Comment by ThomasBachran** [comment]
@SchILD-Kloppenburg : Das Problem vermute ich hier, dass die Vorlage nicht zum Schüler übertragen wurde. Dies kann für alle Schüler über den folgenden Knopf gemacht werden:
![grafik](https://github.com/user-attachments/assets/1fbf036b-81b4-4675-99eb-e142a6c7f790)
Oder bei der Schüler-Laufbahnplanung auch für einzelne Schüler:
![grafik](https://github.com/user-attachments/assets/880ebc07-9a6e-4e9d-9d3f-6cfc5ad14bea)

Danach müssten die Einstellungen der Vorlage auch beim Schüler sichtbar sein. Wenn es immer noch nicht funktioniert, dann bräuchte ich weitere Details, um den Fehler reproduzieren zu könne.

**Comment by SchILD-Kloppenburg** [comment]
Genau das war der "Fehler". Ist somit erledigt.
