### ISSUE TITLE
SVWS-Server 1.0.1: Schüler: Eingaben  / Änderungen werden ohne Rückfrage akzeptiert

### ISSUE THREAD

**Issue by T-Hagel-SK** [SVWS-NRW/SVWS-Server#315]
Hallo zusammen,

mir ist aufgefallen, dass man im Schülermenü einfach in allen Feldern Änderungen vornehmen kann, ohne dass man wie bei Schild2 gefragt wird, ob diese Änderungen gewollt sind. So lassen sich z.B. Namen, Geburtstag, Geschlecht, Staatsangehörigkeit, Konfession, Adresse, Mail, Telefonnummer, Status, etc. ungefragt, bzw. unkommentiert ändern.

Im Falle von Adressänderungen fragt Schild2 ob diese auch für die Erziehungsberechtigten gelten und ebenfalls angepasst werden sollen . Etc.

Ist eine Abfrage gegen versehentliche Änderungen noch in Planung ?

Schöne Grüße
Thomas Hagel

Stadt Köln
Fachanwendungsbetreuung

**Comment by FPfotenhauer** [comment]
Wir sind hierzu in einem Austausch mit IT.NRW.
Solche Prüfungen und Warnungen werden wir zusammen mit den Validatoren nach den Vorgaben von IT.NRW umsetzen.
