### ISSUE TITLE
SVWS Server 1.02 Funktionsbezogen Noten ändern

### ISSUE THREAD

**Issue by Zicl122** [SVWS-NRW/SVWS-Server#316]
Wenn ich als Lehrkraft in den Benutzereinstellungen "Schüler-Leistungsdaten", "Funktionsbezogen ändern" eingeschaltet habe und dann als diese Lehrkraft Noten aus vergangenen SJ ändere, erfolgt eine Fehlermeldung. Als Admin ist das problemlos möglich:
```json
{
  "env": {
    "mode": "beta",
    "version": "1.0.2-SNAPSHOT",
    "commit": "f8be2379bffdb26cf6eb1a23b369103166a0c08d"
  },
  "error": {
    "id": 1,
    "name": "API-Fehler: Dieser Fehler wird durch eine fehlerhafte Kommunikation mit dem Server verursacht. In der Regel bedeutet das, dass die verschickten Daten nicht den Vorgaben entsprechen.",
    "message": "Fetch failed for PATCH: /db/GymAbiLite/schueler/leistungsdaten/358377",
    "stack": [
      "Gn@https://stable.svws-nrw.de/assets/index.js:22:294082",
      "@https://stable.svws-nrw.de/assets/index.js:22:298123"
    ],
    "log": null
  }
}
```

**Comment by ThomasBachran** [comment]
@Zicl122 : Welche Funktion hatte der Benutzer denn in Bezug auf die Leistungsdaten? War er dort Klassenlehrer oder Fachlehrer oder Abteilungsleiter?

**Comment by Zicl122** [comment]
Es geht um Lehrer BISZ. Er ist sowohl Klassenlehrer der 9a und EF Beratungslehrer. Bei beiden Stufen kann er keine Noten aus den vergangenen Jahren ändern.  Berechtigungen - siehe Foto

<img width="523" alt="Bildschirmfoto 2024-12-06 um 08 16 49" src="https://github.com/user-attachments/assets/1cd53451-97d9-4a4f-8a7d-e290d6e182d0">
<img width="1285" alt="Bildschirmfoto 2024-12-06 um 08 17 42" src="https://github.com/user-attachments/assets/11932121-604b-4313-9c10-d7cff4dc4361">

**Comment by ThomasBachran** [comment]
OK. Dann ist das Problem, dass vergangene Abschnitte nicht mit einfachen Rechten nachträglich bearbeitet/korrigiert werden können. Die API hat das korrekt umgesetzt. Im Client ist hier noch ein Bug.

**Comment by ThomasBachran** [comment]
@Zicl122 : Im dev-Branch ist jetzt ein Bugfix zu dieser Sache enthalten. Kannst du bitte prüfen, ob der deinen Fall auch korrekt berücksichtigt. Wenn ja, dann schließ das Issue bitte.
