### ISSUE TITLE
Abschaltung der Diskussionen ... warum ?

### ISSUE THREAD

**Issue by T-Hagel-SK** [SVWS-NRW/SVWS-Server#317]
Hallo zusammen,
wie ich feststelle, wurde der Bereich für Diskussionen abgestellt. Zumindest erscheint beim Aufruf alter Diskussionslinks nun die Fehlermeldung 404. 

Werden die dort geführten Diskussionen an anderer Stelle fortgeführt oder entfallen sie für das Projekt nun ganz ?

Schöne Grüße
Thomas Hagel

Stadt Köln
Fachanwendungsbetreuung

**Comment by T-Hagel-SK** [comment]
Welche SVWS-Forum ?

**Comment by hmt** [comment]
Ja, dieses hier: https://schulverwaltungsinfos.nrw.de/svws/forum/viewforum.php?f=87
