### ISSUE TITLE
Schiebeschalter "Nur sichtbare" springt jedes Mal auf "aus" zurück

### ISSUE THREAD

**Issue by WJohannsen** [SVWS-NRW/SVWS-Server#319]
Hallo allerseits,

der Schiebeschalter "Nur sichtbare" bei Lehrkräften und Kursen springt jedes Mal auf "Aus" zurück, sodass alle Lehrkräfte und Kurse angezeigt werden; bei Klassen gibt es diesen Schiebeschalter erst gar nicht. 

Gewünschtes Verhalten (aus meiner Sicht) wäre das Beibehalten des letzten Status, alternativ "Nur sichtbare" als Standardeinstellung (die man aktiv ausschalten müsste, wenn man alle sehen möchte).

[Edit] Version: 1.0.2 a70d7e9f1519e5a49acab5106e94da6f62f95f16

**Comment by hmt** [comment]
ist mit dem eingehenden Commit drin und damit in der nächsten Version verfügbar.
