### ISSUE TITLE
Gruppenexport lp-Dateien

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/SVWS-Server#32]
Um so langsam mal realitätsnah zu testen, wäre ein Gruppenexport der lp-Dateien wünschenswert.
Ist das noch zu aufwendig oder bewusst noch nicht vorgesehen oder einfach nur noch nicht umgesetzt?
Würde das Testen erheblich vereinfachen.

**Comment by ThomasBachran** [comment]
Das Dateiformat ist noch nicht fertig definiert. Daher wird es noch etwas dauern...
