### ISSUE TITLE
Unterrichtsfächer "Auf Zeugnis"

### ISSUE THREAD

**Issue by WJohannsen** [SVWS-NRW/SVWS-Server#320]
Guten Abend,

im Vergleich SchILD2 - SchILD3 - SVWS-Server fällt mit einer frisch migrierten Datenbank auf:

SchILD2: "Auf Zeugnis" gesetzt, Zeugnisbezeichnung und Überweisungszeugnisbezeichnung gesetzt.
![grafik](https://github.com/user-attachments/assets/ee6babe9-2187-4a81-a069-0bf47be496d2)

SchILD3: "Auf Zeugnis" ist in den Details nicht zu finden (nur in der Übersicht), Bezeichnungen sind beide migriert.
![grafik](https://github.com/user-attachments/assets/b25a8f5d-dae0-485a-b217-83704b618c82)

SVWS-Server: "Auf Zeugnis" ist bei allen Fächern deaktiviert, die Zeugnisbezeichnungen fehlen. Haken "Nachprüfung erlaubt" fehlt, ebenso "Berücksichtigen beim Holen von abgeschlossenen Fächern". 
![grafik](https://github.com/user-attachments/assets/be982276-8a7b-488b-bab6-167913d66bf8)

**Comment by hmt** [comment]
@ThomasBachran die Daten sollten korrekt angezeigt werden:
```vue
				<svws-ui-checkbox :model-value="manager().daten().aufZeugnis" @update:model-value="value => patch({ aufZeugnis: value === true ? true : false })">
					Auf Zeugnis
				</svws-ui-checkbox>
				<svws-ui-text-input placeholder="Bezeichnung (Zeugnis)" :model-value="manager().daten().bezeichnungZeugnis"
					@change="bezeichnungZeugnis => patch({ bezeichnungZeugnis: bezeichnungZeugnis ?? undefined })" />
				<svws-ui-text-input placeholder="Bezeichnung (Überweisungszeugnis)" :model-value="manager().daten().bezeichnungUeberweisungszeugnis"
					@change="bezeichnungUeberweisungszeugnis => patch({ bezeichnungUeberweisungszeugnis: bezeichnungUeberweisungszeugnis ?? undefined })" />
```

Die Daten werden nicht im Schema persistiert bzw. nicht korrekt ausgelesen: 
<img width="328" alt="image" src="https://github.com/user-attachments/assets/283e456e-6eea-424a-8bae-5a6a540ac707">
Nach Speichern von `true` kommt trotzdem ein `false`

**Comment by ThomasBachran** [comment]
@hmt : Die Daten wurden bisher nicht von der API übermittelt. Kannst du bitte prüfen, ob du die Daten im dev-Branch jetzt bekommst?

**Comment by hmt** [comment]
ist drin
