### ISSUE TITLE
Wert für Feststellungsprüfung wird in der DB (Tabelle schuelerSprachenprüfung) nicht gesetzt

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/SVWS-Server#322]
Tabelle: schuelerSprachenprüfung/IstFeststellungsprüfung

![image](https://github.com/user-attachments/assets/6f8fef2d-3409-4b38-b4d5-fcc735f80475)

**Comment by ThomasBachran** [comment]
Das Problem liegt hier im Client. Dieser legt Feststellungsprüfungen nicht mit dem Flag and und unterscheidet nur anhand der Spalte istHSUPruefung. Ich habe das Problem im dev-Branch behoben. Die Spalte istFeststellungspruefung ist hier eigentich redundant.

**Comment by AnneSchueller** [comment]
Rückfrage: Soll in Schild3 nun ebenfalls auf "nicht istHSUPruefung" geprüft werden?
Im dev-Branch wird der Wert für istFeststellungspruefung nach wie vor nicht gesetzt.

**Comment by AnneSchueller** [comment]
Ich hatte ein build vergessen.... funktioniert mit der aktuellen Version
