### ISSUE TITLE
Fragen zur Dokumentation, bzw. Anleitungen der Admin-Seite (aktuell Infos zum privilegierten Benutzer gesucht) 

### ISSUE THREAD

**Issue by T-Hagel-SK** [SVWS-NRW/SVWS-Server#324]
Hallo zusammen,
wir haben nun auf den SVWS-Server 1.0.2 aktualisiert und ich bin in Bezug auf Informationen zum "Privilegierten Benutzer" - neudeutsch - lost.

Von Ribeka war zu erfahren, dass nun auf dem SVWS-Server ein Privilegierter Benutzer Pflicht sei und in der svwsconfig.json-Datei einzutragen sei. Dazu hieß es _"Für den Aufruf bestimmter Funktionen des SVWS-Servers wird nun explizit der privilegierte Benutzer benötigt. Das betrifft z.B. das Registrieren eines Datenbankschemas in der Datei svwsconfig.json. Das gleiche trifft auch für das Entfernen eines Schemas aus der Konfiguration zu."_ 

Dieser Benutzer wurde ja zuletzt kurz vor der oder zur 1.0.0 erst eingeführt. 

Aber ich finde nirgendwo eine Anleitung, wie dieser "privilegierte" Benutzer einzurichten ist, was er konkret macht, was nicht, bzw. wann er genau zu welchem Zweck eingeführt wurde. Ob es einer sein kann oder mehrere ?

Es fehlt hierzu und zu allem anderen eine Hilfeseite, die aus der Admin-Seite heraus aufgerufen werden kann. Anleitungen und Wikis gibt es zu Hauf, nur keine geht hier konkret auf die Admin-Seite ein. Man muss sich die Infos über neue Funktionen/Möglichkeiten aus den diversen Seiten der Releases zusammensuchen.  

Von einer Admin-Seite erwarte, bzw. erhofffe, ich mir allerdings auch, dass diese erkennt, ob alle benötigten Benutzer existieren, bzw. wenn sie fehlen, eine Möglichkeit, diese über die Admin-Seite mit entsprechenden Rechten anzulegen. Die Adminseite sollte in der Lage sein, zu erkennen, ob Datenbank-Benutzer und Datenbanken, die in der svwsconfig-Datei stehen, auf der Datenbank tatsächlich existieren oder nicht. Wenn nicht, sollte die Möglichkeit mit entsprechenden (Root)-Rechten bestehen, das über die Admin-Seite zu korrigieren. Und zwar ohne, dass man manuell die Config-Datei in einem Texteditor bearbeitet. 

Im Falle der nun aktuellen SVWS-Serverversion 1.0.2 fehlt z.B. ein Eintrag zum privilegierten Benutzer, aber die Admin-Seite "meckert" nicht, moniert nicht und bietet auch keine Option an, diesen fehlenden Umstand zu beheben. 

Die Adminseite ist weiterhin relativ spartanisch, funktionell aufgebaut. Sie setzt viel internes Wissen voraus. Neue Mitarbeiter kann man nicht einfach auf die Seite "loslassen".

Wo habe ich bislang nachgeschaut:

- https://schulverwaltungsinfos.nrw.de/svws/wiki/index.php?title=Hinweise_f%C3%BCr_IT-Dienstleister#Nutzer_und_Kennw%C3%B6rter
  -> geht zwar auf "Nutzer und Kennwörter" ein, listet dort aber nur "MariaDB-root", "Schema-Admin" und "Schema-Nutzer" auf

- https://doku.svws-nrw.de/deployment/IT-Umgebungen/
  auch nicht in den dortigen FAQs

- https://doku.svws-nrw.de/deployment/Einrichtung/
  -> listet diesen (und ggf. andere neue ?) Paramter nicht auf

- https://doku.svws-nrw.de/deployment/Einrichtung/#admin-client-web-applikation-zur-verwaltung-von-datenbank-schemata
  -> ebenfalls keine Hinweise auf diesen "privilegierten" Benutzer, lediglich zu den Symbolen, die man als Root-Benutzer angezeigt bekommt

- https://schulverwaltungsinfos.nrw.de/svws/wiki/index.php?title=Schnellinstallation_SVWS-Server_und_SchILD-NRW_3
  -> keine Infos zu den benötigten Benutzern 

- https://schulverwaltungsinfos.nrw.de/svws/wiki/index.php?title=Installation_SVWS-Server_und_SchILD-NRW_3
  -> keine Infos zu den benötigten Benutzern 

- https://schulverwaltungsinfos.nrw.de/svws/wiki/index.php?title=Installation_SVWS-Server_unter_Linux_(Installation)
  -> keine Infos zu den benötigten Benutzern 

- https://schulverwaltungsinfos.nrw.de/svws/wiki/index.php?title=Troubleshooting_Installation
  -> keine Infos zu den benötigten Benutzern 

- https://schulverwaltungsinfos.nrw.de/svws/wiki/index.php?title=FAQ
  ->> Geht zwar auf Benutzerunterschiede ein, listet aber nur "Root-Benutzer", "Datenbank-Benutzer" und "SchILD-NRW3-Benutzer" auf

- https://github.com/SVWS-NRW/SVWS-DB-Scripte/tree/master/current
  -> Endet bei Version 19 vor 5 Monaten

- Im Linuxinstaller -> svws\conf\svwsconfig-template.json 
 Selbst im Template steht nichts von dem privilegierten Benutzer

Daher die Frage und Bitte, die Adminseite um entsprechende Hilfeseiten und Releasenotes zu erweitern (ohne, dass man sich auf externen/weiteren Webseiten erst durch zig Anleitungen oder Issues klicken muss). Bitte dabei auch davon ausgehen, dass nicht alle Schild3-Admins auch schreibenden Zugriff auf die svwsconfig-Datei haben. Nicht alle Linuxadmins werden allen Schild-Admins volle Schreibrechte auf den Server geben wollen... das gilt insbesondere für Umgebungen, in denen Linuxserver von eigenen Abteilungen administriert werden, wie z.B. in Rechenzentren oder bei IT-Dienstleistern. 

Schöne Grüße
Thomas Hagel

Stadt Köln
Fachanwendungssupport / Schild3-Tester seit Feb 2024

**Comment by kroerig** [comment]
Kann es sein, dass hier einfach zwei Begriffe für ein und dasselbe genutzt werden?
Wenn vom einem "privileged user" die Rede ist, dann meint das einen Benutzter mit erhöhten Rechten. Unter Windows ist das i.d.R. der Administrator-Account, unter Linux der root- Benutzer.

Gleiches gilt auch für MariaDB. Hier ist der priviligierte Benutzer ein Benutzer, der Admin-Funktionen ausführen darf.

Beim SVWS ist das dann ein Benutzer, der das Recht hat Funktionen unter `/api/pivileged` zu benutzen. Also Admin in SchILD ist. Wobei SchILD Zentral hier wieder eine Sonderrolle braucht, weil es technisch pro Schule einen oder mehrere Admins in SchILD geben kann, die aber natürliche keine priviligierten Funktionen des SVWS ausführen dürfen.

Ob ein Benutzer diese entspechenden Rechte besitzt, lässt sich über den Endpunkt `/api/privileged/user/isprivileged` abfragen.

**Comment by T-Hagel-SK** [comment]
Die Fragen waren eigentlich:
- wo ist das alles beschrieben ?
- wie ist der privilegierte Benutzer in der Config-Datei einzutragen ?

**Comment by kroerig** [comment]
Im Handbuch von SchILD Zentral, denn das normale SchILD NRW braucht diese Funktion nicht.

**Comment by T-Hagel-SK** [comment]
> Im Handbuch von SchILD Zentral, denn das normale SchILD NRW braucht diese Funktion nicht.

Das verstehe ich nicht. Wenn Schild-NRW diese Funktion nicht braucht, wieso gibt dann die oben genannte API ?

**Comment by FPfotenhauer** [comment]
Es wurde zwar schon ein priviligierter Nutzer in der svwsconfig.json angelegt, jedoch wurden zu diesem Nutzer noch keinerlei Funktionen programmiert. Dies ist für einen späteren Zeitpunkt geplant.

Aus diesem Grund findet man auch noch keine Dokumentation zu diesem Feature.

**Comment by T-Hagel-SK** [comment]
Es macht immer weniger Spaß hier irgendwas zu melden ...

Es werden Fragen gestellt und Issues dann ergebnisoffen geschlossen ... 

Wo würde man denn diese Informationen irgendwann finden ?

Wenn der Nutzer noch keine Funktionen zugewiesen bekommen hat, welche waren denn angedacht ?
Was ist mit späterem Zeitpunkt gemeint ?
