### ISSUE TITLE
laufbahnplanung.svws-nrw.de

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/SVWS-Server#33]
Steht dieses LuPO-Tool (übrigens groooßartig!!!!) schon als (beta-)Installation für eigene Server zur Verfügung?

**Comment by ThomasBachran** [comment]
Zur Zeit noch nicht. Hier sind noch Anpassungen in nächster Zeit geplant. Sobald die umgesetzt sind, werden wir dieses im jeweils aktuellen Release mit zur Verfügung stellen.
