### ISSUE TITLE
Migration Windows 0.8.1 Fehler 500

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/SVWS-Server#34]
Version 0.8.1:
Unter Windows klappt die Migration einer mdb nicht mehr
Unter Linux läuft das jedoch problemlos durch. 
Einstellungen in **[/api/schema/root/migrate/mdb/{schema}](https://localhost/debug/privileged/index.html#/SchemaPrivileged/migrateMDB2Schema)** komplett identisch.
Ist ein Bug im Win-Installer?

Fehler 500.
hier die letzten Zeilen des Protokolls:
 [OK]",
    "    - Erstelle Views: ",
    "    [OK]",
    "    - Setze die DB-Revision in der neu erzeugten Datenbank: ",
    "    [OK]",
    "     [Fehler]",
    "  -> Die Daten konnten nicht erfolgreich aus der Quelldatenbank übertragen werden. ",
    "     Das Schema ist in einem inkonsisten Zustand und wird nicht beim Start angezeigt.",
    "     Wenden Sie sich zum Beheben des Problems an den System-Administrator.",
    "  -> Migration fehlgeschlagen! (Fehler beim Erstellen des Schemas - Datenbank-Transaktion konnte nicht abgeschlossen werden.)",
    "  Fehler bei der Migration (driver='MARIA_DB', location='localhost:3306', user='hayen')"

**Comment by JuergenRichter** [comment]
Habe ich auch schon festgestellt, ist laut Herrn Bachran in Arbeit.

**Comment by FPfotenhauer** [comment]
Sollte im heutigen Update behoben sein. Bitte wieder öffnen, falls nicht.

**Comment by JuergenRichter** [comment]
Kurze Rückmeldung:
-Nach der Installation war der SVWS-Server nicht gestartet, ich hab ihn dann manuell gestartet, konnte aber keine Verbindung herstellen (über localhost/debug)
-Ich habe dann den Rechner neu gestartet, auch danach war zuerst keine Verbindung möglich (obwohl der Dienst lief)
-Nach einigen Minuten hat es dann aber doch funktioniert

**Comment by JuergenRichter** [comment]
Migration von zwei MDBs (in Schemas mit "-" im Namen) hat funktioniert.

**Comment by kroerig** [comment]
> Unter Linux läuft das jedoch problemlos durch.

👍 Das bessere OS gewinnt. ;-)

**Comment by JuergenRichter** [comment]
"-Nach einigen Minuten hat es dann aber doch funktioniert"

Eine Frage dazu:
Ich habe ja durch eine "Sammelmigration" einer SchILDzentral-Datenbank eine größere Antahl von Schulschemas erzeugt (ca. 50). Kann es sein, dass der SVWS-Server beim Hochfahren alle ihm bekannten Schemas durchprüft und dass es deshalb etwas länegr dauerte, bis er "ansprechbar" war?
