### ISSUE TITLE
Laufbahnplanung drei und mehr Zusatzkurse

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/SVWS-Server#37]
Wenn ich drei Zusatzkurse belege, kommt eine Fehlermeldung, die nicht korrekt ist.
Bei der Fehlermeldung, dass nur zwei Zusatzkurse belegt werden dürfen, ... war ein falscher Gedanke

Nachfrage: Eigentlich wollte ich aus den Laufbahndaten einen JSON-Testdatensatz anfertigen. Macht das Sinn, wenn die Fehlermeldungen noch nicht korrekt sind und die Fehlertexte ggf. noch angepasst werden?

![image](https://github.com/SVWS-NRW/SVWS-Server/assets/48889965/a953c1d2-e29e-44f7-8a8c-14d5aa2dbef7)

**Comment by ThomasBachran** [comment]
Die Testdatensätze können erstellt werden, da die Fehlermeldungen hier korrekt sind. Die Zusatzkurbelegung ist hier ungültig, da die Zahl der Zusatzkurse fehlerhaft ist (Überbelegung) und hier auch später eine Wertung unklar wäre. Somit ist die erste Meldung korrekt. Die zweite Meldung mit dem Beginn des Zusatzkurses ist hier auch in Ordnung. Die dritte Meldung ist hier auch in Ordnung, da weder eine Belegung von EF.1 bis Q1.2 vorliegt noch eine gültige Zusatzkursbelegung vorliegt (hier aufgrund von Punkt 1). Ich würde mich hier nicht daran stören, dass ein Fehler hier für zwei Meldungen sorgt.
