### ISSUE TITLE
Fehlermeldung bei Anpassung der Sprachenfolge (Laufbahndaten)

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/SVWS-Server#38]
Wenn ich die Halbjahre der Sprachenfolge ändere, kommt es zu einer Fehlermeldung:
![image](https://github.com/SVWS-NRW/SVWS-Server/assets/48889965/82239bc4-299f-4c58-b0f7-6411c231115f)

Insgesamt kann man hier keine weiteren manuellen Eingaben machen (Ändern anderer Parameter, Hinzufügen und Löschen von Fächern)

**Comment by ThomasBachran** [comment]
@Raffenberg : Das Tab ist zur Zeit noch eine leere Hülle nur zu Ansicht, wo zahlreiche Funktionen zum Anpassen noch fehlen. Die Implementierung der Methoden für Änderungen muss noch erfolgen.

**Comment by ThomasBachran** [comment]
Ich schließe das Issue daher erstmal an dieser Stelle.
