### ISSUE TITLE
Oberstufe_ Laufbahnplanung Fehler Fachkombinationen

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/SVWS-Server#39]
Nach Korrektur von Verletzungen von unerlaubten Fachkombinationen werden die Fehler nicht aus dem Protokoll entfernt:
![grafik](https://github.com/SVWS-NRW/SVWS-Server/assets/84628225/f77b0ae7-acad-4806-bf1b-06849dcdf987)

**Comment by ThomasBachran** [comment]
@HHayen : Kannst du mal schauen, ob du den Fehler reproduzieren kannst? Ich bekomme das bei mir nocht hin.

**Comment by FPfotenhauer** [comment]
Bitte wieder öffnen, wenn der Fehle rnicht beseitigt ist.
