### ISSUE TITLE
Admin-Client im Dockerimage nicht verfügbar

### ISSUE THREAD

**Issue by kroerig** [SVWS-NRW/SVWS-Server#40]
Ich habe das aktuelle Dockerimage geladen, aber in der mitgelieferten `svwsconfig.json` fehlt der beim Release genannte Eintrag für den Admin-Client.

Es gibt auch kein Verzeichnis `adminclient`

**Comment by FPfotenhauer** [comment]
Danke für den Hinweis, wir kümmern uns drum.
