### ISSUE TITLE
Laufbahnplanung (keine Priorität)

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/SVWS-Server#44]
Feature, nicht prioritär:
![grafik](https://github.com/SVWS-NRW/SVWS-Server/assets/84628225/699a2f60-0418-4a1a-bc01-5132a57d631e)
Im "alten" LuPO wurden nicht zulässige Kombinationsfächer bei einer Anwahl eines der Fächer sofort ausgegraut und damit nicht mehr wählbar. HIer erscheint nur das rote Kreuz, Wahl ist aber mit Fehlermeldung möglich. 
Das war m.E. im "alten" LuPO benutzerfreundlicher.

**Comment by ThomasBachran** [comment]
@HHayen : Ich habe den Vorschlag für später als Weiterentwicklung aufgenommen. Eine Umsetzung wird aber nicht sofort erfolgen, da es sich um eine Komfprt-Funktion handelt. Hier haben andere Funktionalitäten Priorität.
