### ISSUE TITLE
Laufbahnplanung Import SVWS-Server (BUG!!)

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/SVWS-Server#45]
in laufbahnplanung.svws-nrw.de wurde hier in SW in Q2 der ZK gewählt.
![grafik](https://github.com/SVWS-NRW/SVWS-Server/assets/84628225/1dfd1b28-96ed-4c8f-843d-f89d4a8b4e4b)

In svws kommt die Wahl aber als GK bzw M an:
![grafik](https://github.com/SVWS-NRW/SVWS-Server/assets/84628225/fb2227d2-95b5-4325-ac9c-6ddf08ef513e)

**Comment by ThomasBachran** [comment]
Der wurde behoben und sollte im nächsten Pre-Release nicht mehr auftauchen.
