### ISSUE TITLE
SVWS-Laufbahnplanung Kommentare/BL

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/SVWS-Server#46]
Im svws-Laufbahnplanung:
1. Die Eintragungen zur Beratung
 ![grafik](https://github.com/SVWS-NRW/SVWS-Server/assets/84628225/f091dd4a-0fd8-4d13-9483-8c1e305e293a)
fände ich weiter oberhalb besser, unten werden die bestimmt oft hinter den ganzen unzulässigen Kobinationen übersehen.

2. Der Eintrag "Kommentar" wird bei allen Schülern übernommen, wenn vorher nicth "Beratungsdaten speichern" geklickt wurde.

**Comment by HHayen** [comment]
**Korrektur:** Nach "Beratungsdaten speichern" verschwinden die Einträge bei den anderen Schülern wieder. 
Dann sind die Einträge auch auf dem Bogen.
**Featurewunsch:** Feld "Beratungsdaten speichern" _Rot_ anzeigen, wenn Daten hinterlegt sind, wieder _Blau_. Dann ist es eindeutiger.
Immer an die Nutzer denken. im "alten" LuPO musste nie "gespeichert" werden :-)

**Comment by FPfotenhauer** [comment]
Bitte nicht zu viel mit Farben arbeiten.
Das fliegt uns bei der Barrierefreiheit später um die Ohren.

**Comment by HHayen** [comment]
Gerne auch **fett** oder anders, da bin ich leidenschaftslos. Nur irgendwie ein Hinweis darauf.

**Comment by ThomasBachran** [comment]
@HHayen : Ich habe den Bereich Beratung mal nach ganz oben geschoben. Hier müssen wir schauen, ob die Position wirklich besser ist.

**Comment by ThomasBachran** [comment]
Die Hervorhebung des Knopfes werden wir in späteren Anpassungen berücksichtigen.
