### ISSUE TITLE
Klausurplanung: Verhalten bei "Weiterblocken" (keine Priorität)

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/SVWS-Server#48]
Hat man z.B. die LKs geblockt, und blockt dann "gemischt" nach, werden die weiteren Ergebisse nicht an die bestehenden Termine angehängt, sondern neue Termine gleicher Fächer ergänzt. Finde ich auf völlig ok so, evtl. kann hier über ein Hinweisfenster nachgedacht werden, dass das so ist und bei geünschter nachträglicher  Mischung alte Termine gelöscht werden müssen.

![grafik](https://github.com/SVWS-NRW/SVWS-Server/assets/84628225/a0447284-d2e6-46db-9fa8-dd68bb9e32e5)

![grafik](https://github.com/SVWS-NRW/SVWS-Server/assets/84628225/417ab758-c1e8-4e05-977f-0ad93bafd541)

**Comment by HHayen** [comment]
Ich finde das super so. Blocken von LKs, Dann "Weiterblocken" GKs. Muss nur richtig dokumentiert werden.Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Mirko ***@***.***> Datum: 03.01.24  16:29  (GMT+01:00) An: SVWS-NRW/SVWS-Server ***@***.***> Cc: HHayen ***@***.***>, Author ***@***.***> Betreff: Re: [SVWS-NRW/SVWS-Server] Klausurplanung: Verhalten bei "Weiterblocken" (keine Priorität) (Issue #48) 
Eigentlich sollte der Button Automatisch blocken bei existierenden Terminen gesperrt sein. Ist gerade eher ein Bug, dass man ihn trotzdem klicken kann. Guter Zeitpunkt mal das "gewünschte Verhalten" zu definieren.
Ist das Sperren bei existierenden Terminen denn aus deiner Sicht sinnvoll?

**Comment by FPfotenhauer** [comment]
Wir dokumentieren das, wenn wir an die Hilfe-Doku gehen.
