### ISSUE TITLE
Klausurplanung: Wichtiger Wunsch Koopkurse markieren

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/SVWS-Server#49]
Ist es möglich, die jenigen Kurse kenntlich zu machen, in denen Schüler mit Status "Extern" sitzen?
Das würde Absprachen mit Koop-Schulen schon an dieser Stelle erheblich vereinfachen.

**Comment by HHayen** [comment]
Ich sehe gerade die Schülerzahlen: 16/18 bedeutet 16 interne von 18, also 2 externe Schüler, das ist auch ok.

**Comment by HHayen** [comment]
Dabei fällt mir auf: Die Zählung Schriftlich/Mündlich ist irritierend. Kann es sein, dass Koop-Schüler alle als Mündlich gezählt werden? Dann würden in meiner DB die Zahlen bzw. Bilanzen stimmen, aber die Anzahl der Klausurschreiber wäre falsch, da Externe nicht gezählt werden:
![grafik](https://github.com/SVWS-NRW/SVWS-Server/assets/84628225/ffd97a26-30ce-402c-b99b-d397ab074152)
Hier ist es so: 
in ER sitzen 25 eigene Schüler, 7 davon schreiben, also alles richtig
in S0-GK1 sitzen 17, davon 15 externe, alle 17 müssen natürlich schreiben, Es werden aber nur die 2 internen dargestellt.

**Comment by mec0-de** [comment]
Danke für den Hinweis. Externe werden nun auch zu den Klausurschreibern gezählt.

**Comment by mec0-de** [comment]
Die Darstellung von Kursen mit externen Schülern übernehme ich mal ins Entwickler-GIT und mache das Issue hier zu.

**Comment by mec0-de** [comment]
ist jetzt im DEV-Branch umgesetzt.
![2024-02-09_12-56-31](https://github.com/SVWS-NRW/SVWS-Server/assets/8179306/0793f716-1562-426b-9de0-bdceae113016)
