### ISSUE TITLE
API: Klassenleitungen

### ISSUE THREAD

**Issue by frostieDE** [SVWS-NRW/SVWS-Server#5]
Endpunkt: `/db/{schema}/klassen/abschnitt/{id}` 
Testdatenbank: `GymAbi.mdb`

Hier erhalte ich die Klassen zu einem entsprechenden Schuljahresabschnitt. Beispiel-Objekt:

```json
{
  "id": 22,
  "kuerzel": "05a",
  "idJahrgang": 1,
  "parallelitaet": "A",
  "sortierung": 50,
  "istSichtbar": true,
  "klassenLehrer": [7, 63]
}
```
Klassenleitung sind offentlich die Lehrkraft mit ID 7 und 63. Wer von den beiden ist Klassenleitung und wer ist ggf. Stellvertreter? Kann der SVWS-Server das überhaupt unterscheiden? 

Bei der Testdaten scheint es so, als wären die IDs stets aufsteigend sortiert.

**Comment by FPfotenhauer** [comment]
Wir behandeln die Klassenlehrer nicht mehr in Reihenfolgen.
Es gibt halt Klassenlehrer. Das ist aus den meisten Schulformen so gespiegelt, das das eher gewünscht ist.
Wir sehen das auch so, weil in eigentlich allen Fällen die "Klassenlehrer" die Berechtigungen haben müssen die Aufgaben zu übernehmen.

**Comment by frostieDE** [comment]
Okay, also zum Verständnis: Es gibt nicht mehr Klassenlehrer und Stellvertreter sondern ausschließlich Klassenleitung?

**Comment by JuergenRichter** [comment]
Man kann schon eine "Hierarchie" definieren (über das Feld "Reihenfolge" in der Tabelle "klassenlehrer" ), diese wird u.a. bei der Zeugnisausgabe verwendet, um feststellen zu können, wer als "Klassenlehrer" die Zeugnisse unterschreibt.

![image](https://user-images.githubusercontent.com/61280188/213396853-4667bc5e-96e6-4e25-bbc3-d1375604e05c.png)
