### ISSUE TITLE
Datenbank-Schema ist zur Zeit deaktviert, da es fehlerhaft ist.

### ISSUE THREAD

**Issue by kroerig** [SVWS-NRW/SVWS-Server#50]
Hallo!

Ich wollte gerade eine frische Docker-Installation erzeugen. Also,

1. Datenbank-Schema (leer) auf bestehendem Server angelegt.
2. Dockerumgebung angelegt
3. Container geladen und konfiguriert
4. Container gestartet

Meldung in der Konsole `Fehler: Schema kann nicht aktualisiert werden. Das Schema wird deaktiviert.` Klar, wie auch. Ist ja leer.

Also SwaggerUI aufgerufen und `/api/schema/migrate/{schema}/mariadb` mit gültigen MariaDB Anmeldedaten ausgeführt.
Meldung:
`Datenbank-Schema ist zur Zeit deaktviert, da es fehlerhaft ist. Bitte wenden Sie sich an Ihren System-Administrator.`

Ja wie bekomme ich denn jetzt die Datenbank freigeschaltet sodass die Api auch Daten importieren kann?

**Comment by FPfotenhauer** [comment]
Einmal bitte den Endpunkt destroy auf das Schema ausführen.

**Comment by kroerig** [comment]
Erst ein destroy auf das Schema und dann ein `/api/schema/root/create/{schema}` führt zu der Meldung: 
```

{
  "success": false,
  "log": [
    "Prüfe, ob das Schema bereits existiert...",
    "  ist noch nicht vorhanden",
    "Erstelle Ziel-Schema für MARIA_DB (server03/svws-test)",
    "  -> Erstellen fehlgeschlagen! (Ziel-Schema ist aktuell gesperrt und kann daher nicht überschrieben werden)"
  ]
}
```
Irgendwie auch nicht sinnig.

**Comment by ThomasBachran** [comment]
Ich vermute mal, dass hier ein Schema manuell angelegt wurde und dafür auch bereits ein Eintrag in der svwsconfig.json vorgenommen wurde. Da das manuell angelegte Schema kein gültiges SVWS-Schema ist, wird dieses hier gesperrt. Hier müsste man erst das Schema aus der svwsconfig.json herausnehmen, den Server neu starten, um die Sperre aufzuheben. Anschließend sollten die create-Methode funktionieren.

Falls bereits ein Schema zuvor durch einen DB-Admin angelegt wurde, dann ist auch der Endpunkt `/api/schema/create/{schema}/{revision}` zu verwenden, da dieser auch mit reduzierten Rechten zurechtkommt, welche sich nur auf das entsprechende Schema beziehen. Der Endpunkt `/api/schema/root/create/{schema}` erfordert hingegen priviligierte Rechte auf die DB und zerstört das bestehende Schema, was in diesem Falle aber nicht gewünscht ist.

@kroerig : Klappt das Erstellen des Schemas nach dem oben beschriebenen Vorgehen?

**Comment by kroerig** [comment]
Ich hatte es ja mit `/api/schema/create/{schema}` versucht, also ohne Angabe der Revision, da ich ja die aktuelle haben möchte. (s.o.).

Ich arbeite ja mit dem Docker Container. D.h. ich gebe den DB Namen und die Zugangsdaten über ENV Variablen beim Deployen des Containers mit. Daraus baut der sich ja seine svwsconfig.json.

**Comment by FPfotenhauer** [comment]
Der Serve rmüsste auch ohne DB starten.

**Comment by kroerig** [comment]
Leider nein. Wenn beim Deployen des Containers keine Datenbank definiert ist, erhalte ich folgende Meldung auf der Konsole und die SwaggerUI ist dann nicht verfügbar.

```
svws_1     | Prüfe Datenbankverbindungen (1)...
svws_1     |   -> zu Schema mysql
svws_1     | Exception in thread "main" java.lang.NullPointerException: Cannot invoke "de.svws_nrw.db.DBConfig.getDBDriver()" because "this.config" is null
svws_1     |    at de.svws_nrw.db.ConnectionManager.createEntityManagerFactory(ConnectionManager.java:131)
svws_1     |    at de.svws_nrw.db.ConnectionManager.<init>(ConnectionManager.java:62)
svws_1     |    at de.svws_nrw.db.ConnectionManager.get(ConnectionManager.java:199)
svws_1     |    at de.svws_nrw.db.Benutzer.<init>(Benutzer.java:61)
svws_1     |    at de.svws_nrw.db.Benutzer.create(Benutzer.java:76)
svws_1     |    at de.svws_nrw.server.jetty.Main.main(Main.java:71)
```

**Comment by FPfotenhauer** [comment]
Da startet der Server aber mit einer Datenbankverbindung.
Das deaktivierte Datenbanken nun gelöscht werden können, sollte in der nächsten Version des SVWS-Server umgesetzt sein. (0.8.9)
