### ISSUE TITLE
Laufbahnplanung

### ISSUE THREAD

**Issue by kroerig** [SVWS-NRW/SVWS-Server#51]
```
Ab der Version 0.8.1 wird nun auch ein passender Laufbahnberatungs-Client mit veröffentlich:
https://github.com/SVWS-NRW/SVWS-Server/packages/2001747

Das svws-laufbahnplanung-0.8.1.zip kann auf einem Webserver entpackt werden.
Dort steht dann ein Web-Lupo zur Verfügung.
Genaue Anleitungen dazu folgen noch.
```

Die Datei besteht ja nur aus ein paar Java-Script Dateien. Wie bekommt man die denn zum Fliegen?

**Comment by FPfotenhauer** [comment]
Einfach in einem Apache oder Nginx Ordner entpacken und diesen als Einstiegspunkt nutzen.

**Comment by FPfotenhauer** [comment]
Wir werden das definitiv noch dokumentieren.
Es steht ja quasi auch da.

**Comment by kroerig** [comment]
Das habe ich ja gemacht, aber ich komme nur eine leere weiße Seite mit folgenden Quelltext:

```
<!DOCTYPE html>
<html lang="de" style="overflow: auto">
	<head>
		<meta charset="utf-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=0.8" />
		<link rel="icon" href="[favicon.svg](view-source:http://192.168.13.73/svws-laufbahnplanung-0.8.5/favicon.svg)" type="image/svg+xml" />
		<title>SVWS NRW - Laufbahnplanung Oberstufe</title>
		<script type="module" crossorigin src="[/assets/index.js](view-source:http://192.168.13.73/assets/index.js)"></script>
		<link rel="stylesheet" href="[/assets/index.css](view-source:http://192.168.13.73/assets/index.css)">
	</head>
	<body style="margin: 0; padding: 0">
		<noscript>
			<div style="display: flex; justify-content: center; align-items: center; min-height: 100vh; width: 100vw; font-family: sans-serif; text-align: center; line-height: 1.5;">
				<strong>Aktivieren Sie Javascript in Ihrem Web-Browser,<br/>um die
					SVWS-Laufbahnplanung verwenden zu können.
				</strong>
			</div>
		</noscript>
		<div id="app"></div>
		
	</body>
</html>
```

aber sonst tut sich da nichts.

**Comment by kroerig** [comment]
ah, ich denke ich sehe den Fehler: Die Software kommt nicht damit klar, wenn man sie in einen Unterordner legt. Das sollte geändert werden.

Blöde Frage: Ist das jetzt der Ersatz für die Lupo-Schülerversion?

**Comment by HHayen** [comment]
Beobachte identisch das selbe Verhalten: Habe alles mal auf unserem Schulserver in einen Unterordner "Laufbahnplaung " gelegt, alles weiß mit obigem Quelltext. 
Liegt aber an der Software, nicht an der index.html, oder?

**Comment by kroerig** [comment]
Achja und 8MB Hintergrundbild als JPG gehört sich nicht.

**Comment by ThomasBachran** [comment]
Das Problem ist der base-Path, der auf '/' eingestellt war. dieser ist jetzt auch './' umgestellt. Dann wird der Client auch aus Unterverzeichnissen ausführbar sein. Die Anpassung ist in v0.8.6 noch nicht enthalten, wird aber dann in späteren Pre-Releases enthalten sein.
