### ISSUE TITLE
Vorbelegter Benutzername

### ISSUE THREAD

**Issue by kroerig** [SVWS-NRW/SVWS-Server#53]
Die Login-Maske des SVWS-Client ist immer mit Admin als Benutzername vorbelegt. Lässt sich das irgendwo abschalten?

Und btw. gibt es irgendwo eine Erklärung der Konfigurationsparameter in der `svwsclient.json`?

**Comment by FPfotenhauer** [comment]
Werden wir bis zum Release 1.0.0 umsetzen.
