### ISSUE TITLE
Import "alter" LuPO Dateien

### ISSUE THREAD

**Issue by kroerig** [SVWS-NRW/SVWS-Server#54]
Würde man jetzt von SchILD2 auf SchILD3 umstellen wollen: Wie bekommt man Laufbahnbögen, die über das klassische LuPO erstellt wurden im SVWS importiert?
Das sind ja Access-Dateien und das neue Format JSON. Gibt es da einen Konverter?

**Comment by ThomasBachran** [comment]
Im SVWS-Client unter "Schule/Datenaustausch/LuPO Laufbahnplanung"... Über den SVWS-Client kann man dann auch das JSON-Format exportieren.

**Comment by kroerig** [comment]
ja, das nützt nur nichts, da die Schüler mit dem alten Format ankommen. Die Beratungen für das Schuljahr 2024/25 sind ja mit LuPO angelaufen.
Und um testen zu können, ob die Planungen mit dem SVWS dann auch das gewünschte Ergebnis liefern, müssen die Daten aus diesen LuPO Dateien halt ins System.
