### ISSUE TITLE
Fehlermeldung nach der Anmeldung auf den Server

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/SVWS-Server#55]
Nach dem Update auf 0.8.7 erhalten wir in Münster an beiden Schulen folgenden Fehler (Schild 3.0 läuft aber!). Die Datenbanken haben wir neu migriert:
![image](https://github.com/SVWS-NRW/SVWS-Server/assets/75179015/7a28e2c2-0f50-4b15-8018-c7bf55d3cdee)

**Comment by kroerig** [comment]
Funktioniert der Aufruf über die API direkt?

**Comment by FPfotenhauer** [comment]
Gibt es einen Schüle rmit der ID 9187 in der DB?

**Comment by Kluesenerm** [comment]
Den Schüler gibt es. ID ist in Schild 3 vorhanden.

**Comment by FPfotenhauer** [comment]
Ok, dann wären wir daran interessiert, das mal zu debuggen.
Wir sollten dazu einmal mailen.

**Comment by FPfotenhauer** [comment]
Wurde mittlerweile die 0.8.8 eingespielt?
Tritt das Problem noch auf?

**Comment by Kluesenerm** [comment]
Mit dem Update wurde der Fehler behoben.
