### ISSUE TITLE
Anzeige der Server-Version unklar

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/SVWS-Server#56]
Der Dienstleister hat bei uns die aktuellster Serverversion 0.8.7 aufgespielt. Aber an mehreren Stellen steht noch die alte Versionsnummer:
![Versionen](https://github.com/SVWS-NRW/SVWS-Server/assets/75179015/0c76aa9b-04bc-4634-8eb1-e2fc2030fa7f)

**Comment by kroerig** [comment]
mal den Browsercache leeren.

**Comment by kroerig** [comment]
Aber wenn Schild ebenfalls die alte Version anzeigt, war vermutlich das Update nicht erfolgreich.

**Comment by FPfotenhauer** [comment]
Gibt es mehrere SVWS-Server?

**Comment by FPfotenhauer** [comment]
Nachtrag: Nutzt Münster den Linux-Installer?

**Comment by Kluesenerm** [comment]
Münster nutzt den Linux-Installer.

**Comment by FPfotenhauer** [comment]
Ich würde mir das gerne einmal anschauen.
Es sieht so aus, als ob einige Teile nicht ausgetauscht wurden.

**Comment by tpre** [comment]
> Münster nutzt den Linux-Installer und ich habe zwei Browser getestet. Außerdem zeigt Schild leider auch die falsche Version an.

Mit dem 0.8.8er Server stimmt die Version im admin-client, wie auch in der Schild3-Beta (die Meldung, dass die 0.8-3 erwartet wird) nicht. Beide Male wird 0.8.7 angezeigt.

**Comment by FPfotenhauer** [comment]
Kann ich Kontakt zu dem IT-Dienstleister aufnehmen?
Ich weiß jetzt, wo das Problem liegt.
