### ISSUE TITLE
Ist Duplikat - Anzeige bei allen Schulformen?

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/SVWS-Server#57]
Das Feld "Ist Duplikat" ist doch eigentlich nur für die BKs relevant oder?

![image](https://github.com/SVWS-NRW/SVWS-Server/assets/79116896/5b02c38a-1357-4a19-8cf0-acade752f00f)

Ich hatte mal eine GY-Schule, die dieses Feld dazu genutzt hat, die Inklusionskinder als Duplikate anzulegen, um diese sowohl in Förderklassen als auch in Regelklassen einordnen zu können.

Frage: Könnte/Sollte man dieses Feld für andere Schulformen nicht ausblenden, damit es hier nicht zu Fehleinträgen kommt?

**Comment by hmt** [comment]
sollte nun behoben sein, bitte einmal prüfen, hab grad keine BK-DB zur Hand

**Comment by AnneSchueller** [comment]
Funktioniert soweit, ist allerdings verrutscht:

![image](https://github.com/SVWS-NRW/SVWS-Server/assets/79116896/d83d92a6-3d62-4ec5-8c5f-a3aeeda9430f)

**Comment by hmt** [comment]
Das irritiert mich jetzt. Bei mir sieht es richtig aus, wenn ich testweise auf Gymnasium prüfe statt BK. Warten wir mal den nightly bis morgen ab.

**Comment by AnneSchueller** [comment]
Sorry, ich hatte meinen Browser zu schmal eingestellt... Funktioniert alles!

**Comment by hmt** [comment]
Ist trotzdem ein Bug, das soll auch bei kleinen Fenstern richtig dargestellt werden :) Danke fürs testen.

**Comment by hmt** [comment]
Also, abschließend geprüft, das macht schon Sinn mit der Anzeige, wenn der Browser sehr schmal ist. Dann wird der Text mit der checkbox etwas kleiner und wandert unter die Überschrift. Das ist auch beim Migrationshintergrund so und wäre anders nicht darstellbar, wenn der Checkboxtext breiter ist als die Textinputs darunter. Ich würde das so lassen.
