### ISSUE TITLE
Latinum-Auswahl trotz Note 5 führt zu benutzerunfreundlichen Fehlermeldung

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/SVWS-Server#58]
Version 0.8.8-SNAPSHOT

Wählt man bei der Sprachenfolge Latium aus, obwohl der Schüler eine 5 hat erscheint folgende Fehlermeldung.
(Die Fehlermeldung ist natürlich richtig, aber etwas benutzerunfreundlich) 

![image](https://github.com/SVWS-NRW/SVWS-Server/assets/79116896/10b1a3f1-2ec8-4fc4-b005-77f654570cfa)

**Comment by ThomasBachran** [comment]
Das Problem wurde behoben. Das Latinum lässt sich jetzt eintragen.
