### ISSUE TITLE
Migration unter Linux mit der 0.8.8 schlägt fehl

### ISSUE THREAD

**Issue by tpre** [SVWS-NRW/SVWS-Server#60]
Ich habe die neue Version unter Linux und Windows installiert. In beiden Fällen kann ich Schild 3.0.80 mit dererzeugten Standard-DB nicht starten. 
Mit dem Windows SVWS-Server bricht er ab mit `mtblLaender: Das Feld 'gueltigVon' wurde nicht gefunden`. Die Dienst von Server und DB hatte ich neu gestartet. 
Mit dem Linux SVWS-Server bricht er ab mit `#42S02Table: svwsdb-V_BenutzerDetails' doesn't exist`.

Beim Linux-SVWS-Server kann ich die DBs nicht migrieren, da der Server immer mit der Fehlermeldung
`Exception in thread "main" java.lang.NoSuchFieldError: Class de.svws_nrw.db.schema.Schema does not have member field 'de.svws_nrw.db.schema.tabellen.Tabelle_Schema_Revision tab_Schema_Revision'`
die Migration abbricht.
Ich migriere mit meinem eigenen Skript, aber mit exakt dem Befehl aus dem Install-Skript.

**Comment by kroerig** [comment]
Mal direkt über Swagger UI probiert?

**Comment by tpre** [comment]
Ich habe mit Swagger UI noch nicht gearbeitet.

**Comment by tpre** [comment]
Also irgendwas ist da irgendwo im Argen. Ich habe mehrmals alles deinstalliert, inkl. mariadb und immer gab es Fehler. Jetzt habe ich wirklich alles gelöscht, auch unter /etc/app und /opt/app und die .env.
Nach der neuen Installation (mit den gleichen Eingaben) klappt es plötzlich. Der SVWS-Server lässt sich installieren, die Migration funktioniert und Schild läuft.

**Comment by FPfotenhauer** [comment]
Das Update wurde entweder nicht mit dem Parameter "--update" ausgeführt.
Oder in der .env Datei wurde der Downloadpfad nicht angepasst auf die aktuelle Version.
Wir haben das im Installer jetzt abgefangen.
