### ISSUE TITLE
SVWS-Server 0.8.8 unter Windows 11 nicht installierbar

### ISSUE THREAD

**Issue by tpre** [SVWS-NRW/SVWS-Server#61]
Wenn ich den SVWS-Server unter Windows 11 installieren will, so läuft die Installation scheinbar fehlerfrei durch, außer das er kein DB-Schema erstellen kann. Nach Prüfung stellte ich fest, das kein DB-Service vorhanden war. Nach weiterer Suche und manueller Ausführung von `mariadb-install-db.exe` erscheint auf der Kommandozeile der Fehler 
`FATAL ERRLR_ Can't create data directory 'c:\Programm Files\SVWS-Server\db\mariadb\data' (access denied)`
Warum auch immer dieser Fehler als lokaler Administrator auftritt. Rufe ich  `mariadb-install-db.exe` in einer Admin-Console auf, dann funktioniert die Installation. In der Ereignisanzeige finde ich auch Einträge zu MariaDB, aber ich finde keinen Service und eine Verbindung mit HeidiSQL klappt auch nicht, weil kein Server gefunden wird, der auch nicht läuft.
Alles sehr seltsam. Was mache ich hier falsch?
Der Installer sollte auch jeden Fall so einen Fehler bemerken!

**Comment by kroerig** [comment]
Der Installationspfad kommt mir etwas seltsam vor. Sollte die Datenbank nicht unter `C:\ProgramData` liegen?
Das würde erklären, warum die Programm nur mit Admin-Rechten funktionieren,

**Comment by tpre** [comment]
Ich habe gerade den nach Deinstallation verbleibenden SVWS-Ordner unter C:\ProgramData gelöscht und erneut eine Installation versucht. Siehe da, es funktioniert. Installation gelungen.
Sollte da beim Deinstallieren ein bisschen untert C:\ProgramData aufgeräumt werden?

Schild3 3.0.80.9 habe ich neu installiert. Connection-File mit Schild_DBConfig.exe getestet, beide Test sind ok, aber Schild bricht ab mit `'' ist kein gültiger Integerwert`.

**Comment by JuergenRichter** [comment]
Bitte mal die Log-Datei zur Verfügung stellen.

**Comment by tpre** [comment]
[svws_server_service.wrapper.log](https://github.com/SVWS-NRW/SVWS-Server/files/13976154/svws_server_service.wrapper.log)
[svws_server_service.err.log](https://github.com/SVWS-NRW/SVWS-Server/files/13976155/svws_server_service.err.log)
[keystore.log](https://github.com/SVWS-NRW/SVWS-Server/files/13976156/keystore.log)
[2024_01_18.request.log](https://github.com/SVWS-NRW/SVWS-Server/files/13976157/2024_01_18.request.log)
[svws_server_service.out.log](https://github.com/SVWS-NRW/SVWS-Server/files/13976158/svws_server_service.out.log)

**Comment by JuergenRichter** [comment]
Ich meinte eher das Eurekalog-Fehlerprotokoll, das bei der Fehlermeldung in SchILD erzeugt wrd.

**Comment by tpre** [comment]
Wie komme ich da ran?

**Comment by FPfotenhauer** [comment]
Ich verstehe das nicht so Recht.
Wir liefern überhaupt kein Programm mariadb-install-db.exe aus.
Bei uns werden die MariaDB-Dateien unter Programm Files enpackt und als Dienst gestartet.
Die Datenbanken liegen dann unter ProgramData.
Wenn der MariaDB-Dienst nicht installiert wurde, macht es m.E. keinen Sinn hier "nachzuarbeiten".

War das ein Update oder eine Neuinstallation?

**Comment by FPfotenhauer** [comment]
> Sollte da beim Deinstallieren ein bisschen untert C:\ProgramData aufgeräumt werden?

Das werden wir auf keinen Fall machen, da man so alle Daten verlieren kann.
Wer die löschen will muss da selber aufräumen und wir haben ja auch ein Script dafür zur Verfügung gestellt.

**Comment by tpre** [comment]
Also ich habe heute nochmal ein paar Stunden investiert, um der Sache genauer auf den Grund zu gehen.

Folgende Versionen: SVWS-Server 0.8.8, Schild 3.0.80.9

Bei der Installation des SVWS-Servers wurde immer exakt die gleichen Daten eingegeben!

1. Installation des SVWS-Servers ohne das ein altes Verzeichnis C:\ProgramData\SVWS-Server existiert.
SVWS-Client läuft, Datenbank wird initialisiert und man kann zugreifen

Schild3: Es kommt der Anmeldedialog, dann erscheint ziemlich lange der SQL-Cursor, dann wechselt der Cursor in diesen runden animierten Cursor und das bleibt so. Also Schild3 läuft nicht. Leider wird kein EurekaLog erstellt.
Geht man dann in der Startleiste->rechte Maus auf dem Programm-Icon->Fenster schließen, kommt ein Fehlerdialog (ich weiß nicht, ob das Zufall war, aber so war es bei mir). Ich erstellle nochmal ein Issue und hänge dort das EurekaLog an.

2. Deinstallation SVWS-Server und direkte Neuinstallation ohne weitere Aktionen. Ergebnis: 
![image](https://github.com/SVWS-NRW/SVWS-Server/assets/23186227/1b13e0ba-7070-4dd6-a6b7-b337b4d21301)
Leider finde ich keine Informationen, was da wirklich passiert. Starte ich das offensichtlich ausgeführte run_server.cmd in C:\¸Program Files\SVWS-Server, so wird keine Verbindung zum SQL-Server aufgebaut (Exception). 

3. Deinstallation SVWS-Server, Entfernung Ordner C:\ProgramData\SVWS-Server\res, Neuinstallation
Installation läuft durch, alles läuft, aber im SVWS-Client ist eine Anmeldung nicht möglich, da keine Verbindung zu localhost möglich ist. Anmeldung im SVWS-Admin geht nicht, da angeblich das Passwort falsch ist (ist es aber nicht).

Was folgt: Offensichtlich liegt ein Problem mit dem Keystore vor, was man spätestens dann bemerkt, wenn man sich die svwsconfig.json anschaut: Ein neues Passwort für den keystore wird erzeugt. Interessanterweise stehe in der Sektion DBKonfiguration keine SchemaKonfiguration und defaultschema ist null. Hmmm, Installation läuft, aber keine DB-Daten wurden geschrieben, obwohl im Installer alles DB-bezogene angeblich funktionierte.

4. Deinstallation und komplette Löschung des Ordners: C:\ProgramData\SVWS-Server (also wie 1.)
Installation läuft, alles klappt und der SVWS-CLient und der SVWS-Admin

Hoffentlich hilft das jetzt besser!

**Comment by FPfotenhauer** [comment]
Das lag einfach daran, dass Schild3 in der Version nicht mit leeren Einstellungen zurecht kam.
Wenn der SVWS-Server läuft und der Client erreichbar ist, dann muss der SVWS-Server ja nicht neu installiert werden.
Dann ist das ein Problem mit Schild3 oder ggf.ein Problem in der Kombination der Versionen.

Die restlichen Problem entstanden aus der nicht vollständigen Deinstallation.

**Comment by tpre** [comment]
@FPfotenhauer Ob irgendwas neu installiert werden muss oder nicht, weiß man ja vorher nicht. Außerdem sollte das System so funktionieren, dass auch Installation und Deinstallation ohne Probleme funktionieren. Wenn das nicht funktioniert, dann ist das sicherlich nicht in Ordnung und führt später zu Problemen.
