### ISSUE TITLE
WBK: In den Leistungsdaten fehlt im Jahrgang 4 (BG ARS) der Karteireiter ZP 10 

### ISSUE THREAD

**Issue by Kluesenerm** [SVWS-NRW/SVWS-Server#63]
Wir vergeben im WS (also auch jetzt) den MSA mit Zentralen Prüfungen. Daher benötigt das WBK in den Leistungsdaten im Jahrgang 4 (im Bildungsgang Abendrealschule) den Karteireiter ZP 10 auch im SVWS-Server.

**Comment by FPfotenhauer** [comment]
Der ZP10 Reiter ist im SVWS-Server noch in keiner Schulform umgesetzt.
