### ISSUE TITLE
Übernahme der Sprachenfolge in die Laufbahnplanung

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#64]
SVWS-Version 0.8.8
Die (neu) eingetragenen Daten in der Sprachenfolge werden nicht in die Laufbahnplanung übernommen.

<img width="658" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/79c60e76-0c9a-43a0-8fb6-091f8252f764">

<img width="694" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/50e64922-9e88-4b11-a460-b8a14ed7e638">

**Comment by FPfotenhauer** [comment]
Ist in der Datenbank E5 korrekt als Statistikkürzel bei Englisch gesetzt?

**Comment by NielsWL** [comment]
<img width="712" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/dc48a9fb-ff78-4422-bef6-2e6badafc0da">

**Comment by FPfotenhauer** [comment]
In der Schild2-Datenbank war das aber nicht gesetzt.
Das müsste mit der Migration von uns geändert worden sein.

**Comment by NielsWL** [comment]
In E ist es tatsächlich nicht gesetzt, wieso auch immer...
In F wird es aber auch nicht übernommen, da ist es in Schild2-DB gesetzt...

<img width="347" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/e36330f3-d24e-4e92-a303-3637e2ab7f23">

**Comment by FPfotenhauer** [comment]
Wir haben das Problem gefunden. In der nächsten Version sollte das eintragbar sein und sich mit der Laufbahnplanung synchronisieren.
