### ISSUE TITLE
MDB-Kennwort bei Installation mit mdb-Migration

### ISSUE THREAD

**Issue by Raffenberg** [SVWS-NRW/SVWS-Server#65]
Beim Installationsprozess mit Migration aus einer MDB wird neuerdings immer nach dem MDB-Kennwort gefragt. Ist das so gewollt? Getestet habe ich mit Realdatenbank.

**Comment by FPfotenhauer** [comment]
Das ist m.E. schon von Anfang an so.

**Comment by Raffenberg** [comment]
Nee. Das ist relativ neu. Vor wenigen Versionen musste man bei der Migration von MDBs kein Kennwort angeben. 

Das würde ja bedeuten, dass wir demnächst das MDB-Kennwort rausgeben müssten.

**Comment by FPfotenhauer** [comment]
Wir haben das jetzt umgangen. Das war aber von Anfang an dort drin.
