### ISSUE TITLE
Laufbahnplanung: Anzeigewunsch

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#66]
Ist es möglich, so wie im aktuellen LuPO, nur die gewählten Fächer anzeigen zu lassen? Das gilt für WebLuPO und den SVWS-Server. 
Das verbessert die Übersichtlichkeit deutlich. Oder übersehe ich den Button irgendwo?

**Comment by ThomasBachran** [comment]
@NielsWL : Die Einschränkung der Fächer auf "nur wählbare" war bereits umgesetzt. Ich habe das für das nächste Release um "nur gewählte" erweitert.
