### ISSUE TITLE
Anzeigeproblem Sprachenfolge

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#67]
Bei Laufbahn>Sprachenfolge wird je nach Zoom-Faktor die Zahl für die Sprachenreihenfolge nicht oder abgeschnitten angezeigt.
Monitor: 4K

<img width="290" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/f1a3727a-ec63-47c8-906b-4bd3275b5eb9">

<img width="322" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/8b55f17e-eb42-42b3-98bc-b79d64c87c48">

<img width="237" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/c2a2f38d-e221-4338-a0c8-9a5d6b328308">

**Comment by FPfotenhauer** [comment]
Das kann ich hier nachvollziehen.
@hmt Kannst du dir das mal anschauen?

**Comment by hmt** [comment]
Sollte gefixt sein. Jetzt ist allerdings auch das Padding weg.
