### ISSUE TITLE
Import von EMail-Adressen

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#68]
Insbesondere am Anfang des Schuljahres sollen mindestens von der neuen JgSt. 5 die von der Schule vergebenen EMail-Adressen (vorname.nachname@...) nach Schild importiert werden. Bei uns zusätzlich auch noch die von uns vergebenen EMail-Adressen der Eltern (vorname.nachname.eltern@...).
Die EMail Adressen werden von uns über eine Excel-Datei erstellt, wo Umlaute, weitere Vornamen, evt. Doppelnamen eliminiert werden. In der Excel-Datei sind Schild-ID, Nachname, Vorname, Geb-Datum, Klasse, usw. vorhanden. Von dort aus kann ich eine CSV-Datei erstellen, wo z.B. die Schild-ID und die beiden EMail-Adressen enthalten sind.
Gibt es eine Möglichkeit, diese Adressen über diese CSV-Datei direkt zu importieren? Bisher musste ich sehr umständlich die dat-Dateien exportieren, verändern und reimportieren. Das wäre schön, wenn das einfacher ginge.

**Comment by kroerig** [comment]
Unter SchILD2 habe ich das immer direkt per SQL gemacht. Das ginge technisch auch bei SchILD3, man müsste nur schauen, in welcher Tabelle die Daten jetzt stehen. Aber mit einem custom-Importer wäre das einfacher.

Ich kenne es von anderer Software so, dass man entweder die Spalten in der CSV zu benennen muss, wie die Datenfelder im Programm heißen oder man die CSV hochlädt und dann den Feldern ein Zielfeld zuweisen kann.

**Comment by FPfotenhauer** [comment]
Das ist ein Issue für Schild3.
