### ISSUE TITLE
Löschen einer Laufbahnplanung

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/SVWS-Server#69]
Gibt es irgendwo die Möglichkeit, eine falsch angelegte Oberstufenplanung wieder zu löschen?
Ich meine den kompletten Eintrag.

![image](https://github.com/SVWS-NRW/SVWS-Server/assets/79116896/7a2864bd-08ff-4ced-9763-6ad4b40a9f9a)

**Comment by ThomasBachran** [comment]
Da wird es eine sehr eingeschränkte Möglichkeit geben. Aktuell haben wir da eine erste Version im Repository, aber noch kein Release damit gemacht.
