### ISSUE TITLE
Schnellanleitung für die Installation / Integration von WebLupo

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#70]
Gibt es schon eine Schnellanleitung für die Installation / Integration von WebLuPO auf den Webserver der Schule?

**Comment by hmt** [comment]
https://doku.svws-nrw.de/Projekte/weblupo/

**Comment by NielsWL** [comment]
Das kenne ich, aber das einfache Kopieren auf unseren Webspace funktioniert nicht.

**Comment by kroerig** [comment]
Doch, aber dürfen nicht den npm Quelltext nehmen, sondern die fertige Version.

**Comment by NielsWL** [comment]
Das ist in der ZIP-Datei... Wenn ich das hochspiele, passiert gar nichts. Auch nicht, wenn ich es einfach bei mir auf dem PC öffne.

<img width="345" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/96b34fa1-0a4e-4e4c-8adb-d6f7d54461f1">

<img width="350" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/71a61e5b-1ce0-4913-b80d-3a79c417334c">

**Comment by hmt** [comment]
stimmt, lokal wird das nicht geladen, wenn man auf die index.html geht. Hit Hilfe eines Servers sollte es aber gehen. Ich vermute, dass es daran liegt, dass es auf dem Dateisystem läuft. Bitte einmal einen lokalen Server verwenden oder auf einem Webserver ablegen.

**Comment by NielsWL** [comment]
ok, läuft. Hatte es ja schon in einen Ordner unseres Webspace hochgeladen. Aber erst die Einrichtung einer Subdomain mit dem Ziel des Unterordners war die Lösung.
