### ISSUE TITLE
0.8.8: DB-Import: Anzeige von Fehlertexten statt nur des roten "Log"-Hinweises 

### ISSUE THREAD

**Issue by T-Hagel-SK** [SVWS-NRW/SVWS-Server#71]
Hallo zusammen,
wir beginnen gerade mit den ersten Tests des SVWS-Servers. Version 0.8.8.

Beim Versuch Schild2-Schemas zu importieren, erhalten wir offenbar eine Fehlermeldung. Was genau das Problem ist, ist hier leider nicht ersichtlich, da lediglich ein rotes Warndreieck und der Text "Log" erscheint. 

So wäre es z.B. hilfreich zu erfahren, ob hier ggf. keine Verbindung zum Schild2-Webserver aufgebaut werden kann (Firewall, Zugangsdaten, etc.) oder ob z.B. bei einer MDB-Datei etwas fehlt (Tabelle, Passwort, etc.).

Im Moment ist das ein Blindflug, bzw. wir müssten, da wir als Tester keinen Zugriff auf die Logfiles des SVWS-Webservers haben, jedes Mal die Linux-Experten anfragen, ob und was dort erfasst wurde.

Schöne Grüße
Thomas Hagel
Stadt Köln
Fachanwendungssupport / Schild3-Projektleitung

**Comment by kroerig** [comment]
Womit machen Sie den DB Import?

**Comment by FPfotenhauer** [comment]
Normalerweise sollte da ein Log erscheinen.
Es kann hier sein, dass ein grundsätzlicher Fehler aufgetreten ist, der nicht ins Log gegangen ist.

Aus der Beschreibung kann ich auch nicht ganz nachvollziehen, was genau versucht wurde.
Soll aus einer MDB migriert werden oder aus der MSSQL-Datenbank?
Wenn aus der MSSQL migrier werden soll, dann müsste man sich ggf. einmal über die Zugangsdaten unterhalten.
Gute Hinweise für uns ist immer, ob man mit einem Datenbank-Tool (z.B DBeaver) auf die Datenbank kommt.

Den Begriff Schild2-Webserver verstehe ich leider nicht.
Da wir hier zum ertsen mal in einer solchen Konstellation arbeiten, ist vielleicht ein direkter Austausch sinnvoller.

**Comment by T-Hagel-SK** [comment]
> _Normalerweise sollte da ein Log erscheinen. Es kann hier sein, dass ein grundsätzlicher Fehler aufgetreten ist, der nicht ins Log gegangen ist._

Hm, wenn hier ein Fehler auftritt, der nicht ins Log geschrieben wird, wären zwei Dinge schön:
1. Eine Anleitung in der auf die jeweiligen Parameter des Configbereiches eingegangen wird. Ich könnte mir vorstellen, dass in unserer Configdatei nicht alles drin steht, was da notwendig ist.
2. Etwas, was ich bei allen schulischen Anwendungen schmerzlich vermisse: sprechendere Fehlermeldungen :-)

---
"_Aus der Beschreibung kann ich auch nicht ganz nachvollziehen, was genau versucht wurde.
Soll aus einer MDB migriert werden oder aus der MSSQL-Datenbank?"_
Ich habe beides probiert. Zunächst gegen unsere SchildZentral-Datenbank und anschließend auf einen Export aus dem Schulträgermodul heraus. Ohne Anzeige was da hängt ... hänge ich da auch gerade in der Luft. 

---
"_Den Begriff Schild2-Webserver verstehe ich leider nicht."
Ich heute auch nicht ... ich meinte unseren SchildZentral-Datenbankserver (für Schild2.x) ... hier vermute ich aber Probleme in der Abstimmung der Firewallsysteme und bin da noch intern in der Klärung.
Aber hier wäre so eine Fehlermeldung wie "Es konnte keine Verbindung zum MSSQL-Server hergestellt werden" oder "Datenbankname oder Passwort sind nicht korrekt" irgendwie hilfreicher.

**Comment by kroerig** [comment]
Also, wenn ich hier eine DB migriere und der Server kann die DB nicht erreichen, dann sehe ich die Fehlermeldung auf der Serverkonsole vom SVWS.

**Comment by kroerig** [comment]
Bei mit läuft der Server in einem Docker Container, daher gehen alle Ausgaben direkt auf die Konsole.
Die müssten die Meldung in der Browserkonsole (F12) sehen können. Oder statt /admin /debug nutzen und direkt die API füttern.

**Comment by kroerig** [comment]
Ich habe das gerade bei mir mal probiert. Es kommt tatsächlich nur dieses Bild:
![grafik](https://github.com/SVWS-NRW/SVWS-Server/assets/5148795/06bdaf23-bb26-411d-b9e6-7e2e436bf4d3)

In der Browserkonsole steht nur:
![grafik](https://github.com/SVWS-NRW/SVWS-Server/assets/5148795/70584b48-bedb-42d5-9ae8-7c3e74b72ddd)

**Comment by T-Hagel-SK** [comment]
> Bei mit läuft der Server in einem Docker Container, daher gehen alle Ausgaben direkt auf die Konsole. Die müssten die Meldung in der Browserkonsole (F12) sehen können. Oder statt /admin /debug nutzen und direkt die API füttern.

Schade, dass es hier nicht den Facepalm-Emoji gibt ...

Sonst ist die Browserkonsole / Entwicklungstools erste Wahl, nur ausgerechnet hier komme ich nicht auf die Idee ...

Da finde ich den sprechenden Fehlertext und weiß nun, wo ich ansetzen muss:
"catch(error) {
			console.warn(`Das Initialiseren des Schemas mit der Schild 2-Datenbank ist fehlgeschlagen.`);
		}"

**Comment by T-Hagel-SK** [comment]
Hm,
in welchem Format werden hier bei "formData.append('srcLocation', location.value);" die Angaben für die Serverlocation benötigt ?
Ich hatte es mit einem Aliasnamen Komma:Port versucht. Aber auch mit Doppelpunkt statt Komma klappt es ebenso wenig, wie nur mit Servernamen oder Servername:Port

Je nach Variante bekomme ich in der Entwicklungskonsole folgende Rückmeldungen:
![20240201_Migrationsversuche_mit_unterschiedlichen_Datenbank-Host-Eintragsvarianten](https://github.com/SVWS-NRW/SVWS-Server/assets/158161190/41275ce2-9f19-41af-809d-6290eeb9e489)

**Comment by T-Hagel-SK** [comment]
Sehr lästig dabei ist, dass man nach JEDEM Versuch, die Felder neu füllen darf ... Daher ja die Anfrage, ob man diese Eckdaten nicht besser in der Config-Datei festlegt ... egal ob man jetzt mit SchildNRW oder -Zentral arbeitet :-)

**Comment by kroerig** [comment]
GUI ist ja schön. Für eine Massenmigration würde ich das Scripten. Wahlweise in einen WSL mit Bash und Curl oder mit Powershell. Was einem halt besser gefällt. Es sind alles nur HTTP Requests.

**Comment by ThomasBachran** [comment]
@T-Hagel-SK : Die Ausgabe des Logs war bisher noch nicht im Admin-Client implementiert. Daher wurde nur der Fehler angezeigt. In dem nächsten Pre-Release wird dann auch das Log im Admin-Client angezeigt werden.

Was das Vorausfüllen angeht, so werden wir während einer Anmeldung eines Benutzers die Parameter für die Quell-DB einer Migration beim erneuten Aufruf des Modals bestehen lassen. Insgesamt ist der Admin-Client hier noch in der Entwicklung und an einigen Stellen noch unvollständig. Im nächsten Pre-Release wird es hier auch eine erste Erweiterung geben.

Vielen Dank für Ihre Rückmeldung!

**Comment by FPfotenhauer** [comment]
Sollte in 0.8.9 umgesetzt sein.
