### ISSUE TITLE
Wunsch: Online-Handbuch für SVWS-Server-Zugang mit /admin, bzw. im Debug-Modus

### ISSUE THREAD

**Issue by T-Hagel-SK** [SVWS-NRW/SVWS-Server#72]
Hallo zusammen,

auch wenn man noch in der Testphase ist, würde ich gerne , browserbasiert, auf dem SVWS-Server auf eine Art Anleitung oder Handreichung vorfinden. Ohne ist das hier ein Blindflug, ein Textadventure. So wäre es z.B. hübsch zu wissen, in welchem Format z.B. der Datenbankhost eingetragen werden soll. 

Schön zu wissen wäre auch, was alles in Config-Dateien in welcher Form eintragbar ist. So frage ich mich gerade, ob man hier nicht die Zugangsdaten zum Schild2-Datenbankserver fest eintragen kann. Im Moment müsste ich sie für jeden Import manuell eintragen.

Gewissermaßen fehlt auch eine Art Leitfaden, wie man einen frisch aufgesetzten SVWS-Server als Admin einrichtet, bzw. wie der SVWS-Server als Tester sowohl webbasiert, als auch Clientbasiert getestet werden kann / sollte. Die Client-Tests sollten sich m.E. an einem einheitlichen Drehbuch orientieren, um Vergleichswerte erhalten zu können. Aktuell ist ja den Beteiligten unklar, wie viele Schulen sich einen SVWS-Server teilen können. Bzw. wie ein vorhandener SVWS-Server optimiert werden kann, um eben mit x Schulen klarzukommen. 

Oder ich habe diese noch nicht gefunden. Die Hilfen unter https://help.svws-nrw.de/ auf die unter https://doku.svws-nrw.de/ verwiesen wird, sind aktuell nicht so richtig mit Leben gefüllt...

Schöne Grüße
Thomas Hagel
Stadt Köln
Fachanwendungssupport / Projektleitung Schild3

**Comment by FPfotenhauer** [comment]
Eine Dokumentation der svwsconfig.json werden wir in Kürze nachreichen.
Danke für den Hinweis.

Den Zielserver kann man momentan nicht fest eintragen. Das ist auch eher eine Funktion, die ein Schild-Zentral-System benötigt, was wiederum nicht unsere Aufgabe ist. Die Programmierung eines solchen Schulträger-Tools ist m.W. im Gange.

Bei unserem letzten Treffen stand der SVWS-Server ja noch nicht zur Verügung. Ich würde die hier gewonnenen Erfahrungen gerne nutzen, um eine Dokumentation zu erstellen, die allen anderen hilft, deshalb ist der Austausch hier sehr wertvoll für uns.

Wir haben hier wenig Erfahrung mit MSSQL, weil wir das nicht wirklich nutzen. Aber ich habe gerade mal eine Migration gestartet, die dort in "leere" läuft und ich kann das so reproduzieren. Wir werden versuchen eine Fehlermeldung zu generieren, die sprechender ist.

**Comment by FPfotenhauer** [comment]
Ich habe hier angefangen eine erste Beschreibung zur Einrichtung zu schreiben:
https://doku.svws-nrw.de/Deployment/Einrichtung/

Die Beschreibung der Parameter im Admin-Client bei der Migration folgen.

**Comment by FPfotenhauer** [comment]
Wir haben in der Version 0.8.9 mal die Beschriftung im Modal des Migrationsprozesses im Admin-Client verbessert.
Eine Rückmeldung, ob das die Bedienbarkeit schon verbessert, wäre super.

**Comment by FPfotenhauer** [comment]
Die Beschreibung ist jetzt ersteinmal komplett.
https://doku.svws-nrw.de/Deployment/Einrichtung/

Bei weiteren Wünschen bitte melden.

**Comment by T-Hagel-SK** [comment]
> Wir haben in der Version 0.8.9 mal die Beschriftung im Modal des Migrationsprozesses im Admin-Client verbessert. Eine Rückmeldung, ob das die Bedienbarkeit schon verbessert, wäre super.

Hm, wenn ich sehe, dass da schon ein Snapshot zu 0.8.10 besteht, warte ich doch besser noch die 0.8.10 ab, oder ?

Gibt es sowas wie eine Versionshistorie ?
Bzw. habe ich die irgendwo übersehen ?

**Comment by T-Hagel-SK** [comment]
> Die Beschreibung ist jetzt ersteinmal komplett. https://doku.svws-nrw.de/Deployment/Einrichtung/
> 
> Bei weiteren Wünschen bitte melden.

Prima, das hilft schon mal sehr weiter :-)

**Comment by hmt** [comment]
> Gibt es sowas wie eine Versionshistorie ?

https://github.com/SVWS-NRW/SVWS-Server/releases

Es ist müßig, auf immer neue Versionen zu warten, denn die gibt es sehr oft. Wenn es nicht um konkrete bekannte Bugs geht, dann ist ein Release lediglich ein Zwischenstand, der veröffentlicht wird und aktuell keinen Bezug zu Stabilität oder Funktionsumfang hat.

**Comment by T-Hagel-SK** [comment]
> https://github.com/SVWS-NRW/SVWS-Server/releases

Prima, Danke habe ich mir notiert.

> Es ist müßig, auf immer neue Versionen zu warten, denn die gibt es sehr oft. Wenn es nicht um konkrete bekannte Bugs geht, dann ist ein Release lediglich ein Zwischenstand, der veröffentlicht wird und aktuell keinen Bezug zu Stabilität oder Funktionsumfang hat.

Ja, das ist richtig, aber ich befinde mich hier in einem Umfeld, in dem jede neue Version eine Reihe von Tickets und Zeiten bedeuten. D.h., wenn es Donnerstags heißt, da kommt nächste Woche ein Update, dann warte ich auf den nächsten Donnerstag, wenn dieses Update (daher auch die Releasenotes) einen bei uns festgestellten Mangel behebt.

Dass Schild-Updates schneller kommen, als ein Update eingespielt ist, das kennen wir ja schon :-) Insbesondere in den Zeiten zwischen Sommer- und Herbstferien :-))
