### ISSUE TITLE
Kursblockung / Kursplanung

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#73]
Hallo zusammen,

ein großes Lob für die Verbesserung bei der Kusplanung in Version 0.8.9. 
Das "ausführliche" Blocken (lokal im Browser) funktioniert bisher gut. Ich werde das mit den gleichen Regeln natürlich noch mit CNF vergleichen...

Drei Fragen habe ich dennoch aktuell:
1) Wie kann ich mehrere Schüler gleichzeitig einem bestimmten Kurs zuweisen?
2) Ich möchte im M-GK1 die gleichen Schüler*innen haben wie im D-GK1 und im E-GK1. In CNF gab es dafür eine Regel. Lässt sich das hier auch als Regel hinzufügen? 
3) Ich möchte bestimmt Schüler*innen nicht zusammen blocken. Wenn beide das gleiche Fach gewählt haben, sollen sie in verschiedene Kurse geblockt werden. Lässt sich das hier auch als Regel hinzufügen?

**Comment by NielsWL** [comment]
Der erste Vergleich mit CNF (Rechnung über jeweils mehrere Stunden mit CNF und auch SVWS) ergibt:
CNF mit 0 Konflikten und einer optimalen Kursdifferenz 1,
SVWS mit 0 Konflikten und einer Kursdifferenz 3. 

Mal schauen, was die Übernachtrechnung mit SVWS ergibt.

**Comment by NielsWL** [comment]
...ok, ich weiß, warum man mit SVWS nur auf eine KD 3 kommt. Aber insgesamt ist es eigentlich eine KD 1.
Die Nachtrechnung hat 5 Stunden gerechnet.

Ich habe folgende Situation:
Kurs TRBB-GK1 mit 4 Schülern (alle fixiert, es kommen dort nicht mehr rein)
Kurs TRBB-GK2 mit 4 Schülern (alle fixiert, es kommen dort nicht mehr rein)
Kurs TRBB-GK3 mit 1 Schüler (auch fixiert, es kommt auch hier keiner mehr rein). 
Nur diese 9 Schüler haben das Fach TRBB.

Diese Regel gab es in CNF:
Fach-Art#TRBB;GK#max. Kursdif. (ignoriert globale Kursdifferenz)#6
So wurde die eigentlich zu hohe (und hier ja nicht änderbare) KD beim Rechnen und auch bei der Anzeige ignoriert.

Wenn ich jetzt beim Rechnen nicht das tatsächliche Ergebnis sehen kann (also KD 1 mit der ignorierten KD 3 in TRBB), weiß ich auch nicht, wann ich aufhören kann zu rechnen. Denn das beste Ergebnis hatte ich bereits nach 15-20 Minuten. Und das ist schneller als mit CNF gewesen.

<img width="523" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/6a29ab0a-aa1d-4b13-9702-fb62ce18c293">

**Comment by FPfotenhauer** [comment]
Danke für die Testarbeit!

Dann können wir aber insgesamt festhalten, dass nun die Qualität der Blockungen schon sehr gut an CNF heran kommt.

**Comment by benjaminbartsch** [comment]
1. Ich glaube das geht noch nicht. Da müssten die GUI-Programmierer umsetzen. Was derzeit aber schon geht ist, alle SuS die derzeit in einem Kurs sitzen, zu fixieren. @hmt: Kann man das umsetzen? Wenn ja wie wäre es sinnvoll? Klick auf Kurs, man sieht die SuS, Checkbox "fixieren"? Nur so eine Idee.

2. Das wäre extrem viel Arbeit und würde den Algorithmus derzeit sehr stark verändern. Das würde ich derzeit nicht primär umsetzen wollen. Als Notlösung könnte man die jeweiligen Gruppen (wenn es zB in der EF sowas wie Pseudoklassen sind) komplett per Hand fixieren.

3. Das wäre als Regel machbar mit nicht zuviel Aufwand. Sowas wie "SchülerIn X nicht zusammen mit SchülerIn Y". 

PS: In Zukunft bietet es sich an, für jeden Punkt ein eigenes Issue zu öffnen, damit man die nacheinander abarbeiten kann.

**Comment by NielsWL** [comment]
1) und 2) sind evt auch identisch.
Wir haben in der kommenden EF wohl 6 Kerngruppen, die jeweils in D, E und M zusammen haben. Da 18 Mal die Schüler einzeln in jeden Kurs hinzuzufügen, ist schon lästig.

**Comment by ThomasBachran** [comment]
Die Punkte 1 und 2 lassen sich sicherlich in einem Zusammenhang behandeln. Für Punkt 1 könnte man eine manuelle Schnellzuordnung von Schüler zu Kursen über ein Modal bereitstellen. Für Punkt zwei könnte man dann eine Übertragung der Schülermenge eines Kurses auf die Schülermenge eines anderen Kurses (mit anderem Fach+Kursart) über einen Button zur Verfügung stellen. Dabei könnten dann die Schüler automatisch gefiltert werden, die keine Fachwahl für den Zielkurs haben.

Punkt 3 kann dann, wie @benjaminbartsch vorgeschlagen hat über eine Zusatzregel umgesetzt werden.

**Comment by HHayen** [comment]
Möchte @NielsWL in seinem Wunsch nach gruppenweiser Zuweisung bekräftigen. Es arbeiten einige Schulen ein der EF mit Kerngruppen in den Fächern D, E, M, (und oft auch SP)

**Comment by hmt** [comment]
Eine Zuweisung in einen über die Schülerfilter ausgewählten Kurs kann man nun per Modal machen. Dabei werden alle anderen Schüler angezeigt, die die gleiche Fachwahl (und Kursart) haben. Per Klick lassen sich so die Schüler aus dem Kurs entfernen oder aus anderen Kursen in den gewählten Kurs umkursen. Ist noch WIP, aber im nächsten Pre-Release dabei.

**Comment by benjaminbartsch** [comment]
An 3. sind wir dran. Es wird 4 Regeln geben.

- SCHUELER_ZUSAMMEN_MIT_SCHUELER_IN_FACH
- SCHUELER_VERBIETEN_MIT_SCHUELER_IN_FACH
- SCHUELER_ZUSAMMEN_MIT_SCHUELER
- SCHUELER_VERBIETEN_MIT_SCHUELER

... das ist jetzt die interne Benennung. 

@ThomasBachran: Wie ist jetzt das Vorgehen. Schließen wir jetzt das "öffentliche" Issue, da wir das intern aufgenommen haben, oder schließen wir es erst dann, wenn wir fertig sind?

**Comment by ThomasBachran** [comment]
Die Punkte 1 und 2 werden auch in einem ersten Ansatz im nächsten Pre-Release vorhanden sein. Das Issue kann also geschlossen werden.
