### ISSUE TITLE
Kursblockung: Regelverletzungen

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#75]
Es werden beim Blocken, auch vor der Rechnung, Regelverletzungen angegeben (hier 2), die aber nicht dokumentiert werden.
Ich weiß, dass diese Regelverletzungen mit den Lehrkräften zusammenhängen, da ich zweimal Kurse der gleichen Lehrkraft parallel fixiert habe, dennoch wäre es sinnvoll, dazu einen Hinweis zu bekommen. Oder?

<img width="263" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/69d86789-e583-4523-acd0-02f48ab57c8e">

**Comment by ThomasBachran** [comment]
Dieser Verbesserungsvorschlag wird in einer zukünftigen Version eingebaut. Ich schließe das Issue erstmal an dieser Stelle.
