### ISSUE TITLE
Ausdruck: Kurse-Schienen-Zuordnung

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#76]
Die Schüler-Anzahl auf dem Ausdruck der Kurse-Schienen-Zuordnung ist falsch.
Es sind bei uns (auch in der DB) nur 122 Schüler, angezeigt wird oben rechts 123.

Zusätzlich wäre es sinnvoll, einen Ausdruck ohne Farben (also mit weißen Tabellenzellen) auswählen zu können.

Beim Ausdruck für einen einzelnen Schüler werden auch in der EF bereits die Abifächer gekennzeichnet. Das ist falsch. Die LKs sind ab der Q1 anzuzeigen, die Abifächer 3 und 4 ab der Q2. Das Gleiche beim Ausdruck Kursbelegung.

<img width="1288" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/c0addc45-3977-485e-a31e-0cd542805e1a">

<img width="265" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/17da7ade-e639-4fe9-b0ab-856354ba92c0">

**Comment by FPfotenhauer** [comment]
Kannst du mal bitte probieren, das Dokument in den Druckeinstellungen nur Schwar-Weiß zu drucken?
Bei uns sah das voll ok aus, deshalb gibt es keine zwei Varianten.

**Comment by NielsWL** [comment]
Ist dann alles grau in grau... aber ok.

**Comment by ThomasBachran** [comment]
> Beim Ausdruck für einen einzelnen Schüler werden auch in der EF bereits die Abifächer gekennzeichnet. Das ist falsch. Die LKs sind ab der Q1 anzuzeigen, die Abifächer 3 und 4 ab der Q2. Das Gleiche beim Ausdruck Kursbelegung.

Bei der EF sollten die Abiturfächer nicht angezeigt werden. Ab der Q1 würde ich die geplanten Abiturfächer 3 und 4 allerdings als Zusatzinformation mit anzeigen - auch wenn diese noch nicht endgültig festgelegt sind. Sollten diese später noch geändert werden, so kann später ein neuer Ausdruck gemacht werden, wo dies automatisch angepasst ist.

**Comment by ThomasBachran** [comment]
Ich schließe das Issue an dieser Stelle. Der Report wird später angepasst.

**Comment by benjaminbartsch** [comment]
@NielsWL: Zu den 123. Das ist die Menge aller Schüler, die mir von der Datenbank geliefert wird.

- Gibt es Karteileichen/Neuzugänge/Sitzenbleiber in deinem Datensatz? Also einen S. der keine Fachwahlen hat?
- Wie sieht es im Kursblockungsdialog aus, wenn man den Schüler-Filter anguckt, welche SuS Anzahl steht da, wenn kein Filter gewählt ist? (siehe Zahl über Addens, Sophie)

![grafik](https://github.com/SVWS-NRW/SVWS-Server/assets/83505980/f289da1d-3dbf-4f9b-8294-59dbcee6c5e1)

**Comment by benjaminbartsch** [comment]
@NielsWL: Könntest du bitte nochmal testen, dass es sich dabei nicht um eine "Neuaufnahme" handelt?

**Comment by benjaminbartsch** [comment]
@NielsWL: Du müsstest das nochmal testen, falls es weiterhin auftaucht und **es keine Neuaufnahme** ist, dann bitte Issue neu öffnen.
