### ISSUE TITLE
Kursplanung: Anzeigeproblem

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#77]
Bei der ersten Auswahl nach dem Start des SVWS-Servers wird keine Blockung (Oberstufe > Kursplanung) angezeigt. Klicke ich dann auf ein anderes Halbjahr (EF.2) und dann wieder auf das erste Halbjahr (EF.1) werden die vorhandenen Blockungen angezeigt.
Klicke ich danach auf einen anderen Bereich (Lehrkräfte, Kurse, ...) und dann wieder auf Oberstufe > Kursplanung wird alles sofort angezeigt.

Vorher:
<img width="638" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/d14ce22c-530f-4b1f-b474-7f8935dffa92">

Nachher:
<img width="666" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/cf208dbb-18cd-4701-95d7-770597f2d766">

**Comment by ThomasBachran** [comment]
@NielsWL : Hier bitte auch nochmal prüfen, ob sich das Problem mit dem nächsten Pre-Release reproduzieren lässt. Es hat da zwischenzeitlich etliche Korrekturen gegeben. Wenn ja, dann übernehme ich das Issue. Wenn nicht, dann kannst du es einfach schließen.

**Comment by NielsWL** [comment]
Der Fehler ist behoben.
