### ISSUE TITLE
Kursplanung: Import/Export?

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#78]
Da die Kursplanung und -blockung erfahrungsgemäß immer sehr lange dauert (einzelne Rechnungen evt mehrere Stunden), haben wir die Blockungen mit CNF immer zu Hause gerechnet (evt. auch über Nacht).
Lässt sich das hier auch realisieren? Also ein Export/Import der Blockungen bzw. der Daten, so dass ich die Rechnungen auf meinem localhost durchführen kann? Die Datenbank kann ich ja sichern (sqlite) und zu Hause wieder aufspielen und dann blocken. Dann müsste ich aber einen Export der fertigen Blockung und einen Import in der Schule machen können.

**Comment by FPfotenhauer** [comment]
Ein Import/Export der Blockungen ist momentan nicht vorgesehen.
Gibt es nicht die Möglichkeit über VPN von zu Hause aus zuzugreifen?

**Comment by NielsWL** [comment]
Das wäre sinnvoll, in Münster ist die Umsetzung scheinbar schwierig. Werde ich aber angehen...

**Comment by kroerig** [comment]
Eigentlich will man solche langen Berechnungen doch im Hintergrund haben. Also man sagt dem Programm, was es berechnen soll. Ein Workerprozess auf dem Server übernimmt den Job und meldet sich erst wieder wenn er fertig ist.

**Comment by NielsWL** [comment]
Ja, aber wenn etwas nicht funktioniert, muss man andere Regeln oder Einstellungen testen und wieder rechnen. Und die Rechnungen dauern tatsächlich Stunden.
