### ISSUE TITLE
Oberstufe: Fehler

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#79]
Plötzlich kann ich nicht mehr auf die Fachwahlen und Kursplanung für die EF.1 (kommendes Schuljahr) zugreifen.
Der Fehler ist reproduzierbar.
Anlegen eines neuen Schülers (Warteliste) in der JgSt. EF für das nächste Schuljahr. Eingegeben habe ich Name, Vorname, Geburtstag, JgSt. EF.
Der folgende Fehler erscheint bei Aufruf der Fachwahlen und Kursplanung.
Nach Löschen des Schülers funktioniert es wieder.

<img width="520" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/5a08b795-fdf6-4fcb-84c5-a1e4f9b02a1e">

**Comment by NielsWL** [comment]
Dazu kommt auch die Frage, wie ich neue Schüler in die Blockung integrieren kann, die noch nicht an der Schule angemeldet sind aber bereits in die Blockung integriert werden sollen. Bei Kurs42 und LuPO konnte ich das machen, ohne die Schüler in die Datenbank eingeben zu müssen.

**Comment by kroerig** [comment]
Weil Kurs42 und LuPO eine eigene Datenbank geführt haben. Das führte hier gerne zu dem Effekt, dass sich der Import nach SchILD auf die Nase gelegt hat, weil die Schreibweise des Namens nicht übereinstimmte.
Jetzt ist SchILD das datenführende System und alle anderen müssen sich unterordnen.

**Comment by NielsWL** [comment]
Die neue Struktur ist mir klar und ja auch total sinnvoll. Die Frage nach den Neuzugängen und der Laufbahnplanung bleibt...

**Comment by kroerig** [comment]
Die Schüler müssen wohl in SchILD angelegt sein. Sie müssen ja auch die Kurswahlen in SchILD hinterlegen.

**Comment by NielsWL** [comment]
Ich habe nochmal getestet:
Die angelegte Schülerin habe ich als Neuaufnahme und als Warteliste eingegeben. Diesmal inkl Geburtstag, Aufnahmedatum und Klasse.
Ich bekomme dennoch den Fehler in den Reitern der Oberstufe.

**Comment by ThomasBachran** [comment]
Beim Anlegen von Schüler mit Schild 3 wurden einige Default-Werte nicht in der SVWS-DB gesetzt. Der SVWS-Server wird mit dem nächsten Pre-Release etwas flexibler mit den fehlenden Daten umgehen, so dass der beschriebene Fehler dann vermutlich nicht mehr auftritt (zumindest habe ich einen Fehler, der dieser Beschreibung entsprich behoben).

@NielsWL : Ich gebe dir mal das Issue zurück und würde dich bitten das ganze nochmal mit dem nächsten Pre-Release zu testen und ggf. zu schließen. Ich weise dich daher erstmal diesem Issue ale Bearbeiter zu.

**Comment by NielsWL** [comment]
Version 0.8.10:
Nun erscheint der neu angelegte Schüler zwar unter Oberstufe > Laufbahnen, jedoch:

1) Nur dann, wenn ich ihn als Neuaufnahme und nicht als Warteliste anlege. Es wird aber beides benötigt.
2) Ich kann keine Laufbahnplanung durchführen, der Reiter wird nicht erstellt, der Link vor dem Namen führt ins Leere.

![image](https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/7999d519-29a1-4c53-ace2-914bcc439637)

**Comment by ThomasBachran** [comment]
Punkt 1 ist mittlerweile behoben und wird im nächsten Pre-Release umgesetzt sein.
Punkt 2 hängt mit Issue #106 zusammen und daher ist das hier dann ein Duplikat. Daher schließe ich dieses Issue.
