### ISSUE TITLE
docker-compose bricht ab

### ISSUE THREAD

**Issue by kroerig** [SVWS-NRW/SVWS-Server#8]
docker-compose lässt sich mit den Dockerfiles nicht ausführen, da das Verzeichnis 'app' nicht vorhanden ist:

```
 => ERROR [ 6/11] COPY app /opt/app/svws                                                                                                                                                                                                0.0s
------
 > [ 6/11] COPY app /opt/app/svws:
------
Dockerfile:9
--------------------
   7 |     RUN mkdir /opt/app/svws/conf
   8 |
   9 | >>> COPY app /opt/app/svws
  10 |     COPY conf /etc/app/svws/conf
  11 |     COPY startup.sh /opt/app/svws/startup.sh

```

**Comment by FPfotenhauer** [comment]
Ich gehe davon aus, dass das Problem erledigt ist, weil Sie woanders ja schreiben, dass Sie es nun am laufen haben.

**Comment by kroerig** [comment]
ja, nachdem ich festgestellt habe, dass die fehlenden Ordner aus dem Release File stammen. Eigentlich hätte ich erwartet, dass das irgendwo steht.
