### ISSUE TITLE
Fehler beim Druck von "Laufbahnwahlbogen gefilterte Schüler" 

### ISSUE THREAD

**Issue by AnneSchueller** [SVWS-NRW/SVWS-Server#80]
Für Q1 und Q2 klappt der Druck
Für Jg10 klappt der Druck "Laufbahnwahlbogen markierter Schüler" für alle SuS

![image](https://github.com/SVWS-NRW/SVWS-Server/assets/79116896/96e0976a-9346-47a0-b0fc-0e65469943c7)

Vt: Fehler beim Herunterladen der PDF-Datei zur Laufbahnplanung
    at Proxy. (https://localhost/assets/index.js:29:402299)
    at async c (https://localhost/assets/SGostLaufbahnfehler.js:1:4140)

**Comment by FPfotenhauer** [comment]
Du schreibt, dass der Druck klappt, aber postest dann eine Fehlermeldung.
Ich verstehe leider die Meldung nicht. Kannst du das bitte genauer erläutern?

**Comment by AnneSchueller** [comment]
Da habe ich zu ungenau geschrieben...
Für Jg 10 und EF führt der Druck Laufbahnwahlbogen gefilterte Schüler zu der oben genannten Fehlermeldung.

**Comment by FPfotenhauer** [comment]
In meiner DB kann ich das nicht nachvollziehen.
Ist das eine G9 Datenbank?
Das log aus der Browserkonsole wäre auch interessant.

**Comment by AnneSchueller** [comment]
Ich habe das nun auch nochmal mit einer anderen DB getestet und da funktioniert der Druck. 
Nach einem Sichern und neu importieren funktioniert der Druck auch bei der anderen DB.
Ich schließe das mal und teste nochmal weiter.

**Comment by FPfotenhauer** [comment]
Warte bitte mal auf die 0.8.10.
Es könnte sein, dass das behoben ist.
Wenn nein, bitte wieder öffnen.
