### ISSUE TITLE
0.8.8 Import von MSSQL-Datenbank -> Fehler 404

### ISSUE THREAD

**Issue by T-Hagel-SK** [SVWS-NRW/SVWS-Server#81]
Ich weiß, es gibt eine neue Version 0.8.9, dennoch würde ich die Fehlermeldung hier gerne erst mal erfassen.

Beim Versuch über /admin Kontakt zum Schild2-DB-Server aufzunehmen und eine Testschule zu importieren führt zur Fehlermeldung:
**https://svws-server.xxx.de/api/schema/migrate/admindb/mssql/163168%7D.
HTTP ERROR 404**

In logischer Reihenfolge gefolgt von Hinweis über die Chrome-Entwicklertools: 
"**Das Initialiseren des Schemas mit der Schild 2-Datenbank ist fehlgeschlagen.**" (RouteDataSchema.ts:352)

Als Parameter für den Server wurde dessen Domänenname:Portnummer eingetragen. Analog zum Eintrag in der JSON-Config-Datei.

Version 0.8.9 wird mir wohl erst Ende der Woche bereitstehen. Dann würde ich das dort noch mal testen.

Schöne Grüße
Thomas Hagel

Stadt Köln
Fachanwendungssupport

**Comment by FPfotenhauer** [comment]
Können Sie einmal probieren eine AccessDB zu migrieren?
Dürfen Sie folgendes Tool benutzen? https://dbeaver.io/
Das nutzt die gleichen Treiber, wie wir.
Wenn man damit eine Verbindung zur Schild2-MSSQL aufbauen kann, dann liegt der Fehler bei uns.
Wir können dazu auch gerne einen Termin vereinbaren. Vielleicht wenn die 0.8.9 läuft?
Und ja, Vor Karneval wird da wohl nichts mehr laufen :-)

**Comment by T-Hagel-SK** [comment]
Den Beaver nutze ich nur privat. Hier bei der Stadt ist der nicht in Betrieb genommen und kann daher auch nicht eingesetzt werden. Dafür haben wir die MySQL Workbench 8.0.22 im Einsatz. Ab morgen können wir wohl auch den ersten Schild3-Client testen (3.78.14). Jetzt müssten wir nur eine Datenbank zum Testen haben ...

Wäre es eine Überlegung bei den nächsten Versionen auch gleich eine Demo-Datenbank mitzuliefern, damit man schon mal sowas wie eine Testschule / -Umgebung hat, um z.B. die Clients testen zu können ? Oder macht das weniger Sinn, weil wohl nicht bei allen Testumgebungen mit Problemen zu rechnen ist ?

Jedoch, wenn ich eine Demo-Access-DB importieren möchte, bekomme ich einen HTTP-Fehler 500:
"_https://svws-server.xxx.de/api/schema/migrate/admindb/mdb
Diese Seite funktioniert nicht
Falls das Problem weiterhin besteht, wende dich an den Inhaber der Website.
HTTP ERROR 405_"

bzw. in den Chrome-Entwickler-Konsole angezeigt:
api/schema/migrate/admindb/mdb:1     Failed to load resource: the server responded with a status of 500 (Server Error)"

--

Wenn ich hingegen mit Swagger versuche ein Schema anzulegen, werden die Aussagen deutlicher:

400	Es wurde ein nicht erlaubter Schema-Name oder Benutzername angegeben.
403	Der angemeldete Benutzer verfügt nicht über die notwendigen Rechte zum Anlegen eines Schemas.
404	Die Schema-Datenbank konnte nicht geladen werden. Die Server-Konfiguration ist fehlerhaft.
500	Der Datenbankzugriff auf das neue Schema mit dem neuen zugehörigen Admin-Benutzer ist fehlgeschlagen oder das SVWS-Schema mit der aktuellen Revision konnte nicht angelegt werden.

Teste ich in Swagger hingegen auf "/config/db/schemata" bekomme ich die beiden Schemata "schild3-test" und "schild3_test" angezeigt. Die werden mir auch im SVWS-Server\admin in der Schema-Liste angezeigt, dort jedoch mit dem Hinweis "kein SVWS-Schema".

Teste ich in Swagger, ob der Datenbankbenutzer die ausreichenden Rechte hat, wird mir das mit "true" bestätigt.

Das Löschen eines Schemas geht in Swagger auch, allerdings bekomme ich die Fehlermeldung, das dies nicht möglich sei (/api/schema/root/destroy/{schema}
-> 403	Das Schema darf nicht gelöscht werden.
-> 404	Das angegebene Schema wurde nicht gefunden.

Aktualisiert man nun die /admin-Seite, ist das Schema weg.

Mal sehen, wie sich 0.8.9 hier schlägt ... mehr dazu eher Ende der Woche.

**Comment by ThomasBachran** [comment]
Der Name "schild3-test" könnte Probleme bereiten, da hier ein "-" im Namen des Schemas vorkommt. Je nach Zugriff kann dies zu Problemen führen (siehe https://mariadb.com/kb/en/identifier-names/, Abschnitt "Unquoted").

**Comment by T-Hagel-SK** [comment]
> Der Name "schild3-test" könnte Probleme bereiten, da hier ein "-" im Namen des Schemas vorkommt. Je nach Zugriff kann dies zu Problemen führen (siehe https://mariadb.com/kb/en/identifier-names/, Abschnitt "Unquoted").

Das fiel mir dann im Nachgang auch ein und habe das Ganze mit "Schild3_test" probiert anzulegen...
Gleiche Fehlerkette und Ergebnis. Schema wird angelegt und lässt sich löschen, mit besagten ausgegebenen Fehlertexten.

**Comment by T-Hagel-SK** [comment]
Ich habe es nun gerade auch bei Swagger mit dem Import der SchILD2000n.mdb versucht, am Ende kommt es aber zur Fehlermeldung "403   Das Schema darf nicht migriert werden."

Jedoch, aktualisiert man die /admin-Seite, taucht in der Schema-Übersicht die eben über Swagger angegebene "SchILD200n_Test"...

Ich würde ja gerne einen Export unserer Testschule als MDB importieren, jedoch ... gibt es beim Export aus dem Schulträgermodul im Moment ein Problem, über das Ribeka bereits informiert ist. Daher die Frage nach einer MDB-Datei, die sich zum Testen der generellen Funktionalität dieser Importfunktion einsetzen lässt.

**Comment by kroerig** [comment]
Hier gibt es Testdatenbanken
https://github.com/SVWS-NRW/SVWS-TestMDBs/archive/refs/heads/main.zip

**Comment by T-Hagel-SK** [comment]
> Hier gibt es Testdatenbanken https://github.com/SVWS-NRW/SVWS-TestMDBs/archive/refs/heads/main.zip

Perfekt, auch das ist nun in unserer Projektseite hinterlegt.

Aber auch damit klappt es nicht, Fehler 500.
Der ist mir beim Swaggertest gegen das Zertificat aufgefallen. Ich lass das mal unsere Webkollegen prüfen.

**Comment by kroerig** [comment]
> Den Beaver nutze ich nur privat. Hier bei der Stadt ist der nicht in Betrieb genommen und kann daher auch nicht eingesetzt werden.

Den gibt es auch als Portable App. https://portapps.io/app/dbeaver-portable/

**Comment by kroerig** [comment]
> Der Name "schild3-test" könnte Probleme bereiten, da hier ein "-" im Namen des Schemas vorkommt. Je nach Zugriff kann dies zu Problemen führen (siehe https://mariadb.com/kb/en/identifier-names/, Abschnitt "Unquoted").

Ich arbeite hier auch mit "-" im Datenbanknamen und habe keine Probleme damit.

Interessant wäre hier das Logfiles des SVWS Servers. Da muss ja irgendwo ein Prozess abbrechen. Ggf. hat die JavaVM zuwenig RAM. Die genehmigt sich bei der Datenbankmigration gerne mal bis zu 8GB pro Vorgang.

**Comment by T-Hagel-SK** [comment]
So SVWS-Server 0.8.9 steht mir nun zur Verfügung. Aber der Import aus der Schild2-Datenbank will immer noch nicht gelingen. 

Was aber nun klappt, viiiielen Dank dafür, ist, dass die Daten für die Quelldatenbank bestehen bleiben und nicht jedes Mal neu eingefügt werden müssen.

Aber es bleibt dabei, dass der Fehler 404 auftritt ("Fehler beim Aufruf der API-Methode Not Found (404)")
Hierzu hatte ich zuvor ein Schema schild3_999888 erstellt, das laut Datenbank auch von ."AllgAdrAnsprechpartner" bis "ZuordnungReportvorlagen" angelegt wurde, Aber danach einen Fehler auswirft. Den würde ich gerne in einem anderen Issue erfassen. Im Grunde ist es egal, welches Schema ich auswähle, es bleibt beim Fehler 404 beim MS-SQL-Import.
In der Chrome-Konsole steht dazu:
![20240208-SVWS-Server_0-8-9_Importieren_aus_Schild2-Datenbank_Fehler_404](https://github.com/SVWS-NRW/SVWS-Server/assets/158161190/bab59e20-df34-45d6-b9a4-650487b1514b)

**Comment by kroerig** [comment]
> Was aber nun klappt, viiiielen Dank dafür, ist, dass die Daten für die Quelldatenbank bestehen bleiben und nicht jedes Mal neu eingefügt werden müssen.

Das sehe ich bei mir im FF nicht. Da muss ich immer neu Tippen.

**Comment by ThomasBachran** [comment]
> dass der Fehler 404 auftritt ("Fehler beim Aufruf der API-Methode Not Found (404)")

Gibt es in der Browser-Konsole unter dem Tab `Network` bei der Detailansicht zur `Response` noch weitere Informationen zu dem Fehler?

**Comment by T-Hagel-SK** [comment]
> Ich sehe es gerade erst: Da steht ein %7D ( } ) nach dem Namen der Datenbank.
> 
> Das gehört da nicht hin. Wo kommt das her? Da ist ein Syntaxfehler.

Ja, das "%7D" hatte ich auch gesehen und den Aufruf ohne den Anhang probiert, gleiches Ergebnis...

**Comment by T-Hagel-SK** [comment]
> > dass der Fehler 404 auftritt ("Fehler beim Aufruf der API-Methode Not Found (404)")
> 
> Gibt es in der Browser-Konsole unter dem Tab `Network` bei der Detailansicht zur `Response` noch weitere Informationen zu dem Fehler?

![20240209_SVWS-Server_0-8-9_Import_aus_MSSQL_DB_Fehler_404_Ansicht_Konsole_Netzwerk](https://github.com/SVWS-NRW/SVWS-Server/assets/158161190/02db9cdb-32e7-44a0-82a4-651c78cb5128)

Ja, aber es dreht sich wohl um das Anhängsel "%7D" ...

**Comment by ThomasBachran** [comment]
Das ist tatsächlich ein Bug im Admin-Client. Dieses Problem sollte dann im nächsten Pre-Release behoben sein.

**Comment by T-Hagel-SK** [comment]
In Swagger sieht der CURL-Aufruf so aus:
curl -X 'POST' \
  'https://svws-server.xxx.de:8443/db/s999888/migrate/mssql/999888' \
  -H 'accept: application/json' \
  -H 'Authorization: Basic c2NoaWxkX3BvYzpkMFJFZVB1TTBUZkFNeWNCc1NVSQ==' \
  -H 'Content-Type: application/json' \
  -d '{
  "username": "schild_demo",
  "password": "xxxxx",
  "location": "1xx.xx.xx.xx:50200",
  "schema": "schild_999888"
}'

Request URL
https://svws-server.vxx.de:8443/db/s999888/migrate/mssql/999888

Server response
Code	Details
403	
Error: response status is 403

Response headers
 content-length: 0 
 server: Jetty(11.0.16)

**Comment by ThomasBachran** [comment]
Das ist jetzt ein 403 und kein 404 mehr. Die Rückmeldung ist also ein Forbidden. Hier müsste man prüfen, ob der angegeben Benutzer auf diesem Weg überhaupt eine Berechtigung für den Zugriff auf dieses Schema hat. Für die weitere Fehleranalyse würde ich vorschlagen mit dem Tool DBeaver auf die MSSQL-Datenbank zuzugreifen. Dieses verwendet auch den JDBC-Treiber und greift daher ähnlich auf die DB zu wie der SVWS-Server.

**Comment by T-Hagel-SK** [comment]
> [...] Hier müsste man prüfen, ob der angegeben Benutzer auf diesem Weg überhaupt eine Berechtigung für den Zugriff auf dieses Schema hat. [...]

Wenn mit "der angegebene Benutzer" der gemeint ist, der auf dem DB-Server die Rechte zum Anlegen neuer Schemata hat, dann konnte das damit bestätigt werden, dass ich unter diesem Nutzer über Swagger Schemata anlegen konnte (bevor sie in einen Fehler gehen ... siehe Issue 82".

Ein Testen mit DBeaver kann ich hier leider nicht anbieten. Das wäre mit einem weiteren Inbetriebnahmeprozess verknüpft, wozu mir schlicht die Zeit fehlt. Mit der SQL Workbench besteht jedenfalls die Verbindung zur Datenbank. Jeweils unter dem gleichen Benutzer.

**Comment by T-Hagel-SK** [comment]
Gerade mal unter Swagger mit root getestet und folgendes erhalten:
can't parse JSON.  Raw result:

Exception [EclipseLink-4002] (Eclipse Persistence Services - 4.0.2.v202306161219): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
Error Code: 0

D.h. es hakt offenbar an der Kommunikation zwischen SVWS-Server und dem Schild2-DB-Server ...

Vielleicht wäre es hilfreich, hier noch eine Kommunikationsprüfroutine mit reinzuziehen, die prüft, ob eine Verbindung zum der Schild2-Datenbank funktioniert ?
