### ISSUE TITLE
0.8.9 Fehler beim Erstellen des Schemas

### ISSUE THREAD

**Issue by T-Hagel-SK** [SVWS-NRW/SVWS-Server#82]
Beim Erstellen im /admin-Bereich über das "+"-Zeichen in der Schema-Übersicht werden zwar laut Datenbank allerlei Tabellen angelegt, aber nach oder zum Erstellen der Trigger für Auto-Inkremente für die Tabelle "ZuordnungReportVorlagen" meldet die Seite einen Fehler. 
![20240208_SVWS-Server_0-8-9_Anlegen_Schema_Fehler_beim_Erstellen_Schema_ist_aber_bis_ZuordnungReportVorlagen_erstellt](https://github.com/SVWS-NRW/SVWS-Server/assets/158161190/d334c529-1339-4cef-8955-54b07bf51899)

Im Swagger passiert das Gleiche, hier mal als JSON-Datei eingefügt (jedoch ohne Angabe unserer DB-Server).
[response_1707381502541.json](https://github.com/SVWS-NRW/SVWS-Server/files/14208172/response_1707381502541.json)

Auch hier bricht das Script (erwartungsgemäß) an der gleichen Stelle ab.

Wenn ich mir den Quelltext zu "Schema.java" anschaue, vermisse ich jedoch einige Tabellen, wie z.B. exemplarisch "Stundenplan_Kalenderwochen_Zuordnung", "Stundenplan_UnterrichtLehrer", "DavRessources". Naja, alles, was nicht in der obigen json-Datei aufgeführt wird. Sind das evtl. die Tabellen, die noch fehlen ?

Vielleicht offtopic, aber beim Quellcodestöbern ist mir in der Datei "Migration.iss" ist u.a. in Zeile 374 aufgefallen, dass dort steht:
'-k -X POST "https://localhost/api/schema/root/migrate/mssql/' + SVWSDBSchema + '" ' +

Warum "/root/" ? Könnte das den Fehler 404 auslösen ?

Ist "root" hier als Hauptverzeichnis, oder der Benutzer "root" zu verstehen, der beim Aufruf der SWVS-URL voreingestellt bei der Anmeldung zu finden ist ? Oder bin ich hier auf der falschen Fährte ?

**Comment by kroerig** [comment]
Das `/root` in der URI gibt an, dass für diesen Endpunkt "Root-Rechte" im Datenbankserver benötigt werden, da hier neben der Datenbank auch Benutzer (GRANT-Rechte) erzeugt werden.

**Comment by T-Hagel-SK** [comment]
> Das `/root` in der URI gibt an, dass für diesen Endpunkt "Root-Rechte" im Datenbankserver benötigt werden, da hier neben der Datenbank auch Benutzer (GRANT-Rechte) erzeugt werden.

Ich glaube nicht, dass hier der Datenbankserver gemeint ist, sondern schon der WebClient.

**Comment by FPfotenhauer** [comment]
OK. Das bedeutet aber, dass dei Verbindung zur MariaDB nun prinzipiell klappt.
Das ist nicht einfach zu debuggen, weil hier anscheinend im SVWS-Server etwas nicht ausgeführt wird.
Welchen FehlerCode liefert die BrowserConsole?

**Comment by kroerig** [comment]
@FPfotenhauer Wir hatten die Steps telefonisch mal durchgespielt und die Migration "eine Schule als Schild-Zentral (MSSQL)" nach SVWS über die SwaggerUI angestoßen.

Es kommt die Rückmeldung "403 - Das Schema darf nicht migriert werden".

Ich hatte @T-Hagel-SK noch gebeten, den Logauszug aus der SwaggerUI hier zu posten, bevor mein Telefonakku leer war.

Was löst die Meldung "Das Schema darf nicht migriert werden" aus?

**Comment by ThomasBachran** [comment]
@kroerig: 403 ist der HTTP-Response-Code für FORBIDDEN. Bei diesem API-Aufruf wird das z.B. dadurch ausgelöst, das keine Verbindung zu dem SQL-Server aufgebaut werden kann. Bei manchen API-Aufrufen findet sich dann eine genauere Fehlerbeschreibung in der HTTP-Response.

**Comment by kroerig** [comment]
dann hilft uns wohl nur das Log.

**Comment by FPfotenhauer** [comment]
Ich hatte ja schon einmal gefragt, ob grundsätzlich die Verbindung zur MSSQL-DB möglich ist.
Mit z.B. DBeaver könnte man das testen. Und es wäre gut, zu erfahren, ob das Schulträgermodul von SchildZentral3 diese Verbindung schafft. Denn das macht ja auch nichts anderes als die API aufzurufen....

**Comment by kroerig** [comment]
Wenn ich @T-Hagel-SK richtig verstanden habe, dann lässt es die Securitypolicy nicht zu Programme und Skripte zu benutzen, die nicht von der IT freigegeben wurden.

Das ist zwar sehr löblich im Sinne der Sicherheit, macht aber eine Fehlersuche umständlicher.

**Comment by T-Hagel-SK** [comment]
> Das ist zwar sehr löblich im Sinne der Sicherheit, macht aber eine Fehlersuche umständlicher.

Das ist nicht löblich, das ist in einem Umfeld wie unserem Rechenzentrum unerlässlich. Wenn ich hier DBeaver in Betrieb nehmen lasse, hätte ich eine Menge Arbeit vor mir. Es ließe sich jedoch einfacher gestalten, in dem man in die Adminseite genau das einbaut ... eine Prüfung, ob ein Zugriff auf die Datenbank möglich ist. Das Schematool von Ribeka bietet das z.B. überall dort an, wo man die Zugangsdaten eintragen kann. Von dort aus klappt der Aufbau und auch das Auslesen der Schulen funktioniert darüber. Jedoch scheitert der Import aus anderen Gründen, die im Supporttool von Ribeka gemeldet wurden.

Man (ich inkl.) muss sich hierbei immer auch in den Hinterkopf rufen, dass wir es mit 2 Welten zu tun haben: 
die eine Welt, in der SchildNRW innerhalb des schulischen Verwaltungsnetzes arbeitet und eine andere, in der das Programm zentral, für mehrere Schulen innerhalb einer zentralen Datenbank bereitgestellt wird. Hier und da könnte es aber auch Schulen geben, in denen MSSQL-Datenbanken zum Einsatz kommen.

Mittlerweile habe ich auch Zugriff auf die Logdateien ... aber auch hier finden sich auch keine anderen Beschreibungen, außer den bereits bekannten. Sowohl über die /Admin-Seite, als auch über Swagger lassen sich die Schemata ja hinzufügen. Sie enden jedoch in der wenig aussagekräftigen Meldung, dass ein Fehler aufgetreten sei.

Logfile Swagger:
1xx.xx.xx.xx - schild_xxx [13/Feb/2024:15:02:43 +0000] "POST /api/schema/root/create/test_schema_swagger/1 HTTP/2.0" 200 8837 "https://svws-server.xx.de:8443/debug/privileged/index.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"

In Swagger steht jedoch auch:
400	
Es wurde ein nicht erlaubter Schema-Name, Benutzername oder eine ungültige Revision angegeben.

No links
403	
Der angemeldete Benutzer verfügt nicht über die notwendigen Rechte zum Anlegen eines Schemas.

No links
404	
Die Schema-Datenbank konnte nicht geladen werden. Die Server-Konfiguration ist fehlerhaft.

No links
500	
Der Datenbankzugriff auf das neue Schema mit dem neuen zugehörigen Admin-Benutzer ist fehlgeschlagen oder das SVWS-Schema mit der Revision konnte nicht angelegt werden.

Jedoch: in der SVWS-Datenbank wurde das jeweilige Schema wie oben beschrieben erstellt und augenscheinlich mit Tabellen gefüllt. Es ist aber unklar, warum hier ein Fehler ausgegeben wird und warum Swagger hier behauptet, dass ein falscher Nutzer eingegeben wurde. 

Also habe ich unter dem aussagefreundlicherem Swagger das Anlegen mal mit falschen Zugangsdaten probiert. Das wird erkannt und direkt mit "Fehler beim Erstellen der Datenbankverbindung zum Ziel-Schema. Sind die Anmeldedaten korrekt?" korrekt im Response Body ausgegeben.

Wiederhole ich den Prozess (ohne Schema/Revision zu ändern) nun aber  mit dem korrekten Passwort, bricht der Vorgang ab, weil "  Fehler: Schema ist bereits vorhanden und kann deswegen nicht neu angelegt werden!". Siehe da, in der Datenbank wurde trotz Fehler in den Zugangsdaten unter "Der Benutzername und das Kennwort für den administrativen Zugang zum Schema", das Schema angelegt. Aber nicht mit Tabellen gefüllt.

Wiederhole ich den Prozess mit einer neuen Schemabezeichnung wird das Schema angelegt und mit der oben beschriebenen Liste (json-Datei) von Tabellen befüllt. 

Daher die Frage, was nach den Tabellen noch in die Datenbank geschrieben wird, wozu scheinbar das Benutzerkonto dann nicht mehr ausreicht ?
Und Zusatzfrage, welche konkrete Benutzerrechte muss dieser Datenbankbenutzer haben ? 

Anlegen und Löschen von Schemata kann unser Benutzer offenbar, Tabellen werden auch angelegt. Wie verhält sich das mit Indizies ? Oder Views, etc. ? Werden die auch angelegt ? Braucht es hierzu ggf. erweiterte DB-Benutzerrechte ?

Was ist mit "Revision" gemeint und wo wird das in der Datenbank vermerkt ? Im Schema-Namen ?

**Comment by ThomasBachran** [comment]
@T-Hagel-SK : Meine Vermutung an dieser Stelle ist, dass der Verbindungsaufbau an einer Konfigurationseinstellung beim Server scheitert, weil der SVWS-Server damit bisher nicht umgehen kann. Dies dürfte zu einer Exception führen, die bei uns zu allgemein angefangen wird.

Eine Möglichkeit ist, dass dies mit der TLS-Verschlüsselung und der dazugehörigen Zertifikatseinstellung zu tun haben könnte. Wenn die Zertifikatsdaten z.B. irgendwie nicht zu dem verwendeten Hostnamen des MSSQL-Servers passen, dann schlägt die Verbindung fehl. Hier haben sich auch im JDBC-Treiber nach und nach mehrere Änderungen ergeben. Ich habe im Laufe der letzten Tage den verwendeten JDBC-Treiber aktualisiert und mehrere Anpassungen vorgenommen, damit der SVWS-Server flexibler mit solchen Problemen umgehen kann. Auch im Admin-Client habe ich einen Bug bezüglich MSSQL gefixt.

Diese Anpassungen werden dann im nächsten Pre-Release zur Verfügung stehen. Ich würde sie dann bitten nochmal zu prüfen, ob der SVWS-Server dann in ihrer Umgebung mit dem Verbindungsaufbau zurecht kommt und die Verbindung aufbauen kann.

**Comment by kroerig** [comment]
> In Swagger steht jedoch auch: 400 Es wurde ein nicht erlaubter Schema-Name, Benutzername oder eine ungültige Revision angegeben.
> 
> No links 403 Der angemeldete Benutzer verfügt nicht über die notwendigen Rechte zum Anlegen eines Schemas.
> 
> No links 404 Die Schema-Datenbank konnte nicht geladen werden. Die Server-Konfiguration ist fehlerhaft.
> 
> No links 500 Der Datenbankzugriff auf das neue Schema mit dem neuen zugehörigen Admin-Benutzer ist fehlgeschlagen oder das SVWS-Schema mit der Revision konnte nicht angelegt werden.

Das sind nur Beispiele und Teil der OpenAPI- Dokumentation. Der interessante Teil steht darüber.

> Daher die Frage, was nach den Tabellen noch in die Datenbank geschrieben wird, wozu scheinbar das Benutzerkonto dann nicht mehr ausreicht ?
> Und Zusatzfrage, welche konkrete Benutzerrechte muss dieser Datenbankbenutzer haben ?

Der 'root' Benutzer unter MariaDB hat alle Rechte (ALL PRIVILEGES), daher wird dieser bei der Migration verwendet. Zumindest aber mal braucht der verwendete Benutzer Rechte

- Datenbanken verwalten
- Tabellen verwalten
- Views verwalten
- Trigger verwalten
- Indizes verwalten
- Benutzer und Rechte verwalten

> Was ist mit "Revision" gemeint und wo wird das in der Datenbank vermerkt ? Im Schema-Namen ?
Revision meint die Version der Datenbankstruktur. Immer dann wenn Änderungen an der Struktur erfolgen wird die Revision um eins erhöht. Welche Revision das Schema hat, steht in der Tabelle `Schema_Status`. Damit prüft der Server ob bei einem Update Migrationen erforderlich sind. Das sieht man dann auch schön beim Start des Servers im Log.

> Es ließe sich jedoch einfacher gestalten, in dem man in die Adminseite genau das einbaut ... eine Prüfung, ob ein Zugriff auf die Datenbank möglich ist.

Die Prüfung gibt es in der API. Die interessanten Zeilen im Response/ Log sind diese (hier am Beispiel Ziel und Quelle MariaDB; was anderes habe ich nicht):
```
svws_1     | Es wird aus dem Datenbankformat 'MARIA_DB' migriert.
svws_1     | Migriere in die MARIA_DB-Datenbank unter mariadb:
svws_1     |   - verwende den root-benutzer: root
svws_1     |   - erstelle das DB-Schema: svws
svws_1     |   - erstelle den Benutzer "svws" für den administrativen Zugriff auf das DB-Schema.
svws_1     | Erstelle Ziel-Schema für MARIA_DB (mariadb/svws)
svws_1     |   -> Verbinde mit einem DB-Root-Manager zu der Ziel-DB...
svws_1     |     - Datenbank-Verbindung erfolgreich aufgebaut (driver='MARIA_DB', schema='svws', location='mariadb', user='svws')
svws_1     |     - Entferne aus der Ziel-DB das alte Schema, falls vorhanden... [OK]
svws_1     |     - Erstelle in der Ziel-DB das Schema und den Admin-Benutzer: [OK]
svws_1     | Migriere von MARIA_DB (192.168.20.202:3306/schild_nrw_test) nach MARIA_DB (mariadb/svws)
svws_1     |   -> Verbinde zur Quell-Datenbank...  [OK]
svws_1     |   Datenbank-Verbindung erfolgreich aufgebaut (driver='MARIA_DB', location='192.168.20.202:3306', user='schild_nrw')
svws_1     |   -> Verbinde zum Ziel-Schema... [OK]
svws_1     |   Datenbank-Verbindung erfolgreich aufgebaut (driver='MARIA_DB', location='mariadb', user='svws')
svws_1     |   -> Erstelle in der Ziel-DB ein SVWS-Schema der Revision 0
```

> Eine Möglichkeit ist, dass dies mit der TLS-Verschlüsselung und der dazugehörigen Zertifikatseinstellung zu tun haben könnte. Wenn die Zertifikatsdaten z.B. irgendwie nicht zu dem verwendeten Hostnamen des MSSQL-Servers passen, dann schlägt die Verbindung fehl.

 @ThomasBachran Das könnte eine Ursache sein. Insb. dann, wenn interne CAs im Einsatz sind, deren Stammzertifikate das Java JRE nicht validieren kann. Wie geht der SVWS Server damit um? Hier wäre dann ggf. ein optionaler Parameter `ignoreTLS` hilfreich, der einfach alle TLS Fehler übergeht. Oder aber man müsste eigene CAs importieren können. Java nutzt ja nicht die Stammzertifikate des Betriebssystems.

**Comment by T-Hagel-SK** [comment]
> @T-Hagel-SK : Meine Vermutung an dieser Stelle ist, dass der Verbindungsaufbau an einer Konfigurationseinstellung beim Server scheitert, weil der SVWS-Server damit bisher nicht umgehen kann. Dies dürfte zu einer Exception führen, die bei uns zu allgemein angefangen wird.

Da würde ich mitgehen, aber, die Verbindung vom SVWS-Server zur SVWS-Datenbank ist ja da, eben weil dort ein Schema angelegt und mit den Tabellen von A-Z gefülllt werden kann. Die Frage die bleibt, ist ja, was geschieht nach der letzten Tabelle und warum es zu einem Fehler führt ?

Bzw. ist es überhaupt ein Fehler ? Wie kann ich feststellen, ob ein vom SVWS-Server angelegtes Schema vollständig ist ?

Zu TLS und Zerfifikaten. Greift der Ansatz denn auch in diesem Fall, wo ja eine Kommunikation und ein Schreiben auf der Datenbank möglich ist ?

**Comment by kroerig** [comment]
> Wäre es daher vielleicht eine Idee, mal sowas wie einen Online-Workshop anzubieten ?

Die wird es sicher geben, wenn das Produkt fertig ist (wenn man bei Software je von fertig reden kann). Den normalen Anwender und Schuldamin interessiert die API im normalen Betrieb nicht. Wir sind hier aber ja noch in der Entwicklungsphase und da ist es machmal hilfreich direkt die Schnittstellen anzusprechen. Dann sieht man nämlich ggf. mehr als in den graphischen Oberflächen.

Im JSON oben sehen wir ja, dass der Prozess mittendrin mit einem Fehler abbricht. Ich würde wetten, dass wir an der Stelle eine Java Exception im Server-Log sehen.

Also @T-Hagel-SK: Während der Prozess läuft mal das Server-Log auf der Konsole mitlaufen lassen und schauen, was dort steht, wenn der Prozess abbricht. Da sollte ein Stack-Trace ausgegeben werden.
(Wir können das gerne per Telefon und Teamviewer gemeinsam machen, klingeln Sie einfach mal durch.)

**Comment by FPfotenhauer** [comment]
@T-Hagel-SK Bitte warten Sie einmal das kommende Release ab. Darin sind die Änderungen im Treiber. Vielleicht ist das Problem dann ja gelöst.

**Comment by T-Hagel-SK** [comment]
> Also @T-Hagel-SK: Während der Prozess läuft mal das Server-Log auf der Konsole mitlaufen lassen und schauen, was dort steht, wenn der Prozess abbricht. Da sollte ein Stack-Trace ausgegeben werden. (Wir können das gerne per Telefon und Teamviewer gemeinsam machen, klingeln Sie einfach mal durch.)

Das ist ein nettes Angebot, aber, auch das ist hier in meinem Umfeld nicht ohne weiteren Aufwand möglich. Ich habe hier einzig einen Webserver, den ich im Browser aufrufen kann. Ich habe keine Konsole und ich habe keinen Zugriff auf Betriebssystemeebene. Alles was ich dort testen oder einstellen will, muss über Arbeitsaufträge beauftragt werden, damit diese nun mal dokumentiert von den jeweiligen Experten ausgeführt wird und nicht durch einen technikinteressierten Anwendungssupporter :-)


> Wir müssen die Verbindung zu MSSQL ja nur für die Migration hinbekommen, danach benötigen wir das nicht mehr.
Die Verbindung zum MSSQL-Server ist m.E. für das Anlegen eines Schemas auf dem SVWS-Datenbankserver (MariaDB) nicht notwendig. Die kommt ja erst dann zum Tragen, wenn man den Import anwirft ... Das war ja Thema des Issues 81, das bereits geschlossen wurde.

Im übrigen habe ich ein paar Zweifel, dass das Ribekatool für die Schemaverwaltung die API für den Import aus SchildZentral verwendet. da die Verbindung zum SchildZentral-DB-Server funktioniert. Aber vom SVWS-Server aus nicht. Es wird wohl sicherlich andere APIs nutzen, aber die zum Aufbau zur SchildZentral-DB eher nicht (Spekulativ).

**Comment by FPfotenhauer** [comment]
Wir haben hier überhaupt keine Eile und wenn das Einspielen des neuen Releases etwas dauert, dann ist das eben so.
Wenn aber der Fehler im MSSQL-Treiber stckt, dann wird man um die neue Version nicht herum kommen.

Und ich bin mir sehr sicher, dass das Schild-Zentral-Tool die Migartion über unsere API macht.
Wenn von dort aus nach SVWS migriert werden kann, dann wäre die Information wichtig, wie (welche genau) die Parameter an den SVWS-Server übergeben werden.

**Comment by T-Hagel-SK** [comment]
Sooo ... nun liegt mir auch das Logfile von gestern von Java vor ...

Der Casus Knacksus ist folgender:
Feb 13 15:11:35 kvmua618 java[3228260]:       -> Erstelle Trigger für Auto-Inkremente
Feb 13 15:11:35 kvmua618 java[3228260]: [qtp905654280-69] WARN org.mariadb.jdbc.message.server.ErrorPacket - Error: 1419-HY000: You do not have the SUPER privilege and binary logging is enabled (you *might* want to use the less safe log_bin_trust_function_creators variable)
Feb 13 15:11:35 kvmua618 java[3228260]: [EL Warning]: 2024-02-13 15:11:35.476--UnitOfWork(1657904059)--Exception [EclipseLink-4002] (Eclipse Persistence Services - 4.0.2.v202306161219): org.eclipse.persistence.exceptions.DatabaseException
Feb 13 15:11:35 kvmua618 java[3228260]: Internal Exception: java.sql.SQLException: (conn=87037) You do not have the SUPER privilege and binary logging is enabled (you *might* want to use the less safe log_bin_trust_function_creators variable)

Dieses Fehlerbild wiederholt sich bei den weiteren Versuchen Trigger anzulegen.
Ich klär das mal mit unseren Datenbankkollegen

**Comment by T-Hagel-SK** [comment]
Rückmeldung von den Datenbankkollegen. Der Datenbankbenutzer war soweit korrekt eingerichtet, aber ...

Der aktivierte BINLOG führte dazu, dass der Server sich weigert, dass u.A. trigger angelegt werden.
siehe auch: [https://dev.mysql.com/doc/refman/8.0/en/stored-programs-logging.html](url)

Nach Anpassen der Option in der Config 
--log_bin_trust_function_creators=ON

lassen sich nun auch bei uns die Schemata fehlerfrei anlegen.

(Ein Import aus SchildZentral klappt noch nicht, auch ein Import aus einer MDB klappt noch nicht, aber hierzu wollten wir ja noch das nächste Release abwarten).

**Comment by FPfotenhauer** [comment]
Ich schließe das hier.
