### ISSUE TITLE
Ansicht Filter Kursblocken

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/SVWS-Server#84]
![grafik](https://github.com/SVWS-NRW/SVWS-Server/assets/84628225/b36b67ef-cebd-4207-9b0a-60fc670ac34e)
Kann dieser Filter als Default immer sichtbar sein?
Wird immer benötigt, und wenn es nur die Ansicht ist, welcher Kurs gerade angeklickt wurde.

**Comment by hmt** [comment]
Der Filterstatus wird nun in der Benutzerkonfiguration abgelegt. Also einmal geöffnet, bleibt es so, initial ist der Filter geöffnet.
