### ISSUE TITLE
Kursblockung Anzeige Schienennamen

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/SVWS-Server#85]
Ändert man den Schienen namen bleibt
die Nummer dennoch stehenund der Name erscheint nicht.
Außerdem bleibt immer ein Eingabefenster sichtbar und verschwindet nicht mehr.
![grafik](https://github.com/SVWS-NRW/SVWS-Server/assets/84628225/ad7c60e7-ad78-4633-9413-072ee362c65b)

**Comment by hmt** [comment]
Ein Klick woanders schließt das Feld nun auch.
In der Tabelle oben bleibt der Name bei der Schienennummer, das ist so beabsichtigt, weil der Platz sonst nicht reicht. Der Name wird aber in der Umwahlansicht so wie eingegeben angezeigt.
Mit esc kann man die Eingabe ebenfalls abbrechen.

**Comment by NielsWL** [comment]
Kann der Name nicht zusätzlich angezeigt werden? Das finde ich auch wichtig! Evt mit gedrehter Schrift?

**Comment by ThomasBachran** [comment]
Das mit dem Platzsparen werden wir als Default so lassen. Im nächsten Pre-Release werden wir einen Knopf anbieten, welcher das Verhalten aber Benutzerspezifisch umstellt. Das ist dann für die Schulen interessant, die ihre Schienen gezielt benennen wollen.
