### ISSUE TITLE
Kursblockung Anzeige Extern

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/SVWS-Server#86]
Kann zu der Eigenschaft "Extern" noch die Schulnummer der externen Schule angezeigt werden?
Hintergrund: Wir haben zwei Koopschulen, oft ist wichtig zu erkenn, von wo jemand genau kommt.
![grafik](https://github.com/SVWS-NRW/SVWS-Server/assets/84628225/78b94cfe-d516-4932-89d9-da6e9fceaabb)

**Comment by hmt** [comment]
kommt nun direkt hinter `extern`: (extern 123456)
