### ISSUE TITLE
Kurs für weitere S sperren

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/SVWS-Server#87]
![grafik](https://github.com/SVWS-NRW/SVWS-Server/assets/84628225/1f2b8825-b652-4301-9c68-b6d7197dd0d5)
Wunsch: 
Kursauswahl: Kurs für weitere Schüler sperren.

Also wenn in einem Kurs 3 S fixiert wurden, darf niemand mehr dazu.

**Comment by benjaminbartsch** [comment]
Da überlege ich mir eine Regel wie zB
KURS X FÜR NICHTFIXIERTE SUS SPERREN
ich muss mal gucken, wie sich das im Algorithmus umsetzen lässt.

**Comment by HHayen** [comment]
Es geht natürlich über: 
Bestehende Schüler im Kurs fixieren, dann Schülerzahl für den Kurs auf die Anzahl der bestehenden Schüler begrenzen. Aber Sperren wäre netter.

**Comment by benjaminbartsch** [comment]
@NielsWL , @HHayen: Also eine Extra-Regel dafür einzuführen halte ich nicht für gut, gerade auch wenn es plötzlich dann beide Regeln gibt "sperre den Kurs" und "Kurs-Obergrenze = 20 SuS", was hätte dann bei Nichteindeutigkeit höhere Priorität.

Wir können aber "Kurs für weitere SuS sperren" als Synonym nehmen für "Kurs ____ begrenzen auf maximal ____ SuS" und diese Regel dann automatisch generieren. Aber hier ergibt sich die Frage, wie sich dies in verschiedenen Szenarien verhalten soll. Da brauche ich von euch Hinweise, wie es aus Benutzer-Sicht gewünscht ist.

1) Der Kurs hat 3 fixierte SuS und 0 nicht fixierte SuS und es gibt noch **keine** Kurs-Obergenzen-Regel.
2) Der Kurs hat 3 fixierte SuS und 20 nicht fixierte SuS und es gibt noch **keine** Kurs-Obergenzen-Regel.
3) Der Kurs hat 3 fixerte SuS und 0 nicht fixierte SuS und es gibt bereits **eine** Kurs-Obergenzen-Regel.
4) Der Kurs hat 3 fixerte SuS und 20 nicht fixierte SuS und es gibt bereits **eine** Kurs-Obergenzen-Regel.

Meine Gedanken dazu:
1) --> max. 3 Regel erstellen
2) --> ??? unklar 3 oder 23 ? Bei 23 muss dann klar sein, dass die 20 nicht fixierten SuS wechseln könnten.
3) --> nichts tun oder Regel überschreiben mit dem Wert 3?
4) --> nichts tun oder Regel überchreiben mit dem Wert aus 2)?

**Comment by HHayen** [comment]
Ich habe gerade viele Situationen durchgespielt: Es genügt, Schüler zu fixieren, dann die Schülerzahl auf genau diese Menge zu begrenzen.
Habe es auch so in die Doku ([help.svws-nrw-de/gost](https://help.svws-nrw.de/gost/kursplanung/#beispiele-und-praxistipps) als Beispiel übernommen.
Das ist sogar flexibler als den Kurs für weitere zu sperren.
Aus meiner Sicht kann das Issue geschlossen werden, da das damit verbundene Problem gelöst werden kann.
Ich hätte aber aus alter Kurs42-Gewohnheit immer noch gerne die Möglichkeit, Kurse beim Blocken unberücksichtigt zu lassen. 
Es ist keine falsche Praxis, immer mal nur bestimmt Kurse zu blocken, z.B nur den Mu-Ku-VoPro-Bereich, oder nur die Reli-PP-Kurse oder einfach nur die LKs. Geht alles über Fixierungen, aber das alte **Ja/Nein** war schon recht praktisch.

**Comment by benjaminbartsch** [comment]
Das Issue zu schließen finde ich gut. ;-) Ich warte aber noch damit, bis Nils das okay gibt.

Für "Ja/Nein" bitte ein neues Issue öffnen.

**Comment by NielsWL** [comment]
Hauke:
Ich habe gerade viele Situationen durchgespielt: Es genügt, Schüler zu fixieren, dann die Schülerzahl auf genau diese Menge zu begrenzen.
Habe es auch so in die Doku (help.svws-nrw-de/gost ) als Beispiel übernommen.


Finde ich super!
