### ISSUE TITLE
Kurse beim Blocken nicht berücksichtigen

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/SVWS-Server#88]
Wäre ein Haken für:
Kurs beim Blocken ignorieren sinnvoll?

Oder kann das anders realisiert werden derzeit? z.B. so:
1. Kurs in Schiene fixieren
2. Kurs Schüler fixieren
3. Kurs für weitere Schüler sperren

**Comment by ThomasBachran** [comment]
Ich würde das über die Fixier- und Sperr-Regeln handhaben, ansonsten sehe ich das Problem, dass die GUI noch komplexer und unübersichtlicher wird, was wir vermeiden sollten..
