### ISSUE TITLE
Fehler: LuPO Import (LuPO Version 2.1.7.3)

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#89]
Beim erneuten Import der LuPO-Datei wird ein Fehler angezeigt, da die Anzahl der Schüler nicht übereinstimmt, da in der LuPO-Datei bereits potentielle Neuzugänge enthalten sind. Da ich die Neuzugänge aber in Schild nicht anlegen kann, ohne dass dieser Fehler (https://github.com/SVWS-NRW/SVWS-Server/issues/79) entsteht, weiß ich nicht weiter...
Der Fehler ist reproduzierbar.

<img width="732" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/b28d5f33-d632-4a2b-8211-8f5b21b24ab5">

**Comment by ThomasBachran** [comment]
Das Anlegen von Schülern über einen LuPO-Import ist nicht geplant. Die Schüler sollen zur Zeit über Schild 3 angelegt werden. Danach kann man die Fachwahlen wie gewohnt aus LuPO importieren, wenn in LuPO die Schüler-ID gesetzt ist. Da dies mit Issue #79 zusammenhängt schließe ich dieses Issue.
