### ISSUE TITLE
LuPO-Import (SVWS WebLuPO 0.8.9)

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#90]
Beim Einzelimport von Laufbahndaten (bearbeitet mit WebLuPO 0.8.9) sollte ein Protokoll der Veränderungen angezeigt werden.

**Comment by FPfotenhauer** [comment]
Es wäre gut, wenn wir soetwas auf Die Version nach 1.0.0 verschieben könnten.
