### ISSUE TITLE
Kursplanung: Regeln

### ISSUE THREAD

**Issue by NielsWL** [SVWS-NRW/SVWS-Server#91]
Es sind ja einige Regeln, die noch beim Blocken benötigt werden. Zum Beispiel für das Blocken der Q2, wenn die Zusatzkurse hinzukommen und einige Kurse zusammengelegt werden.
Wie ist denn da der Fahrplan?

Hier ein paar Beispiele aus CNF...

<img width="442" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/7788d7ad-517b-48c2-8274-dd1e1989b564">

<img width="444" alt="image" src="https://github.com/SVWS-NRW/SVWS-Server/assets/71388959/02932522-287c-4232-b121-a66ed19a9780">

**Comment by ThomasBachran** [comment]
@NielsWL : Das Ziel ist hier nicht, alle Regeln des CNF-Tools abzubilden. Interessant ist hier die Arbeitsabläufe abbilden zu können. Daher würde mich hier interessieren, welche Regeln für dich aus welchem Grund wichtig sind.

Mein Vorschlag: Du schließt dieses Issue und erstellst für die einzelnen Arbeitsläufe Issues, in denen du beschreibst, welche Funktionalität du benötigst und mit welchen Regeln du dies mit dem CNF-Tool bisher erreicht hast. Ok?

**Comment by NielsWL** [comment]
Das hört sich gut an. Es gibt ja unterschiedliche Vorgehensweisen für EF, Q1 und Q2, werde ich dann so neu eröffnen und die Arbeitsabläufe darstellen.
