### ISSUE TITLE
"Schema löschen" löscht den Benutzer nicht

### ISSUE THREAD

**Issue by kroerig** [SVWS-NRW/SVWS-Server#92]
Löscht man über die API ein Schema, wird der im SQL Benutzer dazu nicht mit gelöscht? Bug oder Feature?

Theoretisch will man für jedes Schema einen eigenen Benutzer haben, praktisch könnte es vorkommen, dass ein Benutzer für alle Schemata genutzt wird.
Im WebAdmin sollte dann IMHO ein Hinweis dazu stehen, dass der Benutzer ggf. manuell zu Löschen ist.

**Comment by ThomasBachran** [comment]
Der Benutzer wird nicht gelöscht. Er verliert allerdings seine Rechte auf das gelöschte Schema, so dass er diese nicht bei einer Neu-Erstellung diese Rechte wiedererlangt.
Das Löschen der Benutzer geht nicht in allen Umgebungen, da ein Benutzer evtl. weitere Rechte auf andere Schemata hat oder auch von einer Datenbank-Abteilung in einem Rechenzentrum verwaltet wird.
