### ISSUE TITLE
Vorschlag: Passwortkomplexität MariaDB Benutzer

### ISSUE THREAD

**Issue by kroerig** [SVWS-NRW/SVWS-Server#93]
Der WebAdmin (oder besser die API) sollten sicherstellen, dass das Passwort für den MariaDB Benutzer ausreichend komplex ist.
Wäre es nicht vllt. sogar sicherer, wenn der Client bzw. die API ein sicheres Passwort generieren?

**Comment by T-Hagel-SK** [comment]
Müsste das nicht schon auf Seiten der Datenbankeinrichtung passieren ?

Wie viele Personen haben in der klassischen Schulumgebung schon Zugriff auf den Datenbankserver und dort Rechte Datenbanken anzulegen ? Jeder DB-Admin sollte doch in der Lage sein, kryptische Passwörter zu erzeugen :-)

Ich würde die Passwortrichtlinie nicht an den WebClient oder eine API auslagern, sondern diese auf dem DB-Server belassen.

**Comment by ThomasBachran** [comment]
Im Windows-Installer werden für den Datenbank-Zugriff automatisch generiert. Das ist das einfachste Deployment-Szenario. Bei Deployment-Szenarien auf Linux-Basis mit mehreren Schemata gehe ich auch von einem professionellen DB-Management aus, so dass zusätzliche Einschränkungen durch die API oder den Admin-Client im Konflikt zu diesem stehen könnten und ggf. sogar kontraproduktiv sein könnten.
