### ISSUE TITLE
WebAdmin: Erneuter Login erforderlich

### ISSUE THREAD

**Issue by kroerig** [SVWS-NRW/SVWS-Server#94]
Ich wollte gerade eine DB migrieren. Der Vorgang brach ab. Um dann einen neuen Anlauf starten zu können, musste ich mich erst am WebAdmin neu anmelden, sonst kam bei Aufruf des Migrationsfensters immer der alte Inhalt mir der abgebrochenen Aktion.

Mehrere DBs nacheinander so zu migrieren ist damit nicht möglich.

Umgebung:
SVWS 0.8.9 (Docker)
Firefox 122.01

**Comment by T-Hagel-SK** [comment]
> Ich wollte gerade eine DB migrieren. Der Vorgang brach ab. Um dann einen neuen Anlauf starten zu können, musste ich mich erst am WebAdmin neu anmelden, sonst kam bei Aufruf des Migrationsfensters immer der alte Inhalt mir der abgebrochenen Aktion.
> 
> Mehrere DBs nacheinander so zu migrieren ist damit nicht möglich.
> 
> Umgebung: SVWS 0.8.9 (Docker) Firefox 122.01

Hm, das Neueintragen der DB-Parameter hatte ich unter der 0.8.9 bislang erst, nachdem ich die Seite geschlossen hatte. Ich nehme an, dass das ein Sicherheitsfeature ist :-)

Vielleicht lassen sich die Schild2-Datenbank-Parameter ja in einer weiteren Fassung direkt in der Config-Datei hinterlegen ?

**Comment by ThomasBachran** [comment]
> Vielleicht lassen sich die Schild2-Datenbank-Parameter ja in einer weiteren Fassung direkt in der Config-Datei hinterlegen ?

@T-Hagel-SK : Haben sie hier eine konkrete Vorstellung, wo das sein soll? Meinen Sie die svwsconfig.json? Die Zugriffsdaten müssten hier aber entsprechend geschützt sein, damit hier kein unberechtigter Zugriff möglich ist. Das ist problemantisch. Ein Vorgehen hierfür sollten wir in einem getrennten Issue diskutieren.

**Comment by ThomasBachran** [comment]
Ab dem nächsten Pre-Release sollte der Inhalt des Migrationsfensters beim Erneuten Öffnen wieder zurückgesetzt werden. Als Komfortfunktion habe ich dann noch eingebaut, dass man das Log verwerfen kann und das Migrationsfenster ohne es zu Schließen wiederverwenden kann.
