### ISSUE TITLE
Zugangsdaten für SchildZentral2-Datenbank fest hinterlegen

### ISSUE THREAD

**Issue by T-Hagel-SK** [SVWS-NRW/SVWS-Server#95]
Wie in Issue93 angerissen, wäre es beim Vorhaben, mehrere Schulen nacheinander über den SVWS-Server zu migrieren, hilfreich, wenn man diese Zugangsdaten nicht immer wieder neu eintragen müsste, wie es derzeit in 0.8.9 noch der Fall ist.

Zwar kann man hier schon eine begrenzte Zeit auf die bei Migrations(versuchen/vorhaben) eingetragenen Daten zurückgreifen, spätestens beim Schließen / Beenden der Browsersitzung aber, tippt man diese wieder von Neuem ein.

Besser wäre es, gerade wenn man noch im Aufbau und in den Testphasen ist, wenn diese Zugangsdaten zur Schild2-Datenbank im Hintergrund geladen würde. HIerzu hatte Hr. Bachran in [https://github.com/SVWS-NRW/SVWS-Server/issues/94#issuecomment-1935635609](url) gefragt, wie das gehen könne.

Nun, wenn ich mir etwas wünschen könnte, dann ware das ein Formular auf der /Admin-Seite, in dem man diese Daten eingeben kann, die dann mit einem verschlüsselten Passwort in einer gesonderten Datei auf dem Webserver abgelegt wird. Das Formular wäre dann auch in der Lage, diese Datei auszulesen / darzustellen um es ggf. bei Tippfehlern korrigieren zu können, ohne alle Daten neu einzugeben. Diese Datei könnte dann noch zusätzlich über .htaccess für Zugriffe von außen abgesichert werden ...

Also im weiteren Sinne wie bei der UDL-/DAT-Erstellung unter SchildZentral, wo die Zugangsdaten zur Schild2-Datenbank verschlüsselt abgelegt werden....

**Comment by FPfotenhauer** [comment]
Sie werden doch von Schild-Zentral ein Schulträgermodul bekommen.
Mit unserem Tool können Sie gerne Einzelmigrationen machen.
Die Massen sollten dann mit dem Tool von Ribeka gemacht werden.

Wir müssen hie rleider aufpassen, was Schild-Zentral ist und was SVWS-NRW.

**Comment by T-Hagel-SK** [comment]
> Sie werden doch von Schild-Zentral ein Schulträgermodul bekommen. Mit unserem Tool können Sie gerne Einzelmigrationen machen. Die Massen sollten dann mit dem Tool von Ribeka gemacht werden.
> 
> Wir müssen hie rleider aufpassen, was Schild-Zentral ist und was SVWS-NRW.

Ja, mein Fehler ... ich wollte hier gerade genau das reinschreiben ...

Von Ribeka gibt es ein sog. Schemaverwaltungstool, das genau den Job machen soll.  In dem Programm wird der Zugang zu der/den SchildZentral2-Datenbank/en je Schulträger eingetragen. Von dort aus werden die Schulnummern und Eckdaten ausgelesen und und die jeweiligen SVWS-Server erfasst.

Da auch das Programm sich vom UI nicht viel von der derzeitigen Admin-Oberfläche unterscheidet (funktional, nicht selbsterklärend :-) ) wird man sich auch da rantasten dürfen.

Da aber auch der Kollege Knoerig auf den Zug aufgesprungen ist, aber nur eine Schule betreut, scheint evtl. doch Bedarf auch bei einer SchildNRW-Datenbank zu bestehen, dass die Eckparameter fest hinterlegt werden. Sei es, weil die Exporte nicht auf Anhieb sauber laufen, oder man die Oberflächen austesten möchte .... 

Daher diesen Isssue wieder schließen.
