### ISSUE TITLE
Unzulässige Kombinationen doppelt??

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/SVWS-Server#96]
Ich habe das mal ins Wiki geschrieben. 

https://schulverwaltungsinfos.nrw.de/svws/wiki/index.php?title=F%C3%A4cher_(Vorgaben_und_Bedingungen)

Dabei kam mir die Frage: Ist das wirklich so gewollt und sehe ich die Logik nicht? Oder kann hier gespart werden?
Wenn gilt: Fach1 schließt Fach 2 aus, dann gilt das nach meiner Logik auch umgekehrt.
Regel 1: "Wer ER hat, kann nicht in KR sitzen".
Situation: Sitzt jemand in KR und dann noch ER, so hat er ER und kann nach Regel 1 nicht in KR sitzen.

Es braucht also Regel 2: "Wer KR hat, kann nicht in ER sitzen" nicht.

Der Beratungsbogen markiert derzeit immer nur das ausgeschlossene Fach. Da sich die Fächer aber gegenseitig ausschließen, müssten doch auch immer beide markert werden und es bräucht enur die Hälfte der Regeln.

**Comment by benjaminbartsch** [comment]
Ich kann zur Umsetzung in der GUI nichts sagen, aber von der Aussagenlogik stimmt das.

Bild: https://de.wikipedia.org/wiki/Implikation
![grafik](https://github.com/SVWS-NRW/SVWS-Server/assets/83505980/290d8d08-d069-4b13-85cd-4c302565895c)

A --> -B
ist äquivalent zu
-A ODER -B
ist äquivalent zu
-B ODER -A
ist äquivalent zu
B --> -A

**Comment by ThomasBachran** [comment]
@HHayen : Das war im Belegprüfungsalgorithmus korrekt umgesetzt. Allerdings hatte die GUI hier einen Fehler bei der Anzeige. Das Problem müsste jetzt behoben sein und müsste dann im nächste Pre-Release auch nicht mehr auftauchen.
