### ISSUE TITLE
Geforderte Kombination "ODER"-Regel

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/SVWS-Server#97]
Die "Geforderten Kombinationen" sind ein großartiger Fortschritt. Insbsondere die ZK-Berücksichtgung.

Wäre dabei jedoch auch eine ODER-Regel möglich?

Beispiel:
GE-ZK fordert (SW-LK oder SW-GK)
Wer GE-ZK hat MUSS SW als LK oder GK belegen, aber eben nicht als ZK. 

Oder (noch trickiger, aber durchaus real):
GK-ZK verbietet (KR oder ER oder PL) ODER (KU oder MU)

**Comment by ThomasBachran** [comment]
Dafür müsste das Konzept dieser Regeln deutlich verbessert werden. Das aktuelle Konzept nutzt die ursprünglichen Datenbanktabellen vor der Migration und ist leider nicht so flexibel gestaltet. Eine Anpassung wäre hier zwar komfortabel, ist aber in absehbarer Zeit nicht umsetzbar.
