### ISSUE TITLE
WIKI SVWS-Client

### ISSUE THREAD

**Issue by HHayen** [SVWS-NRW/SVWS-Server#98]
Ich habe mich mal einfach daran gemacht, das WIKI für SVWS-Client anzulegenund die ersten Einträge gemacht.

https://schulverwaltungsinfos.nrw.de/svws/wiki/index.php?title=SVWS-Client

Wäre schön, wenn dazu ein paar Rückmeldungen kämen, ob das im Aufbau/Struktur so ok ist.
Inhaltliche Rückmeldung zu Fehlern oder anderer Belange jederzeit an mich per
900008@schule.nrw.de

**Comment by FPfotenhauer** [comment]
Wir haben eine Doku für den SVWS-Client.
Da sollten wir direkt hier hineinschreiben.
Wie das klappen kann müssten wir in Ruhe besprechen.

**Comment by HHayen** [comment]
Gerne. Ich will niemandem die Arbeit wegnehmen. Da ich bei meinen Tests aber eh viel dokumentiere steht mein Angebot für den gesamten Bereich "Oberstufe" und was damit unmittelbar verbunden ist.
Im WIKI sollte der Teil "svws-Client" dann aber zu den "helps" verweisen.

**Comment by FPfotenhauer** [comment]
Zugang wurde geschaffen.
