### ISSUE TITLE
SVWS-Server Wunsch: Java-Logs Fehlermitteilung bis auf SVWS-Oberfläche & Java-Logs über Jetty in eigene Logdatei bereitstellen  

### ISSUE THREAD

**Issue by T-Hagel-SK** [SVWS-NRW/SVWS-Server#99]
In Issue 81 wurde ja das Thema "Schema-Anlage nicht vollständig, bzw. Abbruch mit Fehler" behandelt.
Am Ende stellte sich heraus, dass in den Java-Logfiles der Fehler ausgegeben wurde, dass dem verwendeten DB-User die Rechte für die Anlage von Triggern fehlten.

D.h. es wäre hilfreich, wenn auf der Admin-Oberfläche nicht nur die HTTP-Fehler ausgegeben würden, sondern auch die, die Java offenbar vorhält. 

Des weiteren dürfte es gerade in zentralen Umgebungen wie bei uns der Fall sein, dass die Schild3-Anwendungsbetreuer keinen Zugriff auf die SVWS-Konsole und damit auch auf die Logfiles haben. 

Daher von unseren Linux-Spezialisten auch die Anfrage, ob es für die Haltung von Logs nicht einfacher wäre, dass die Logs nicht mehr nur im "systemd / journalctl" gehalten werden, sondern dass der Jetty dafür eine eigene Log Datei anlegt. Diese könnten dann von den Linux-Spezialisten rotiert werden, um sie für einen bestimmten Zeitraum vorhalten / archivieren zu können.

**Comment by kroerig** [comment]
Schauen Sie mal hier: https://doku.svws-nrw.de/Deployment/Einrichtung/
Da ist die Konfiguration des SVWS Server beschrieben. Da kann man auch den LogPfad setzen.

Einfacher ginge es in einer Dockerumgebung. Dort schreibt der Prozess alle Meldungen einfach nach STDOUT. Über Portainer u.ä. lässt sich das Log so ganz einfach in (fast) Echtzeit einsehen.

Was sie auch bedenken sollten: Auch wenn man technisch mehrere Schulen über einen SVWS Server laufen lassen kann, im Logfile lassen sich die Prozesse später nicht mehr auseinanderhalten. Und wenn dann Fehler auftreten muss man ggf. auch mal Live-Debuggen können. Und da ist es dann doch hilfreich, wenn a) jede Schule eine eigene Instanz hat und b) der Anwendungsbetreuer Zugriff auf die Logfiles hat.

Und um jetzt nicht 80 VMs aufsetzen zu müssen, die sich den größten Teil des Tages langweilen, bietet sich halt Docker an. Entweder pur mit Docker Compose oder verwaltet mit z.B. K8s (Kubernetes)

**Comment by T-Hagel-SK** [comment]
> Schauen Sie mal hier: https://doku.svws-nrw.de/Deployment/Einrichtung/ Da ist die Konfiguration des SVWS Server beschrieben. Da kann man auch den LogPfad setzen.

In der Anleitung steht: 
 LoggingPath	"./logs"	Pfad zu den Logdateien.

Bislang kenne ich nun 2 Log-Varianten ... die mit den HTTP-Requests und die mit den Java-Fehlermeldungen. 

Das soll sich allein mit diesem Parameter einstellen lassen ?

> Einfacher ginge es in einer Dockerumgebung. Dort schreibt der Prozess alle Meldungen einfach nach STDOUT. Über Portainer u.ä. lässt sich das Log so ganz einfach in (fast) Echtzeit einsehen.

Ja, das Docker-Thema. Im Prinzip eine gute Idee. Auch die Idee, den Schulen nur noch ein Gesamtpaket (einen Container) bereitzustellen, statt einer Sammlung von Updates. Finde ich gut. Frage mich aber weiterhin, wie viele Schulen über Personal verfügen, diese Dockerumgebung zu verwenden. Es soll auch IT-Dienstleister geben, bei denen Docker nicht verwendet wird. 

Nun bei uns kommen bislang keine Dockersysteme zum Einsatz. Die Gründe würden den Rahmen hier sprengen. Uns sind die Vorteile bekannt, Docker steht uns hier aber nicht zur Verfügung und dürfte auch nicht als Minimalvoraussetzung herhalten.

> Und da ist es dann doch hilfreich, wenn a) jede Schule eine eigene Instanz hat und b) der Anwendungsbetreuer Zugriff auf die Logfiles hat.

Nun, wie sage ich es ? :-)

In Köln betreut mein Team derzeit rund 260 städtische Schulen an fast 300 Standorten. Bei der Variante jede Schule eine eigene Instanz bekommen die Kollegen aus dem Linux-Bereich Schnappatmung, wenn dann nochmal ein Viertel mehr Webserver dazukommen. Laut Hr. Pfotenhauer sei der Flaschenhals noch die Kursplanung, die aber an den Grundschulen z.B. nicht zum Einsatz kommt, weswegen man dort mehrere Schulen auf einen SVWS-Server bündeln kann. Mit etwas über 150 Grundschulen ist es also schon eine Frage, ob man nun 150 Webserver hinknallt, oder "nur" 10.

Wenn die Logfiles dann bei gleichzeitiger Nutzung durch mehrere Schulen derzeit nicht mehr zu unterscheiden sind, wäre der Ansatz doch eher, dass die Logfiles nach Schulnummern erzeugt werden.  

Wir freuen uns ja jetzt schon wie Bolle darauf, künftig nicht mehr Fehler in einer Datenbank zu finden, sondern in demnächst in mehr als 300. Neben den SchildNRW-Schemata kommen ja noch welche für SchildMedia, SchildWeb und Co dazu. Im Moment kann man nicht mal sagen, ob und in welchem Maße sich die Supportzeiten ausdehnen werden und wie viel aufwändiger Updates in unserem Umfeld werden. 

Sicherlich lassen die Dinge scripten, trotzdem muss dann halt eine Menge mehr als jetzt getestet werden. Die Erfahrung der letzten Jahre hat gezeigt, dass vor der Verteilung an rund 2.500 PCs und in die Citrix-Farm, die einzelnen Module erstmal grundsätzlich und dann gegen gemeldete Fehler getestet werden sollten. Es gibt nichts ekligeres als wenn zum Schuljahresende Programmteile abstürzen. Doch, Statistik kann da durchaus mithalten.

Zumal es mit den Updates von Datenbanken und Webservern nicht getan ist, da ist ja auch immer noch ein PC-Clients mit im Testrennen. 

Doch zurück zum Wunsch ... 

Der nach einer zentraleren Ablage von Logfiles wurde ja jetzt noch um die schulnummerscharfe Auslagerung von Logfiles ergänzt :-)

**Comment by FPfotenhauer** [comment]
Alle Exception grundsätzlich in den Client durchzureichen ist leider nicht möglich.
Wenn wir den Betrieb einmal im Griff haben, dann sollte sich die Anzahl der zu debuggenden Ereignisse auch deutlich reduzieren.
Momentan haben Sie von uns ja auch nur eine "Einzelinstallation" zum testen, ob es überhaupt läuft.
Für alles Weitere muss dann abgewartet werden, was der zentrale Dienstleister empfielt.

Wir werden uns um ein erweitertes Logging auf jeden Fall Gedanken machen, wenn es unsere Ressourcen erlauben.
